### ISSUE TITLE
Sync not working and no longer any option not to sync

### ISSUE THREAD

**Issue by ed-sparkes** [a85/POSTMan-Chrome-Extension#10006]
Since upgrading to the latest version i lose all my work every time my computer is reset, collections history etc. which is very frustrating. 

Seems the sync is not working although no info as to why just "Socket Not connected"

```
[17697][1579814375186][requester][warn]["Failed to subscribe to workspace for all APIs",{"name":"Error","message":"","stack":"Error\n    at SafeSubscriber.realtimeRequest$.pipe.subscribe.event [as _next] (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:459249:24)\n    at SafeSubscriber.__tryOrUnsub (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41998:16)\n    at SafeSubscriber.next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41936:22)\n    at Subscriber._next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41879:26)\n    at Subscriber.next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41856:18)\n    at FilterSubscriber._next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:146294:30)\n    at FilterSubscriber.Subscriber.next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41856:18)\n    at RefCountSubscriber.Subscriber._next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41879:26)\n    at RefCountSubscriber.Subscriber.next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41856:18)\n    at Subject.next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:76923:25)\n    at ConnectableSubscriber.Subscriber._next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41879:26)\n    at ConnectableSubscriber.Subscriber.next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41856:18)\n    at EventEmitter.realtimeRequestBus.subscribe.event (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:459196:14)\n    at EventEmitter.emit (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:50168:5)\n    at _dispatch (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:144700:14)\n    at EventEmitter.<anonymous> (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:144710:9)\n    at EventEmitter.emit (events.js:182:13)"}]
[17697][1579814375249][requester][warn]["APIDevService~getAPIs: Failed to get APIs.",{"error":{"message":"SyncRequestService\\x7erequestListener: Could not fetch from sync. Socket not connected."}}]
[17697][1579814375251][requester][warn]["Failed to refresh API List",{"error":{"message":"SyncRequestService\\x7erequestListener: Could not fetch from sync. Socket not connected."}}]
[17697][1579815249045][requester][info]["ACService~can: No permission found for",{"model":"workspace","modelId":"ddaa676e-cf44-4dbe-8315-28ae1d9ecd8b","action":"ADD_COLLECTION_TO_WORKSPACE"}]
[17697][1579815276793][requester][info]["ACService~can: No permission found for",{"model":"workspace","modelId":"ddaa676e-cf44-4dbe-8315-28ae1d9ecd8b","action":"CREATE_HISTORY"}]
[17697][1579816745284][requester][info]["ACService~can: No permission found for",{"model":"workspace","modelId":"ddaa676e-cf44-4dbe-8315-28ae1d9ecd8b","action":"CREATE_HISTORY"}]
[17697][1579817887869][requester][info]["ACService~can: No permission found for",{"model":"workspace","modelId":"ddaa676e-cf44-4dbe-8315-28ae1d9ecd8b","action":"CREATE_HISTORY"}]
[17697][1579817900449][requester][info]["ACService~can: No permission found for",{"model":"workspace","modelId":"ddaa676e-cf44-4dbe-8315-28ae1d9ecd8b","action":"CREATE_HISTORY"}]
[17697][1579818666212][requester][info]["ACService~can: No permission found for",{"model":"workspace","modelId":"ddaa676e-cf44-4dbe-8315-28ae1d9ecd8b","action":"CREATE_HISTORY"}]
[17697][1579818669759][requester][info]["ACService~can: No permission found for",{"model":"workspace","modelId":"ddaa676e-cf44-4dbe-8315-28ae1d9ecd8b","action":"CREATE_HISTORY"}]
[17697][1579818680451][requester][info]["ACService~can: No permission found for",{"model":"workspace","modelId":"ddaa676e-cf44-4dbe-8315-28ae1d9ecd8b","action":"CREATE_HISTORY"}]
```

**Comment by postman-staff** [comment]
Hi Ed,

Sorry to hear about this experience. Happy to help!
Could you share any screenshots as to what is seen every time the application launches?

Also, please submit a ticket to us via https://postman.com/support if you are using the application with an account. This helps us check further on your account and you can also share logs on the same ticket for us to troubleshoot this next.

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
Hi Ed,

Just following up here - let me know if you have any other questions or concerns as we haven't heard back.

You can use the same GitHub title while submitting a ticket to help us identify and process faster.

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
Hi @ed-sparkes,

I'll be closing this next on our end as we haven't heard back. If the issue persists, please reach out to us by submitting a ticket here: https://www.postman.com/support ​so we can investigate further.

Have a nice day.

via @Raj-postman | Postman Support
