### ISSUE TITLE
Unable to open requests on single/double clicking on the request from a collection from the Collections Tab

### ISSUE THREAD

**Issue by mihaiPopia** [a85/POSTMan-Chrome-Extension#10034]
Unable to open requests on single/double clicking on the request from a collection from the Collections Tab. However, if I right-click on the request and open in a new tab, then the request opens up properly.

1. Go to Any collection
2. Click on any request
3. Nothing happens

 - Postman Version: 8.6.2
 - Operating System: Win10

https://user-images.githubusercontent.com/83951130/122236158-f4bff780-cec6-11eb-9487-42cd5da205c9.mp4

```
vendor-shared.js:349973 Use `shouldComponentUpdate` in an `observer` based component breaks the behavior of `observer` and might lead to unexpected results. Manually implementing `sCU` should not be needed when using mobx-react.
mixinLifecycleEvents @ vendor-shared.js:349973
vendor-shared.js:55415 Initializing the global config
requester.js:75417 DesktopLocationService ~ init initialized
vendor-shared.js:292850 NavigationService ~ Initialized: Success
requester.js:51552 initializeNavigation~boot - Success
vendor-shared.js:1139079 Refused to load the script 'https://js.stripe.com/v3' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

injectScript @ vendor-shared.js:1139079
vendor-shared.js:1171073 Error: Failed to load Stripe.js
    at HTMLScriptElement.<anonymous> (vendor-shared.js:1139136)
    at HTMLScriptElement.sentryWrapped (vendor-shared.js:1170560)
(anonymous) @ vendor-shared.js:1171073
vendor-shared.js:1171073 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 model-events listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:63361:15)
    at EventEmitter.addListener (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:63377:10)
    at EventBus._subscribe (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:81616:16)
    at DBResourceWatcher.subscribeToEventBus (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:598706:73)
    at bootWLModels (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/requester.js:25366:79)
    at file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:53558:39
    at replenish (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:54570:17)
    at iterateeCallback (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:54554:17)
    at file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:55306:16
    at file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:53563:13
    at file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/requester.js:52620:18
(anonymous) @ vendor-shared.js:1171073
vendor-shared.js:1171073 Proxy process identifier proxy_node_process_prod
vendor-shared.js:1171073 Could not find on CollectionStore. Missing or invalid parameter.
(anonymous) @ vendor-shared.js:1171073
vendor-shared.js:1171073 App updater event Object
vendor-shared.js:1171073 Disconnected from Interceptor
2vendor-shared.js:1171073 Use `shouldComponentUpdate` in an `observer` based component breaks the behavior of `observer` and might lead to unexpected results. Manually implementing `sCU` should not be needed when using mobx-react.
(anonymous) @ vendor-shared.js:1171073
vendor-shared.js:1171073 Could not find on CollectionStore. Missing or invalid parameter.
(anonymous) @ vendor-shared.js:1171073
vendor-shared.js:1171073 Could not find on WorkspaceStore. Missing or invalid parameter.
(anonymous) @ vendor-shared.js:1171073
requester.html:1 A cookie associated with a cross-site resource at http://app.getpostman.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
2sentry-app.postmanlabs.com/api/22/store/?sentry_key=8fb2d5d1749642eface793d3dd93a6d8&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (TOO MANY REQUESTS)
vendor-shared.js:1171073 Could not find on CollectionStore. Missing or invalid parameter.
(anonymous) @ vendor-shared.js:1171073
vendor-shared.js:1171073 Warning: a promise was created in a handler but was not returned from it    at Deferred.push.Deferred.toPromise (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:110840:19)    at Deferred.push.Deferred.then (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:110699:22)    at ConsoleEventStore.updateMeta (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:1161059:5)    at file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:1160994:14    at transaction$$1 (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:232145:26)    at file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:1160992:63From previous event:    at ConsoleEventStore.hydrate (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:1160991:5)    at executeAction$$1 (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:230149:19)    at ConsoleEventStore.res (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:230141:16)    at new BaseListStore (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:234690:116)    at new ConsoleEventStore (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:1160874:5)    at getStore (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:234035:55)    at new ConsoleStore (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:1161178:99)    at getStore (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:234035:55)    at new RequesterBottomPaneHeader (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:1052158:91)    at Lg (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:316:171)    at fi (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:358:149)    at Rj (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:445:490)    at Qj (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:428:265)    at Kj (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:428:194)    at yj (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:421:172)    at file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:305:115    at push.exports.unstable_runWithPriority (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:512:467)    at cg (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:304:325)    at fg (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:305:61)    at gg (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:304:496)    at Mj (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:422:66)    at reactionScheduler (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:231307:47)    at runReactions$$1 (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:231283:5)    at endBatch$$1 (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:230995:9)    at transaction$$1 (file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:232148:9)    at file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/vendor-shared.js:294979:65
(anonymous) @ vendor-shared.js:1171073
vendor-shared.js:1171073 Could not find on WorkspaceStore. Missing or invalid parameter.
(anonymous) @ vendor-shared.js:1171073
2vendor-shared.js:1171073 sign in bailed. force connect.
vendor-shared.js:1171073 Skipping force reconnect as still preparing and no attempt of connection has been made yet.
(anonymous) @ vendor-shared.js:1171073
vendor-shared.js:1171073 Could not find on WorkspaceStore. Missing or invalid parameter.
(anonymous) @ vendor-shared.js:1171073
308vendor-shared.js:1171073 Could not find on CollectionStore. Missing or invalid parameter.
(anonymous) @ vendor-shared.js:1171073
3vendor-shared.js:1171073 Could not find on EditorStore. Missing or invalid parameter.
(anonymous) @ vendor-shared.js:1171073
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/path.js.map: 
2DevTools failed to load SourceMap: Could not load content for file:///C:/Users/flutter/AppData/Local/Postman/app-8.6.2/resources/app.asar/js/iso2022.js.map: 
vendor-shared.js:1171073 Could not find on EditorStore. Missing or invalid parameter.
```

**Comment by DannyDainton** [comment]
Hey @mihaiPopia 

Are you able to create a short video of the app showing this behaviour, please?

**Comment by mihaiPopia** [comment]
Hello @DannyDainton 

I added the video above logs

**Comment by DannyDainton** [comment]
Thank you - It looks like a similar thing as this one https://github.com/postmanlabs/postman-app-support/issues/9951

Could you try signing out and in again to see if that helps out here?

**Comment by mihaiPopia** [comment]
Funny how i tried reinstalling but didn't think about logging out.
That worked, thank you!

**Comment by DannyDainton** [comment]
Awesome, I'm going to close this one out for now.
