### ISSUE TITLE
Postman fails to open after upgrading to PopOS 21.04

### ISSUE THREAD

**Issue by kounelios13** [a85/POSTMan-Chrome-Extension#10126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hello. I have installed postman using snap in pop os 20.04 . I upgraded pop os to 21.04 and now postman wont start 

If i try it from a command line i get the following error

```
A JavaScript error occurred in the main process
Uncaught Exception:
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 1 (Unknown system error 1)
    at Object.networkInterfaces (os.js:195:16)
    at getIPType (/snap/postman/133/usr/share/Postman/resources/app/node_modules/node-ipc/entities/Defaults.js:67:34)
    at new Defaults (/snap/postman/133/usr/share/Postman/resources/app/node_modules/node-ipc/entities/Defaults.js:45:21)
    at new Parser (/snap/postman/133/usr/share/Postman/resources/app/node_modules/node-ipc/entities/EventParser.js:8:14)
    at Object.<anonymous> (/snap/postman/133/usr/share/Postman/resources/app/node_modules/node-ipc/dao/client.js:15:19)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/snap/postman/133/usr/share/Postman/resources/app/node_modules/node-ipc/services/IPC.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
```

### Steps To Reproduce

1. Use PopOS 20.04 and install postman as a snap 
2. Update PopOS 20.04 to 21.04
3. Open postman

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/11466138/125831461-fbc3836b-bcc7-40a7-aa88-58fd429699f5.png)

### Environment Information

```markdown
- Operating System: PopOS 21.04
- Platform Type: Native App / Snap
- Postman Version:  7.36.5
```

**Comment by postman-staff** [comment]
Hi there,

Thanks for reaching out and sorry to see you are having trouble using the Postman app installed using snap.

To troubleshoot further we will need App logs, your email ID & other details. Since GitHub being a public platform it is not good to get those details on this thread from you for security reasons.

Could you open a new ticket on our support channel using this link - https://www.postman.com/support/, please? Also, do add this GitHub issue number and your GitHub username in the request description to make it easy for us to track.

We will wait to hear back from you on our support channel.

via @Swapnil-getpostman | Postman Support

**Comment by kounelios13** [comment]
Hi. I am using linux. How can I get app logs

**Comment by postman-staff** [comment]
Hi there,

Thanks for writing us on our support channel and will respond to you on the support ticket.

As of now, we will move ahead and close out this thread.

via @Swapnil-getpostman | Postman Support

**Comment by mricharz** [comment]
Hi Postman Team, this handling is very helpful to others having the same issues. Thank you!
/ironicoff

The logs says that postman-proxy-ca.crt is missing. Happening directly after fresh install from flatpak.

I think that Postman itself will not help because this flatpak package is not published by the Postman Team and will therefore not be supported. Tell me if i am wrong.

I ended up installig it using snap:
`sudo apt update
sudo apt install snapd
sudo snap install postman`

and starting it via terminal:
`postman`

I hope this helps anyone.

**Comment by R70YNS** [comment]
Ended up installing the app directly from the site.  Unfortunately this means I've ended up losing all local collections that weren't exported.

**Comment by vlalef** [comment]
> Hi Postman Team, this handling is very helpful to others having the same issues. Thank you! /ironicoff
> 
> The logs says that postman-proxy-ca.crt is missing. Happening directly after fresh install from flatpak.
> 
> I think that Postman itself will not help because this flatpak package is not published by the Postman Team and will therefore not be supported. Tell me if i am wrong.
> 
> I ended up installig it using snap: `sudo apt update sudo apt install snapd sudo snap install postman`
> 
> and starting it via terminal: `postman`
> 
> I hope this helps anyone.

This worked for me, thank you a lot!
