### ISSUE TITLE
Scratch Pad not working

### ISSUE THREAD

**Issue by lolpez** [a85/POSTMan-Chrome-Extension#10209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Scratch Pad does not open, it displays "Something Went Wrong"
The last log from renderer-scratchpad.log is

`[4760][1628559506966][scratchpad][error]["Could not complete migration.",{"name":"Error","message":"Migration: IndexedDB schema migration failed. IndexedDb was not upgraded successfully after `dexie.open`.","stack":"Error: Migration: IndexedDB schema migration failed. IndexedDb was not upgraded successfully after `dexie.open`.\n    at file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/requester.js:76593:37\n    at file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:212244:23\n    at callListener (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:211927:19)\n    at endMicroTickScope (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:212014:25)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:212081:17)"},{"0000_initial":"started","0001_add_archived_resources_table":"started","0002_add_variable_sessions_table":"started","0003_add_editor_tables":"started"}]
[4760][1628559506970][scratchpad][error]["Migration: Could not complete migration.",{"name":"Error","message":"Migration: IndexedDB schema migration failed. IndexedDb was not upgraded successfully after `dexie.open`.","stack":"Error: Migration: IndexedDB schema migration failed. IndexedDb was not upgraded successfully after `dexie.open`.\n    at file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/requester.js:76593:37\n    at file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:212244:23\n    at callListener (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:211927:19)\n    at endMicroTickScope (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:212014:25)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:212081:17)"},{"0000_initial":"started","0001_add_archived_resources_table":"started","0002_add_variable_sessions_table":"started","0003_add_editor_tables":"started"}]
[4760][1628559506971][scratchpad][info]["booted - scratchpad"]
[4760][1628559506972][scratchpad][error]["Error in requester boot sequence",{"name":"Error","message":"Migration: IndexedDB schema migration failed. IndexedDb was not upgraded successfully after `dexie.open`.","stack":"Error: Migration: IndexedDB schema migration failed. IndexedDb was not upgraded successfully after `dexie.open`.\n    at file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/requester.js:76593:37\n    at file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:212244:23\n    at callListener (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:211927:19)\n    at endMicroTickScope (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:212014:25)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:212081:17)"}]
[4760][1628559506981][scratchpad][warn]["Error while triggering websocket connection for user - ",{"name":"Error","message":"Could not get waterline model for user. ORM not initialized.","stack":"Error: Could not get waterline model for user. ORM not initialized.\n    at Object.getModel (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:242311:29)\n    at Object.findOne (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:242373:5)\n    at Object.get (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:246649:75)\n    at file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/requester.js:10908:91\n    at file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:59996:9\n    at file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:61026:16\n    at iterateeCallback (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:60979:17)\n    at file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:61736:16\n    at file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:59993:13\n    at file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/requester.js:76681:7\n    at file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:212244:23\n    at callListener (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:211933:19)\n    at endMicroTickScope (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:212014:25)\n    at physicalTick (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:211989:30)"}]
[4760][1628559506992][scratchpad][warn]["Error in fetching user information",{"name":"Error","message":"Could not get waterline model for user. ORM not initialized.","stack":"Error: Could not get waterline model for user. ORM not initialized.\n    at Object.getModel (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:242311:29)\n    at Object.findOne (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:242373:5)\n    at Object.get (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:246649:75)\n    at file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:1145631:7\n    at Hub.push.Hub.configureScope (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:1151890:13)\n    at callOnHub (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:1150353:28)\n    at Object.configureScope (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:1150425:5)\n    at Object.setUserScope (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:1145629:17)\n    at EventEmitter.<anonymous> (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:1145564:16)\n    at EventEmitter.emit (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:69753:5)\n    at _dispatch (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:88096:14)\n    at EventEmitter.<anonymous> (file:///C:/Users/luiyi/AppData/Local/Postman/app-8.10.0/resources/app.asar/js/vendor-shared.js:88107:9)\n    at EventEmitter.emit (events.js:315:20)\n    at Object.onMessage (electron/js2c/renderer_init.js:91:925)"}]
`
[renderer-scratchpad.log](https://github.com/postmanlabs/postman-app-support/files/6958348/renderer-scratchpad.log)

### Steps To Reproduce

1. Open a workspace
2. Click on settings button (the one next to the profile icon)
3. Click on "Scratch Pad"
4. Error page is displayed

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/12414645/128795457-d574dd08-dd1e-4f2b-9c22-035b6297375c.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 8.10.0
```

**Comment by postman-staff** [comment]
Hi @lolpez,
Thank you for reaching out to Postman support. Sorry to see that you are facing issues with our application but happy to help!

Firstly, Could you confirm if the Web Version works for you as a temporary means to get you unblocked? You can navigate to https://go.postman.co/ to access the Web version.

We've typically seen the instructions to **clear out the local files/rename the Postman folder **as instructed to address this type of issue generally. You would have to pay attention to the **Requirements** section before deleting any local files, just to make sure you don't lose any work.

Could you please try the steps mentioned in the below article and let me know it to helps : https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-?

Finally, Could you provide us with Application logs as instructed here: https://support.postman.com/hc/en-us/articles/360033270134-Where-can-I-find-logs-for-the-Postman-app-?** make sure to include all the logs from the logs folder.**

Thank you for your cooperation, looking forward to your response.

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi @lolpez,
Hope you are doing good!

Let me know if the suggested workaround helped you in getting the desktop app scratchpad working fine?
If you are still facing any issues, then could you please write to us at help@getpostman.com for further assistance, along with the log file attached and with the Github ID(10209)

Please feel free to reach out to the above mentioned email address with the logs files mentioned in the previous response.
Thank you!

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi @lolpez,

Just a friendly ping to know if you are able to use the Scratchpad successfully or if you are still facing issues?

Please feel free to submit a request at postman.com/support if you still need assistance. But do remember to mention the Github ID(10209).

Best regards,
Lincimary​ | Product Support Engineer

Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by lolpez** [comment]
It is still not working, I am still on postman 8.10.0

**Comment by postman-staff** [comment]
Hi @lolpez,

Sorry to hear that you are still running into issues.
As mentioned in my previous email could you please submit a request at postman.com/support along with the log files and the Github ID(10209)?

Awaiting for your feedback.

via @Lincimary | Postman Support

**Comment by lolpez** [comment]
done, hope it can help

**Comment by postman-staff** [comment]
Hi @lolpez,

Thank you so much!
We have received the logs. We will continue the conversation on the other ticket that you have raised.

Best regards,
Lincimary​ | Product Support Engineer

Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by chrisdeso** [comment]
@lolpez We'll be closing this issue out but feel free to reopen it – or to follow up via the support ticket created – if you have any other questions!
