### ISSUE TITLE
Collection not found when creating new forks

### ISSUE THREAD

**Issue by hkarjala** [a85/POSTMan-Chrome-Extension#10452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Problem started during this week. This is happening frequently.

When we try to create new forks to another workspace - after some time we're correctly directed to correct workspace, but end up with tab stating "Collection not found". 

I can see the fork creation logged in the workspace overview - but clicking the link there as well opens the "Collection not found" tab.

This is happening for all our users. We're using mainly Postman native app and updating to latest version as they come.
This has also be seen happening with Postman web in same way.

On some cases, the fork IS created - but cannot be seen in workspaces collection list until restarting Postman.
Also this also can be seen in both postman app and postman web.

This is happening when target workspace has lots of other collections and environment files, as well as with brand new clean workspaces.

Our collections are quite big, from couple of hundreds of requests to +2000 requests I guess (used to be able to tell exactly when postman was still showing the number of request in collections....)

### Steps To Reproduce

1. Create a fork of collection from one workspace to another
2. Stare at "Collection not found" tab in wonder

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: v9.1.5
```

**Comment by hkarjala** [comment]
Same thing ongoing with v9.2.0. And this morning seems to be completely impossible for us (several different users) to create new forks from our master collection.

From Postman app logs I'm getting following:
`[34276][1637745035527][requester][info]["RealtimeSyncMessageService~publishRealtimeIncomingMessage: Message received collection:subscribe Timeline in message: user:6400538"]
[34276][1637745035528][requester][info]["BaseSyncTimeline~processServerChange: Started processing changeset for collection:subscribe:f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55 Timeline:user:6400538"]
[34276][1637745035529][requester][info]["BaseSyncTimeline~subscribe: Subscribing to real time changes for collection:6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55"]
[34276][1637745035529][requester][info]["BaseSyncTimeline~_sync: Starting sync for collection:6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55"]
[34276][1637745035530][requester][info]["BaseSyncTimeline~processServerChange: Finished processing changeset for collection:subscribe:f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55 Timeline:user:6400538"]
[34276][1637745035532][requester][info]["RealtimeSyncMessageService~publishRealtimeIncomingMessage: Message received workspace:broadcast Timeline in message: undefined:undefined"]
[34276][1637745035533][requester][info]["CollectionMetaListingAPIAdapter: Adding to CollectionStoreV2",["6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55"]]
[34276][1637745035537][requester][info]["BaseSyncTimeline~getPendingClientChanges: Starting to get pending changes for collection:6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55"]
[34276][1637745035537][requester][info]["BaseSyncTimeline~getPendingClientChanges: Finished to get pending changes for collection:6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55"]
[34276][1637745035538][requester][info]["BaseSyncTimeline~getPendingServerChanges: Starting /sync call for collection:6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55"]
[34276][1637745035720][requester][warn]["BaseSyncTimeline~getPendingServerChanges: Error in collection:6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55 /sync response",{"name":"Error","message":"We could not find the collection you are looking for","stack":"Error: We could not find the collection you are looking for\n    at b.getPendingServerChanges (file:///C:/Users/henri.karjalainen/AppData/Local/Postman/app-9.2.0/resources/app.asar/js/vendor-shared.js:2973:501140)\n    at async b._sync (file:///C:/Users/henri.karjalainen/AppData/Local/Postman/app-9.2.0/resources/app.asar/js/vendor-shared.js:2973:493791)"}]
[34276][1637745035720][requester][warn]["Could not subscribe to collection:6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55",{"name":"Error","message":"We could not find the collection you are looking for","stack":"Error: We could not find the collection you are looking for\n    at b.getPendingServerChanges (file:///C:/Users/henri.karjalainen/AppData/Local/Postman/app-9.2.0/resources/app.asar/js/vendor-shared.js:2973:501140)\n    at async b._sync (file:///C:/Users/henri.karjalainen/AppData/Local/Postman/app-9.2.0/resources/app.asar/js/vendor-shared.js:2973:493791)"}]
[34276][1637745036227][requester][info]["RealtimeSyncMessageService~publishRealtimeIncomingMessage: Message received collection:subscribe Timeline in message: user:6400538"]
[34276][1637745036228][requester][info]["BaseSyncTimeline~processServerChange: Started processing changeset for collection:subscribe:f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55 Timeline:user:6400538"]
[34276][1637745036228][requester][info]["BaseSyncTimeline~subscribe: Subscribing to real time changes for collection:6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55"]
[34276][1637745036228][requester][info]["BaseSyncTimeline~_sync: Starting sync for collection:6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55"]`
`[34276][1637745036229][requester][info]["BaseSyncTimeline~processServerChange: Finished processing changeset for collection:subscribe:f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55 Timeline:user:6400538"]
[34276][1637745036231][requester][info]["RealtimeSyncMessageService~publishRealtimeIncomingMessage: Message received workspace:broadcast Timeline in message: undefined:undefined"]
[34276][1637745036231][requester][info]["CollectionMetaListingAPIAdapter: Adding to CollectionStoreV2",["6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55"]]
[34276][1637745036232][requester][info]["BaseSyncTimeline~getPendingClientChanges: Starting to get pending changes for collection:6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55"]
[34276][1637745036233][requester][info]["BaseSyncTimeline~getPendingClientChanges: Finished to get pending changes for collection:6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55"]
[34276][1637745036233][requester][info]["BaseSyncTimeline~getPendingServerChanges: Starting /sync call for collection:6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55"]
[34276][1637745036234][requester][warn]["Sync state invalid. Changeset processed is behind the last sync state",{"model":"user","modelId":"6400538"},22026100463,22026072211]
[34276][1637745036472][requester][warn]["BaseSyncTimeline~getPendingServerChanges: Error in collection:6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55 /sync response",{"name":"Error","message":"You are not permitted to perform the action.","stack":"Error: You are not permitted to perform the action.\n    at b.getPendingServerChanges (file:///C:/Users/henri.karjalainen/AppData/Local/Postman/app-9.2.0/resources/app.asar/js/vendor-shared.js:2973:501140)\n    at async b._sync (file:///C:/Users/henri.karjalainen/AppData/Local/Postman/app-9.2.0/resources/app.asar/js/vendor-shared.js:2973:493791)"}]
[34276][1637745036472][requester][warn]["Could not subscribe to collection:6400538-f5c6aaeb-9269-4e07-9f13-fc7f0ce26e55",{"name":"Error","message":"You are not permitted to perform the action.","stack":"Error: You are not permitted to perform the action.\n    at b.getPendingServerChanges (file:///C:/Users/henri.karjalainen/AppData/Local/Postman/app-9.2.0/resources/app.asar/js/vendor-shared.js:2973:501140)\n    at async b._sync (file:///C:/Users/henri.karjalainen/AppData/Local/Postman/app-9.2.0/resources/app.asar/js/vendor-shared.js:2973:493791)"}]`

**Comment by hkarjala** [comment]
This has been fixed (started working again 26th Nov. onwards)
