### ISSUE TITLE
Postman Not able to start Up

### ISSUE THREAD

**Issue by garvit-joshi** [a85/POSTMan-Chrome-Extension#10619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When starting postman, it does not start:
```
The disableGPU setting is set to RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at internal/fs/utils.js:630:42
    at hidden (internal/errors.js:294:14)
    at Object.openSync (fs.js:468:10)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.exports.lockSync (/opt/postman/app/resources/app/node_modules/lockfile/lockfile.js:277:17)
    at retryThrow (/opt/postman/app/resources/app/node_modules/lockfile/lockfile.js:316:20)
    at Object.exports.lockSync (/opt/postman/app/resources/app/node_modules/lockfile/lockfile.js:307:12)
    at retryThrow (/opt/postman/app/resources/app/node_modules/lockfile/lockfile.js:316:20)
    at Object.exports.lockSync (/opt/postman/app/resources/app/node_modules/lockfile/lockfile.js:307:12)
    at retryThrow (/opt/postman/app/resources/app/node_modules/lockfile/lockfile.js:316:20)
    at Object.exports.lockSync (/opt/postman/app/resources/app/node_modules/lockfile/lockfile.js:307:12)
    at retryThrow (/opt/postman/app/resources/app/node_modules/lockfile/lockfile.js:316:20)
    at Object.exports.lockSync (/opt/postman/app/resources/app/node_modules/lockfile/lockfile.js:307:12)
    at retryThrow (/opt/postman/app/resources/app/node_modules/lockfile/lockfile.js:316:20)
    at Object.exports.lockSync (/opt/postman/app/resources/app/node_modules/lockfile/lockfile.js:307:12)
    at retryThrow (/opt/postman/app/resources/app/node_modules/lockfile/lockfile.js:316:20)
Not disabling GPU
```

### Steps To Reproduce

1. Postman Does not open, on clicking on App as well as terminal

### Environment Information

```markdown
- Operating System: Manjaro Linux (5.15.16-1)
- Platform Type: Native App
- Postman Version: 9.11
```

**Comment by RaisinTen** [comment]
Are there any Postman processes running in the background? If there are any, could you terminate them and rerun Postman and let us know how it goes?

**Comment by RaisinTen** [comment]
Can you also share the output you get when you run:
```shell
ls -l ~/.config/Postman/storage/
```
?

**Comment by garvit-joshi** [comment]
Hi, 
Just Checked now and found out that the postman is working fine. I restarted two times and nothing seems to work the day I created the issue.
Here is the output of the program:
```
-rw-r--r-- 1 garvit-joshi garvit-joshi 79 Jan 29 22:25 requester.json
-rw-r--r-- 1 garvit-joshi garvit-joshi 86 Jan 29 22:25 settings.json
-rw-r--r-- 1 garvit-joshi garvit-joshi  0 Jan 29 22:26 settings.json.lock
```

**Comment by RaisinTen** [comment]
Thanks! Did you get this output when the app was in a running state?

**Comment by RaisinTen** [comment]
> Just Checked now and found out that the postman is working fine.

Closing the issue as it seems to be resolved for now. Thanks!
