### ISSUE TITLE
~/.config/Postman/window owned by root on ubuntu 18

### ISSUE THREAD

**Issue by ljgww** [a85/POSTMan-Chrome-Extension#10624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Postman wont start
last reported lines on run

at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/storage.js:59:23
FSReqCallback.oncomplete (fs.js:171:23)

then exits and does not report any errors

### Steps To Reproduce

1. Download latest postman
2. unzip archive in appropriate folder
3. run Postman launcher

### Environment Information

```markdown
- Operating System: Ubunty 18
- Platform Type: Linux
- Postman Version: 9.11.0
```

### Additional Context?

Previous versions worked. Last used 9.8.2
Cannot download previous version and install
reinstalling 9.8.2 does not help
same issue

**Comment by ljgww** [comment]
Was looking deeper in run log

        ~/bin/postman-9.11.0-linux-x64/Postman$ ./Postman 
	The disableGPU setting is set to undefined
	Not disabling GPU
	Main~createDefaultWorkingDir - Default working dir creation already attempted
	1643790908273 main info "Booting Postman 9.11.0, linux-5.4.0-96-generic on x64"
	1643790908274 main info "EventBus~initialize - Success"
	1643790908275 main info "Proxy configuration has not been setup"
	1643790908275 main info "CloudProxyManager~init - Success"
	1643790908280 main info "UpdateHandler~init - Success"
	libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
	1643790908487 main info "RuntimeIPCAgent~started: Success"
	1643790908488 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
	1643790908489 main info "LeaderSelection: Initialized successfully"
	1643790908500 main warn "WaterlineNedb~registerDatastore: Could not update indicesEACCES: permission denied, open '/home/lj/.config/Postman/window'"
	1643790908509 main info "GPU detected VID 4318 DID 7298 ACTIVE true"
	1643790908517 main error "Bootstrap-models~bootstrap -Failed",{"errno":-13,"code":"EACCES","syscall":"open","path":"/home/lj/.config/Postman/window","name":"Error","message":"EACCES: permission denied, open '/home/lj/.config/Postman/window'","stack":"Error: EACCES: permission denied, open '/home/lj/.config/Postman/window'"}
	TypeError: Cannot read property 'collections' of undefined
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/main.js:727:32
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/bootstrap-models.js:34:14
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/lib/waterline.js:918:25
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/lib/waterline.js:719:25
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/node_modules/async/dist/async.js:952:25
	    at iteratorCallback (/home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/node_modules/async/dist/async.js:995:17)
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/node_modules/async/dist/async.js:847:20
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/async/lib/async.js:52:16
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/async/lib/async.js:264:21
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/async/lib/async.js:44:16
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/common/adapters/waterline-shared-nedb.js:325:33
	    at newArguments.<computed> (/home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/executor.js:29:17)
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/persistence.js:305:26
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/persistence.js:138:23
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/storage.js:105:30
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/node_modules/async/lib/async.js:485:30
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/storage.js:91:68
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/storage.js:59:23
	    at FSReqCallback.oncomplete (fs.js:171:23)
	1643790908521 main error "Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"Cannot read property 'collections' of undefined","stack":"TypeError: Cannot read property 'collections' of undefined\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/main.js:727:32\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/bootstrap-models.js:34:14\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/lib/waterline.js:918:25\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/lib/waterline.js:719:25\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/node_modules/async/dist/async.js:952:25\n    at iteratorCallback (/home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/node_modules/async/dist/async.js:995:17)\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/node_modules/async/dist/async.js:847:20\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/async/lib/async.js:52:16\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/async/lib/async.js:264:21\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/async/lib/async.js:44:16\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/common/adapters/waterline-shared-nedb.js:325:33\n    at newArguments.<computed> (/home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/executor.js:29:17)\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/persistence.js:305:26\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/persistence.js:138:23\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/storage.js:105:30\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/node_modules/async/lib/async.js:485:30\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/storage.js:91:68\n    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/storage.js:59:23\n    at FSReqCallback.oncomplete (fs.js:171:23)"}
	Main~handleUncaughtError - Uncaught errors TypeError: Cannot read property 'collections' of undefined
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/main.js:727:32
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/bootstrap-models.js:34:14
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/lib/waterline.js:918:25
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/lib/waterline.js:719:25
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/node_modules/async/dist/async.js:952:25
	    at iteratorCallback (/home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/node_modules/async/dist/async.js:995:17)
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/waterline/node_modules/async/dist/async.js:847:20
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/async/lib/async.js:52:16
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/async/lib/async.js:264:21
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/async/lib/async.js:44:16
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/common/adapters/waterline-shared-nedb.js:325:33
	    at newArguments.<computed> (/home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/executor.js:29:17)
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/persistence.js:305:26
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/persistence.js:138:23
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/storage.js:105:30
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/node_modules/async/lib/async.js:485:30
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/storage.js:91:68
	    at /home/lj/bin/postman-9.11.0-linux-x64/Postman/app/resources/app/node_modules/nedb/lib/storage.js:59:23
	    at FSReqCallback.oncomplete (fs.js:171:23)


Noticed error and fixed the issue.

apparently:

`~/.config/Postman/window` took root ownership (for a unknown reason to me)

changed 'window' file permissions to my user ownership

Postman starts now. Seems to be fine.

**Comment by ljgww** [comment]
Just to leave an observation.

Since this is config that is obviously used for different versions of postman that could be installed on the same system. 
Once I have fixed access right to a file all other versions of postman I had installed started working as well.

**Comment by jviotti** [comment]
Thanks for the clarification @ljgww. I'll rename the title of this issue to better reflect the root problem.

**Comment by Softianix** [comment]
I had the same issue:
```shell
The disableGPU setting is set to undefined
Not disabling GPU
...
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
...
```
when installing Postman on Fedora Workstation 37 using manual installation (extracting from .tar.gz), but I have fixed it by installing Postman using "Software" app, instead
