### ISSUE TITLE
Socket.IO message without arguments

### ISSUE THREAD

**Issue by viktorvorobev** [a85/POSTMan-Chrome-Extension#10621]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

I have a Python project that utilizes Socket IO API. I have a bunch of methods that process Socket IO events without arguments, e.g.:
```python
@socketio.on('get data')
def get_data():
    payload = foo()
    socketio.emit('response', payload)
```
But I can't do that with Postman, because currently it won't let me send a message without arguments, which causes the following exception:
```
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 945, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 882, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/socketio/server.py", line 679, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/lib/python3.8/site-packages/socketio/server.py", line 708, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/lib/python3.8/site-packages/flask_socketio/__init__.py", line 283, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "../../build/lib/file/file/file/file/file.py", line 30, in socketio_wrapper
  File "/usr/lib/python3.8/site-packages/flask_socketio/__init__.py", line 698, in _handle_event
    ret = handler(*args)
TypeError: get_data() takes 0 positional arguments but 1 was given
```

### Describe the solution you'd like

I'd like to have an ability to send Socket IO events with no arguments at all.

### Describe alternatives you've considered

I can, of course, for debug purposes handle the issue with adding unused `args` and `kwargs`, but that's not suitable solution in some cases.

**Comment by kennarddh** [comment]
Any solution for this?

**Comment by IlTeo285** [comment]
problem still present
