### ISSUE TITLE
unable to use grpc reflection when health checks configured

### ISSUE THREAD

**Issue by cgeers** [a85/POSTMan-Chrome-Extension#10844]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using postman to interrogate a grpc server's exposed services via reflection, an "unkown error" is reported if the default health check service is enabled.  Digging around in the logs, from `logs/renderer-requester.log` I see:

```
[1424][1649863276559][requester][error][{"name":"Error","message":"unknown error","stack":"Error
    at ClientDuplexStreamImpl.dataCallback (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/grpc-reflection-js/build/src/client.js:111:28)
    at ClientDuplexStreamImpl.emit (events.js:315:20)
    at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at ClientDuplexStreamImpl.Readable.push (internal/streams/readable.js:223:10)
    at Object.onReceiveMessage (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:382:24)
    at Object.onReceiveMessage (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:291:178)
    at /Applications/Postman.app/Contents/Resources/app.asar/node_modules/@grpc/grpc-js/build/src/call-stream.js:217:74
    at processTicksAndRejections (internal/process/task_queues.js:75:11)"}]
``` 

The default and service specific health checks appear to be working properly when using other client utilities (`grpcurl`, `grpc_cli`, etc.) but postman seems to have trouble with it.

### Steps To Reproduce

* have a grpc server that utilizes `grpc::EnableDefaultHealthCheckService(true);`
* using postman, create new grpc request, enter url and choose "use server reflection". 
* observe error

### Screenshots or Videos

<img width="448" alt="Screen Shot 2022-04-13 at 12 10 40 PM" src="https://user-images.githubusercontent.com/99883/163234777-a79070a4-53bf-498d-92a7-811aaecd0a72.png">

### Operating System

macOS

### Postman Version

9.15.13

### Postman Platform

Postman App

### Additional Context?

when disabling health checks, using postman grpc server reflection appears to work well.

**Comment by vitaliyantonov22** [comment]
The same one

**Comment by codenirvana** [comment]
@cgeers @vitaliyantonov22 can you share a demo repository to reproduce this behavior locally to fast-track the fix?

**Comment by pnquest** [comment]
I have just run into this, it doesn't specifically have to be the health check that is configured. Any service that hosts more than a single GRPC service on the same endpoint will cause this behavior. In asp.net core that would look like this in the startup code:

``` c#
app.UseEndpoints(e => 
{
  e.MapGrpcService<Service1>();
  e.MapGrpcService<Service2>();
});
```

If either map service call is commented out, postman will work fine, but when both are active, it fails.

**Comment by chadxzs** [comment]
I ran into this today as well. @pnquest description is reproducible for me, namely, having multiple services on the same port. I commented out my health check service and Postman reflection worked.

**Comment by DoktorGhost** [comment]
The issue might be that the proto file contains additional levels of nesting.
For example, I had something like this:

```
syntax = "proto3";

package myPkg;

import "direct1/direct2/direct3/direct4/direct5/myprotofile.proto";      <----- this is bag
import "google/protobuf/empty.proto"
```

And I was getting the exact same error as you.
But when I moved everything from the nested **direct1/direct2/direct3/direct4/direct5/myprotofile.proto** into a single file and removed the import, reflection started working.

**Comment by d3m1gd** [comment]
the fix is indeed in keeping imports to 3 parts of path, `import "dir/dir/file.proto"`, if path is longer, one gets the 'unknown error'

**Comment by DoktorGhost** [comment]
> the fix is indeed in keeping imports to 3 parts of path, `import "dir/dir/file.proto"`, if path is longer, one gets the 'unknown error'

it is also important how you generate the files from the proto-file. you need to look at this line
`--proto_path . \`
proto_path points to the import root, if you specify a non-absolute import path in one protofile, and an absolute one in another, then reflection will not work

importing the same file in different protofiles
one proto-file:
`import "api/grpc/protobuf/data/v1/data_3.proto";`

two proto-file:
`import "data/v1/data_3.proto";`

need to be brought to one form
if `import "api/grpc/protobuf/data/v1/data_3.proto";`
That `--proto_path . \`

or
if `import "data/v1/data_3.proto";`
That `--proto_path api/grpc/protobuf \`
