### ISSUE TITLE
Error: submitURL is a required option to crashReporter.start

### ISSUE THREAD

**Issue by mrcaidev** [a85/POSTMan-Chrome-Extension#11022]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman can't start via desktop icon, and when I tried to start it in terminal by `postman`, I got error outputs like:

```
The disableGPU setting is set to undefined
Not disabling GPU
App threw an error during load
Error: submitURL is a required option to crashReporter.start
    at CrashReporter.start (electron/js2c/browser_init.js:41:471)
    at /usr/share/postman/app/main.js:135:19
    at /usr/share/postman/app/node_modules/async/lib/async.js:718:13
    at iterate (/usr/share/postman/app/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/usr/share/postman/app/node_modules/async/lib/async.js:281:9)
    at _parallel (/usr/share/postman/app/node_modules/async/lib/async.js:717:9)
    at Object.async.series (/usr/share/postman/app/node_modules/async/lib/async.js:739:9)
    at Object.<anonymous> (/usr/share/postman/app/main.js:130:7)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: submitURL is a required option to crashReporter.start
    at CrashReporter.start (electron/js2c/browser_init.js:41:471)
    at /usr/share/postman/app/main.js:135:19
    at /usr/share/postman/app/node_modules/async/lib/async.js:718:13
    at iterate (/usr/share/postman/app/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/usr/share/postman/app/node_modules/async/lib/async.js:281:9)
    at _parallel (/usr/share/postman/app/node_modules/async/lib/async.js:717:9)
    at Object.async.series (/usr/share/postman/app/node_modules/async/lib/async.js:739:9)
    at Object.<anonymous> (/usr/share/postman/app/main.js:130:7)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
```

### Steps To Reproduce

1. Open terminal.
2. Execute `postman`.
3. See error outputs.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/78269445/174518408-c0d50268-0fee-49f9-991f-848d2c91bffb.png)

### Operating System

Arch Linux

### Postman Version

9.19.0

### Postman Platform

Postman App

**Comment by epubreader** [comment]
I have the same issue with postman, Operation system: manjaro

**Comment by RaisinTen** [comment]
@mrcaidev @epubreader how did y'all download Postman btw? Could y'all try to download it from https://www.postman.com and let me know if this issue still persists?

**Comment by RaisinTen** [comment]
I tried to install Postman v9.19.0 on a `manjaro-xfce-21.2.2-220123-linux515.iso` VM running on Parallels, both from https://www.postman.com as well as the snap (`sudo snap install postman`) and I'm not able to reproduce this error on either one of them. These are the [only officially supported ways of installing Postman on Linux](https://learning.postman.com/docs/getting-started/installation-and-updates/#installing-postman-on-linux), so my guess is that y'all are installing it from an untrusted source that changes the underlying version of Electron to run Postman, which is completely unsupported.

**Comment by epubreader** [comment]
can you remove postman and then try this command ` pacman -S postman`?
thanks.

**Comment by RaisinTen** [comment]
@epubreader I tried that and it produces an error for me:
```console
$ sudo pacman -S postman
error: target not found: postman
```

**Comment by mrcaidev** [comment]
> I tried to install Postman v9.19.0 on a `manjaro-xfce-21.2.2-220123-linux515.iso` VM running on Parallels, both from https://www.postman.com as well as the snap (`sudo snap install postman`) and I'm not able to reproduce this error on either one of them. These are the [only officially supported ways of installing Postman on Linux](https://learning.postman.com/docs/getting-started/installation-and-updates/#installing-postman-on-linux), so my guess is that y'all are installing it from an untrusted source that changes the underlying version of Electron to run Postman, which is completely unsupported.

Thanks! I installed Postman from official download website and it works. Maybe the problem is on the AUR side.

**Comment by RaisinTen** [comment]
> Maybe the problem is on the AUR side.

@mrcaidev Feel free to report the problem on the AUR issue tracker and drop a link here! We'll be happy to help out the maintainers, so that no one else has to face this problem. :)

**Comment by aminvakil** [comment]
I can run without a problem both from desktop and terminal.
