### ISSUE TITLE
Workspaces does not get loaded

### ISSUE THREAD

**Issue by gaurangpdl** [a85/POSTMan-Chrome-Extension#11094]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I installed latest postman version and It is not able to load workspaces. I am able to view my workspace in online/browser postman.

Issue is only for desktop app.

below is logs for the same.

`
[56531][1658164690487][requester][info]["SharedRuntimeListeners~boot - Success"]
[56531][1658164690488][requester][info]["booted - requester"]
[56531][1658164690557][requester][error]["IPCNode~createClient~something wrong connecting to the IPC server",{"errno":-2,"code":"ENOENT","syscall":"connect","address":"/Users/gaurangparmar/Library/Application Support/Postman/proxy_node_process_prod.sock","name":"Error","message":"connect ENOENT /Users/gaurangparmar/Library/Application Support/Postman/proxy_node_process_prod.sock","stack":"Error: connect ENOENT /Users/gaurangparmar/Library/Application Support/Postman/proxy_node_process_prod.sock\n    at __node_internal_captureLargerStackTrace (node:internal/errors:463:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:641:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1142:16)"}]
[56531][1658164690557][requester][info]["CloudProxyHandler: Proxy configuration has not been setup"]
[56531][1658164690581][requester][error]["CurrentUserDetailsService~failed-to-initialize",{"name":"TypeError","message":"Failed to fetch","stack":"TypeError: Failed to fetch\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:104:152118\n    at Function.request (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:5475)\n    at Object.request (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:2174:63019)\n    at H (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:4203:53234)\n    at init (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:66304)"},{"context":{"api":"CurrentUserDetailsService","domain":"iam"},"error":{}}]
[56531][1658164690584][requester][info]["Disconnected from Interceptor"]
[56531][1658164690596][requester][info]["SyncManagerNew~createSocket - socket url","https://bifrost-v4.getpostman.com"]
[56531][1658164690596][requester][info]["SyncManagerNew~createSocket","sailsIO.connect",{"url":"https://bifrost-v4.getpostman.com","opts":{"reconnectionDelay":10000,"reconnectionDelayMax":60000,"reconnectionAttempts":8,"randomizationFactor":0.3}}]
[56531][1658164690596][requester][info]["SyncManagerNew~createSocket - userContext: ",{"userId":"20789344","teamId":"0","os":"OS X 21.5.0","type":"app_native","version":"9.25.1-ui-220714-1251","productVersion":"9.25.1"}]
[56531][1658164690645][requester][info]["SessionValidation - Registering listener"]
[56531][1658164690649][requester][error]["performVersionLockCheck: Error while checking version lock",{"name":"TypeError","message":"Failed to fetch","stack":"TypeError: Failed to fetch\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:104:152118\n    at Function.request (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:5475)\n    at E (https://desktop.postman.com/_ar-assets/requester-desktop-d12bf0b7249ea23a8f87.min.js:239:26482)\n    at f (https://desktop.postman.com/_ar-assets/requester-desktop-d12bf0b7249ea23a8f87.min.js:239:24398)\n    at g (https://desktop.postman.com/_ar-assets/requester-desktop-d12bf0b7249ea23a8f87.min.js:239:23318)\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:85:9153\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:569:80946\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:104:163556\n    at h (https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:302:64734)\n    at p (https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:302:64638)\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:697:98741\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:104:163630\n    at s (https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:85:9448)\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:85:9252"}]
[56531][1658164690650][requester][info]["performVersionLockCheck: Checking cached response"]
[56531][1658164690651][requester][info]["performVersionLockCheck: Version is valid according to cached response"]
[56531][1658164690652][requester][warn]["prefetchWorkspaceData: Prefetching of data failed",{"name":"TypeError","message":"Failed to fetch","stack":"TypeError: Failed to fetch\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:104:152118\n    at Function.request (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:5475)\n    at Object.<anonymous> (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:892:15812)\n    at Generator.next (<anonymous>)\n    at https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:892:15704\n    at new Promise (<anonymous>)\n    at o (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:892:15449)\n    at Object.getWithGateway (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:892:15750)\n    at Object.<anonymous> (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:132105)\n    at Generator.next (<anonymous>)\n    at https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:131635\n    at new Promise (<anonymous>)\n    at b (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:131380)\n    at Object.getWorkspaceWithGateway (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:131956)\n    at a (https://desktop.postman.com/_ar-assets/requester-desktop-d12bf0b7249ea23a8f87.min.js:405:65783)"}]
[56531][1658164690653][requester][info]["UI pulled the session locked information on init"]
[56531][1658164690653][requester][error][{"name":"TypeError","message":"Failed to fetch","stack":"TypeError: Failed to fetch\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:104:152118\n    at Function.request (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:5475)\n    at o (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:4203:28867)\n    at init (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:2939:105915)\n    at r (https://desktop.postman.com/_ar-assets/requester-desktop-d12bf0b7249ea23a8f87.min.js:691:35439)\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:104:163556\n    at h (https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:302:64734)\n    at p (https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:302:64638)\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:697:98741\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:104:163630\n    at https://desktop.postman.com/_ar-assets/requester-desktop-d12bf0b7249ea23a8f87.min.js:371:4968"}]
[56531][1658164690667][requester][info]["ConnectionModeStore~_isFirstLoad",false]
[56531][1658164690681][requester][info]["NavigationService ~ [BROWSER] Transitioning io the initial route with the URL:","workspace/04add7d0-76a7-4dd5-8127-19546ea91560"]
[56531][1658164690853][requester][info]["SyncManagerNew~_onConnect"]
[56531][1658164690857][requester][info]["SyncManagerNew~signIn",{}]
[56531][1658164690857][requester][info]["setupVersionLockListener: Attached listener for version lock check events"]
[56531][1658164690858][requester][info]["SyncTimelineHelper: Force stopping all timelines"]
[56531][1658164690858][requester][info]["BaseSyncTimeline~forceStop: Force stop user:20789344"]
[56531][1658164690867][requester][info]["subscribeToTeamEvents: Bailing out as team ID is not available"]
[56531][1658164690869][requester][info]["BaseSyncTimeline~subscribe: Subscribing to real time changes for user:20789344"]
[56531][1658164690869][requester][info]["BaseSyncTimeline~_sync: Starting sync for user:20789344"]
[56531][1658164690870][requester][info]["BaseSyncTimeline~getPendingClientChanges: Starting to get pending changes for user:20789344"]
[56531][1658164690870][requester][info]["BaseSyncTimeline~getPendingClientChanges: Finished to get pending changes for user:20789344"]
[56531][1658164690870][requester][info]["BaseSyncTimeline~getPendingServerChanges: Starting /sync call for user:20789344"]
[56531][1658164690899][requester][info]["SyncManagerNew~setSync",true]
[56531][1658164690899][requester][info]["SyncManagerNew~signIn",{"forceConnect":false}]
[56531][1658164690899][requester][info]["SyncTimelineHelper: Force stopping all timelines"]
[56531][1658164690899][requester][info]["BaseSyncTimeline~forceStop: Force stop user:20789344"]
[56531][1658164690901][requester][info]["subscribeToTeamEvents: Bailing out as team ID is not available"]
[56531][1658164690902][requester][info]["BaseSyncTimeline~subscribe: Subscribing to real time changes for user:20789344"]
[56531][1658164690902][requester][info]["BaseSyncTimeline~_sync: Starting sync for user:20789344"]
[56531][1658164690903][requester][info]["BaseSyncTimeline~getPendingClientChanges: Starting to get pending changes for user:20789344"]
[56531][1658164690903][requester][info]["BaseSyncTimeline~getPendingClientChanges: Finished to get pending changes for user:20789344"]
[56531][1658164690903][requester][info]["BaseSyncTimeline~getPendingServerChanges: Starting /sync call for user:20789344"]
[56531][1658164690980][requester][info]["BaseSyncTimeline~SyncFinishedObservable: Successful sync proceeding with integrity check and force sync for user:20789344"]
[56531][1658164690980][requester][info]["BaseSyncTimeline~_handleForceSync: Bailing out of force sync for user:20789344"]
[56531][1658164690991][requester][info]["BaseSyncTimeline~SyncFinishedObservable: Successful sync proceeding with integrity check and force sync for user:20789344"]
[56531][1658164690991][requester][info]["BaseSyncTimeline~_handleForceSync: Bailing out of force sync for user:20789344"]
[56531][1658164691066][requester][error]["WorkspaceNavigationService~handleOpenWorkspace",{"name":"TypeError","message":"Failed to fetch","stack":"TypeError: Failed to fetch\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:104:152118\n    at Function.request (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:5475)\n    at Object.<anonymous> (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:892:15812)\n    at Generator.next (<anonymous>)\n    at https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:892:15704\n    at new Promise (<anonymous>)\n    at o (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:892:15449)\n    at Object.getWithGateway (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:892:15750)\n    at Object.<anonymous> (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:132105)\n    at Generator.next (<anonymous>)\n    at https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:131635\n    at new Promise (<anonymous>)\n    at b (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:131380)\n    at Object.getWorkspaceWithGateway (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:131956)\n    at y.<anonymous> (https://desktop.postman.com/_ar-assets/WorkspaceDetailsPage-b53c5722cc3b1666da80.min.js:41:31252)\n    at Generator.next (<anonymous>)\n    at s (https://desktop.postman.com/_ar-assets/WorkspaceDetailsPage-b53c5722cc3b1666da80.min.js:41:29308)"}]
[56531][1658164691067][requester][error]["WorkspacePageController~error occurred",{"name":"error","message":"Generic error while fetching","stack":"error: Generic error while fetching\n    at y.<anonymous> (https://desktop.postman.com/_ar-assets/WorkspaceDetailsPage-b53c5722cc3b1666da80.min.js:41:31774)\n    at Generator.throw (<anonymous>)\n    at o (https://desktop.postman.com/_ar-assets/WorkspaceDetailsPage-b53c5722cc3b1666da80.min.js:41:29359)"}]
[56531][1658164691156][requester][warn]["GateKeeperService~_handleKeyUpdate: Invalid key type provided",{"type":"flags","value":false}]
[56531][1658164691156][requester][info]["GateKeeperService~onNotificationToggle Key value toggled for Notification to true"]
[56531][1658164691156][requester][info]["GateKeeperService~onSyncToggle Key value toggled for Sync to true"]
[56531][1658164691156][requester][info]["GateKeeperService~onWebsocketToggle Key value toggled for Websocket to true"]
[56531][1658164691156][requester][warn]["SyncManagerNew~attachGateKeeperHandlers: listening to notification event",{"name":"notification","namespace":"gatekeeper","data":{"isEnabled":true}}]
[56531][1658164691163][requester][error][{"name":"TypeError","message":"Failed to fetch","stack":"TypeError: Failed to fetch\n    at https://desktop.postman.com/_ar-assets/vendors-bc416ace2416d78c4c89.min.js:104:152118\n    at Function.request (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1727:5475)\n    at Object.request (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:4379:24805)\n    at Object.getNotificationCenterIntegrations (https://desktop.postman.com/_ar-assets/common-7c435e00cf4efb65af8c.min.js:1:11877)\n    at Object.fetchNotificationCenterIntegrations (https://desktop.postman.com/_ar-assets/requester-desktop-d12bf0b7249ea23a8f87.min.js:691:28490)"}]
[56531][1658164703477][requester][warn]["ActiveViewManager~popActiveView: Cannot pop the last active view"]
[56531][1658164703478][requester][error]["ModalViewManager~ isClosed: The model with the name update-not-available does not exist in the active modals"]
`

### Steps To Reproduce

1. You already have workspace in 9.19.x and older.
2. Install latest version
3. Restart postman

### Screenshots or Videos

![2B27E51B-77B9-41D6-8727-7CF15954CB8F](https://user-images.githubusercontent.com/108284690/179568825-cfbf4f3d-d29e-46a4-8df5-af4d2cd3eb77.jpeg)

### Operating System

macOs

### Postman Version

9.25.1

### Postman Platform

Postman App

**Comment by akshay-kulkarni-03** [comment]
@gaurangpdl thanks for reporting this! I was unable to reproduce this issue as I also updated to latest 9.25.1 app version and workspace seems to be loading for me. Can you try to close the app and then open it again to see if its still happening?

**Comment by gaurangpdl** [comment]
I have closed multiple times and re-opened. I have uninstalled and  re-installed application still the same issue.

**Comment by DannyDainton** [comment]
Hey @gaurangpdl 

Can you try going to `Help > Clear Cache and Reload` to see if that makes a difference, please?

Do you see the Workspaces if you navigate to https://go.postman.co in a browser?

**Comment by gaurangpdl** [comment]
Hey Danny, 

As i mentioned online postman was working.

I just opened today and it has started working. I should close this.
