### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by sryze** [a85/POSTMan-Chrome-Extension#11205]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman gets stuck on the white loading screen

Error in console log:

```
C:\Users\myuser\AppData\Local\Postman\app-9.27.0\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:270 Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at C:\Users\myuser\AppData\Local\Postman\app-9.27.0\resources\app.asar\node_modules\@electron\remote\dist\src\main\server.js:77:24
    at Array.map (<anonymous>)
    at getObjectMembers (C:\Users\myuser\AppData\Local\Postman\app-9.27.0\resources\app.asar\node_modules\@electron\remote\dist\src\main\server.js:73:18)
    at valueToMeta (C:\Users\myuser\AppData\Local\Postman\app-9.27.0\resources\app.asar\node_modules\@electron\remote\dist\src\main\server.js:160:22)
    at C:\Users\myuser\AppData\Local\Postman\app-9.27.0\resources\app.asar\node_modules\@electron\remote\dist\src\main\server.js:485:16
    at IpcMainImpl.<anonymous> (C:\Users\myuser\AppData\Local\Postman\app-9.27.0\resources\app.asar\node_modules\@electron\remote\dist\src\main\server.js:322:27)
    at IpcMainImpl.emit (node:events:394:28)
    at IpcMainImpl.emit (node:domain:470:12)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:10774)
    at Object.emit (node:events:394:28)
    at Object.emit (node:domain:470:12)
```

### Steps To Reproduce

1. Start Postman

### Operating System

Windows 10

### Postman Version

9.27.0

### Postman Platform

Postman App

**Comment by MC-sanderv** [comment]
This is an older report from the v9 era and hasn’t had any updates. We’ve also seen newer reports of similar behaviour on more recent versions, and those are being tracked separately.

Since I can’t reproduce this on the latest Postman builds and this issue hasn’t been updated in a long time, I’m closing it out.

If anyone still runs into this on a specific version setup, please reopen with logs and system details.
