### ISSUE TITLE
Postman for Linux v10.6.0 crashes on window unminimize

### ISSUE THREAD

**Issue by kruthers64** [a85/POSTMan-Chrome-Extension#11548]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After the automatic update to 10.6.0, Postman always crashes when unminimizing.  Tried clearing config and disabling hardware acceleration with no luck.  Here's the output from the terminal after unminizing:

```
RangeError: Maximum call stack size exceeded
    at BrowserWindow.visibilityChanged (node:electron/js2c/browser_init:33:725)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/username/apps/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/username/apps/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/username/apps/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
1671033022128 main error "Main~handleUncaughtError - Uncaught errors",{"name":"RangeError","message":"Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded\n    at BrowserWindow.visibilityChanged (node:electron/js2c/browser_init:33:725)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/home/username/apps/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/home/username/apps/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/home/username/apps/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)"}
Main~handleUncaughtError - Uncaught errors RangeError: Maximum call stack size exceeded
    at BrowserWindow.visibilityChanged (node:electron/js2c/browser_init:33:725)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/username/apps/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/username/apps/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/username/apps/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
```

### Steps To Reproduce

1. Minimize postman (hide to the taskbar)
2. Unminimize

### Operating System

Linux 5.15.0-53-generic #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Postman Version

10.6.0

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by BehzadBz** [comment]
Same issue here. Installed flatpak version for now. I will wait for a fix.

**Comment by jviotti** [comment]
@dsanders11 Is this reproducible for you? Looks like an infinite loop with something around `BrowserWindow`?

**Comment by schadsey** [comment]
Same here. 10.6.0 on Ubuntu 18.04.6 LTS, 4.15.0-197-generic

Stack trace:

```
RangeError: Maximum call stack size exceeded
    at arrayClone (node:events:747:20)
    at BrowserWindow.emit (node:events:400:23)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/google/Postman/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/google/Postman/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/google/Postman/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
1671141328906 main error "Main~handleUncaughtError - Uncaught errors",{"name":"RangeError","message":"Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded\n    at arrayClone (node:events:747:20)\n    at BrowserWindow.emit (node:events:400:23)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/opt/google/Postman/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/opt/google/Postman/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/opt/google/Postman/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)"}
Main~handleUncaughtError - Uncaught errors RangeError: Maximum call stack size exceeded
    at arrayClone (node:events:747:20)
    at BrowserWindow.emit (node:events:400:23)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/google/Postman/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/google/Postman/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/google/Postman/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)


```

**Comment by fmiqbal** [comment]
Also happen in `Linux 6.0.12-arch1`,  using `i3-wm 4.21.1`, installed using pacman aur from `https://aur.archlinux.org/packages/postman-bin`, crashed when switching window
1. Open postman
2. Switch active window
3. Go back to postman
4. Crash

but it doesnt happen when switching workspace (let postman be in workspace 9), switch to other workspace, then switch back to workspace 9, it doesnt crash.`

also doesnt happen when using split screen or make postman float

Logs attached after crashing
[logs.zip](https://github.com/postmanlabs/postman-app-support/files/10255956/logs.zip)

**Comment by jerinajay** [comment]
https://user-images.githubusercontent.com/61222214/208599190-4cbb7faa-0a79-470a-b1b9-3ad135eb1254.mp4

**Comment by twitharshil** [comment]
Hey Folks, 

Thanks for reporting, this seems to be a legit issue.  We have the fix implemented and working in our internal builds, it will be available with the next release of Postman (v10.7.0).

**Comment by htr3n** [comment]
I got the same issue with Ubuntu 22.10 and Postman 10.6. Another relevant problem is, I tried to pin down Postman 10.5.8 by disabling the automated update but failed. After deleting Postman 10.6, cleaning all Postman configs and unpacked 10.5.8 and starting it, Postman still automatically downloads and updates to 10.6 when starting up, which causes the crashes over and over.

I tried to delete Postman and unpack the 10.5.8 and start it again. The option `Automatically download major updates` is disabled but Postman still downloads and updates to 10.6?

**Comment by VanlonTsai** [comment]
> I got the same issue with Ubuntu 22.10 and Postman 10.6. Another relevant problem is, I tried to pin down Postman 10.5.8 by disabling the automated update but failed. After deleting Postman 10.6, cleaning all Postman configs and unpacked 10.5.8 and starting it, Postman still automatically downloads and updates to 10.6 when starting up, which causes the crashes over and over.
> 
> I tried to delete Postman and unpack the 10.5.8 and start it again. The option `Automatically download major updates` is disabled but Postman still downloads and updates to 10.6?

Hi, Alex
My temp solution is add this record to /etc/hosts. It will cause auto download fail to avoid update.

```
# avoid postman auto update
127.0.0.1 dl.pstmn.io
```

**Comment by htr3n** [comment]
@VanlonTsai Thanks for the tips.

**Comment by proton5000** [comment]
i have the same issue on fedora 37, postman 10.6.7, version from flatpak with the same crash after unminimase the postman window
`Linux fedora 6.0.15-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Dec 21 18:33:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by rflitcroft** [comment]
It would be most useful if you could post a direct download link to the latest version of Postman for Linux64 which does *not* exhibit this bug. Some of us need to work without waiting for v10.7

**Comment by rflitcroft** [comment]
> I got the same issue with Ubuntu 22.10 and Postman 10.6. Another relevant problem is, I tried to pin down Postman 10.5.8 by disabling the automated update but failed. After deleting Postman 10.6, cleaning all Postman configs and unpacked 10.5.8 and starting it, Postman still automatically downloads and updates to 10.6 when starting up, which causes the crashes over and over.
> 
> I tried to delete Postman and unpack the 10.5.8 and start it again. The option `Automatically download major updates` is disabled but Postman still downloads and updates to 10.6?

Do you have a direct link for v 10.5.8? They are not easy to find.

**Comment by VanlonTsai** [comment]
@rflitcroft 
Hi, Richard
Here you are.

https://dl.pstmn.io/download/version/10.5.2/linux64

**Comment by romanpastu** [comment]
Same issue Postman 10.6 , and Fedora 36, using flatpak

**Comment by alysnnix** [comment]
I installed the `flatpack` version and I'm having the same problem but on Ubuntu 22.04.1 LTS

- It also doesn't appear in the dock until it finishes loading in the ubuntu panel ;-;


https://user-images.githubusercontent.com/26152669/210443365-659d82cd-7f48-43ad-bd0e-723caf9e0a42.mp4

**Comment by Ronnie76er** [comment]
I just downloaded 10.7, and the problem isn't there anymore.

**Comment by twitharshil** [comment]
Thanks for the confirmation @Ronnie76er. Marking the ticket as closed as it is now resolved.
