### ISSUE TITLE
Postman keep on crashing in Kali Linux

### ISSUE THREAD

**Issue by jerinajay** [a85/POSTMan-Chrome-Extension#11569]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After sending some request it's getting crashed

### Steps To Reproduce

```sh
$ /opt/Postman/app/postman
The disableGPU setting is set to undefined
Not disabling GPU
Main~createDefaultWorkingDir - Default working dir creation already attempted
1671444740770 main info "Booting Postman 10.6.0, linux-5.19.0-kali2-amd64 on x64"
1671444740771 main info "EventBus~initialize - Success"
1671444740774 main info "Proxy configuration has not been setup"
1671444740775 main info "CloudProxyManager~init - Success"
1671444740782 main info "UpdateHandler~init - Success"
1671444740784 main info "LeaderSelection: Initialized successfully"
1671444740785 main info "VersionDependencyService: Initialized successfully"
1671444740793 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1671444740806 main info "GPU detected VID 4318 DID 7476 ACTIVE true"
1671444740806 main info "GPU detected VID 32902 DID 39745 ACTIVE false"
[4369:1219/154220.810381:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
1671444741432 main info "RuntimeIPCAgent~started: Success"
1671444743020 main info "UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}
INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge
InterceptorBridge: Trying to connect Native App IPC~Interceptor Bridge
IPCClient ~ WindowHandler: New event is received { type: 'window-opened' }
1671444743036 main info "windowManager: First requester booted successfully."
1671444743037 main info "windowManager~restoreWindows: Restoring requester windows"
1671444743037 main info "Main~AppEvents - Received booted event for process requester.Version 10.6.7 UI Version: 10.6.7-ui-221210-1433 Desktop Platform Version: 10.6.0"
1671444743057 main info "performBackgroundShellMigration: Migration has already been done. Bailing out"
1671444744889 main info "Main - model-events~user - (user, bootstrapUser) received"
IPCClient ~ WindowHandler: New event is received { type: 'unmaximize', windowId: 1 }
IPCClient ~ WindowHandler: New event is received { type: 'maximize', windowId: 1 }
IPCClient ~ WindowHandler: New event is received { type: 'unmaximize', windowId: 1 }
IPCClient ~ WindowHandler: New event is received { type: 'resize', windowId: 1 }
IPCClient ~ WindowHandler: New event is received { type: 'resize', windowId: 1 }
IPCClient ~ WindowHandler: New event is received { type: 'resize', windowId: 1 }                                                                                                                                 
IPCClient ~ WindowHandler: New event is received { type: 'maximize', windowId: 1 }                                                                                                                               
IPCClient ~ WindowHandler: New event is received { type: 'resize', windowId: 1 }                                                                                                                                 
IPCClient ~ WindowHandler: New event is received { type: 'unmaximize', windowId: 1 }                                                                                                                             
IPCClient ~ WindowHandler: New event is received { type: 'maximize', windowId: 1 }                                                                                                                               
IPCClient ~ WindowHandler: New event is received { type: 'unmaximize', windowId: 1 }                                                                                                                             
IPCClient ~ WindowHandler: New event is received { type: 'resize', windowId: 1 }                                                                                                                                 
IPCClient ~ WindowHandler: New event is received { type: 'resize', windowId: 1 }                                                                                                                                 
RangeError: Maximum call stack size exceeded                                                                                                                                                                     
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)                                                                                                                                          
    at Object.windowBoundsHandler (/opt/Postman/app/resources/app/services/windowManager.js:1176:12)                                                                                                             
    at BrowserWindow.emit (node:events:402:35)                                                                                                                                                                   
    at BrowserWindow.emit (node:domain:475:12)                                                                                                                                                                   
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)                                                                                                                                          
    at Object.windowBoundsHandler (/opt/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
1671462390739 main error "Main~handleUncaughtError - Uncaught errors",{"name":"RangeError","message":"Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/opt/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/opt/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/opt/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/opt/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)"}
Main~handleUncaughtError - Uncaught errors RangeError: Maximum call stack size exceeded
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
IPCClient ~ WindowHandler: New event is received { type: 'resize', windowId: 1 }
(node:4330) UnhandledPromiseRejectionWarning: TypeError: Object has been destroyed
    at /opt/Postman/app/resources/app/services/windowManager.js:873:40
(Use `postman --trace-warnings ...` to show where the warning was created)
(node:4330) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/61222214/208457646-9d429586-1a3d-4543-b60e-72308018422d.png)

### Operating System

Linux

### Postman Version

10.6.7

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by abdullahwaqar** [comment]
Same issue but for me it happens after i minimize the application and then maximize, attached the log below

```
1671466122662 main info "windowManager: First requester booted successfully."
1671466122662 main info "windowManager~restoreWindows: Restoring requester windows"
1671466122663 main info "Main~AppEvents - Received booted event for process requester.Version 10.6.7 UI Version: 10.6.7-ui-221210-1433 Desktop Platform Version: 10.6.0"
1671466122678 main info "performBackgroundShellMigration: Migration has already been done. Bailing out"
1671466125359 main info "Main - model-events~user - (user, bootstrapUser) received"
RangeError: Maximum call stack size exceeded
    at Object.windowBoundsHandler (/home/awr417h/bin/Postman/app/resources/app/services/windowManager.js:1157:20)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/awr417h/bin/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/awr417h/bin/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/awr417h/bin/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
1671466130031 main error "Main~handleUncaughtError - Uncaught errors",{"name":"RangeError","message":"Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded\n    at Object.windowBoundsHandler (/home/awr417h/bin/Postman/app/resources/app/services/windowManager.js:1157:20)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/home/awr417h/bin/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/home/awr417h/bin/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/home/awr417h/bin/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)"}
Main~handleUncaughtError - Uncaught errors RangeError: Maximum call stack size exceeded
    at Object.windowBoundsHandler (/home/awr417h/bin/Postman/app/resources/app/services/windowManager.js:1157:20)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/awr417h/bin/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/awr417h/bin/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/awr417h/bin/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
```

#11548

**Comment by jviotti** [comment]
Thanks for the reproduction steps @abdullahwaqar. @twitharshil @thundron Can you take a look at this whenever you get a chance?

**Comment by numaanashraf** [comment]
Duplicate of #11548
