### ISSUE TITLE
Postman memory leak leading to application crash

### ISSUE THREAD

**Issue by cmroxy** [a85/POSTMan-Chrome-Extension#11562]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am observing a memory leak within Postman App with a simple collection run (looping over the same request).
The Postman App process crashes when the process used memory is reaching 3.5/4 GBytes of RAM.

[Performance.postman_collection.json.txt](https://github.com/postmanlabs/postman-app-support/files/10251412/Performance.postman_collection.json.txt)

### Steps To Reproduce

1. Create a New Collection
2. Create a Dummy Request calling https://postman-echo.com/get
3. In the Pre-request Script of the Dummy request, insert the following code : postman.setNextRequest("Dummy")
4. Run the collection
5. At OS level , observe the process memory used by the Postman App
6. The memory used will keep growing, leading to the Postman Application crash when process memory reaches 3-4 Gb after 2-3 minutes. This has been reproduced on Windows and MacOS

### Operating System

MacOS

### Postman Version

10.6.0

### Postman Platform

Postman App

### User Account Type

Signed Out User

### Additional Context?

It might be related to the Postman local environments (how much history, how many collections are avalaible in the postman app).  A fresh new environment doesn't seem to cause crash immediately (slower "memory leak")

**Comment by marcpo** [comment]
Similar issue for me. Seeing 2 processes (Postman and Postman renderer). The memory goes up to the early 3GB and the Postman application crashes.
- There are about 100 requests perform during the run (before the crash)
- Mostly PUT requests with a payload size around 5MB => 5MB x 100 => 500 MB => far from 3GB.
- Using Pre-request Script to build the PUT payload

That's a blocker for us.

**Comment by malvikach** [comment]
Hi @cmroxy @marcpo  

Thanks for sharing your feedback. 

We are working on Performance Improvements for Collection Runner to improve its memory usage (by freeing up memory during the run). The changes are to be released in the next few days. I will keep you updated once the release is done. 

Appreciate any feedback you can provide on this. 

Thanks Again

**Comment by asoltesz** [comment]
Same issue for me (v8.5.1, Windows 10).

I create a Collection Runner set for 3000 execution with very simple and small requests. 
After I start executing the set in the Runner, it starts gobbling up memory like crazy.

After a short while (couple of minutes) it crashes.
(or Windows kills it, I don't know which because it puts memory usage over 90%)

This is an important feature but practically unusable as it is.

**Comment by malvikach** [comment]
We have done some improvements in the latest versions of Postman (v10.12.0). This should improve memory usage by runner (by freeing up memory during the run). It would help if you upgrade the app version and try it out.

Our internal benchmarking suggests that this should improve the usage by 2x( the same amount of memory to be consumed for double the no.of iterations or double the size of the collection)

Please let us know your feedback on the above and if this helps your workflows. We are also identifying other avenues to improve memory usage by Runner and avoid the occurrence of App Crashes. We will keep this issue updated with more news. 

Cheers!
Malvika

**Comment by edwardbeckett** [comment]
I'm experiencing the same behavior running Postman 10.12.0 on Windows 10 Pro. 
I was able to trace the stack to an uncaught error... Pretty sure we have a race condition. 
This should be fun. Here's the germane info...  

```json 
[main][error]["Main~handleUncaughtError` - Uncaught errors",
{"name":"Error",
"message":"Render frame was disposed before WebFrameMain could be accessed",
"stack":"Error: Render frame was disposed before WebFrameMain could be accessed
```

**Comment by pranavp-miro** [comment]
Any update on this issue. I have been facing it (on mac) for sometime and it's pretty annoying.
```
[67578][1688734600626][main][info]["Main~AppEvents - Received booted event for process requester.Version undefined UI Version: undefined Desktop Platform Version: 10.15.0"]
[67578][1688734724388][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"Error","message":"Render frame was disposed before WebFrameMain could be accessed","stack":"Error: Render frame was disposed before WebFrameMain could be accessed\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:19)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:9)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:9)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:94:9)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:9)\n    at stringify (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:25:3)\n    at Format.transform (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/logform/json.js:24:19)\n    at DerivedLogger._transform (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/winston/lib/winston/logger.js:235:29)\n    at DerivedLogger.Transform._read (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:184:10)\n    at DerivedLogger.Transform._write (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:172:83)\n    at doWrite (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:428:64)\n    at writeOrBuffer (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:417:5)\n    at DerivedLogger.Writable.write (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:334:11)\n    at DerivedLogger.log (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/winston/lib/winston/logger.js:164:14)\n    at /Applications/Postman.app/Contents/Resources/app.asar/node_modules/@postman/app-logger/lib/collectors/AbstractCollector.js:33:23\n    at Array.forEach (<anonymous>)"}]
```

**Comment by thundron** [comment]
Hello everyone, a question just to better check the provided information: @edwardbeckett how did you trace the memory leak back to the error you pasted? Can you share some more information on the debugging maybe?
To me that seems to be a one-off which is not related to the leak in question; it is much more likely that the Collection code itself is, at some point, running into a higher and higher memory leak over time, which the error you mentioned shouldn't be a part of.
Are you able for instance to see that error for as many times as the requests are with coinciding times?

**Comment by edwardbeckett** [comment]
> Hello everyone, a question just to better check the provided information: @edwardbeckett how did you trace the memory leak back to the error you pasted? Can you share some more information on the debugging maybe? To me that seems to be a one-off which is not related to the leak in question; it is much more likely that the Collection code itself is, at some point, running into a higher and higher memory leak over time, which the error you mentioned shouldn't be a part of. Are you able for instance to see that error for as many times as the requests are with coinciding times?

My apologies... that has been some time ago and I must admit that I abandoned working with Postman as this issue was a major showstopper for me... I pivoted to a more robust and sustainable solution.

**Comment by thundron** [comment]
Happy to hear that! On the other hand, we didn't find any traces leading to the error you mentioned as it is, in fact, unrelated so if anybody else has more information to share, it will be welcome!

**Comment by Gnarnaw2** [comment]
I'm in the same boat. It loads up 9 GBs of RAM then crashes. I'm just about to abandon it.

**Comment by wwangsa** [comment]
I have the same error message as edwardbecket and pranavp-miro.. Based on the log, it's related to the collector. I'm on OSx 14.3.1 and Postman 10.22.13. On a typical day, I run multiple requests and I keep Postman open. It always crash on me when I run one of the flows. After crash, the flow runs just fine. 

Seeing from the responses above, it seems related to memory usage. Each time I run my flow, it will increase about 200 MB. After the Postman's memory usage reaches 1GB, the usage drops back to 500MB. I wonder if this related to how much memory left in the OS when the usage reaches 1GB. I looked at mac's memory and it only has 2GB free out of 16GB.


`[main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"Error","message":"Render frame was disposed before WebFrameMain could be accessed","stack":"Error: Render frame was disposed before WebFrameMain could be accessed\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:19)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:9)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:9)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:94:9)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:9)\n    at stringify (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:25:3)\n    at Format.transform (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/logform/json.js:24:19)\n    at DerivedLogger._transform (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/winston/lib/winston/logger.js:235:29)\n    at DerivedLogger.Transform._read (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:184:10)\n    at DerivedLogger.Transform._write (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:172:83)\n    at doWrite (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:428:64)\n    at writeOrBuffer (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:417:5)\n    at DerivedLogger.Writable.write (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:334:11)\n    at DerivedLogger.log (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/winston/lib/winston/logger.js:164:14)\n    at /Applications/Postman.app/Contents/Resources/app.asar/node_modules/@postman/app-logger/lib/collectors/AbstractCollector.js:33:23\n    at Array.forEach (<anonymous>)"}]`

**Comment by malvika-chaudhary** [comment]
Hi all 👋

Been a while but wanted to inform you that we have made some important Performance Improvements to collection runner to reduce the CPU utilization/overhead especially while running large collections. 

Please let us know if you still see any issues while running collections. I will be closing this ticket but please do not hesitate to reopen and inform us about any issues that you might still be seeing. 

Cheers!
Malvika
