### ISSUE TITLE
Postman desktop app closed unexpectly

### ISSUE THREAD

**Issue by ramrasi** [a85/POSTMan-Chrome-Extension#11571]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

when try to open Postman desktop app from Taskbar. it closed unexpectedly.

### Steps To Reproduce

try to minimize and maximize the App on Linux

### Operating System

Linux

### Postman Version

10.6.0

### Postman Platform

Postman App

### User Account Type

Signed Out User

### Additional Context?

[27839][1671512429131][main][info]["Booting Postman 10.6.0, linux-5.15.79-51.138.amzn2.x86_64 on x64"]
[27839][1671512429135][main][info]["EventBus~initialize - Success"]
[27839][1671512429140][main][info]["Proxy configuration has not been setup"]
[27839][1671512429141][main][info]["CloudProxyManager~init - Success"]
[27839][1671512429162][main][info]["UpdateHandler~init - Success"]
[27839][1671512429165][main][info]["LeaderSelection: Initialized successfully"]
[27839][1671512429167][main][info]["VersionDependencyService: Initialized successfully"]
[27839][1671512429182][main][info]["LinuxAutoUpdater~Cleanup - Initial cleanup successful"]
[27839][1671512429229][main][info]["GPU detected VID 7439 DID 4369 ACTIVE true"]
[27839][1671512430497][main][info]["RuntimeIPCAgent~started: Success"]
[27839][1671512432579][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[27839][1671512432602][main][info]["windowManager: First requester booted successfully."]
[27839][1671512432602][main][info]["windowManager~restoreWindows: Restoring requester windows"]
[27839][1671512432603][main][info]["Main~AppEvents - Received booted event for process requester.Version undefined UI Version: undefined Desktop Platform Version: 10.6.0"]
[27839][1671512525856][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"RangeError","message":"Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded\n    at arrayClone (node:events:747:20)\n    at BrowserWindow.emit (node:events:400:23)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/home/xxxxxxxxxx/Tools/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/home/xxxxxxxxxx/Tools/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/home/xxxxxxxxxx/Tools/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)"}]

**Comment by numaanashraf** [comment]
Duplicate of #11548
