### ISSUE TITLE
Postman window disappear when minimize and restore again

### ISSUE THREAD

**Issue by VanlonTsai** [a85/POSTMan-Chrome-Extension#11578]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman window disappear when I minimize the window and restore again.

### Steps To Reproduce

1. Start a Postman
2. Click minimize button at top-right of the window
3. Click Postman at the task bar

### Screenshots or Videos

![2022-12-21-Postman-01](https://user-images.githubusercontent.com/121168691/208901891-569aa9fd-98d9-43f6-8c2b-f3ea0e6eb27c.png)
![2022-12-21-Postman-02](https://user-images.githubusercontent.com/121168691/208901929-6c872740-6564-4c69-b915-9d42bc79a12c.png)
![2022-12-21-Postman-03](https://user-images.githubusercontent.com/121168691/208901946-9519e15a-ed61-44c6-8d31-1c1242865071.png)
![2022-12-21-Postman-04](https://user-images.githubusercontent.com/121168691/208901966-09f831e9-0a46-4fde-8cf6-699cf40ae73e.png)
![2022-12-21-Postman-05](https://user-images.githubusercontent.com/121168691/208901982-84ccfcee-f79e-4eab-9579-a683dd6c564f.png)

### Operating System

Linux Mint 20.1 x86_64

### Postman Version

10.6.0

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

The error message in the terminal console as follow.

```
vanlon@LinuxMint:~/software/Postman$ ./Postman 
The disableGPU setting is set to true
Disabling GPU
Setting disableGPU to true

(postman:16723): Gtk-WARNING **: 19:47:59.153: Theme parsing error: gtk-contained.css:307:4332: Not using units is deprecated. Assuming 'px'.

(postman:16723): Gtk-WARNING **: 19:47:59.153: Theme parsing error: gtk-contained.css:307:4368: Not using units is deprecated. Assuming 'px'.

(postman:16723): Gtk-WARNING **: 19:47:59.157: Theme parsing error: gtk-contained.css:347:4379: Not using units is deprecated. Assuming 'px'.

(postman:16723): Gtk-WARNING **: 19:47:59.157: Theme parsing error: gtk-contained.css:347:4416: Not using units is deprecated. Assuming 'px'.

(postman:16723): Gtk-WARNING **: 19:47:59.270: Theme parsing error: gtk-contained.css:914:51: negative values are not allowed.
[16758:1221/194759.477285:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is 
Main~createDefaultWorkingDir - Default working dir creation already attempted
1671623279517 main info "Booting Postman 10.6.0, linux-5.4.0-135-generic on x64"
1671623279518 main info "EventBus~initialize - Success"
1671623279520 main info "Proxy configuration has not been setup"
1671623279521 main info "CloudProxyManager~init - Success"
1671623279529 main info "UpdateHandler~init - Success"
1671623279531 main info "LeaderSelection: Initialized successfully"
1671623279531 main info "VersionDependencyService: Initialized successfully"
1671623279540 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1671623280163 main info "RuntimeIPCAgent~started: Success"
[16723:1221/194800.654682:ERROR:nss_util.cc(286)] After loading Root Certs, loaded==false: NSS error code: -8018
1671623281619 main info "UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}
INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge
InterceptorBridge: Trying to connect Native App IPC~Interceptor Bridge
1671623281631 main info "windowManager: First requester booted successfully."
1671623281631 main info "windowManager~restoreWindows: Restoring requester windows"
1671623281631 main info "Main~AppEvents - Received booted event for process requester.Version undefined UI Version: undefined Desktop Platform Version: 10.6.0"
IPCClient ~ WindowHandler: New event is received { type: 'window-opened' }
RangeError: Maximum call stack size exceeded
    at Object.windowBoundsHandler (/home/vanlon/software/Postman/app/resources/app/services/windowManager.js:1157:20)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/vanlon/software/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/vanlon/software/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/vanlon/software/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
1671623332460 main error "Main~handleUncaughtError - Uncaught errors",{"name":"RangeError","message":"Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded\n    at Object.windowBoundsHandler (/home/vanlon/software/Postman/app/resources/app/services/windowManager.js:1157:20)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/home/vanlon/software/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/home/vanlon/software/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/home/vanlon/software/Postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)"}
Main~handleUncaughtError - Uncaught errors RangeError: Maximum call stack size exceeded
    at Object.windowBoundsHandler (/home/vanlon/software/Postman/app/resources/app/services/windowManager.js:1157:20)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/vanlon/software/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/vanlon/software/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/home/vanlon/software/Postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
```

**Comment by mreschke** [comment]
I have the same issue.
OS: Manjaro (latest)
Window Manager: i3

Postman for Linux
Version 10.6.7
UI Version 10.6.7-ui-221210-1433
Desktop Platform Version 10.6.0
Architecture x64
OS Platform linux 5.15.78-1-MANJARO

Opening and running Postman works great, until I switch to another window, then switch back to postman, it crashes and dies.


```
$> postman                                                                                                                                                                                                                     
The disableGPU setting is set to undefined
Not disabling GPU
Main~createDefaultWorkingDir - Default working dir creation already attempted
1671663392499 main info "Booting Postman 10.6.0, linux-5.15.78-1-MANJARO on x64"
1671663392499 main info "EventBus~initialize - Success"
1671663392501 main info "Proxy configuration has not been setup"
1671663392501 main info "CloudProxyManager~init - Success"
1671663392506 main info "UpdateHandler~init - Success"
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
1671663392508 main info "LeaderSelection: Initialized successfully"
1671663392508 main info "VersionDependencyService: Initialized successfully"
[1273453:1221/155632.509443:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
1671663392515 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1671663392523 main info "GPU detected VID 4318 DID 8124 ACTIVE true"
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[1273500:1221/155632.588146:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[1273555:1221/155632.651277:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[1273608:1221/155632.672388:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[1273608:1221/155632.673950:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
1671663392967 main info "RuntimeIPCAgent~started: Success"
1671663393986 main info "UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}
INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge
InterceptorBridge: Trying to connect Native App IPC~Interceptor Bridge
IPCClient ~ WindowHandler: New event is received { type: 'window-opened' }
1671663394002 main info "windowManager: First requester booted successfully."
1671663394003 main info "windowManager~restoreWindows: Restoring requester windows"
1671663394003 main info "Main~AppEvents - Received booted event for process requester.Version 10.6.7 UI Version: 10.6.7-ui-221210-1433 Desktop Platform Version: 10.6.0"
1671663394013 main info "performBackgroundShellMigration: Migration has already been done. Bailing out"
1671663394771 main info "Main - model-events~user - (user, bootstrapUser) received"

----------------------
Postman starts and works fine. When I switch away, and come back to the Postman window, I get this error and Postman dies.
----------------------

RangeError: Maximum call stack size exceeded
    at BrowserWindow.emit (node:events:340:44)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/postman/app/resources/app/services/windowManager.js:1176:12)
1671663396846 main error "Main~handleUncaughtError - Uncaught errors",{"name":"RangeError","message":"Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded\n    at BrowserWindow.emit (node:events:340:44)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/opt/postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/opt/postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/opt/postman/app/resources/app/services/windowManager.js:1176:12)\n    at BrowserWindow.emit (node:events:402:35)\n    at BrowserWindow.emit (node:domain:475:12)\n    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)\n    at Object.windowBoundsHandler (/opt/postman/app/resources/app/services/windowManager.js:1176:12)"}
Main~handleUncaughtError - Uncaught errors RangeError: Maximum call stack size exceeded
    at BrowserWindow.emit (node:events:340:44)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/postman/app/resources/app/services/windowManager.js:1176:12)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at Object.windowBoundsHandler (/opt/postman/app/resources/app/services/windowManager.js:1176:12)
```

**Comment by numaanashraf** [comment]
Duplicate of #11548
