### ISSUE TITLE
Can not download a large file using Postman

### ISSUE THREAD

**Issue by sprice9161** [a85/POSTMan-Chrome-Extension#11644]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I need to support a download of 1 GB for our customers. We have a series of requests that result in a URL for the user to download a single file using an encoded file token inserted into the endpoint or a url in the case of multiple files where a url is generated. 

Using Postman, when I test multiple files equating a to a zip file of 129 mb and place the URL in a standalone request clicking "Send and Download", the request will fail around 2 minutes in. See screen shot). When the request is run in the folder with the other requests, Postman crashes (shuts down) and has to be restarted.

Small files seem to work fine. I haven't yet determined exactly how large of a file I can successfully download.

Note: This is not an issue if I paste the URL's directly into a browser and  download the files.

Request Timeout is set to "0"
Max Response size is set to "0"

### Steps To Reproduce

1. Open a new request tab
2. Select GET operation
3. Enter the url "https://auto-newforma-punchlistitems-supporteddocs-upload.s3.us-east-2.amazonaws.com/1gb.test"
This is an S3 bucket in AWS requiring No Authorization.
Here is another 1 gb file form a free test file hosting site "https://speed.hetzner.de/1GB.bin"

Executing the requests standalone may run for about 5 min. Sometimes Postman crashes and sometimes it displays an error. There is nothing in the console to indicate what the error might be other than to say that nothing responded.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/18660936/213005680-392c8dbe-f954-43ae-94e2-c1e3b2871a13.png)
![image](https://user-images.githubusercontent.com/18660936/213005735-3c70ea3c-cddb-43ec-b1d3-5f3dd7841e2a.png)

### Operating System

Windows 10 Pro

### Postman Version

10.8

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

[main.log](https://github.com/postmanlabs/postman-app-support/files/10460262/main.log)
[renderer-requester.log](https://github.com/postmanlabs/postman-app-support/files/10460264/renderer-requester.log)

**Comment by giridharvc7** [comment]
@sprice9161 Thank you for reporting this issue, what is your intention with these downloads? Do you want them to be stored in your machine/wokring directory or do you intend to do something with the large responses?

**Comment by sprice9161** [comment]
The goal is to provide our customer the ability to download a single file. The download endpoint requires no authentication. Our customers interface with our application thought our endpoints. The files in this instance will be media files such as jpgs, or mp4. The could also be construction layout files like an Autodesk file, or spec documentation in the form of PDF's. The largest file that I have been able to download using Postman is 110 mb. I was told that you should support up to 770mb.

I believe the customer plans on passing the file along. Our application is a backend in a larger system.  Our standalone application is self contained but in this environment our customers use another application similar in nature to our own and we server as the backend with our functionality so that they can take advantage of our existing features. The files get attached to objects that we call PunchlistItem. Supporting documents are uploaded to the object and downloaded when an event is detected based on a GET query. We build a list of files based on this event filter and the files are then downloaded and moved within this eco system. I don't know exactly where they go but if it is of importance I can find out.

For the time being I am performing the downloads manually by coping the URL from the previous request into a browse.

**Comment by yormy** [comment]
When I try to download a file of 680MB postman just quits (Postman for Linux Version 9.31.0)

**Comment by mljohns89** [comment]
+1 Having this issue too.  @giridharvc7 is there any timeline on this fix yet?  

Here is error in the logs from crash:  `main.log`

```
[91992][1686849556122][main][error]["Main~handleUncaughtError - Uncaught errors",{
    "code": "ERR_STRING_TOO_LONG",
    "name": "Error",
    "message": "Cannot create a string longer than 0x1fffffe8 characters",
    "stack": "Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:642:37)   at Buffer.toString (node:buffer:811:14)
       at getResponseJSON (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/postman-runtime/lib/runner/extensions/item.command.js:71:35)
       at PostmanCollectionRun.<anonymous> (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/postman-runtime/lib/runner/extensions/item.command.js:212:61)
       at apply (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:489:27)
       at /Applications/Postman.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:9541:36
       at /Applications/Postman.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:4943:15
       at Function.<anonymous> (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:9540:7)
       t apply (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:490:27)
       at Function.invokeMap (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:6627:16)
       at Instruction.<anonymous> (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/postman-runtime/lib/runner/instruction.js:148:48)
       at PostmanCollectionRun.<anonymous> (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/postman-runtime/lib/runner/extensions/request.command.js:79:28)
       at PostmanCollectionRun.<anonymous> (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/postman-runtime/lib/runner/extensions/request.command.js:95:21)
       at apply (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:489:27)
       at /Applications/Postman.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:9541:36
       at /Applications/Postman.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:4943:15"
}]
```

**Comment by tools400** [comment]
Same with me and Postman v11.29.0 when downloading a folder from a JFrog Artifactory:

```bash
curl --location 'https://{{artifactory_server}}/artifactory/api/archive/download/binaries/com/obi/activemq?archiveType=zip'
```

From the `main.log` file:

```text
[8616][1737363091540][main][error]["Main~handleUncaughtError - Uncaught errors",{"code":"ERR_STRING_TOO_LONG","name":"Error",
  "message":"Cannot create a string longer than 0x1fffffe8 characters",
  "stack":"Error: Cannot create a string longer than 0x1fffffe8 characters
  ...
```

**Comment by Petersdavis** [comment]
Upvote  -- our use case creating a server for streaming modified docker tarballs.

**Comment by hero3616** [comment]
Same issue here. PowerShell (Invoke-WebRequest), curl, Chrome works for ~6GB files but Postman just runs the request forever and Cancel button becomes unresponsive. Small files work fine. I have Settings -> General -> Max response size set to 0 (unlimited).
