### ISSUE TITLE
Loading External JS Files

### ISSUE THREAD

**Issue by jaybillhighway** [a85/POSTMan-Chrome-Extension#1180]
We have a lot of code that I like to load into Pre-Request script Sandbox instead of cutting and pasting . Can that be done, may be support requirejs ? or simple reference to a CDN js ?

Thanks

Jay

**Comment by abhijitkane** [comment]
We're working on a way to allow import of custom JS files into the scripting sandbox, but can't offer an approximate date right now.

**Comment by johnnavarra** [comment]
You can modify the tester_sandbox.html in the AppData\Local\Google\Chrome\User Data\Default\Extensions\fhbjgbiflinjbdggehcddcbncdddomop directory to include the js files. The caveat is that an update to the packaged extension will overwrite your changes, so backup your changes regularly.

The other option is to import via jQuery:

// Import the CryptoJS library with jQuery
$.getScript("http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/sha256.js", 
function() 
{});

the problem with this is that using that import takes two actions so running this with collector will make a false test.

**Comment by abernix** [comment]
I'm using getScript myself, as well.  The caveat mentioned above is true, but as mentioned, it doesn't work properly until the second request, and all your results are from the previous call.  I guess this is my :+1:

**Comment by abernix** [comment]
I guess some sort of callback would make it work okay too.

i.e. `postman.wait()` makes it not execute the actual request until you call `postman.ready()` yourself? Or something.

**Comment by dotCipher** [comment]
+1 on this

**Comment by yiweig** [comment]
Any update on this? would also like to include external js libraries

**Comment by abtiddle** [comment]
+1 on this

**Comment by jackrabb1t** [comment]
+1

**Comment by rohan-pulekar** [comment]
Any updates on this?
I was using postman app and created a test case in it. My Tests tab has:

$.getScript("/Users/rpulekar/work/workspace_for_sothebys/sample.js", 
function() 
{});
function1();

And my sample.js has:
function function1() {
    tests["test2"] = responseCode.code === 200;
}

When I run the test, I get:

> There was an error evaluating the test script.  function1 is not defined

**Comment by deive** [comment]
If it helps you can put js into an environment variable and load it with:
`eval(postman.getGlobalVariable("environment variable key"));`

**Comment by johnnavarra** [comment]
That's a great idea!

On Wed, Mar 9, 2016 at 5:24 AM, deive notifications@github.com wrote:

> If it helps you can put js into an environment variable and load it with:
> eval(postman.getGlobalVariable("environment variable key"));
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmanlabs/postman-app-support/issues/1180#issuecomment-194226755
> .

## 

AIM: obliviouslyaware
ICQ: 5147787
googletalk

**Comment by shamasis** [comment]
Yeah. Make a request to your JS and in its test script, save the response in a global or environment variable. Then in subsequent scripts, simply eval the variable at the beginning.

**Comment by bijeebuss** [comment]
+1

**Comment by IPWright83** [comment]
I want to be able to do this - but I want to do this for the **Tests** rather than the pre-request script. I've put together a JavaScript snippet that mimicks Jasmine syntax to allow for a richer set of tests to be built (and will automatically include additional information in the test name if it fails) - but it's a lot of code to paste at the end of each test case.

I've also tried to use jQuery.getScript but the Tests run synchronously so I end up with no tests being executed when I'm reliant on the jQuery callback.

**Comment by IPWright83** [comment]
@johnnavarra I just read your comment about the tester_sandbox.html - that's incredibly useful, thanks! I've managed to include some custom scripts and now have a lovely testing interface. If I can I'll try and share the code to do this later:

![image](https://cloud.githubusercontent.com/assets/1374775/14859321/9041f5ee-0c9b-11e6-9752-228c3143a256.png)

**Comment by shamasis** [comment]
Hi, the presently suggested way to include external script is by using a request to fetch its content. See - http://blog.getpostman.com/2015/09/29/writing-a-behaviour-driven-api-testing-environment-within-postman/ and https://github.com/BigstickCarpet/postman-bdd

In this way, you'll be safe from breakage caused by future changes to internal app architecture or Chrome platform changes.

**Comment by IPWright83** [comment]
@shamasis Thanks for that - looks like a useful way of doing it.

**Comment by johnnavarra** [comment]
@Shamasis this is FANTASTIC! Thank you!

On Thu, Apr 28, 2016 at 1:27 AM, Shamasis Bhattacharya <
notifications@github.com> wrote:

> Hi, the presently suggested way to include external script is by using a
> request to fetch its content. See -
> http://blog.getpostman.com/2015/09/29/writing-a-behaviour-driven-api-testing-environment-within-postman/
> and https://github.com/BigstickCarpet/postman-bdd
> 
> In this way, you'll be safe from breakage caused by future changes to
> internal app architecture or Chrome platform changes.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/postmanlabs/postman-app-support/issues/1180#issuecomment-215313568

## 

AIM: obliviouslyaware
ICQ: 5147787
googletalk

**Comment by shamasis** [comment]
I'm so glad. We're also working towards getting to a more elegant solution to this and work around Chrome platform restrictions to get there. Will post an update when there's something interesting.

**Comment by stianlagstad** [comment]
+1. Glad you're working on this!

**Comment by tariqghalib** [comment]
I am new to postman testing. I am currently trying to load an external script that I wrote to pull some db data as part of pre-request script. The script is:

var express = require('express');
var app = express();
app.get('/', function (req, res) {

var sql = require("mssql");
// config for your database
var config = {
user: 'xxxx',
password: 'xxxx',
server: 'xxx.xx.xx.xx', 
database: 'xxxxxxxx', 
port: xxxx
};
// connect to your database
sql.connect(config, function (err) {
if (err) console.log(err);
// create Request object
var request = new sql.Request();
// query to the database and get the records
request.query('SELECT \* FROM xxxxx', function (err, recordset) {
if (err) console.log(err)
// send records as a response
res.send(recordset);

});
});
});
var server = app.listen(5000, function () {
console.log('Server is running..');
});

I have tried to add this through $.getScript ('myScript') way and through adding the script as an environment variable but its throwing an error. Any help will be much appreciated!

Version/App Information:
-->

Postman Version: 4.4.2
App (Chrome app or Mac app): Chrome
OS details: Windows 7 professional
Is the Interceptor on and enabled in the app: Yes
Did you encounter this recently, or has this bug always been there: Its not a default feature
Expected behaviour: Import the external JS scripts successfully
Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Error: Cannot find module 'express'
at s (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/request-snippet-generator.js:1:156)
at s (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/request-snippet-generator.js:1:122)
at eval (eval at loadCustomFile (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/tester/Evaluator.js:238:39), :1:27)
at eval (eval at loadCustomFile (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/tester/Evaluator.js:238:39), :40:3)
at r.loadCustomFile (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/tester/Evaluator.js:238:34)
at chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/tester/Evaluator.js:215:25

STEPS:

Add the above script as a pre-request script
In the Test tab do: $.getScript('Path_to_myscript');

Second Way:

Add the script as a global environment variable
In the Test tab do: eval(postman.getGlobalVariable('Path_to_myscript'));

Can someone please give a simple guide on how to do this?

**Comment by johnnavarra** [comment]
Example, generate code displays:
POST /premierleadexchange.asmx HTTP/1.1
Host: production.detroittradingexchange.com
Content-Type: text/xml
SOAPAction: "www.detroittradingexchange.com/NEWCAR_PostGX"
Cache-Control: no-cache
Postman-Token: 692312f6-181b-5a18-bd93-461621fe5e8c

<soap:Envelope
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/">
    soap:Body
        <NEWCAR_PostGX xmlns="www.detroittradingexchange.com/">
            <User>0000-3178</User>
            <Password>3178AJG</Password>
            <Message>&lt;?xml version="1.0" encoding="UTF-8"?&gt;
                &lt;NEWCAR_POSTGX_REQUEST
                    xmlns="www.detroittradingexchange.com/SellerMessages"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="
www.detroittradingexchange.com/SellerMessages
http://www.detroittradingexchange.com/SellerMessages/NewCarSellGx_request.xsd
"&gt;
                &lt;Lead_Metadata&gt;
-                    &lt;DTX_GEN_ID&gt; 0000-3178&lt;/DTX_GEN_ID&gt;*
                  &lt;LEAD_GEN_METHOD&gt; null&lt;/LEAD_GEN_METHOD&gt;
                  &lt;LEAD_SOURCE_IP&gt;
  66.11.125.12&lt;/LEAD_SOURCE_IP&gt;
                  &lt;CAMPAIGN_ID&gt; null&lt;/CAMPAIGN_ID&gt;
                  &lt;GEN_LEAD_ID&gt; DTEVALUATION1&lt;/GEN_LEAD_ID&gt;
                  &lt;SELF_GENERATED_LEAD&gt;
  false&lt;/SELF_GENERATED_LEAD&gt;
                  &lt;SOURCE&gt; DTVERIFIED_151000&lt;/SOURCE&gt;
              &lt;/Lead_Metadata&gt;
              &lt;Post_Instructions&gt;
                  &lt;Reservation_ID&gt;
  4512002053|0000-2120|4f4f2622-d751-4954-b8f9-7603875ad12e|02750&lt;/Reservation_ID&gt;
              &lt;/Post_Instructions&gt;
              &lt;Lead_Data&gt;
                  &lt;VEHICLE_INFO&gt;
                      &lt;YEAR&gt;  2016&lt;/YEAR&gt;
                      &lt;MAKE&gt;  Ford&lt;/MAKE&gt;
                      &lt;MODEL&gt;  Focus&lt;/MODEL&gt;
                      &lt;TRIM&gt; null&lt;/TRIM&gt;
                      &lt;INTERIOR_COLOR&gt; black&lt;/INTERIOR_COLOR&gt;
                      &lt;EXTERIOR_COLOR&gt; White&lt;/EXTERIOR_COLOR&gt;
                  &lt;/VEHICLE_INFO&gt;
                  &lt;PURCHASE_INFO&gt;
                      &lt;FINANCING&gt; lease&lt;/FINANCING&gt;
                      &lt;TIME_FRAME_DAYS&gt; 7&lt;/TIME_FRAME_DAYS&gt;
                  &lt;/PURCHASE_INFO&gt;
                  &lt;PERSONAL_INFO&gt;
                      &lt;FIRST_NAME&gt; Barack&lt;/FIRST_NAME&gt;
                      &lt;LAST_NAME&gt; Obama&lt;/LAST_NAME&gt;
                  &lt;/PERSONAL_INFO&gt;
                  &lt;CONTACT_INFO&gt;
-                        &lt;HOME_PHONE&gt; 5869338914&lt;/HOME_PHONE&gt; *
-                        &lt;EMAIL&gt; Juan933@detroittrading.net
  Juan933@detroittrading.net&lt;/EMAIL&gt; *
-                        &lt;WORK_PHONE&gt; 2489338914&lt;/WORK_PHONE&gt; *
-                        &lt;WORK_PHONE_EXT&gt;
  1205&lt;/WORK_PHONE_EXT&gt; *
-                        &lt;MOBILE_PHONE&gt; 5864658914&lt;/MOBILE_PHONE&g*
  t;
                      &lt;CONTACT_TIME&gt; Any&lt;/CONTACT_TIME&gt;
                  &lt;/CONTACT_INFO&gt;
                  &lt;RESIDENCE_INFO&gt;
                      &lt;ADDRESS&gt; 2898 Colonial&lt;/ADDRESS&gt;
                      &lt;CITY&gt; Southfield&lt;/CITY&gt;
                      &lt;STATE_PROVINCE&gt; MI&lt;/STATE_PROVINCE&gt;
                      &lt;ZIP_POSTAL_CODE&gt;
  48075&lt;/ZIP_POSTAL_CODE&gt;
                      &lt;COUNTRY&gt; USA&lt;/COUNTRY&gt;
                      &lt;/RESIDENCE_INFO&gt;
                  &lt;/Lead_Data&gt;
                  &lt;BUYER_DETAILS&gt;
          &lt;TRADE_IN&gt;
            &lt;YEAR&gt; 2010&lt;/YEAR&gt;
            &lt;MAKE&gt; Ford&lt;/MAKE&gt;
            &lt;MODEL&gt; Fusion&lt;/MODEL&gt;
            &lt;TRIM&gt; SEL&lt;/TRIM&gt;
            &lt;EXTERIOR_COLOR&gt; Grey&lt;/EXTERIOR_COLOR&gt;
            &lt;MILEAGE&gt; 100000&lt;/MILEAGE&gt;
          &lt;/TRADE_IN&gt;
        &lt;/BUYER_DETAILS&gt;
              &lt;/NEWCAR_POSTGX_REQUEST&gt;
          </Message>
          <DebugMode>false</DebugMode>
      </NEWCAR_PostGX>
  /soap:Body
  /soap:Envelope

Actual sent payload received by the server:
<?xml version="1.0" encoding="UTF-8"?>
                <NEWCAR_POSTGX_REQUEST
                    xmlns="www.detroittradingexchange.com/SellerMessages"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="
www.detroittradingexchange.com/SellerMessages
http://www.detroittradingexchange.com/SellerMessages/NewCarSellGx_request.xsd
">
                <Lead_Metadata>
-                    <DTX_GEN_ID> {{User}}</DTX_GEN_ID> *
                  <LEAD_GEN_METHOD> null</LEAD_GEN_METHOD>
                  <LEAD_SOURCE_IP> 66.11.125.12</LEAD_SOURCE_IP>
                  <CAMPAIGN_ID> null</CAMPAIGN_ID>
                  <GEN_LEAD_ID> DTEVALUATION1</GEN_LEAD_ID>
                  <SELF_GENERATED_LEAD> false</SELF_GENERATED_LEAD>
                  <SOURCE> DTVERIFIED_151000</SOURCE>
              </Lead_Metadata>
              <Post_Instructions>
                  <Reservation_ID>
  4512002053|0000-2120|4f4f2622-d751-4954-b8f9-7603875ad12e|02750</Reservation_ID>
              </Post_Instructions>
              <Lead_Data>
                  <VEHICLE_INFO>
                      <YEAR>  2016</YEAR>
                      <MAKE>  Ford</MAKE>
                      <MODEL>  Focus</MODEL>
                      <TRIM> null</TRIM>
                      <INTERIOR_COLOR> black</INTERIOR_COLOR>
                      <EXTERIOR_COLOR> White</EXTERIOR_COLOR>
                  </VEHICLE_INFO>
                  <PURCHASE_INFO>
                      <FINANCING> lease</FINANCING>
                      <TIME_FRAME_DAYS> 7</TIME_FRAME_DAYS>
                  </PURCHASE_INFO>
                  <PERSONAL_INFO>
                      <FIRST_NAME> Barack</FIRST_NAME>
                      <LAST_NAME> Obama</LAST_NAME>
                  </PERSONAL_INFO>
                  <CONTACT_INFO>
-                        <HOME_PHONE> 586{{3D1}}{{4D1}}</HOME_PHONE> *
-                        <EMAIL> Juan{{3D1}}@detroittrading.net
  <Juan%7B%7B3D1%7D%7D@detroittrading.net></EMAIL> *
-                        <WORK_PHONE> 248{{3D1}}{{4D1}}</WORK_PHONE> *
-                        <WORK_PHONE_EXT> 1205</WORK_PHONE_EXT> *
-                        <MOBILE_PHONE> 586{{3D3}}{{4D1}}</MOBILE_PHONE> *
-                        <CONTACT_TIME> Any</CONTACT_TIME> *
                  </CONTACT_INFO>
                  <RESIDENCE_INFO>
                      <ADDRESS> 2898 Colonial</ADDRESS>
                      <CITY> Southfield</CITY>
                      <STATE_PROVINCE> MI</STATE_PROVINCE>
                      <ZIP_POSTAL_CODE> 48075</ZIP_POSTAL_CODE>
                      <COUNTRY> USA</COUNTRY>
                      </RESIDENCE_INFO>
                  </Lead_Data>
                  <BUYER_DETAILS>
          <TRADE_IN>
            <YEAR> 2010</YEAR>
            <MAKE> Ford</MAKE>
            <MODEL> Fusion</MODEL>
            <TRIM> SEL</TRIM>
            <EXTERIOR_COLOR> Grey</EXTERIOR_COLOR>
            <MILEAGE> 100000</MILEAGE>
          </TRADE_IN>
        </BUYER_DETAILS>
              </NEWCAR_POSTGX_REQUEST>

**Comment by garunski** [comment]
+1

**Comment by bquack** [comment]
+1
I have been using the method of loading JS into a global variable and then using eval(), but I don't like the fact that I have to make this a first step in all of my collections. It would be nice if there was a more elegant solution for this such as having an external list of JS resources. It would also be great if external JSON Schemas could have something similar.... maybe even a third variable scope that can store schemas.

**Comment by magichair** [comment]
+1
Our team is storing a handful of js libraries in global environment variables, this is very hacky

**Comment by otoniel-isidoro** [comment]
+1

**Comment by serkand** [comment]
+1

**Comment by johntiror** [comment]
+1

**Comment by theGhostJW** [comment]
+1

**Comment by codenirvana** [comment]
+1

**Comment by jdiaz4517** [comment]
+1

**Comment by grinderX19** [comment]
+1

I wonder why modifications of tester_sandbox.html are not picked up by Postman native app (Linux one in my case). Second workaround with evaluation of global var is not very convenient to say the least...

**Comment by jbeckton** [comment]
The problem with $.getScript() is that it is async. Forget the shorthand method and use ajax directly so you can make it synchronous.

$.ajax({
    async: false,
    url: "jui/js/myscript.js",
    dataType: "script"
});

**Comment by murli5in** [comment]
Hi  I am trying to create a Db connections in .js using node.js pg-pool package . 
is possible to call js functions in postman? please share your thoughts

**Comment by pillravi** [comment]
+1

**Comment by dymen1** [comment]
+1

**Comment by thaihau** [comment]
+1

**Comment by ghost** [comment]
+1
Any update on this?

**Comment by ghost** [comment]
@shamasis regarding your point about working around Chrome platform restrictions. Isn't this a non-issue for the Windows and Mac native apps since they run on Electron?

**Comment by biglynch** [comment]
+1

**Comment by Senior-Fin** [comment]
+1

**Comment by dfang** [comment]
+1

**Comment by RJ05** [comment]
+1

**Comment by jonasezitis** [comment]
+1

**Comment by guvkon** [comment]
+1

**Comment by joseph4tw** [comment]
+1

**Comment by Pawana93** [comment]
+1

**Comment by mikklaos** [comment]
+1

**Comment by ginere** [comment]
+1

**Comment by Skeen** [comment]
+1

**Comment by jisooh** [comment]
+1

**Comment by gaheinrichs** [comment]
+1

**Comment by TheCoderGuyVlad** [comment]
+1 for thread
+1 for eval global var idea
+1 for other suggestions here

**Comment by pokryva** [comment]
biiiig +1 for being able to load external js libraries for use in pre-request scripts **in the native app**, given [this](http://blog.getpostman.com/2017/03/14/going-native/) blog post and the big yellow warning that appeared in my chrome app today ;)
![image](https://user-images.githubusercontent.com/15121868/32092520-3af2e306-baf9-11e7-8853-499ba82eec8e.png)

**Comment by silvanu** [comment]
+1

**Comment by HoGuan6666666** [comment]
+1

**Comment by nickm8** [comment]
+1

**Comment by skyboyer** [comment]
+1

**Comment by pencilkill** [comment]
+1

**Comment by gtagle** [comment]
+1

**Comment by GrimSmiler** [comment]
+2

**Comment by bradobro** [comment]
+1

**Comment by bruceg-qualtrics** [comment]
+1

**Comment by lazyboywu** [comment]
+1

**Comment by Keoven** [comment]
+1

**Comment by arctouch-eltonsantana** [comment]
+1

**Comment by ghost** [comment]
@abhijitkane @shamasis Is this feature still on the roadmap (as this issue is from 2015)? Postman is excellent but not being able to add to the sandbox libraries is very limiting. The current workaround (storing an entire library as a global variable after a GET request) is not ideal.

**Comment by gklp** [comment]
+1

**Comment by feskovio** [comment]
+1

**Comment by dinfyru** [comment]
+1

**Comment by BobinMax** [comment]
**+1**

**Comment by trevorhanus** [comment]
+1

**Comment by rozaydin** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by cyrfer** [comment]
+1

**Comment by khamiltonuk** [comment]
+1

**Comment by vdcardenas** [comment]
+1

**Comment by Ocsidot** [comment]
Please add this functionality inside Postman, it will be a great help

**Comment by jarrodparkes** [comment]
+1

**Comment by ivaaaan** [comment]
+1

**Comment by rhostem** [comment]
+1

**Comment by SuperAL** [comment]
My solution for running some scripts every time a request was sent:
```js
// in collection Tests tab
pm.sendRequest("path/to/the/script.js", (err, res) => { eval(res.text()); });
```

**Comment by Nahis** [comment]
+1

**Comment by rfarinel** [comment]
+1

**Comment by mccannt** [comment]
+1

**Comment by nickclicksco** [comment]
+1

**Comment by 0Steve0** [comment]
+1

**Comment by dpiechota** [comment]
+1

**Comment by aking1012** [comment]
For Content-Encoding: gzip, it's looking like the only semi-reasonable way to do it is to smush it inside of the environment variable.  Still have to try it out, but https://github.com/beatgammit/gzip-js/blob/master/lib/gzip.js should be useful, since it's a single file gzip implementation.

**Comment by RobynLiu** [comment]
+1

**Comment by p00j4** [comment]
I added the js (moment.js) I wanted in the tester_sandbox.html file and reloaded the native postman MAC app, but it didn't help. I get not found error `ReferenceError: moment is not defined`
Am I missing anything here?

**Comment by grinderX19** [comment]
**p00j4**, this approach doesn't work with native apps.
It seems the only way to use external JS is as follows:

> If it helps you can put js into an environment variable and load it with:
> eval(postman.getGlobalVariable("environment variable key"));

**Comment by Ocsidot** [comment]
@grinderX19 and @p00j4 , MomentJS can be loaded in postman siince it's one of available internal module (https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox_api_reference)

To use MomentJs, you just need to do var moment = require("moment");
Then the library is loaded into your variable

Regards

**Comment by kimpettersen** [comment]
+1!!

I've done something similar to @SuperAL mentioned
`pm.sendRequest("path/to/the/script.js", (err, res) => { eval(res.text()); });`
But when the script grows above a certain size Postman just crashes immediately. Has anyone else experienced this?

**Comment by PawelKazimirowicz** [comment]
Is it possible to configure in Postman Adyen secured fields?
https://docs.adyen.com/developers/checkout/api-integration/using-secured-fields

The js file is used to encrypt credit card data and send it to the API endpoint.

What I want to achieve is
1. In Pre-request Script request js filed
2. Parse response and set environment variables
3. Use those variable in the request body

**Comment by p00j4** [comment]
thanks @Ocsidot yes this works now.  Wondering why it wasn't working earlier is more scarier 🤦‍♀️

**Comment by RobertAKARobin** [comment]
+1 on this. JS embedded in JSON is super lame, and has me looking at alternatives.

**Comment by mohit-sentieo** [comment]
+1 on this

**Comment by ashwani-kumar04** [comment]
Hi, 
I also faced this issue as maintaining js code in separate files makes more sense. I created a gulp plugin and a sample project to replace the javascript code in the Json using Gulp build. The plugin is still in its early stage and I am in the process to put together a how-to guide for the same. 
It can be found here:

[Npm plugin](https://www.npmjs.com/package/gulp-postcol)
[Sample project](https://github.com/ashwanikumar04/postman-collections-scripts)

**Comment by jhardin-aptos** [comment]
A definite +1 on this feature.

We have a desire to run a database query to get the data to verify the REST results (potentially in a loop) vs. hardcoding the data in the tests or running some external scripted step to generate an environment file - the npm package **mssql** looks like it would be perfect, but the web of dependencies and potentially their size makes the prospect of trying to include it all via the approaches described above somewhat daunting.

It would be _wonderful_ if there was some mechanism to install arbitrary npm modules in the postman sandbox (with dependency resolution); a usable alternative might be to make `require()` in a postman script be able to look in the global npm repository if the module isn't already in the postman sandbox.

**Comment by cenxun** [comment]
Maybe we can temporarily introduce external js functions, or customize global functions.

**Comment by vrolijken** [comment]
> We're working on a way to allow import of custom JS files into the scripting sandbox, but can't offer an approximate date right now.

Nearly three years on, can you offer an approximate date?

**Comment by elielr01** [comment]
Hello! I also support this request! It would be awesome to load custom node modules.

Right now, I wanted to use `http-signature` in a pre-request script. It would be a lot easier just to be able to load that module to the available libraries and use it directly.

Thanks for all the efforts!

**Comment by nickevansuk** [comment]
Yes please!

**Comment by alastair-todd** [comment]
Can someone explain why we are forced to use a sandbox at all?

I'm a big boy now.

Seriously, we have stock code for obtaining a jwt token from AWS Cognito and writing it to an environment variable in an automated fashion, and here I am trying to hack around with loading the Cognito javascript libraries through ajax and eval....Billy Bonkers

**Comment by IanKemp** [comment]
In slightly more than 6 months' time, this feature request will be half a decade old. As such I think it's safe to say Postman is never going to implement it.

**Comment by josenicomaia** [comment]
+1
+1
+1
+1

**Comment by panmanphil** [comment]
I'll add to this request. We have existing scripts that create bearer tokens we can use for local testing, but the best I've been able to do is have those scripts load to the clipboard so I can manually paste into an environment variable. Would love to be able to read from a system environment variable, or a file. Or the clipboard, or shell out to run a script. anything!

**Comment by impdatacompstuff** [comment]
+1

**Comment by kapalkat** [comment]
+1 It would be extremely useful!

**Comment by aoyama-val** [comment]
+1

**Comment by joelkim** [comment]
+1

**Comment by martinp999** [comment]
+1

**Comment by martin-braun** [comment]
I really appreciate Postman, it's really a great piece of software and very useful, but ... 5 years and no result on this issue? :(

**Comment by mccannt** [comment]
@martin-braun Thanks for the response. 
While we understand this is a long-standing issue and conceptually an easy thing to fix. There are performance, security and architecture considerations to making a change like this.
So while we would love to make the change and call it a day, we need to ensure that it's done right and is well thought out to protect our users.

We have not forgotten or ignored this request, just please appreciate that we are working to make enhancements that will allow for functionality like this.

**Comment by vrolijken** [comment]
@mccannt It would appear to me that a (large?) number of your users are developers who are able to protect themselves, e.g. by deciding when they'll use this feature. The behaviour requested can be executed in Postman right now, it's just harder to do so.

**Comment by CHANist** [comment]
+1 in year 2021, really want to use local external js file, so that multiple collection / APIs can reuse the same set of function, without duplicating any functions in each collections.

**Comment by Ocsidot** [comment]
Personally, as many of you I suppose I use the trick to save a module inside the global and load it with eval().

It is working but I have to rebuild my global on every Jenkins run to ensure to always have the latest version from my colleagues. Moreover, we cannot have  tests on the functions delivered this way which may sometimes be a problem.

Hope this feature will come some day

**Comment by Cuneytt** [comment]
Open since 2015, good job Postman

**Comment by poddubitskya** [comment]
A real blocker to plan some real investments into this tool
Especially considering the age of this ticket

**Comment by disouzam** [comment]
> If it helps you can put js into an environment variable and load it with:
> `eval(postman.getGlobalVariable("environment variable key"));`

Awesome idea! Saved my weekend!

**Comment by vlav98** [comment]
Is there any news about this feature?  😔

**Comment by afattahi54** [comment]
I found a solution at: [here](https://postman-quick-reference-guide.readthedocs.io/en/latest/libraries.html#custom-libraries)

````js
pm.sendRequest("https://example.com/your-script.js", (error, response) => {
    if (error || response.code !== 200) {
        pm.expect.fail('Could not load external library');
    }

    eval(response.text());

    // YOUR CODE HERE
});

`````

````js
pm.sendRequest("https://unpkg.com/papaparse@5.1.0/papaparse.min.js", (error, response) => {
    if (error || response.code !== 200) {
        pm.expect.fail('Could not load external library');
    }

    eval(response.text());

    const csv = `id,name\n1,John`;
    const data = this.Papa.parse(csv); // notice the this
    console.log(data);
});

````

**Comment by poddubitskya** [comment]
> I found a solution at: [here](https://postman-quick-reference-guide.readthedocs.io/en/latest/libraries.html#custom-libraries)
> 
> ```js
> pm.sendRequest("https://example.com/your-script.js", (error, response) => {
>     if (error || response.code !== 200) {
>         pm.expect.fail('Could not load external library');
>     }
> 
>     eval(response.text());
> 
>     // YOUR CODE HERE
> });
> ```
> 
> ```js
> pm.sendRequest("https://unpkg.com/papaparse@5.1.0/papaparse.min.js", (error, response) => {
>     if (error || response.code !== 200) {
>         pm.expect.fail('Could not load external library');
>     }
> 
>     eval(response.text());
> 
>     const csv = `id,name\n1,John`;
>     const data = this.Papa.parse(csv); // notice the this
>     console.log(data);
> });
> ```

Yup, strictly speaking you can load an external JS file

It could be cool though to use a bunch of external libraries securely, have some version tracking (ain't a dreamer?) and set up a reusable reference once per collection

**Comment by mhanci92** [comment]
This workaround seems not to work with libraries that internally require other libs (that are not available in postman). For instance, take a look at the following module that I was trying to load into Postman: 

``` https://cdn.jsdelivr.net/npm/cacheable-lookup@6.0.4/source/index.min.js ```

The cacheable-lookup lib requires the lib "dns" internally. Hence, when loading the external lib and executing the eval() function on it:

```
pm.sendRequest("https://cdn.jsdelivr.net/npm/cacheable-lookup@6.0.4/source/index.min.js", (error, response) => {
    if (error || response.code !== 200) {
        pm.expect.fail('Could not load the external cacheable-lookup library!');
    }

    eval(response.text());
    const cachable = this.CacheableLookup;
});
```

I observe the following error (on the postman console):
```Error: Cannot find module 'dns' ```

Or do I miss something here?

**Comment by RavenHursT** [comment]
Come on Postman. It's been 7 YEARS and y'all _still_ haven't figured out a way to allow us to include npm modules in our collections?

The current "solution" is to either copy/paste the lib code into a global env var, or fetch that JS, and then use `eval()`?  Really??

Nearly _every_ web-based JS platform allows for this (codesandbox.io, stackblitz.com, repl.it, etc). Surely this isn't that hard?

**Comment by josenicomaia** [comment]
Just drop it.

**Comment by gdollard** [comment]
even when I try the 'code in the global env var & eval()' approach I still get the "Cannot find module" error, presumably because of the sandbox restriction. So those who say it's working for them, how so?

**Comment by william-wallace-simplisafe** [comment]
The absence of built-in library import/management tool makes postman very awkward to use with common evolving libraries.  I'm in a situation where I have multiple collections that all use common functions that I have written in a pre-request scripts.  I end up duplicating code from collection to collection because of postman's lack of functionality to import libraries.  I would like to create a javascript library and unit test the functions in it separately then publish it so it could be required just like the built-in libraries are used.  The problem arises when my custom library uses a third party library that is not included in postman's built-in set.  Please expand this functionality as the existing solution is not enough

Additionally, many libraries cannot be fetched and used with `eval()` as some are zip archives that need to be extracted.  I don't currently know of any way to import these with postman.

**Comment by b-y-f** [comment]
8 years still no update?

**Comment by mikklaos** [comment]
Just close the issue as Wont do. I will stop following this

**Comment by appurva21** [comment]
Hey everyone! 👋🏼 

It’s been a long time coming, and we are excited to announce that Postman now supports **importing external packages from NPM directly into your scripts**. No more awkward workarounds!

Go to your request's `Scripts` tab and use `pm.require` to import the package you need. For example:

```js

const { ulid } = pm.require('npm:ulid');

console.log(ulid());

```

![Image](https://github.com/user-attachments/assets/9775a2db-99d6-4fc9-b752-135f519a7ad9)




📌 You can find more details about external packages support and limitations here: https://github.com/postmanlabs/postman-app-support/issues/13542

Give it a try and let us know how it goes. I’ll go ahead and close this one for now, but feel free to open a new ticket if you have more questions or run into any issues. 🚀
