### ISSUE TITLE
Logging into Postman from new computer; all requests empty

### ISSUE THREAD

**Issue by DWRoelands** [a85/POSTMan-Chrome-Extension#11919]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I’ve been using Postman for years. I have an account and my workspace is saved on the postman website.

I got a new computer. Installed Postman. Logged into my Postman account. My workspace is there. My collections are there. My requests are there, but the requests are all empty.

Every URL is gone. Every query parameter is gone. Every custom header is gone.

### Steps To Reproduce

1. Download Windows 10 x64 Postman app from Postman website
2. Install client on a computer that has not previously been used for Postman at all.
3. Log into existing Postman account.
4. All workspaces exist.  All collections exist.  All requests exist, but all requests are empty.  URLs are gone, query strings are gone, parameters are gone.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/829031/231787050-190dc691-fdae-492f-bcaf-b17fcedcf5d9.png)

### Operating System

Windows

### Postman Version

10.12.0

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

I've used Postman for years, both via the web interface and via the Windows client (as evidenced in my session history).  I've lost so much work because of this and I'm not sure what I could have done differently.

**Comment by giridharvc7** [comment]
@DWRoelands Can you please email logs to our support (support@postman.com) so that we can take a deeper look into this?

**Comment by Jandev** [comment]
Hi,

Did you ever get this sorted out?
I see similar behavior, but only for 1 of my collections.

During the day, I'm adding the data for the requests back (endpoints, request data, etc.).
Closing and starting the Desktop app (Version 10.14.9) shows me all data is lost again.

I've also been working on the web version (https://web.postman.co/), and storing the requests over there.
On refreshing the page, all requests are empty again.

The Desktop version says I'm Online and 'In sync', and I'm obviously online when using the web version.

I've checked my DNS logs (Pihole) and no traffic to any `postman` or `pst*`-domain is blocked.

When switching to another collection and modifying/adding requests over there, data is persisted. It might be this collection is bugged, so will also try creating a new one.

**Update**

After exporting and importing the data to a different collection, I'm seeing similar behavior. After restarting Postman, all data appears to be lost.

What I did discover just now is something strange, and can reproduce every time:

1. Open a request which is turned empty
2. Change the name of the request (adding or removing a character to it)
3. See the data (endpoint, body, headers) re-appear

It looks like some initial loading of the request is awry.

From the `main.log`

```
[86372][1686222134494][main][info]["Booting Postman 10.14.2, win32-10.0.22621 on x64"]
[86372][1686222134496][main][info]["EventBus~initialize - Success"]
[86372][1686222134498][main][info]["Proxy configuration has not been setup"]
[86372][1686222134498][main][info]["CloudProxyManager~init - Success"]
[86372][1686222134521][main][info]["performShellDataMigration: Migration has already been done. Bailing out"]
[86372][1686222134522][main][info]["UpdateHandler~init - Success"]
[86372][1686222134523][main][info]["LeaderSelection: Initialized successfully"]
[86372][1686222134524][main][info]["VersionDependencyService: Initialized successfully"]
[86372][1686222134546][main][info]["GPU detected VID 4318 DID 8113 ACTIVE false"]
[86372][1686222134546][main][info]["GPU detected VID 32902 DID 19594 ACTIVE false"]
[86372][1686222134546][main][info]["GPU detected VID 5140 DID 140 ACTIVE false"]
[86372][1686222134572][main][info]["shellController~init: Success"]
[86372][1686222134588][main][info]["shellMeta~init: Success"]
[86372][1686222134589][main][info]["partitionMigrationService: State of V7 partition:"]
[86372][1686222134589][main][info]["partitionMigrationService: V7 partitions",[]]
[86372][1686222134589][main][info]["partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no partition with scratchpad namespace"]
[86372][1686222134589][main][info]["partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no transit partition which could have been used for scratchpad"]
[86372][1686222134589][main][info]["partitionMigrationService~init: Success"]
[86372][1686222134617][main][info]["partitionMigrationService~runV8PartitionsIntegrity: Two way migration~ removing the following partitions from v8",[]]
[86372][1686222134628][main][info]["userPartitionService~getRecentV8UserPartition: recent v8 user context partition ","60c4a2df-5768-4224-987b-89fc51f32b24"]
[86372][1686222134629][main][info]["userPartitionService~_rectifyTheActivePartitionOfApplication: Setting the active partition to ","60c4a2df-5768-4224-987b-89fc51f32b24"]
[86372][1686222134651][main][info]["userPartitionService~init: Success"]
[86372][1686222134667][main][info]["userPartitionService: State of v8 partition system:"]
[86372][1686222134676][main][info]["shell~init~getPartitionToLoad: loading active partition"]
[86372][1686222134679][main][info]["userPartitionService: List of partitions:",[{"partitionId":"60c4a2df-5768-4224-987b-89fc51f32b24","namespace":"users","userId":"3047595","teamId":"0","lastUpdated":"2023-06-08T11:01:29.524Z"},{"partitionId":"5b9fbe8c-cdd6-4b9c-9a5e-676dcba6b7fc","namespace":"scratchPad","userId":0,"teamId":0,"isDirty":false}]]
[86372][1686222134679][main][info]["userPartitionService: users global meta:",{}]
[86372][1686222136778][main][info]["RuntimeIPCAgent~started: Success"]
[86372][1686222136994][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[86372][1686222137005][main][info]["windowManager: First requester booted successfully."]
[86372][1686222137005][main][info]["windowManager~restoreWindows: Restoring requester windows"]
[86372][1686222137005][main][info]["Main~AppEvents - Received booted event for process requester.Version 10.14.9 UI Version: 10.14.9-ui-230606-0439 Desktop Platform Version: 10.14.2"]
[86372][1686222137458][main][info]["Main~getPlatformLaunchPerfMetrics"]
[86372][1686222137933][main][info]["Main - model-events~user - (user, bootstrapUser) received"]
[86372][1686222137933][main][info]["model-events~user - bootstrapUser received"]
[86372][1686222137963][main][info]["userPartitionService~associateTransitPartition: ",{"partitionId":"60c4a2df-5768-4224-987b-89fc51f32b24","context":{"namespace":"users","userId":"3047595","teamId":"0"}}]
[86372][1686222137995][main][info]["userPartitionService: State of v8 partition system:"]
[86372][1686222138005][main][info]["userPartitionService: List of partitions:",[{"partitionId":"60c4a2df-5768-4224-987b-89fc51f32b24","namespace":"users","userId":"3047595","teamId":"0","lastUpdated":"2023-06-08T11:02:17.963Z"},{"partitionId":"5b9fbe8c-cdd6-4b9c-9a5e-676dcba6b7fc","namespace":"scratchPad","userId":0,"teamId":0,"isDirty":false}]]
[86372][1686222138006][main][info]["userPartitionService: users global meta:",{}]
```

I do see some errors in the `renderer-requester.log`, just not really sure what it means.

```
[86372][1686222144545][requester][info]["BaseSyncTimeline~_handleForceSync: Finished force sync for collection:3047595-0bc4f11d-6a46-49a4-a1ac-c0165bff7c2e"]
[86372][1686222144624][requester][error]["RequestMethodsService~getCustomUserMethods: Error fetching custom user methods",{"name":"TypeError","message":"e is not iterable","stack":"TypeError: e is not iterable\n    at o.getCustomUserMethods (https://desktop.postman.com/_ar-assets/RequestWorkbench-c547a0b112baf945.min.js:1513:5442)\n    at r.getMethodsList (https://desktop.postman.com/_ar-assets/RequestWorkbench-c547a0b112baf945.min.js:336:136555)\n    at render (https://desktop.postman.com/_ar-assets/RequestWorkbench-c547a0b112baf945.min.js:336:139923)\n    at ee (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1263:44246)\n    at https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1263:7473\n    at ge (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1263:50487)\n    at e.track (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1263:55291)\n    at r.u [as render] (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1263:7425)\n    at r.<anonymous> (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1263:7568)\n    at r.t.render (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1263:7580)\n    at Ha (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1308:70016)\n    at Ua (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1308:69811)\n    at ks (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1308:105303)\n    at vc (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1308:96777)\n    at gc (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1308:96702)\n    at cc (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1308:93732)\n    at https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1308:45486\n    at t.unstable_runWithPriority (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1369:3795)\n    at Gi (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1308:45195)\n    at Yi (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1308:45431)\n    at Zi (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1308:45366)\n    at uc (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1308:94023)\n    at qe (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1263:56769)\n    at Ue (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1263:56358)\n    at Ne (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1263:53051)\n    at https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1263:44166\n    at Q (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1263:44204)\n    at e.n (https://desktop.postman.com/_ar-assets/vendors-871780ed84e7d339.min.js:1263:43879)\n    at https://desktop.postman.com/_ar-assets/RequestWorkbench-c547a0b112baf945.min.js:360:9604\n    at nrWrapper (https://desktop.postman.com/?desktopVersion=10.14.2&userId=3047595&teamId=0:10:29518)"}]
[86372][1686222145772][requester][warn]["CollectionStoreV2~findOne: Using collection model id instead of uid is deprecated. Please use uid instead."]
[86372][1686222161686][requester][info]["RealtimeSyncMessageService~publishRealtimeIncomingMessage: Message received workspace:broadcast Timeline in message: undefined:undefined"]
[86372][1686222161687][requester][info]["CollectionListingAPIAdapter: Adding to CollectionStoreV2",["3047595-0bc4f11d-6a46-49a4-a1ac-c0165bff7c2e"]]
[86372][1686222161772][requester][info]["RequestInterfaceV2~createRequest - Error in dispatching sync action: ",{"name":"Error","message":"CollectionController: Could not find request to update","stack":"Error: CollectionController: Could not find request to update\n    at https://desktop.postman.com/_ar-assets/common-953c7fa76265b473.min.js:4411:150904\n    at nrWrapper (https://desktop.postman.com/?desktopVersion=10.14.2&userId=3047595&teamId=0:10:29518)"}]
[86372][1686222162706][requester][warn]["CollectionStoreV2~findOne: Using collection model id instead of uid is deprecated. Please use uid instead."]
[86372][1686222311192][requester][error]["ReleaseListStore~getReleases: apiId or apiVersionId is missing"]
[86372][1686222311637][requester][error][{"name":"TypeError","message":"Cannot read properties of undefined (reading 'created_at')","stack":"TypeError: Cannot read properties of undefined (reading 'created_at')\n    at a._wasTeamCreatedBeforeApril2021 (https://desktop.postman.com/_ar-assets/UniverseHomepage-bff0abf3ebc00e73.min.js:242:14523)\n    at https://desktop.postman.com/_ar-assets/UniverseHomepage-bff0abf3ebc00e73.min.js:242:15446\n    at nrWrapper (https://desktop.postman.com/?desktopVersion=10.14.2&userId=3047595&teamId=0:10:29518)"}]
[86372][1686222336956][requester][info]["BaseSyncTimeline~unsubscribe: Unsubscribing to real time changes & subscriptions for workspace:a38ebd75-566b-4212-8ea3-bf07352eb74d"]
[86372][1686222336956][requester][info]["BaseSyncTimeline~unsubscribe: Unsubscribing to real time changes & subscriptions for environment:3047595-8d81deff-a0d0-4587-a7c2-6cdf493bfca0"]
[86372][1686222336982][requester][info]["BaseSyncTimeline~unsubscribe: Unsubscribing to real time changes & subscriptions for collection:3047595-0bc4f11d-6a46-49a4-a1ac-c0165bff7c2e"]
[86372][1686222337114][requester][info]["BaseSyncTimeline~unsubscribe: Unsubscribed timeline collection:3047595-0bc4f11d-6a46-49a4-a1ac-c0165bff7c2e"]
[86372][1686222337120][requester][info]["BaseSyncTimeline~unsubscribe: Unsubscribed timeline workspace:a38ebd75-566b-4212-8ea3-bf07352eb74d"]
[86372][1686222337123][requester][info]["BaseSyncTimeline~unsubscribe: Unsubscribed timeline environment:3047595-8d81deff-a0d0-4587-a7c2-6cdf493bfca0"]
```

**Comment by ankitjaggi** [comment]
@Jandev Can you please email logs to our support ([support@postman.com](mailto:support@postman.com)) so that we can take a deeper look into this?

**Comment by DWRoelands** [comment]
No, it never got resolved.  I opened a ticket with Postman support and their response was (paraphrased), "Sorry, you must have done something wrong."

Not a great experience.

**Comment by giridharvc7** [comment]
@DWRoelands , @Jandev We've raised an update that'll reach you around next week. In case, please give it a try and let us know if you face it. 

In case you still face this issue -  it'll be great if we can get on a call to debug this. You can setup a call at your convenient time here https://calendly.com/giridhar-vc-postman/

**Comment by Jandev** [comment]
Thanks for following up on it!

I had the opportunity to schedule a call with one of the engineers via the support team.
However, I accidentally deleted the workspace where this problem was occurring and apparently didn't have any exports/backups from this workspace and/or collection. Because it only occurred in a single workspace, I can't reproduce it anymore, and mentioned to the support team they can close my issue with the comment "Can't reproduce".

The team did try to search what went wrong, via the logs I provided and after providing a couple of identifiers for my workspace, account, etc.

**Comment by DWRoelands** [comment]
Postman support unable to reproduce or identify root cause and suggested that the problem was user error.   Closed as "Won't Fix/Can't Reproduce".

**Comment by matucker3030** [comment]
Same issue, still a problem

**Comment by marekog** [comment]
This has happened to a friend, and now to me as well. Everything is lost.

**Comment by christopher-bonitz** [comment]
Yep, wanted to try out Postman after Insomnia got messy, lost all 4 requests url and parameter details.
Wondered if that was the default, sounds like its not

**Comment by mwaterous** [comment]
Still an issue in 2026. I have put together a collection of requests on one computer, logged in on another and they're superficially there...except they're all empty. Parameters are gone, URLs are gone, request bodies, and all the methods have gone back to GET regardless of what they were.

Similar issue when duplicating. It duplicates the title and nothing else. The rest of the request is gone.
