### ISSUE TITLE
Newman + Postman 3 

### ISSUE THREAD

**Issue by riyunoa** [a85/POSTMan-Chrome-Extension#1191]
Hey everyone,

We've got an issue with a Postman 3 exported file causing the following error:

```
/home/gillian/npm/lib/node_modules/newman/node_modules/request/request.js:345
        throw new Error('Argument error, options.body.')
              ^
Error: Argument error, options.body.
    at Request.self._buildRequest (/home/gillian/npm/lib/node_modules/newman/node_modules/request/request.js:345:15)
    at Request.init (/home/gillian/npm/lib/node_modules/newman/node_modules/request/request.js:533:10)
    at new Request (/home/gillian/npm/lib/node_modules/newman/node_modules/request/request.js:99:8)
    at request (/home/gillian/npm/lib/node_modules/newman/node_modules/request/index.js:54:11)
    at Object.jsface.Class._execute (/home/gillian/npm/lib/node_modules/newman/src/runners/RequestRunner.js:181:26)
    at null._onTimeout (/home/gillian/npm/lib/node_modules/newman/src/runners/RequestRunner.js:222:11)
    at Timer.listOnTimeout (timers.js:110:15)
```

Found out that when we saved the file with postman 3, the property "rawModeData": "", which worked in Newman, became "rawModeData": [""] and that caused issues. Changing it back fixed it. Maybe Newman needs to be updated to accept an array? 

Thanks!

Newman version: 1.2.16
Postman version: 3.0.0.10 (packaged)
OS: linux
Architecture: x86-64
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
Cannot reproduce. Will push a check in v3.0.1

**Comment by abhijitkane** [comment]
@riyunoa - Can you check if this issue still occurs with v3.0.4 of Postman?
