### ISSUE TITLE
Postman Extension for VSCode is not working

### ISSUE THREAD

**Issue by ybhwang** [a85/POSTMan-Chrome-Extension#12118]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The first time I installed the extension provided from the marketplace, there was no problem with the operation, but from some point it does not operate normally.

### Steps To Reproduce

1. Install the [extension](https://marketplace.visualstudio.com/items?itemName=Postman.postman-for-vscode)
2. Open that extension from the side menu -> **infinite Loading**

3. After entering Postman through the command palette
4. Run the provided commands (All commands give the following error)
   - Error Message Pattern: `command 'postman-for-vscode.*' not found`

### Screenshots or Videos

![postman_vscode_command_palatte_error_message](https://github.com/postmanlabs/postman-app-support/assets/26553392/8cd4cf14-bbea-4da6-bc4e-b6275b6ff76b)

### Operating System

macOS

### Postman Version

13.4

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
Hi @ybhwang It will be really helpful if you can also share a screen recording and extension logs. It will help us debug the issue faster.

Please have a look at the below screenshot to understand how you can retrieve the logs.

<img width="420" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/44100113/59f9ee13-cf8d-4acb-9c64-bd8b5b04be43">

**Comment by ybhwang** [comment]
> Hi @ybhwang It will be really helpful if you can also share a screen recording and extension logs. It will help us debug the issue faster.
> 
> Please have a look at the below screenshot to understand how you can retrieve the logs.
> 
> <img alt="image" width="420" src="https://user-images.githubusercontent.com/44100113/247011699-59f9ee13-cf8d-4acb-9c64-bd8b5b04be43.png">

Same error pattern... but it shows without modal.

![스크린샷 2023-06-21 오전 10 31 45](https://github.com/postmanlabs/postman-app-support/assets/26553392/55fbaf27-9ef3-4d37-9bd8-1bfb834651aa)

**Comment by ybhwang** [comment]
If any of you have this same problem, try this solution.

1. Download the package from Visual Studio Code official site
2. Unzip it
3. Cut & Paste new app to overwrite the existing app in your Application directory.

**Comment by pravnkr** [comment]
This is still not working on my mac

Inside the log files I have the following lines
`
(2023-08-08T08:48:41.794Z) [info] [extension] Extension activation started: 1691484521793
(2023-08-08T08:56:09.728Z) [info] [extension] Extension activation started: 1691484969723
(2023-08-08T08:58:02.252Z) [info] [extension] Extension activation started: 1691485082249
(2023-08-08T09:02:57.046Z) [info] [extension] Extension activation started: 1691485377045
(2023-08-08T09:04:36.749Z) [info] [extension] Extension activation started: 1691485476748
`

It's just infinitely loading, earlier it was working before I closed the vscode.

**Comment by pankajk07** [comment]
@pravnkr Do you see any other error on the VS Code dev tools? 
You can open the dev tools from `Help > Toggle Developer Tools `

**Comment by pravnkr** [comment]
@pankajk07 yeah I am getting this in console
`
Activating extension 'Postman.postman-for-vscode' failed: Unable to parse decrypted password.
$onExtensionActivationError @ mainThreadExtensionService.ts:113
log.ts:441   ERR Unable to read file '/Users/praveen/Library/Application Support/Code - Insiders/logs/20230808T145122/window1/exthost/output_logging_20230808T145124/11-Postman.log' (Error: Unable to resolve nonexistent file '/Users/praveen/Library/Application Support/Code - Insiders/logs/20230808T145122/window1/exthost/output_logging_20230808T145124/11-Postman.log'): Error: Unable to read file '/Users/praveen/Library/Application Support/Code - Insiders/logs/20230808T145122/window1/exthost/output_logging_20230808T145124/11-Postman.log' (Error: Unable to resolve nonexistent file '/Users/praveen/Library/Application Support/Code - Insiders/logs/20230808T145122/window1/exthost/output_logging_20230808T145124/11-Postman.log')
    at e.FileService.w (vscode-file://vscode-app/private/var/folders/3t/bd6qcwk13kl2qcgj0pnjvd_c0000gn/T/AppTranslocation/8B01E988-C24E-43AC-A9B6-82A54EA2262E/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:624:18204)
    at e.FileService.v (vscode-file://vscode-app/private/var/folders/3t/bd6qcwk13kl2qcgj0pnjvd_c0000gn/T/AppTranslocation/8B01E988-C24E-43AC-A9B6-82A54EA2262E/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:624:17865)
    at async e.FileService.u (vscode-file://vscode-app/private/var/folders/3t/bd6qcwk13kl2qcgj0pnjvd_c0000gn/T/AppTranslocation/8B01E988-C24E-43AC-A9B6-82A54EA2262E/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:624:17147)
    at async e.FileOutputChannelModel.I (vscode-file://vscode-app/private/var/folders/3t/bd6qcwk13kl2qcgj0pnjvd_c0000gn/T/AppTranslocation/8B01E988-C24E-43AC-A9B6-82A54EA2262E/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1638:39935)
    at async vscode-file://vscode-app/private/var/folders/3t/bd6qcwk13kl2qcgj0pnjvd_c0000gn/T/AppTranslocation/8B01E988-C24E-43AC-A9B6-82A54EA2262E/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1638:39131
`

**Comment by pravnkr** [comment]
@pankajk07 yeah I am getting this in console
`
Activating extension 'Postman.postman-for-vscode' failed: Unable to parse decrypted password.
$onExtensionActivationError @ mainThreadExtensionService.ts:113
log.ts:441   ERR Unable to read file '/Users/praveen/Library/Application Support/Code - Insiders/logs/20230808T145122/window1/exthost/output_logging_20230808T145124/11-Postman.log' (Error: Unable to resolve nonexistent file '/Users/praveen/Library/Application Support/Code - Insiders/logs/20230808T145122/window1/exthost/output_logging_20230808T145124/11-Postman.log'): Error: Unable to read file '/Users/praveen/Library/Application Support/Code - Insiders/logs/20230808T145122/window1/exthost/output_logging_20230808T145124/11-Postman.log' (Error: Unable to resolve nonexistent file '/Users/praveen/Library/Application Support/Code - Insiders/logs/20230808T145122/window1/exthost/output_logging_20230808T145124/11-Postman.log')
    at e.FileService.w (vscode-file://vscode-app/private/var/folders/3t/bd6qcwk13kl2qcgj0pnjvd_c0000gn/T/AppTranslocation/8B01E988-C24E-43AC-A9B6-82A54EA2262E/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:624:18204)
    at e.FileService.v (vscode-file://vscode-app/private/var/folders/3t/bd6qcwk13kl2qcgj0pnjvd_c0000gn/T/AppTranslocation/8B01E988-C24E-43AC-A9B6-82A54EA2262E/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:624:17865)
    at async e.FileService.u (vscode-file://vscode-app/private/var/folders/3t/bd6qcwk13kl2qcgj0pnjvd_c0000gn/T/AppTranslocation/8B01E988-C24E-43AC-A9B6-82A54EA2262E/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:624:17147)
    at async e.FileOutputChannelModel.I (vscode-file://vscode-app/private/var/folders/3t/bd6qcwk13kl2qcgj0pnjvd_c0000gn/T/AppTranslocation/8B01E988-C24E-43AC-A9B6-82A54EA2262E/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1638:39935)
    at async vscode-file://vscode-app/private/var/folders/3t/bd6qcwk13kl2qcgj0pnjvd_c0000gn/T/AppTranslocation/8B01E988-C24E-43AC-A9B6-82A54EA2262E/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1638:39131
`

**Comment by pankajk07** [comment]
@pravnkr There seems to be an issue with your keychain, due to which VS Code is not able to fetch the auth details. Can you try deleting the the keychain entry for Postman's vscode extension and try to load the window again. 

<img width="342" alt="Screenshot 2023-08-08 at 3 40 13 PM" src="https://github.com/postmanlabs/postman-app-support/assets/44100113/29c04a55-a3df-4322-a8f8-9a7c20e69655">

**Comment by pravnkr** [comment]
Thanks @pankajk07 that worked.

**Comment by akarpov91** [comment]
@pravnkr deleting the keychain is constantly required.

Is there a more permanent/stable solution?

**Comment by neil-m** [comment]
> deleting the the keychain entry for Postman's vscode extension

can you elaborate on how to do this?

**Comment by vidhyasagarreddy** [comment]
Extension is still broken. I'm using VS Code Insiders build

**Comment by pankajk07** [comment]
@vidhyasagarreddy The issue is being tracked over here https://github.com/postmanlabs/postman-app-support/issues/12923
