### ISSUE TITLE
Update 10.16.0 -> 10.17.0 not working

### ISSUE THREAD

**Issue by capc0** [a85/POSTMan-Chrome-Extension#12233]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The auto updater is having trouble fully installing version 10.17.0.

### Steps To Reproduce

1. Download and install Windows version 10.16 from https://www.postman.com/downloads/
2. Start the Installer -> Postmann will launch
3. Whenever quitting Postman, the auto updater tries to install 10.17 which fails -> Postman does not start anymore without repeating step 1 & 2.

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/27284008/89f2f10e-ed8c-4fcd-b4c4-9088d88c4e9c)

![image](https://github.com/postmanlabs/postman-app-support/assets/27284008/605c7894-76cd-44b5-a57f-e25e1ea8a91f)

https://github.com/postmanlabs/postman-app-support/assets/27284008/5109a760-8430-49f7-b7d6-2708b616488b

### Operating System

Windows

### Postman Version

10.17.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by mkubele** [comment]
I have the same problem on MacOS (Apple Silicon). It happens even on the clean install

**Comment by levimayer21** [comment]
Same problem, perfectly matching the issue's description, on Windows 10. Saw this in the Squirrel-CheckForUpdate.log.
```
[15. 08. 23 15:07:20] info: Program: Starting Squirrel Updater: --checkForUpdate https://dl.pstmn.io/update/WIN64/10.16.0/stable?installationId=72edaaab-37f4-4a6b-b44c-179c3338a346&userId=17672311&syncEnabled=true&teamPlan=&teamId=0
[15. 08. 23 15:07:20] info: Program: Fetching update information, downloading from https://dl.pstmn.io/update/WIN64/10.16.0/stable?installationId=72edaaab-37f4-4a6b-b44c-179c3338a346&userId=17672311&syncEnabled=true&teamPlan=&teamId=0
[15. 08. 23 15:07:20] info: CheckForUpdateImpl: Using existing staging user ID: 69856cef-2aba-53fb-b3e5-4f89036fd072
[15. 08. 23 15:07:20] info: CheckForUpdateImpl: Downloading RELEASES file from https://dl.pstmn.io/update/WIN64/10.16.0/stable?installationId=72edaaab-37f4-4a6b-b44c-179c3338a346&userId=17672311&syncEnabled=true&teamPlan=&teamId=0
[15. 08. 23 15:07:20] info: FileDownloader: Downloading url: https://dl.pstmn.io/update/WIN64/10.16.0/stable/RELEASES?installationId=72edaaab-37f4-4a6b-b44c-179c3338a346&userId=17672311&syncEnabled=true&teamPlan=&teamId=0&id=Postman-win64&localVersion=10.16.0&arch=amd64
[15. 08. 23 15:07:21] warn: UpdateInfo: Couldn't get release notes for:Postman-win64-10.17.0-full.nupkg: System.IO.FileNotFoundException: Could not find file 'C:\Users\----\AppData\Local\Postman\packages\Postman-win64-10.17.0-full.nupkg'.
File name: 'C:\Users\----\AppData\Local\Postman\packages\Postman-win64-10.17.0-full.nupkg'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.ZipPackage.<>c__DisplayClass9_0.<.ctor>b__0()
   at NuGet.ZipPackage.EnsureManifest()
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
```

**Comment by SandraLane** [comment]
Same issue on macbook

**Comment by dmitrylen-fieldpulse** [comment]
Same issue on MacBook  M1, both macOS Sequoia 15.2 and macOS Tahoe 26.0.1

**Comment by MC-sanderv** [comment]
Closing this as it appears to be a version-specific update failure for the 10.17.0 package. 
With Postman now on v11+ this specific installer conflict is likely resolved.


If anyone still encounters this updater issue, you could try installing latest version cleanly manually, or as a hack deleting:
%AppData%\Local\Postman\packages\
%AppData%\Local\Postman\Update.exe


If the issue persists on the current v11 builds, please open a new ticket with updated logs.
