### ISSUE TITLE
Postman crashes 

### ISSUE THREAD

**Issue by Hooman88** [a85/POSTMan-Chrome-Extension#12424]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman crashes in a very random way

### Steps To Reproduce

I have not found yet any known way to reproduce it. I found the error inside the **main.log**

### Operating System

Windows

### Postman Version

v10.19.6 

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?
`
[28964][1697803576089][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"Error","message":"Render frame was disposed before WebFrameMain could be accessed","stack":"Error: Render frame was disposed before WebFrameMain could be accessed\n    at decirc (C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\fast-safe-stringify\\index.js:100:19)\n    at decirc (C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\fast-safe-stringify\\index.js:100:9)\n    at decirc (C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\fast-safe-stringify\\index.js:100:9)\n    at decirc (C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\fast-safe-stringify\\index.js:94:9)\n    at decirc (C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\fast-safe-stringify\\index.js:100:9)\n    at stringify (C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\fast-safe-stringify\\index.js:25:3)\n    at Format.transform (C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\logform\\json.js:24:19)\n    at DerivedLogger._transform (C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\winston\\lib\\winston\\logger.js:235:29)\n    at DerivedLogger.Transform._read (C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\readable-stream\\lib\\_stream_transform.js:184:10)\n    at DerivedLogger.Transform._write (C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\readable-stream\\lib\\_stream_transform.js:172:83)\n    at doWrite (C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\readable-stream\\lib\\_stream_writable.js:428:64)\n    at writeOrBuffer (C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\readable-stream\\lib\\_stream_writable.js:417:5)\n    at DerivedLogger.Writable.write (C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\readable-stream\\lib\\_stream_writable.js:334:11)\n    at DerivedLogger.log (C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\winston\\lib\\winston\\logger.js:164:14)\n    at C:\\Users\\h.seyfi\\AppData\\Local\\Postman\\app-10.19.0\\resources\\app.asar\\node_modules\\@postman\\app-logger\\lib\\collectors\\AbstractCollector.js:33:23\n    at Array.forEach (<anonymous>)"}
`

**Comment by Fulerent** [comment]
Hi! I have problem too after 5-10 minutest work with Postman. Macbook 14 M1 Monterey:

`
[72101][1698059108607][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"Error","message":"Render frame was disposed before WebFrameMain could be accessed","stack":"Error: Render frame was disposed before WebFrameMain could be accessed\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:19)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:9)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:9)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:94:9)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:9)\n    at stringify (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:25:3)\n    at Format.transform (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/logform/json.js:24:19)\n    at DerivedLogger._transform (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/winston/lib/winston/logger.js:235:29)\n    at DerivedLogger.Transform._read (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:184:10)\n    at DerivedLogger.Transform._write (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:172:83)\n    at doWrite (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:428:64)\n    at writeOrBuffer (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:417:5)\n    at DerivedLogger.Writable.write (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:334:11)\n    at DerivedLogger.log (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/winston/lib/winston/logger.js:164:14)\n    at /Applications/Postman.app/Contents/Resources/app.asar/node_modules/@postman/app-logger/lib/collectors/AbstractCollector.js:33:23\n    at Array.forEach (<anonymous>)"}]
`

**Comment by jviotti** [comment]
Hey there! What OS name and version are you running? Any chance this is on macOS Sonoma?

**Comment by Hooman88** [comment]
Windows Professional  version: **10.0.19045**

**Comment by Eufix** [comment]
I have the same problem with the same stack trace.   
Manjaro linux, 6.1.55-1-MANJARO

**Comment by mjshakespeare** [comment]
I'm seeing this issue on windows 11.
```
Error: Render frame was disposed before WebFrameMain could be accessed
    at decirc (C:\Users\username\AppData\Local\Postman\app-10.19.7\resources\app.asar\node_modules\fast-safe-stringify\index.js:100:19)
```

**Comment by MC-sanderv** [comment]
Closing as stale.
Reported on older v10.x builds and related to Electron runtime behavior. 

Please open a new issue if this still happens on the latest version.
