### ISSUE TITLE
Postman Desktop Client non functional

### ISSUE THREAD

**Issue by Ady999999999** [a85/POSTMan-Chrome-Extension#12436]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman Desktop Client non functional, can't load any collections, workspace is not accessible.
Basically we have no functionality with the desktop client . I'm monitoring this issue with my co worker who also has the same issue.

We are both logged in users, free plan.

### Steps To Reproduce

1. Open Postman Tool
2. Try access current Workspace, observe it can't be loaded
3. Try to Access any collection, observe it can't be loaded

### Screenshots or Videos

![Postman Error](https://github.com/postmanlabs/postman-app-support/assets/148074818/863558d7-ad94-4423-8d90-a81087d8fdf6)

![image](https://github.com/postmanlabs/postman-app-support/assets/148074818/37810cac-4391-41f4-8fd9-fe1a170270b8)

### Operating System

Windows

### Postman Version

v10.19

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ChasNelson1990** [comment]
I am having the some problem with a Linux version of the PDC. On opening the logs I see an error and a warning during boot - possibly reelated?
```bash
[11201][1698321920555][requester][info]["OfflineAPIClientService~init: Boot started"]
[11201][1698321920555][requester][info]["ScratchpadMigrationBootFirmware~bootFirmware : Booting started"]
[11201][1698321920555][requester][info]["bootMigrationFirmware~initializeMigrationFirmware : started"]
[11201][1698321920556][requester][info]["bootMigrationFirmware~getFirmwareWebview : partition string created","persist:547082fc-4436-4b22-af45-5ebfa709ee91"]
[11201][1698321920556][requester][info]["bootMigrationFirmware~getFirmwareWebview : webview created"]
[11201][1698321920563][requester][info]["bootMigrationFirmware~getLocalStorageAdapter : getting local storage adapter"]
[11201][1698321920796][requester][warn]["prefetchWorkspaceData: Prefetching of data failed",{"name":"TypeError","message":"Failed to fetch","stack":"TypeError: Failed to fetch\n    at t.<computed> (https://desktop.postman.com/?desktopVersion=10.18.10&userId=29300394&teamId=0:10:5819)\n    at https://desktop.postman.com/_ar-assets/vendors-4f26158693e3d147.min.js:2930:143332\n    at Function.request (https://desktop.postman.com/_ar-assets/common-a195baebf2b28d18.min.js:7725:623545)\n    at Object.<anonymous> (https://desktop.postman.com/_ar-assets/common-a195baebf2b28d18.min.js:10182:122398)\n    at Generator.next (<anonymous>)\n    at https://desktop.postman.com/_ar-assets/common-a195baebf2b28d18.min.js:10182:122290\n    at nrWrapper (https://desktop.postman.com/?desktopVersion=10.18.10&userId=29300394&teamId=0:10:29518)\n    at new Promise (<anonymous>)\n    at new r (https://desktop.postman.com/?desktopVersion=10.18.10&userId=29300394&teamId=0:10:8414)\n    at o (https://desktop.postman.com/_ar-assets/common-a195baebf2b28d18.min.js:10182:122035)\n    at Object.getWithGateway (https://desktop.postman.com/_ar-assets/common-a195baebf2b28d18.min.js:10182:122336)\n    at Object.<anonymous> (https://desktop.postman.com/_ar-assets/common-a195baebf2b28d18.min.js:10182:51326)\n    at Generator.next (<anonymous>)\n    at https://desktop.postman.com/_ar-assets/common-a195baebf2b28d18.min.js:10182:50824\n    at nrWrapper (https://desktop.postman.com/?desktopVersion=10.18.10&userId=29300394&teamId=0:10:29518)\n    at new Promise (<anonymous>)\n    at new r (https://desktop.postman.com/?desktopVersion=10.18.10&userId=29300394&teamId=0:10:8414)\n    at C (https://desktop.postman.com/_ar-assets/common-a195baebf2b28d18.min.js:10182:50569)\n    at Object.getWorkspaceWithGateway (https://desktop.postman.com/_ar-assets/common-a195baebf2b28d18.min.js:10182:51145)\n    at s (https://desktop.postman.com/_ar-assets/requester-desktop-121d6310ee3fad56.min.js:403:81923)"}]
[11201][1698321922346][requester][info]["DesktopLocationService ~ init initialized"]
[11201][1698321922349][requester][info]["NavigationService ~ Initialized: Success"]
[11201][1698321922349][requester][info]["initializeNavigation~boot - Success"]
[11201][1698321922351][requester][info]["EventBus~initialize - Success"]
[11201][1698321922351][requester][info]["Messaging~boot - Success"]
[11201][1698321922370][requester][info]["bootCrashReporter~ Success"]
[11201][1698321922371][requester][info]["Telemetry~boot - Success"]
[11201][1698321922372][requester][info]["bootConfigurations~initialize - Success"]
[11201][1698321922373][requester][info]["migrateLocalStorage: Bailing out"]
[11201][1698321922375][requester][info]["Settings~boot - Success"]
[11201][1698321922453][requester][info]["Migrations: Skipping migrations. No migrations to apply."]
[11201][1698321922542][requester][info]["bootstrapModels - Success"]
[11201][1698321922542][requester][info]["WLModels~boot - Success"]
[11201][1698321922546][requester][info]["Session~boot - Success"]
[11201][1698321922547][requester][info]["IndependentServices~boot - Success"]
[11201][1698321922554][requester][info]["AppModels~boot - Success"]
[11201][1698321922566][requester][info]["initializeConfigurationsValues - Success"]
[11201][1698321922576][requester][info]["CookiesBootHelper~Migration: Bailing out, no migrations to apply."]
[11201][1698321922586][requester][info]["bootIndependentServicesShared: Success"]
[11201][1698321922587][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-initializeConfigurationsValues to client envets with value 11.699999999982538"]
[11201][1698321922600][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-clearConsoleDesktop to client envets with value 7.900000000023283"]
[11201][1698321922601][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-cleanupRunner to client envets with value 2.5"]
[11201][1698321922601][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-migrateCookiesFromElectron to client envets with value 0.1999999999825377"]
[11201][1698321922601][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-cleanupCookies to client envets with value 5"]
[11201][1698321922601][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-clearAPISchema to client envets with value 3.1000000000058208"]
[11201][1698321922601][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-clearEditorDataCache to client envets with value 1.3999999999941792"]
[11201][1698321922602][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-bootIndependentServicesShare to client envets with value 0.29999999998835847"]
[11201][1698321922602][requester][info]["performSingletonJobs: Success"]
[11201][1698321922607][requester][info]["checkVersionLock: Starting version lock check"]
[11201][1698321932647][requester][error]["performVersionLockCheck: Error while checking version lock",{"name":"Error","message":"The version lock check did not complete within 10000ms","stack":"Error: The version lock check did not complete within 10000ms\n    at https://desktop.postman.com/_ar-assets/requester-desktop-121d6310ee3fad56.min.js:976:209016\n    at a (https://desktop.postman.com/_ar-assets/vendors-4f26158693e3d147.min.js:2930:57623)\n    at nrWrapper (https://desktop.postman.com/?desktopVersion=10.18.10&userId=29300394&teamId=0:10:29518)"}]
[11201][1698321932651][requester][info]["performVersionLockCheck: Checking cached response"]
[11201][1698321932651][requester][info]["performVersionLockCheck: No cached response exists for the user"]
[11201][1698321932651][requester][info]["checkVersionLock: Version lock check failed."]
[11201][1698321932651][requester][info]["showBlockingUI: Showing the UI."]
[11201][1698321961418][requester][warn]["CurrentUserDetailsService~failed-to-fetch-user-flags",{"error":{"name":"serverError","message":"Bad Gateway","source":"gateway"}},{"context":{"api":"CurrentUserDetailsService","domain":"iam"},"error":{"error":{"name":"serverError","message":"Bad Gateway","source":"gateway"}}}]
```

**Comment by ifyyf** [comment]
When I am not logged into Postman, it can run normally and send requests

After I logged in, I accounted for a similar issue: Unable to fetch data
and Postman is completely unusable after logging in

<img width="753" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/75622685/619461ab-b92c-4142-80f3-7c9c49667bbd">

The following are possible related logs

[88330][1698321171578][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"Cannot read properties of undefined (reading 'send')","stack":"TypeError: Cannot read properties of undefined (reading 'send')\n    at Object.sendMessageToInterceptor (/Applications/Postman.app/Contents/Resources/app.asar/services/websocketServer.js:144:10)\n    at Object.requesterWindowHandler (/Applications/Postman.app/Contents/Resources/app.asar/services/websocketServer.js:389:14)\n    at EventEmitter.emit (node:events:402:35)\n    at EventEmitter.emit (node:domain:475:12)\n    at _dispatch (/Applications/Postman.app/Contents/Resources/app.asar/common/_event-bus.js:256:14)\n    at EventBus._publish (/Applications/Postman.app/Contents/Resources/app.asar/common/_event-bus.js:207:9)\n    at Object.closedHandler (/Applications/Postman.app/Contents/Resources/app.asar/services/windowManager.js:1072:18)\n    at BrowserWindow.emit (node:events:390:28)\n    at BrowserWindow.emit (n

**Comment by numaanashraf** [comment]
We are investigating this and have started taking actions to mitigate this. Could you restart your app and check if the issue is resolved? 

Incident status: https://status.postman.com/incidents/ttjny8611gr0

**Comment by shinde-ha** [comment]
Seems to be resolved on my end. I hope it is same for everyone else.

**Comment by ifyyf** [comment]
> We are investigating this and have started taking actions to mitigate this. Could you restart your app and check if the issue is resolved?
> 
> Incident status: https://status.postman.com/incidents/ttjny8611gr0

I have tried restarting the application, even uninstalling and reinstalling it, and the results are still the same

**Comment by ifyyf** [comment]
> 我们正在对此进行调查，并已开始采取行动来缓解这一问题。您可以重新启动您的应用程序并检查问题是否已解决吗？
> 
> 事件状态：[https ://status.postman.com/incidents/ttjny8611gr0](https://status.postman.com/incidents/ttjny8611gr0)

It's working properly, thank you very much

**Comment by ChasNelson1990** [comment]
> We are investigating this and have started taking actions to mitigate this. Could you restart your app and check if the issue is resolved?
> 
> Incident status: https://status.postman.com/incidents/ttjny8611gr0

Yup, seems resolved here too. Thanks!

**Comment by Ady999999999** [comment]
Resolved here too, thank you!

**Comment by ifyyf** [comment]
it is now running normally. Thank you again






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "postmanlabs/postman-app-support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月26日(星期四) 晚上8:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [postmanlabs/postman-app-support] Postman Desktop Client non functional (Issue #12436)





 
We are investigating this and have started taking actions to mitigate this. Could you restart your app and check if the issue is resolved?
 
Incident status: https://status.postman.com/incidents/ttjny8611gr0

**Comment by numaanashraf** [comment]
Thanks everyone! Closing this.
