### ISSUE TITLE
Postman closes unexpectedly

### ISSUE THREAD

**Issue by SlavaUtesinov** [a85/POSTMan-Chrome-Extension#12466]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Recently Posman has started to close itself unexpectedly after intensive usage and sometimes it loads it's workspace or some parts of workspace like environments or collections of requests too long or can't find all elements (for example some requests are gone, after several restarts it works)

### Steps To Reproduce

intensive invokation of grpc requests with environments switches and edits

### Operating System

macOS Ventura 13.5

### Postman Version

Version 10.20.0 UI Version: 10.20.0-ui-231018-1251 Desktop Platform Version: 10.20.0 (10.20.0)

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Maybe it has to do with recent Kaspersky update (https://community.postman.com/t/postman-not-starting-up-stuck-in-preparing-workspace/10132/1)

PS Extracts from logs:

**main.log**
`
[67200][1699608021362][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"Error","message":"Render frame was disposed before WebFrameMain could be accessed","stack":"Error: Render frame was disposed before WebFrameMain could be accessed\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:19)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:9)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:9)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:94:9)\n    at decirc (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:100:9)\n    at stringify (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/fast-safe-stringify/index.js:25:3)\n    at Format.transform (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/logform/json.js:24:19)\n    at DerivedLogger._transform (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/winston/lib/winston/logger.js:235:29)\n    at DerivedLogger.Transform._read (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:184:10)\n    at DerivedLogger.Transform._write (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:172:83)\n    at doWrite (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:428:64)\n    at writeOrBuffer (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:417:5)\n    at DerivedLogger.Writable.write (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:334:11)\n    at DerivedLogger.log (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/winston/lib/winston/logger.js:164:14)\n    at /Applications/Postman.app/Contents/Resources/app.asar/node_modules/@postman/app-logger/lib/collectors/AbstractCollector.js:33:23\n    at Array.forEach (<anonymous>)"}]
`

**render-requester.log**
`[32559][1699618829421][requester][error]["ReleaseListStore~getReleases: apiId or apiVersionId is missing"]
[32559][1699618829469][requester][info]["EnvironmentSelectorContainer~getActiveApiInWorkbench: Active Tab is not a child of an API"]
[32559][1699618829485][requester][error]["i18n ~ missingKeyHandler",["en-US"],"app-header","<0>Test scripts are written in JavaScript, and are run after the response is received. Learn more about</0><1>test scripts</1>"]`

**Comment by cmendez2121** [comment]
I'm running on Windows 11 and running Kaspersky Internet security 21.3.10.391 and the only way to make WORK postman is suspending protection , 

have set on firewall exclusions to the EXE file, on network added domains , i did everything i could and nothing works 
even the network monitor does not appear postman as a running APP, checing postman  suppose its an electron app or something similar, but checking other similar apps like evernote, evernote it appearas on network monitor as an app but postman no

**Comment by satokenta940** [comment]
I also encountered the same problem, currently using [Apidog ](https://apidog.com/)

**Comment by MC-sanderv** [comment]
Closing as stale.

Reported on older v10.x builds and appears environment-specific (Electron + security software). 


Please open a new issue if this still happens on the latest version.
