### ISSUE TITLE
Crash on changing user/ workspace on Linux

### ISSUE THREAD

**Issue by daviddawson** [a85/POSTMan-Chrome-Extension#12469]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Whenever I change workspace/ user, the app crashes.

```
1699873558951 main info "VersionDependencyService: Resetting UI version as user logged out/switched account"
1699873558951 main info "Main - model-events~user - (users, switch) received"
TypeError: Object has been destroyed
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2484)
    at IPCChannel.cleanup (/home/david/app/Postman/app/resources/app/common/channels/IPCChannel.js:85:16)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
1699873558960 main error "Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"Object has been destroyed","stack":"TypeError: Object has been destroyed\n    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2484)\n    at IPCChannel.cleanup (/home/david/app/Postman/app/resources/app/common/channels/IPCChannel.js:85:16)\n    at listOnTimeout (node:internal/timers:557:17)\n    at processTimers (node:internal/timers:500:7)"}
Main~handleUncaughtError - Uncaught errors TypeError: Object has been destroyed
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2484)
    at IPCChannel.cleanup (/home/david/app/Postman/app/resources/app/common/channels/IPCChannel.js:85:16)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
1699873558963 main info "Shell~init~switchUser: switching to user ","1595211"
```

### Steps To Reproduce

1. Open postman
2. switch user
3. app crashes

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/206276/ff4f6c65-74fa-4172-bf4a-e9a4bb0c838a)

### Operating System

Ubuntu Linux 22.04.3 LTS

### Postman Version

10.19.17

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by MC-sanderv** [comment]
Closing as stale.

Reported on an older v10.x build and related to Electron lifecycle during user switch.

Please re-open with logs if this still happens on the latest version.
