### ISSUE TITLE
Markdown Editor is broken because of a JavaScript Uncaught TypeError error

### ISSUE THREAD

**Issue by pozil** [a85/POSTMan-Chrome-Extension#12487]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I've been working on the description of a collection and I'm not longer able to switch to the Markdown Editor. Selecting it from the dropdown doesn't do anything. I realized that this is because of a JavaScript error (see stack trace below).
This issue affects both the Web UI and the Desktop app.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')
    at m (turndown-plugin-gfm.js:123:23)
    at Object.filter (turndown-plugin-gfm.js:96:41)
    at m (turndown.js:423:18)
    at d (turndown.js:411:11)
    at u.forNode (turndown.js:396:19)
    at k.I (turndown.js:930:27)
    at turndown.js:895:42
    at NodeList.reduce (<anonymous>)
    at k.A (turndown.js:888:19)
    at k.I (turndown.js:931:27)
    at turndown.js:895:42
    at NodeList.reduce (<anonymous>)
    at k.A (turndown.js:888:19)
    at k.turndown (turndown.js:800:28)
    at t.default (convert-html-to-md.js:28:28)
    at Object.slateToMD (MimirEditor.js:291:24)
    at requester-legacy-abc0e25fbfaa75b5.min.js:3780:2888
    at Oe (SingleSelect.js:123:1)
    at useStateManager-783b07d5.esm.js:40:1
    at r.onChange (Select-126cf1dd.esm.js:1222:1)
    at r.setValue (Select-126cf1dd.esm.js:1249:1)
    at r.selectOption (Select-126cf1dd.esm.js:1277:1)
    at A.g (Select-126cf1dd.esm.js:2460:1)
    at Object.l (react-dom.production.min.js:14:82)
    at h (react-dom.production.min.js:14:235)
    at react-dom.production.min.js:14:289
    at _ (react-dom.production.min.js:15:72)
    at lt (react-dom.production.min.js:52:162)
    at st (react-dom.production.min.js:51:218)
    at ct (react-dom.production.min.js:52:334)
    at mt (react-dom.production.min.js:56:10)
    at D (react-dom.production.min.js:287:182)
    at F (react-dom.production.min.js:19:50)
    at en (react-dom.production.min.js:70:279)
    at Qt (react-dom.production.min.js:69:96)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:460)
    at Zo (react-dom.production.min.js:122:318)
    at M (react-dom.production.min.js:287:41)
    at Jt (react-dom.production.min.js:68:371)
    at HTMLDocument.s (helpers.js:85:1)
    at HTMLDocument.nrWrapper (12721794-67cb9baa-e0da-4986-957e-88d8734647e2:10:29518)
```

### Steps To Reproduce

1. Fork [this collection](https://www.postman.com/salesforce-developers/workspace/salesforce-developers/collection/12721794-67cb9baa-e0da-4986-957e-88d8734647e2):
2. Try to edit the description with the Markdown editor.

### Screenshots or Videos

![Screenshot 2023-11-22 at 13 27 24](https://github.com/postmanlabs/postman-app-support/assets/5071767/6cc5194c-3ae7-4738-8c38-4eb28703d8f3)

### Operating System

macOS 14.1.1 + Chrome latest version

### Postman Version

10.18.11-231017-1121

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by jellevandevelde** [comment]
Hi @pozil,

Our team is currently investigating this issue. After forking the linked Collection, it seems that the conversion between the 2 editors (WYSYWYG, Markdown) is causing unexpected behavior.

In the meantime, you can navigate to "Settings" > "Default documentation editor" to select "Markdown editor" as your default editor.

We will continue updating this thread as we find a solution for the reported issue.

**Comment by jellevandevelde** [comment]
It is now possible to switch between both editors again by using the dropdown in the toolbar; I have verified by forking the shared Collection. Thanks for reporting the bug and sharing the required details 👍.
