### ISSUE TITLE
'Add Cookie' button fails with type error when domain begins with a `.`

### ISSUE THREAD

**Issue by itsalaidbacklife** [a85/POSTMan-Chrome-Extension#12498]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Adding a cookie manually fails on Mac OS 13.5.1 with Postman versions:
Version 10.20.3
UI Version: 10.20.3-ui-231120-0418
Desktop Platform Version: 10.20.0 (10.20.0)

When I attempt to add a cookie with the 'Add cookie' button to a domain that begins with `.` e.g. `.assistments.org` or `.google.com`, the domain appears to be successfully added, but the 'Add cookie' button fails to open the text area for entering the cookie contents. The js console shows that Postman hits a `TypeError` every time you hit the 'Add cookie' button for these domains:

```
CookiesManagementContainer.js:198 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at CookiesManagementContainer.js:198:65
    at CookieManager.js:276:35
    at CookieManager.js:145:48
    at <anonymous>
    at nrWrapper (?desktopVersion=10.20.0&userId=12135047&teamId=0:10:29518)
```

### Steps To Reproduce

1. Create a new request with the '+' button 
2. Click 'cookies' to open the cookie manager
3. Add a new domain that begins with a `.` e.g. `.google.com`
4. Click that new domain to expand it
5. Click the 'Add Cookie' button underneath the newly added domain
6. Note that the text area for entering the cookie key/value pair does not open and a type error appears in the js console

### Screenshots or Videos

https://github.com/postmanlabs/postman-app-support/assets/6520704/56e77a70-ed4b-49ce-b73c-1e193436580b

### Operating System

MacOS (version 13.5.1)

### Postman Version

10.20.3

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by IT-Cru** [comment]
This issue still exists and it is blocking us to use cookie domains for multiple systems like backend and frontend which share same cookie via a dot starting cookie domain like .example.com

Also syncing with recent Chrome Postman interceptor extension doesn't work. It always cut of the dot at beginning of such a cookie domain in a way that .example.com becomes example.com

Correct me if I'm wrong, but this is a very common way to share a cookie between different subdomains. So maybe we could raise priority of this issue?

### My actual Postman versions:

Version 12.6.7
UI Version: 12.6.7-ui-260416-2244
Desktop Platform Version: 12.6.6 (12.6.6)
