### ISSUE TITLE
ProgramManager.ts:107 Uncaught (in promise) Error: Merlin worker not available

### ISSUE THREAD

**Issue by Ali1703** [a85/POSTMan-Chrome-Extension#12644]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

ProgramManager.ts:107 Uncaught (in promise) Error: Merlin worker not available
    at u.<anonymous> (ProgramManager.ts:107:1)
    at Generator.next (<anonymous>)
    at ProgramManager.ts:13:1
    at nrWrapper (?desktopVersion=10.22.0&userId=30452720&teamId=3092693:10:29518)
    at new Promise (<anonymous>)
    at new r (?desktopVersion=10.22.0&userId=30452720&teamId=3092693:10:8414)
    at c (ProgramManager.ts:9:1)
    at u.createLocalSession (ProgramManager.ts:102:1)
    at u.<anonymous> (ProgramManager.ts:154:1)
    at Generator.next (<anonymous>)
    at ProgramManager.ts:13:1
    at nrWrapper (?desktopVersion=10.22.0&userId=30452720&teamId=3092693:10:29518)
    at new Promise (<anonymous>)
    at new r (?desktopVersion=10.22.0&userId=30452720&teamId=3092693:10:8414)
    at c (ProgramManager.ts:9:1)
    at u.startRun (ProgramManager.ts:146:1)
    at RunButton.tsx:39:1
    at q (vendors-1e0191816fac6644.min.js:1:1136816)
    at Object.u (vendors-1e0191816fac6644.min.js:1400:428)
    at h (vendors-1e0191816fac6644.min.js:1400:571)
    at vendors-1e0191816fac6644.min.js:1400:717
    at y (vendors-1e0191816fac6644.min.js:1400:803)
    at ut (vendors-1e0191816fac6644.min.js:1400:16311)
    at at (vendors-1e0191816fac6644.min.js:1400:16144)
    at ct (vendors-1e0191816fac6644.min.js:1400:16500)
    at mt (vendors-1e0191816fac6644.min.js:1400:17707)
    at B (vendors-1e0191816fac6644.min.js:1400:114317)
    at U (vendors-1e0191816fac6644.min.js:1400:2126)
    at en (vendors-1e0191816fac6644.min.js:1400:23665)
    at Qt (vendors-1e0191816fac6644.min.js:1400:22882)
    at t.unstable_runWithPriority (vendors-1e0191816fac6644.min.js:1469:3795)
    at Gi (vendors-1e0191816fac6644.min.js:1400:45195)
    at R (vendors-1e0191816fac6644.min.js:1400:114094)
    at Yt (vendors-1e0191816fac6644.min.js:1400:22698)
    at HTMLDocument.a (vendors-1e0191816fac6644.min.js:2962:57623)
    at HTMLDocument.nrWrapper (?desktopVersion=10.22.0&userId=30452720&teamId=3092693:10:29518)

### Steps To Reproduce

1.Create flow with 20+ requests
2.Run collection

### Screenshots or Videos

![image_2024-02-13_17-01-40](https://github.com/postmanlabs/postman-app-support/assets/159925507/cabc853f-ce01-4441-84fe-8d748913426b)

### Operating System

Windows

### Postman Version

10.23.0

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

The problem will be reproduced 100%. How do I handle the error:
1) I see an error
2) I delete Postman from the computer
3) Download again
4) The problem goes away
5) I make a certain number of successful collection launches (flow)
6) after N number of times the error appears again

**Comment by rabbah** [comment]
This was fixed.
