### ISSUE TITLE
Performance Test error "Failed to start run"

### ISSUE THREAD

**Issue by vitin21** [a85/POSTMan-Chrome-Extension#12852]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm facing an issue with the new Performance Test tool. I'm trying to run just one Request from my Collection and it is returning me an generic error with the message "Failed to start run". I didn't find any kind of output from this error. Here are some prints of what I ran.

![image](https://github.com/postmanlabs/postman-app-support/assets/96988967/f7e34354-8613-4b70-89b6-a739303461d5)
![image](https://github.com/postmanlabs/postman-app-support/assets/96988967/1b2afa38-9c46-42d0-bfd8-8814ddd87ab0)

If any information about my request is needed to figure out what is going on please let me know.

### Steps To Reproduce

Create an Collection and try to run a simple Performance Test with any parameters

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/96988967/7079dcc9-0300-4117-9ffd-41037e7da567)

### Operating System

Windows

### Postman Version

11.0.7

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by s93rum06** [comment]
<pre>
[18176][1715471123192][main][info]["Booting Postman 11.0.12, win32-10.0.19045 on x64"]
[18176][1715471123194][main][info]["EventBus~initialize - Success"]
[18176][1715471123196][main][info]["Proxy configuration has not been setup"]
[18176][1715471123196][main][info]["CloudProxyManager~init - Success"]
[18176][1715471123215][main][info]["performShellDataMigration: Migration has already been done. Bailing out"]
[18176][1715471123216][main][info]["UpdateHandler~init - Success"]
[18176][1715471123218][main][info]["LeaderSelection: Initialized successfully"]
[18176][1715471123218][main][info]["VersionDependencyService: Initialized successfully"]
[18176][1715471123240][main][info]["GPU detected VID 4318 DID 7944 ACTIVE false"]
[18176][1715471123240][main][info]["GPU detected VID 5140 DID 140 ACTIVE false"]
[18176][1715471123243][main][info]["newAccountRegionPreferenceService~getPreferenceWithFallback - Preference not found in storage."]
[18176][1715471123244][main][info]["newAccountRegionPreferenceService~getToggleMenuTemplate - Using preference:","useUSRegion"]
[18176][1715471123256][main][info]["shellController~init: Success"]
[18176][1715471123267][main][info]["shellMeta~init: Success"]
[18176][1715471123267][main][info]["partitionMigrationService: State of V7 partition:"]
[18176][1715471123268][main][info]["partitionMigrationService: V7 partitions",[]]
[18176][1715471123268][main][info]["partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no partition with scratchpad namespace"]
[18176][1715471123268][main][info]["partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no transit partition which could have been used for scratchpad"]
[18176][1715471123268][main][info]["partitionMigrationService~init: Success"]
[18176][1715471123283][main][info]["partitionMigrationService~runV8PartitionsIntegrity: Two way migration~ removing the following partitions from v8",[]]
[18176][1715471123288][main][info]["userPartitionService~getRecentV8UserPartition: recent v8 user context partition ","8120dbe8-f271-4a9d-9519-8394b751ab87"]
[18176][1715471123288][main][info]["userPartitionService~_rectifyTheActivePartitionOfApplication: Setting the active partition to ","8120dbe8-f271-4a9d-9519-8394b751ab87"]
[18176][1715471123296][main][info]["userPartitionService~init: Success"]
[18176][1715471123311][main][info]["userPartitionService: State of v8 partition system:"]
[18176][1715471123314][main][info]["shell~init~getPartitionToLoad: loading active partition"]
[18176][1715471123316][main][info]["userPartitionService: List of partitions:",[{"partitionId":"8120dbe8-f271-4a9d-9519-8394b751ab87","namespace":"users","userId":"34858560","teamId":"0","lastUpdated":"2024-05-11T23:35:52.352Z"},{"partitionId":"3162e21b-a368-44b2-a4cb-8e30a5eef382","namespace":"scratchPad","userId":0,"teamId":0,"isDirty":false}]]
[18176][1715471123316][main][info]["userPartitionService: users global meta:",{}]
[18176][1715471123320][main][info]["Main:windowManager~newRequesterWindow: Fetch and update runtime config: us"]
[18176][1715471124618][main][info]["RuntimeIPCAgent~started: Success"]
[18176][1715471125740][main][info]["Main~getRemoteInitPath:: "]
[18176][1715471126240][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[18176][1715471126255][main][info]["windowManager: First requester booted successfully."]
[18176][1715471126255][main][info]["windowManager~restoreWindows: Restoring requester windows"]
[18176][1715471126255][main][info]["Main~AppEvents - Received booted event for process requester.Version 11.0.12 UI Version: 11.0.12-ui-240509-0541 Desktop Platform Version: 11.0.12"]
[18176][1715471126361][main][info]["Main~getRemoteInitPath:: "]
[18176][1715471126595][main][info]["Main~getPlatformLaunchPerfMetrics"]
[18176][1715471127716][main][info]["Main - model-events~user - (user, bootstrapUser) received"]
[18176][1715471127716][main][info]["model-events~user - bootstrapUser received"]
[18176][1715471127730][main][info]["INTERCEPTOR CONNECTIVITY: Attempting to start websocket server on port 15611"]
[18176][1715471162394][main][info]["ExecutionProcess ~ First boot"]
[18176][1715471162805][main][info]["ExecutionSystem execution ~ ipc connection successfully established"]
[18176][1715471162805][main][info]["[ExecutionProcessLauncher] Spawned the execution process, pid: ",12984]
[18176][1715471162817][main][info]["ExecutionSystem execution ~ ipc connection successfully established"]
[18176][1715471165490][main][error]["ExecutionProcess ~ Boot error",{"name":"Error","message":"Unhandled error. ({\n  subsystem: 'system.startup',\n  error: {\n    message: \"Cannot destructure property 'memory' of '(intermediate value)' as it is undefined.\",\n    stack: \"TypeError: Cannot destructure property 'memory' of '(intermediate value)' as it is undefined.\\n\" +\n      '    at ExecutionEngine._getNumberOfPossibleGroups (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\ScenarioManager\\\\ExecutionEngine\\\\Engine.js:127:13)\\n' +\n      '    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\\n' +\n      '    at async ExecutionEngine.setup (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\ScenarioManager\\\\ExecutionEngine\\\\Engine.js:154:49)\\n' +\n      '    at async onStartup (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\ScenarioManager\\\\index.js:38:5)\\n' +\n      '    at async startup (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\lib\\\\system\\\\_life-cycle.js:30:5)\\n' +\n      '    at async C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\lib\\\\system\\\\_life-cycle.js:219:7\\n' +\n      '    at async C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\preload\\\\desktop\\\\node-process\\\\IPC.js:1:2486'\n  },\n  source: 'ExecutionSystem:LifeCycle',\n  message: 'Error in starting up the ExecutionSystem',\n  severity: undefined,\n  timestamp: '2024-05-11T23:46:05.497Z'\n})","stack":"Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({\n  subsystem: 'system.startup',\n  error: {\n    message: \"Cannot destructure property 'memory' of '(intermediate value)' as it is undefined.\",\n    stack: \"TypeError: Cannot destructure property 'memory' of '(intermediate value)' as it is undefined.\\n\" +\n      '    at ExecutionEngine._getNumberOfPossibleGroups (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\ScenarioManager\\\\ExecutionEngine\\\\Engine.js:127:13)\\n' +\n      '    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\\n' +\n      '    at async ExecutionEngine.setup (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\ScenarioManager\\\\ExecutionEngine\\\\Engine.js:154:49)\\n' +\n      '    at async onStartup (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\ScenarioManager\\\\index.js:38:5)\\n' +\n      '    at async startup (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\lib\\\\system\\\\_life-cycle.js:30:5)\\n' +\n      '    at async C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\lib\\\\system\\\\_life-cycle.js:219:7\\n' +\n      '    at async C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\preload\\\\desktop\\\\node-process\\\\IPC.js:1:2486'\n  },\n  source: 'ExecutionSystem:LifeCycle',\n  message: 'Error in starting up the ExecutionSystem',\n  severity: undefined,\n  timestamp: '2024-05-11T23:46:05.497Z'\n})\n    at new NodeError (node:internal/errors:372:5)\n    at EventEmitter.emit (node:events:516:17)\n    at sendEvent (C:\\Users\\jerry\\AppData\\Local\\Postman\\app-11.0.12\\resources\\app.asar\\services\\automation-testing\\lib\\communication.js:19:19)\n    at broadcastError (C:\\Users\\jerry\\AppData\\Local\\Postman\\app-11.0.12\\resources\\app.asar\\services\\automation-testing\\lib\\communication.js:164:3)\n    at C:\\Users\\jerry\\AppData\\Local\\Postman\\app-11.0.12\\resources\\app.asar\\services\\automation-testing\\lib\\system\\_life-cycle.js:221:7\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async C:\\Users\\jerry\\AppData\\Local\\Postman\\app-11.0.12\\resources\\app.asar\\preload\\desktop\\node-process\\IPC.js:1:2486"}]
[18176][1715471183990][main][info]["ExecutionProcess ~ Already booted"]
[18176][1715471202169][main][info]["ExecutionProcess ~ Already booted"]
[18176][1715471578625][main][info]["WindowManager~closeHandler - Closed Window (id: 1 )"]
[18176][1715471578649][main][info]["Quitting app"]
[18176][1715471578649][main][info]["ExecutionProcessLauncher ~ No actively running power-save-blocker"]
[18176][1715471578653][main][info]["ExecutionSystem execution ~ ipc connection closed."]
</pre>

**Comment by vgrlima** [comment]
Sorry @s93rum06 I didn't get it. Can you explain what it means?

**Comment by tagtag21** [comment]
I'm getting a similar error
 I get the error "Something went wrong while setting up your system for performance testing."
[logs.zip](https://github.com/postmanlabs/postman-app-support/files/15466711/logs.zip)
![111Screenshot_4 (1)](https://github.com/postmanlabs/postman-app-support/assets/4338963/1a492d3f-b414-40ef-88c9-b978eb73d85f)

**Comment by RubenUeber** [comment]
I'm facing the same issue. Does anybody know how to solve this problem?

**Comment by postfrzero** [comment]
Hey folks -- if you're facing this problem on a Windows machine, could you let us know if the following two commands run successfully when run individually?

```
systeminfo | find "Available Physical Memory"
(Get-CimInstance -ClassName Win32_OperatingSystem).FreePhysicalMemory
```

Let's move the conversation over to #12608 since it was created first. Closing this ticket to avoid duplicates.

**Comment by pranav-getpie** [comment]
Facing the same issue, on 11.6.2

**Comment by shreyas-panduranga** [comment]
> Facing the same issue, on 11.6.2

@coder-parasharp28 Does this happen consistently? Can you please describe the problem with a few more details like screenshot of the error, the OS/platform you are running on?

Also, can you follow [this](https://github.com/postmanlabs/postman-app-support/issues/12852#issuecomment-2141221573) and let us know what you see?

**Comment by pranav-getpie** [comment]
Yes, it started to happen consistently.
Using Windows 11

Surprisingly, I restarted my machine and now am able to run smoothly.
Kudos and thanks for the prompt reply!
