### ISSUE TITLE
App hangs on startup in Win11

### ISSUE THREAD

**Issue by ptiseo-ep** [a85/POSTMan-Chrome-Extension#13060]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I’ve been using the Postman app on Win11 for a long time now. I stopped using it for 2-3 months due to other projects. Now, I have come back and when I start the app, it hangs with the spinner endlessly spinning. The menus sometimes show no text (although it always shows arrows and keymaps). I have updated the app, cleared the cache and disabled hardware acceleration. The main.log shows the error below.

[85060][1722870508901][main][error][“Main~handleUncaughtError - Uncaught errors”,{“name”:“TypeError”,“message”:“Cannot read properties of undefined (reading ‘send’)”,“stack”:“TypeError: Cannot read properties of undefined (reading ‘send’)\n at Object.sendMessageToInterceptor (C:\Users\someone\AppData\Local\Postman\app-11.6.1\resources\app.asar\services\websocketServer.js:127:10)\n at Object.requesterWindowHandler (C:\Users\someone\AppData\Local\Postman\app-11.6.1\resources\app.asar\services\websocketServer.js:370:14)\n at EventEmitter.emit (node:events:529:35)\n at EventEmitter.emit (node:domain:489:12)\n at _dispatch (C:\Users\someone\AppData\Local\Postman\app-11.6.1\resources\app.asar\common\_event-bus.js:256:14)\n at EventBus._publish (C:\Users\someone\AppData\Local\Postman\app-11.6.1\resources\app.asar\common\_event-bus.js:207:9)\n at Object._closedHandler (C:\Users\someone\AppData\Local\Postman\app-11.6.1\resources\app.asar\services\windowManager.js:1094:18)\n at BrowserWindow.emit (node:events:517:28)\n at BrowserWindow.emit (node:domain:489:12)\n at C:\Users\someone\AppData\Local\Postman\app-11.6.1\resources\app.asar\node_modules\@electron\remote\dist\src\main\server.js:480:71”}]

### Steps To Reproduce

1. Start Postman App; App fires up
2. Wait for spinner to stop spinning
3. Wait more
4. Go for coffee
5. Play with dog
6. Wait more
7. Read a book
8. ...

### Operating System

Windows

### Postman Version

11.7.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ajmszymanska** [comment]
Hi, I have the same problem : 

Postman version:  11.9.0

[32212][1724825586360][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"Cannot read properties of undefined (reading 'send')","stack":"TypeError: Cannot read properties of undefined (reading 'send')\n    at Object.sendMessageToInterceptor (C:\\Users\\someotherone\\AppData\\Local\\Postman\\app-11.9.0\\resources\\app.asar\\services\\websocketServer.js:127:10)\n    at Object.requesterWindowHandler (C:\\Users\\someotherone\\AppData\\Local\\Postman\\app-11.9.0\\resources\\app.asar\\services\\websocketServer.js:370:14)\n    at EventEmitter.emit (node:events:529:35)\n    at EventEmitter.emit (node:domain:489:12)\n    at _dispatch (C:\\Users\\someotherone\\AppData\\Local\\Postman\\app-11.9.0\\resources\\app.asar\\common\\_event-bus.js:256:14)\n    at EventBus._publish (C:\\Users\\someotherone\\AppData\\Local\\Postman\\app-11.9.0\\resources\\app.asar\\common\\_event-bus.js:207:9)\n    at Object._closedHandler (C:\\Users\\someotherone\\AppData\\Local\\Postman\\app-11.9.0\\resources\\app.asar\\services\\windowManager.js:1094:18)\n    at BrowserWindow.emit (node:events:517:28)\n    at BrowserWindow.emit (node:domain:489:12)"}]

**Comment by ptiseo-ep** [comment]
Well, nice to know I am not alone in the silence! :)

Based on the reply, I just updated to v11.9.0 and still have the same issue.

**Comment by hazelZ59** [comment]
Uncaught errors",{"name":"TypeError","message":"Cannot read properties of undefined (reading 'send')","stack":"TypeError: Cannot read properties of undefined (reading 'send')

Same issue for that lol


Update:
After I deleted all postman related cache files, and reinstall postman again, the issue didn't happen again.
Hope this info can help.

**Comment by devlopermitesh** [comment]
yes facing the same issue ,then I deleted all postman related cache files, and reinstall postman again,  but after sometime when close and start postman again ,face same errro

**Comment by IgorPietraszko** [comment]
Not sure if related but I am seeing this issue.  Already uninstalled once.  Will try again.

duckdb-utils: Failed to load system root CAs: Cannot read properties of null (reading 'indexOf')
[DuckDBService] Using centralized DB path: C:\Users\<redacted>\AppData\Roaming\Postman\duckdb\results.db
[DuckDBService] Created new singleton instance with global guard
The disableGPU setting is set to undefined
Not disabling GPU
Main: Starting cleanup of stale files
Main: Cleanup of stale files completed
Main~createDefaultWorkingDir - Default working dir creation already attempted
ProtocolHandler~init - Success with status: true]
1769807118329 main info "Booting Postman 11.82.6, win32-10.0.26200 on x64"
1769807118330 main info "EventBus~initialize - Success"
1769807118334 main info "Proxy configuration has not been setup"
1769807118334 main info "CloudProxyManager~init - Success"
1769807118340 main info "performShellDataMigration: Migration has already been done. Bailing out"
1769807118341 main info "UpdateHandler~init - Success"
1769807118342 main info "LeaderSelection: Initialized successfully"
[MockServer IPC] Handlers registered
1769807118345 main info "main~onAppReady - Mock server IPC setup successful"
1769807118421 main info "GPU detected VID 4318 DID 10400 ACTIVE false"
1769807118421 main info "GPU detected VID 32902 DID 42912 ACTIVE false"
1769807118421 main info "GPU detected VID 5140 DID 140 ACTIVE false"
1769807118549 main info "main.js: Agent started"
1769807118549 main error "[payments] failed to enable sandbox mode",{"name":"Error","message":"app.enableSandbox() can only be called before app is ready","stack":"Error: app.enableSandbox() can only be called before app is ready\n    at initPaymentView (C:\\Users\\<redacted>\\AppData\\Local\\Postman\\app-11.82.6\\resources\\app.asar\\main.js:942:109229)\n    at C:\\Users\\<redacted>\\AppData\\Local\\Postman\\app-11.82.6\\resources\\app.asar\\main.js:21:31349"}
1769807118550 main info "main.js: Payment view IPC handlers initialized"
1769807118550 main info "shellController~init: Success"
1769807118550 main info "shellMeta~init: Success"
1769807118551 main info "partitionMigrationService: State of V7 partition:"
1769807118551 main info "partitionMigrationService: V7 partitions",[]
1769807118551 main info "partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no partition with scratchpad namespace"
1769807118551 main info "partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no transit partition which could have been used for scratchpad"
1769807118551 main info "partitionMigrationService~init: Success"
1769807118552 main info "partitionMigrationService~runV8PartitionsIntegrity: Two way migration~ removing the following partitions from v8",[]
1769807118552 main info "userPartitionService~_rectifyTheActivePartitionOfApplication: Setting the active partition to ",null
1769807119977 main info "newAccountRegionPreferenceService~getPreferenceWithFallback - Preference not found in storage."
1769807119978 main info "newAccountRegionPreferenceService~getToggleMenuTemplate - Using preference:","useUSRegion"
1769807119988 main info "userPartitionService~init: Success"
1769807119999 main info "userPartitionService: State of v8 partition system:"
1769807119999 main info "shell~init~getPartitionToLoad: loading scratchpad partition"
1769807120000 main info "userPartitionService: List of partitions:",[{"partitionId":"7df5af2c-e77e-435e-9e83-9cf2a7f925f3","namespace":"scratchPad","userId":0,"teamId":0,"isDirty":false}]
1769807120000 main info "userPartitionService: users global meta:",{}
1769807120000 main info "Main:windowManager~newRequesterWindow: Fetch and update runtime config: undefined"
