### ISSUE TITLE
Postman Desktop Stuck 

### ISSUE THREAD

**Issue by JieShengHon** [a85/POSTMan-Chrome-Extension#13070]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have stuck when login to the postman desktop, It stuck there for long time.

### Steps To Reproduce

1. Open postman 
2. it stuck there forever and cannot even click on the close button, need to manually close it using task manager 

### Operating System

Windows

### Postman Version

11.7.0-240730-0646

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by abhijeetborole** [comment]
Hi @JieShengHon, could you help us with more logs and a screen recording of the issue? For console logs, you can press `F12` -> go to the console tab. -> right click -> save as.

**Comment by JieShengHon** [comment]
![POSTMAN STUCK](https://github.com/user-attachments/assets/afa178f1-2825-4a0a-a371-9f48f01b3205)

Here is the image

**Comment by JieShengHon** [comment]
> Hi @JieShengHon, could you help us with more logs and a screen recording of the issue? For console logs, you can press `F12` -> go to the console tab. -> right click -> save as.

I use postman desktop app

**Comment by stolkom** [comment]
The same problem with a flatpak version of Postman on Linux Mint 21.3.

main.log:
```[8][1723618434876][main][info]["Booting Postman 11.7.0, linux-6.5.0-45-generic on x64"]
[8][1723618434878][main][info]["EventBus~initialize - Success"]
[8][1723618434879][main][info]["Proxy configuration has not been setup"]
[8][1723618434879][main][info]["CloudProxyManager~init - Success"]
[8][1723618434909][main][info]["performShellDataMigration: Migration has already been done. Bailing out"]
[8][1723618434913][main][info]["UpdateHandler~init - Success"]
[8][1723618434914][main][info]["LeaderSelection: Initialized successfully"]
[8][1723618434914][main][info]["VersionDependencyService: Initialized successfully"]
[8][1723618434916][main][info]["LinuxAutoUpdater~Cleanup - Initial cleanup successful"]
[8][1723618434929][main][info]["GPU detected VID 4098 DID 5688 ACTIVE true"]
[8][1723618434933][main][info]["newAccountRegionPreferenceService~getToggleMenuTemplate - Using preference:","useEURegion"]
[8][1723618434946][main][info]["shellController~init: Success"]
[8][1723618434948][main][info]["shellMeta~init: Success"]
[8][1723618434948][main][info]["partitionMigrationService: State of V7 partition:"]
[8][1723618434949][main][info]["partitionMigrationService: V7 partitions",[]]
[8][1723618434949][main][info]["partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no partition with scratchpad namespace"]
[8][1723618434949][main][info]["partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no transit partition which could have been used for scratchpad"]
[8][1723618434949][main][info]["partitionMigrationService~init: Success"]
[8][1723618434955][main][info]["partitionMigrationService~runV8PartitionsIntegrity: Two way migration~ removing the following partitions from v8",[]]
[8][1723618434957][main][info]["userPartitionService~getRecentV8UserPartition: recent v8 user context partition ","7f9b5fd4-21fc-47d5-8d0d-79f523aeedf4"]
[8][1723618434958][main][info]["userPartitionService~_rectifyTheActivePartitionOfApplication: Setting the active partition to ","7f9b5fd4-21fc-47d5-8d0d-79f523aeedf4"]
[8][1723618434962][main][info]["userPartitionService~init: Success"]
[8][1723618434971][main][info]["userPartitionService: State of v8 partition system:"]
[8][1723618434973][main][info]["shell~init~getPartitionToLoad: loading active partition"]
[8][1723618434974][main][info]["userPartitionService: List of partitions:",[{"partitionId":"7f9b5fd4-21fc-47d5-8d0d-79f523aeedf4","namespace":"users","userId":"18851496","teamId":"0","lastUpdated":"2024-05-13T13:49:16.623Z"},{"partitionId":"b7083009-7f9e-48fe-82cb-e247e6cb1647","namespace":"scratchPad","userId":0,"teamId":0,"isDirty":false}]]
[8][1723618434974][main][info]["userPartitionService: users global meta:",{}]
[8][1723618434976][main][info]["Main:windowManager~newRequesterWindow: Fetch and update runtime config: undefined"]
[8][1723618435955][main][info]["Main~getRemoteInitPath:: "]
[8][1723618436007][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[8][1723618436017][main][info]["windowManager: First requester booted successfully."]
[8][1723618436017][main][info]["windowManager~restoreWindows: Restoring requester windows"]
[8][1723618436017][main][info]["Main~AppEvents - Received booted event for process requester.Version 11.7.0 UI Version: 11.7.0-ui-240730-0645 Desktop Platform Version: 11.7.0"]
[8][1723618436097][main][info]["Main~getRemoteInitPath:: "]
[8][1723618436255][main][info]["Main~getPlatformLaunchPerfMetrics"]
[8][1723618436518][main][info]["INTERCEPTOR CONNECTIVITY: Attempting to start websocket server on port 15611"]
[8][1723618437272][main][info]["Main - model-events~user - (user, bootstrapUser) received"]
[8][1723618437272][main][info]["model-events~user - bootstrapUser received"]
```
renderer-requester.log:
```[8][1723618435843][requester][info]["DesktopLocationService ~ init initialized"]
[8][1723618435845][requester][info]["NavigationService ~ Initialized: Success"]
[8][1723618435845][requester][info]["initializeNavigation~boot - Success"]
[8][1723618435847][requester][info]["EventBus~initialize - Success"]
[8][1723618435847][requester][info]["Messaging~boot - Success"]
[8][1723618435858][requester][info]["bootCrashReporter~ Success"]
[8][1723618435859][requester][info]["Telemetry~boot - Success"]
[8][1723618435860][requester][info]["bootConfigurations~initialize - Success"]
[8][1723618435860][requester][info]["migrateLocalStorage: Bailing out"]
[8][1723618435862][requester][info]["Settings~boot - Success"]
[8][1723618435876][requester][info]["Migrations: Skipping migrations. No migrations to apply."]
[8][1723618435914][requester][info]["bootstrapModels - Success"]
[8][1723618435914][requester][info]["WLModels~boot - Success"]
[8][1723618435916][requester][info]["Session~boot - Success"]
[8][1723618435917][requester][info]["IndependentServices~boot - Success"]
[8][1723618435920][requester][info]["AppModels~boot - Success"]
[8][1723618435926][requester][info]["initializeConfigurationsValues - Success"]
[8][1723618435934][requester][info]["CookiesBootHelper~Migration: Bailing out, no migrations to apply."]
[8][1723618435940][requester][info]["bootIndependentServicesShared: Success"]
[8][1723618435940][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-initializeConfigurationsValues to client envets with value 5.600000008940697"]
[8][1723618435946][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-clearConsoleDesktop to client envets with value 5.5"]
[8][1723618435947][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-cleanupRunner to client envets with value 2.4000000059604645"]
[8][1723618435947][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-migrateCookiesFromElectron to client envets with value 0.09999999403953552"]
[8][1723618435947][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-cleanupCookies to client envets with value 3.2000000029802322"]
[8][1723618435947][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-clearAPISchema to client envets with value 1.7000000029802322"]
[8][1723618435947][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-clearEditorDataCache to client envets with value 0.5999999940395355"]
[8][1723618435947][requester][info]["instrumentSeries ~ Sending metric requester-init-singleton-bootIndependentServicesShare to client envets with value 0.29999999701976776"]
[8][1723618435947][requester][info]["performSingletonJobs: Success"]
[8][1723618435953][requester][info]["checkVersionLock: Starting version lock check"]
[8][1723618435953][requester][info]["checkVersionLock: Cached response present. Starting validation"]
[8][1723618435953][requester][info]["checkVersionLock: Version is valid according to cached response"]
[8][1723618435953][requester][info]["checkVersionLock: Checking version lock in non-blocking flow"]
[8][1723618435954][requester][info]["checkVersionLock: Version lock check passed"]
[8][1723618435968][requester][info]["SyncManagerNew~setSync",true]
[8][1723618435968][requester][info]["SyncManagerNew~signIn",{"forceConnect":true}]
[8][1723618435968][requester][info]["Sync~boot - Success"]
[8][1723618435969][requester][info]["SyncManagerNew~createSocket",{"forceConnect":true}]
[8][1723618435975][requester][info]["PostUpdateBackup~init: Success"]
[8][1723618435976][requester][info]["Shared~boot - Success"]
[8][1723618435984][requester][info]["ExtensibleCollections~boot - Success"]
[8][1723618435985][requester][info]["DBWatcher~boot - Success"]
[8][1723618435989][requester][info]["ThemeManager~boot - Success"]
[8][1723618435991][requester][error]["NavigationService~register- A route already registered for this intent. Duplicate routes not supported."]
[8][1723618435992][requester][error]["NavigationService~register- A route already registered for this intent. Duplicate routes not supported."]
[8][1723618435992][requester][error]["NavigationService~register- A route already registered for this intent. Duplicate routes not supported."]
[8][1723618435992][requester][error]["NavigationService~register- A route already registered for this intent. Duplicate routes not supported."]
[8][1723618435992][requester][error]["NavigationService~register- A route already registered for this intent. Duplicate routes not supported."]
[8][1723618435992][requester][error]["NavigationService~register- A route already registered for this intent. Duplicate routes not supported."]
[8][1723618435992][requester][error]["NavigationService~register- A route already registered for this intent. Duplicate routes not supported."]
[8][1723618435992][requester][error]["NavigationService~register- A route already registered for this intent. Duplicate routes not supported."]
[8][1723618435992][requester][info]["WorkbenchService~boot - Success"]
[8][1723618435992][requester][info]["ContextBarRegistry~boot - Success"]
[8][1723618435993][requester][info]["Store~boot - Success"]
[8][1723618435995][requester][info]["Shortcuts~boot - Success"]
[8][1723618435998][requester][info]["SyncManagerNew~createSocket - socket url","https://bifrost-v4-global.gw.postman.com"]
[8][1723618435998][requester][info]["SyncManagerNew~createSocket","sailsIO.connect",{"url":"https://bifrost-v4-global.gw.postman.com","opts":{"reconnectionDelay":10000,"reconnectionDelayMax":60000,"reconnectionAttempts":8,"randomizationFactor":0.3}}]
[8][1723618435999][requester][info]["SyncManagerNew~createSocket - userContext: ",{"userId":"18851496","teamId":"0","os":"linux 6.5.0-45-generic","type":"app_native","version":"11.7.0-ui-240730-0645","productVersion":"11.7.0"}]
[8][1723618436004][requester][info]["NewConsole~boot - Success"]
[8][1723618436005][requester][info]["APIDevInterface~boot - Success"]
[8][1723618436005][requester][error]["NavigationService~register- A route already registered for this intent. Duplicate routes not supported."]
[8][1723618436006][requester][info]["OfflineAPIClientService~init: started"]
[8][1723618436006][requester][info]["OfflineAPIClientService~init: settings cache isOfflineAPIClientEnabled",false]
[8][1723618436006][requester][info]["initializePostV8UpdateCheck: Success"]
[8][1723618436011][requester][info]["Requester~boot - Success"]
[8][1723618436015][requester][info]["SharedRuntimeListeners~boot - Success"]
[8][1723618436016][requester][info]["booted - requester"]
[8][1723618436173][requester][info]["CloudProxyHandler: Proxy configuration has not been setup"]
[8][1723618436236][requester][info]["SessionValidation - Registering listener"]
[8][1723618436243][requester][info]["UI pulled the session locked information on init"]
[8][1723618436256][requester][info]["instrumentSeries ~ Sending metric requester-init-series-getLaunchParams to client envets with value 2.9000000059604645"]
[8][1723618436256][requester][info]["instrumentSeries ~ Sending metric requester-init-series-windowConfig to client envets with value 0.09999999403953552"]
[8][1723618436257][requester][info]["instrumentSeries ~ Sending metric requester-init-series-Logger to client envets with value 1.800000011920929"]
[8][1723618436257][requester][info]["instrumentSeries ~ Sending metric requester-init-series-verifyApplicationDowngrade to client envets with value 13.5"]
[8][1723618436257][requester][info]["instrumentSeries ~ Sending metric requester-init-series-initializeNavigation to client envets with value 2.4000000059604645"]
[8][1723618436257][requester][info]["instrumentSeries ~ Sending metric requester-init-series-initializeNavigationForDomains to client envets with value 0.5999999940395355"]
[8][1723618436257][requester][info]["instrumentSeries ~ Sending metric requester-init-series-Messaging to client envets with value 1.7999999970197678"]
[8][1723618436257][requester][info]["instrumentSeries ~ Sending metric requester-init-series-CrashReporter to client envets with value 11"]
[8][1723618436257][requester][info]["instrumentSeries ~ Sending metric requester-init-series-Telemetry to client envets with value 0.5"]
[8][1723618436257][requester][info]["instrumentSeries ~ Sending metric requester-init-series-registerServiceWorkerListeners to client envets with value 0.09999999403953552"]
[8][1723618436257][requester][info]["instrumentSeries ~ Sending metric requester-init-series-initializeConfigurations to client envets with value 0.5999999940395355"]
[8][1723618436257][requester][info]["instrumentSeries ~ Sending metric requester-init-series-migrateLocalStorage to client envets with value 0.30000001192092896"]
[8][1723618436257][requester][info]["instrumentSeries ~ Sending metric requester-init-series-Settings to client envets with value 1.8999999910593033"]
[8][1723618436257][requester][info]["instrumentSeries ~ Sending metric requester-init-series-initializeDB to client envets with value 14.100000008940697"]
[8][1723618436257][requester][info]["instrumentSeries ~ Sending metric requester-init-series-WLModels to client envets with value 37.70000000298023"]
[8][1723618436257][requester][info]["instrumentSeries ~ Sending metric requester-init-series-bootWindowConfig to client envets with value 2.7000000029802322"]
[8][1723618436258][requester][info]["instrumentSeries ~ Sending metric requester-init-series-IndependentServices to client envets with value 0.699999988079071"]
[8][1723618436258][requester][info]["instrumentSeries ~ Sending metric requester-init-series-AppModels to client envets with value 3"]
[8][1723618436258][requester][info]["instrumentSeries ~ Sending metric requester-init-series-performSingletonSteps to client envets with value 27.100000008940697"]
[8][1723618436258][requester][info]["instrumentSeries ~ Sending metric requester-init-series-CurrentUserDetailsService to client envets with value 3.5999999940395355"]
[8][1723618436258][requester][info]["instrumentSeries ~ Sending metric requester-init-series-i18nService to client envets with value 1.6000000089406967"]
[8][1723618436258][requester][info]["instrumentSeries ~ Sending metric requester-init-series-checkVersionLock to client envets with value 1.5"]
[8][1723618436258][requester][info]["instrumentSeries ~ Sending metric requester-init-series-prefetchWorkspaceData to client envets with value 9.699999988079071"]
[8][1723618436258][requester][info]["instrumentSeries ~ Sending metric requester-init-series-Shared to client envets with value 12.300000011920929"]
[8][1723618436258][requester][info]["instrumentSeries ~ Sending metric requester-init-series-RuntimeInterface to client envets with value 1.2000000029802322"]
[8][1723618436258][requester][info]["instrumentSeries ~ Sending metric requester-init-series-bootExtensibleCollections to client envets with value 6.899999991059303"]
[8][1723618436258][requester][info]["instrumentSeries ~ Sending metric requester-init-series-initializeCommunicationForCookies to client envets with value 0.20000000298023224"]
[8][1723618436258][requester][info]["instrumentSeries ~ Sending metric requester-init-series-setupVersionLockListener to client envets with value 0.20000000298023224"]
[8][1723618436258][requester][info]["instrumentSeries ~ Sending metric requester-init-series-setupProductUpdatesListener to client envets with value 0"]
[8][1723618436258][requester][info]["instrumentSeries ~ Sending metric requester-init-series-bootDBWatcher to client envets with value 0.09999999403953552"]
[8][1723618436259][requester][info]["instrumentSeries ~ Sending metric requester-init-series-bootThemeManager to client envets with value 4.600000008940697"]
[8][1723618436259][requester][info]["instrumentSeries ~ Sending metric requester-init-series-bootWorkbenchService to client envets with value 2.7999999970197678"]
[8][1723618436259][requester][info]["instrumentSeries ~ Sending metric requester-init-series-bootContextBarRegistry to client envets with value 0.20000000298023224"]
[8][1723618436259][requester][info]["instrumentSeries ~ Sending metric requester-init-series-Requester to client envets with value 18.200000002980232"]
[8][1723618436259][requester][info]["instrumentSeries ~ Sending metric requester-init-series-bootRuntimeListeners to client envets with value 4.5"]
[8][1723618436259][requester][info]["instrumentSeries ~ Sending metric requester-init-series-PlanFeaturesInterface to client envets with value 0.5"]
[8][1723618436313][requester][info]["performVersionLockCheck: Current version is valid for the user"]
[8][1723618436371][requester][info]["BaseSyncTimeline~subscribe: Subscribing to real time changes for workspace:9ed81706-1df2-433e-8cc3-f7e079fa009e"]
[8][1723618436371][requester][info]["BaseSyncTimeline~_sync: Starting sync for workspace:9ed81706-1df2-433e-8cc3-f7e079fa009e"]
[8][1723618436424][requester][info]["TabUIStore~requestingSaveTabId : savingTabId",]
[8][1723618436483][requester][info]["BaseSyncTimeline~subscribe: Skipping new subscribe for workspace:9ed81706-1df2-433e-8cc3-f7e079fa009e. Timeline is syncing."]
[8][1723618436535][requester][info]["ConnectionModeStore~_isFirstLoad",false]
[8][1723618436559][requester][info]["BaseSyncTimeline~getPendingClientChanges: Starting to get pending changes for workspace:9ed81706-1df2-433e-8cc3-f7e079fa009e"]
[8][1723618436565][requester][info]["SyncManagerNew~_onConnect"]
[8][1723618436574][requester][info]["SyncManagerNew~signIn",{}]
[8][1723618436574][requester][info]["setupVersionLockListener: Attached listener for version lock check events"]
[8][1723618436578][requester][info]["SyncTimelineHelper: Force stopping all timelines"]
[8][1723618436578][requester][info]["BaseSyncTimeline~forceStop: Force stop user:18851496"]
[8][1723618436578][requester][info]["BaseSyncTimeline~forceStop: Force stop workspace:9ed81706-1df2-433e-8cc3-f7e079fa009e"]
[8][1723618436579][requester][info]["subscribeToTeamEvents: Bailing out as team ID is not available"]
[8][1723618436589][requester][info]["BaseSyncTimeline~getPendingClientChanges: Finished to get pending changes for workspace:9ed81706-1df2-433e-8cc3-f7e079fa009e"]
[8][1723618436590][requester][info]["BaseSyncTimeline~getPendingServerChanges: Starting /sync call for workspace:9ed81706-1df2-433e-8cc3-f7e079fa009e"]
[8][1723618436642][requester][error]["ReleaseListStore~getReleases: apiId or apiVersionId is missing"]
[8][1723618436662][requester][error]["ReleaseListStore~getReleases: apiId or apiVersionId is missing"]
[8][1723618436883][requester][warn]["ListingAPIAdapter~_getUnsubscribeAPIResponseWithSocket: Failed to unsubscribe entities",{"name":"Error","message":"CollectionListingAPIAdapter~getListUnsubscribeAPIEndpoint: not implemented for parent workspace","stack":"Error: CollectionListingAPIAdapter~getListUnsubscribeAPIEndpoint: not implemented for parent workspace\n    at o.getListUnsubscribeAPIEndpoint (https://desktop.postman.com/_ar-assets/common-745f4e0f45fcd0ee.min.js:2093:456022)\n    at o._getUnsubscribeAPIResponseWithSocket (https://desktop.postman.com/_ar-assets/common-745f4e0f45fcd0ee.min.js:2093:321983)"}]
[8][1723618436912][requester][info]["BaseSyncTimeline~SyncFinishedObservable: Successful sync proceeding with integrity check and force sync for workspace:9ed81706-1df2-433e-8cc3-f7e079fa009e"]
[8][1723618436913][requester][info]["BaseSyncTimeline~_handleForceSync: Bailing out of force sync for workspace:9ed81706-1df2-433e-8cc3-f7e079fa009e"]
[8][1723618436929][requester][info]["CollectionEagerFetchManager~prioritizeItems: found config",{"favorites":true,"maxCount":5,"recencyWeight":0.4,"usageWeight":0.4,"favoriteWeight":0.2,"maxTrackingTime":1296000000,"maxSize":20971520}]
[8][1723618436929][requester][info]["~triggerEagerFetch: Triggering eager fetch for 18851496-fa488231-5298-4a2f-8979-33e996fe5763",{"modelId":"18851496-fa488231-5298-4a2f-8979-33e996fe5763","isFavorite":false,"id":"collection/18851496-fa488231-5298-4a2f-8979-33e996fe5763","lastInteraction":1723618383392,"openCount":1,"activationCount":2,"childrenUsageCount":45,"model":"collection","size":3429}]
[8][1723618436929][requester][info]["CollectionEagerFetchManager~fetch: Eager fetching","18851496-fa488231-5298-4a2f-8979-33e996fe5763"]
[8][1723618436930][requester][info]["BaseSyncTimeline~subscribe: Subscribing to real time changes for collection:18851496-fa488231-5298-4a2f-8979-33e996fe5763"]
[8][1723618436930][requester][info]["BaseSyncTimeline~_sync: Starting sync for collection:18851496-fa488231-5298-4a2f-8979-33e996fe5763"]
[8][1723618436933][requester][info]["BaseSyncTimeline~subscribe: Subscribing to real time changes for user:18851496"]
[8][1723618436933][requester][info]["BaseSyncTimeline~_sync: Starting sync for user:18851496"]
[8][1723618436934][requester][info]["BaseSyncTimeline~getPendingClientChanges: Starting to get pending changes for collection:18851496-fa488231-5298-4a2f-8979-33e996fe5763"]
[8][1723618436934][requester][info]["BaseSyncTimeline~getPendingClientChanges: Finished to get pending changes for collection:18851496-fa488231-5298-4a2f-8979-33e996fe5763"]
[8][1723618436935][requester][info]["BaseSyncTimeline~getPendingServerChanges: Starting /sync call for collection:18851496-fa488231-5298-4a2f-8979-33e996fe5763"]
[8][1723618436935][requester][info]["BaseSyncTimeline~getPendingClientChanges: Starting to get pending changes for user:18851496"]
[8][1723618436936][requester][info]["BaseSyncTimeline~getPendingClientChanges: Finished to get pending changes for user:18851496"]
[8][1723618436936][requester][info]["BaseSyncTimeline~getPendingServerChanges: Starting /sync call for user:18851496"]
[8][1723618436944][requester][info]["UsageController~cleanTracking: Deleting expired tracking info",{"id":[]}]
[8][1723618437142][requester][error]["ReleaseListStore~getReleases: apiId or apiVersionId is missing"]
[8][1723618437236][requester][info]["BaseSyncTimeline~SyncFinishedObservable: Successful sync proceeding with integrity check and force sync for user:18851496"]
[8][1723618437236][requester][info]["BaseSyncTimeline~_handleForceSync: Bailing out of force sync for user:18851496"]
[8][1723618437305][requester][info]["SyncManagerNew~setSync",true]
[8][1723618437307][requester][info]["BaseSyncTimeline~getPendingServerChanges: Finished /sync call for collection:18851496-fa488231-5298-4a2f-8979-33e996fe5763"]
[8][1723618437308][requester][info]["BaseSyncTimeline~processServerChange: Started processing changeset for collection:import:fa488231-5298-4a2f-8979-33e996fe5763 Timeline:collection:18851496-fa488231-5298-4a2f-8979-33e996fe5763"]
[8][1723618437348][requester][info]["BaseSyncTimeline~processServerChange: Finished processing changeset for collection:import:fa488231-5298-4a2f-8979-33e996fe5763 Timeline:collection:18851496-fa488231-5298-4a2f-8979-33e996fe5763"]
[8][1723618437356][requester][info]["BaseSyncTimeline~SyncFinishedObservable: Successful sync proceeding with integrity check and force sync for collection:18851496-fa488231-5298-4a2f-8979-33e996fe5763"]
[8][1723618437356][requester][info]["BaseSyncTimeline~_handleForceSync: Starting force sync for collection:18851496-fa488231-5298-4a2f-8979-33e996fe5763"]
[8][1723618437356][requester][info]["BaseSyncTimeline~_handleForceSync: Finished force sync for collection:18851496-fa488231-5298-4a2f-8979-33e996fe5763"]
[8][1723618437372][requester][info]["CollectionEagerFetchManager~fetch: Eager fetching done","18851496-fa488231-5298-4a2f-8979-33e996fe5763","TEST.API"]
[8][1723618437601][requester][error]["CollectionDefinitionInterface~fetchTypedCollectionConsentStore: Typed collections feature is not supported."]
[8][1723618437602][requester][error]["CollectionDefinitionInterface~fetchTypedRequestDefinitionStore: Typed collections feature is not supported."]
[8][1723618437619][requester][warn]["BaseEditorModel~conflictState: Conflicted Tab detected"]
```

**Comment by gomez-git** [comment]
Same for macOS 13.6.9, Postman 11.8.0, UI 11.8.0-ui-240806-0811, arm64, OS X 22.6.0, stuck for 2-3 minutes and then start to work.

**Comment by stolkom** [comment]
> The same problem with a flatpak version of Postman on Linux Mint 21.3.

Ok, I've fixed it this way:
 - uninstall Postman App
 - rename the local data folder `~/.var/app/com.getpostman.Postman`
 - install Postman App again
 - start and sign in
 - get crash
 - copy certs from the old directory to `~/.var/app/com.getpostman.Postman/config/Postman/proxy/` or generate new certs
 - profit

**Comment by epiphanyplx** [comment]
Signing out and signing back in resolved this same issue for me.

**Comment by dev-vaayen** [comment]
None of the mentioned solutions worked out for me other than installing installing Postman again from [its website](https://www.postman.com/downloads/?deviceId=1726e4f3-aa7c-43b8-b816-2ad142557c1c). The snap version is still installed and still doesn't work but the one that I extracted from  it's tar file is working as required.

**Comment by varungbt** [comment]
facing the same issue

**Comment by varungbt** [comment]
The issue is re-appearing again today. Postman app stuck loading.

**Comment by sdancer75** [comment]
the same here.

```
[11056][1734353436920][main][info]["Booting Postman 11.22.0, win32-10.0.26100 on x64"]
[11056][1734353436922][main][info]["EventBus~initialize - Success"]
[11056][1734353436923][main][info]["Proxy configuration has not been setup"]
[11056][1734353436923][main][info]["CloudProxyManager~init - Success"]
[11056][1734353436958][main][info]["performShellDataMigration: Migration has already been done. Bailing out"]
[11056][1734353436959][main][info]["UpdateHandler~init - Success"]
[11056][1734353436960][main][info]["LeaderSelection: Initialized successfully"]
[11056][1734353436960][main][info]["VersionDependencyService: Initialized successfully"]
[11056][1734353436980][main][info]["GPU detected VID 4318 DID 9708 ACTIVE false"]
[11056][1734353436981][main][info]["GPU detected VID 32902 DID 42891 ACTIVE false"]
[11056][1734353436981][main][info]["GPU detected VID 5140 DID 140 ACTIVE false"]
[11056][1734353436982][main][info]["shellController~init: Success"]
[11056][1734353436982][main][info]["shellMeta~init: Success"]
[11056][1734353436982][main][info]["partitionMigrationService: State of V7 partition:"]
[11056][1734353436983][main][info]["partitionMigrationService: V7 partitions",[]]
[11056][1734353436983][main][info]["partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no partition with scratchpad namespace"]
[11056][1734353436983][main][info]["partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no transit partition which could have been used for scratchpad"]
[11056][1734353436983][main][info]["partitionMigrationService~init: Success"]
[11056][1734353436983][main][info]["partitionMigrationService~runV8PartitionsIntegrity: Two way migration~ removing the following partitions from v8",[]]
[11056][1734353436983][main][info]["userPartitionService~getRecentV8UserPartition: recent v8 user context partition ","76660da4-5b19-4c83-bbbc-2e85c1320fdf"]
[11056][1734353436984][main][info]["userPartitionService~_rectifyTheActivePartitionOfApplication: Setting the active partition to ","76660da4-5b19-4c83-bbbc-2e85c1320fdf"]
[11056][1734353436990][main][info]["newAccountRegionPreferenceService~getPreferenceWithFallback - Preference not found in storage."]
[11056][1734353436990][main][info]["newAccountRegionPreferenceService~getToggleMenuTemplate - Using preference:","useUSRegion"]
[11056][1734353436999][main][info]["userPartitionService~init: Success"]
[11056][1734353437014][main][info]["userPartitionService: State of v8 partition system:"]
[11056][1734353437014][main][info]["shell~init~getPartitionToLoad: loading active partition"]
[11056][1734353437014][main][info]["userPartitionService: List of partitions:",[{"partitionId":"76660da4-5b19-4c83-bbbc-2e85c1320fdf","namespace":"users","userId":"12610795","teamId":"5103944","lastUpdated":"2024-12-09T11:08:48.763Z"},{"partitionId":"9a4a99d5-684a-4f8a-80a1-f468fe17a349","namespace":"scratchPad","userId":0,"teamId":0,"isDirty":false}]]
[11056][1734353437015][main][info]["userPartitionService: users global meta:",{}]
[11056][1734353437015][main][info]["Main:windowManager~newRequesterWindow: Fetch and update runtime config: us"]
[11056][1734353437641][main][info]["Main~getRemoteInitPath:: "]
[11056][1734353437660][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[11056][1734353437661][main][info]["INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge"]
[11056][1734353437666][main][info]["windowManager: First requester booted successfully."]
[11056][1734353437666][main][info]["windowManager~restoreWindows: Restoring requester windows"]
[11056][1734353437666][main][info]["Main~AppEvents - Received booted event for process requester.Version 11.22.0 UI Version: 11.22.0-ui-241126-0633 Desktop Platform Version: 11.22.0"]
[11056][1734353437706][main][info]["Main~getRemoteInitPath:: "]
[11056][1734353437832][main][info]["Main~getPlatformLaunchPerfMetrics"]
[11056][1734353438165][main][info]["INTERCEPTOR CONNECTIVITY: Attempting to start websocket server on port 15611"]
```

**Comment by Anish98821** [comment]
The problem seems to be with the "issue" link that can be seen on requests generated from a definition. 

![image](https://github.com/user-attachments/assets/c43445f1-2b8a-4089-98bb-a9130b549e12)

What fixed it for me is deleting that collection using the web client and regenerating it. It goes back to the frozen state if I click on the issue again.

**Comment by Crestina2001** [comment]
Same issue here.

**Comment by varungbt** [comment]
I deleted the entire Postman folder in %appdata%. I am going to wait an see what happens with this deletion operation

**Comment by RicardofVallejo** [comment]
Open a new postman window and close the problematic one

<img width="477" alt="Image" src="https://github.com/user-attachments/assets/0099b7fb-931c-4af3-87b3-4873f7afeab1" />

**Comment by leland-falde** [comment]
Same issue here. Flows was working yesterday. I finally got it working and then it wouldn't save. It said it would save...but go to website and reload and changes not saved.

redo the work that got lost...copy/pasted flow to a new file. it works again.

today, feeling victorious, i go to demonstrate the work and the Flow will not load. 

doesn't matter if using desktop app or chrome browser.

restarted computer.

installed Brave browser.

i'm really hopeful this works because i've spent countless hours fighting flows.

**Comment by rabbah** [comment]
We're rolling a fix for this as we speak.

**Comment by rabbah** [comment]
Apologies for this experience - we've identified an issue and rolling a fix presently @leland-falde.

**Comment by rabbah** [comment]
@leland-falde an update was rolled out that fixes the specific issue you encountered. Please let me know if you’re facing any other issue. And if you have feedback on flows, do [share](https://community.postman.com/t/i-m-the-product-lead-of-flows-and-i-want-your-feedback/73690/18) it with us.

**Comment by sdancer75** [comment]
Yes, the update fixed the problem for me. Thanx

**Comment by leland-falde** [comment]
> [@leland-falde](https://github.com/leland-falde) an update was rolled out that fixes the specific issue you encountered. Please let me know if you’re facing any other issue. And if you have feedback on flows, do [share](https://community.postman.com/t/i-m-the-product-lead-of-flows-and-i-want-your-feedback/73690/18) it with us.

Yes, the update fixes the problem for me! Thank you!
