### ISSUE TITLE
Runner Run Performance freeze after several minutes

### ISSUE THREAD

**Issue by evorios** [a85/POSTMan-Chrome-Extension#13166]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I run stress test in performance mode I always get freezed tab window. I cannot close it. Only if I press "Force close all tabs". But after it happen second try to run stress test always failed. Only closing/opening the program helps. The required waiting time before freezing always varies, from 5 to 8 minutes.

### Steps To Reproduce

1. Create request in folder
2. On folder run performance stress test with default settings
3. Wait until it is freezed before its finishing

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/dcf3a86d-dd73-4a63-84ca-40f62fd8d9f1)

### Operating System

Windows

### Postman Version

11.14.1

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Logs:
```
[15520][1727721177430][requester][info]["RunnerRunPerformance <> execution ~ ipc connection closed."]
[15520][1727721177737][requester][info]["RunnerMetricStore~init: Initialized the workload"]
[15520][1727721177947][requester][info]["RunnerMetricStore~start: Started the workload"]
[15520][1727721646918][requester][error]["Promise operation timed out after 10000 ms",{"stack":"Error: Operation timed out after 10000 ms\n    at n (https://desktop.postman.com/_ar-assets/CollectionRunnerWorkbench-427712cf6afdb56a.min.js:70:213711)\n    at a (https://desktop.postman.com/_ar-assets/CollectionRunnerWorkbench-427712cf6afdb56a.min.js:70:214536)\n    at s.updateWindowSize (https://desktop.postman.com/_ar-assets/CollectionPerformanceRunWorkbench-a92b412277279251.min.js:98:9705)\n    at E.refreshEverySecond (https://desktop.postman.com/_ar-assets/CollectionPerformanceRunWorkbench-a92b412277279251.min.js:98:30297)\n    at i (https://desktop.postman.com/_ar-assets/vendors-8d1d0f339f6d4273.min.js:1494:36940)\n    at nrWrapper (https://desktop.postman.com/?desktopVersion=11.14.0&userId=*******&teamId=0&region=us:15:17817)","promise":{}}]
[15520][1727721646918][requester][error]["VisualisationStore~refreshEverySecond - Error occurred while loading performance run Metrics",{"name":"Error","message":"Operation timed out after 10000 ms","stack":"Error: Operation timed out after 10000 ms\n    at n (https://desktop.postman.com/_ar-assets/CollectionRunnerWorkbench-427712cf6afdb56a.min.js:70:213711)\n    at a (https://desktop.postman.com/_ar-assets/CollectionRunnerWorkbench-427712cf6afdb56a.min.js:70:214536)\n    at s.updateWindowSize (https://desktop.postman.com/_ar-assets/CollectionPerformanceRunWorkbench-a92b412277279251.min.js:98:9705)\n    at E.refreshEverySecond (https://desktop.postman.com/_ar-assets/CollectionPerformanceRunWorkbench-a92b412277279251.min.js:98:30297)\n    at i (https://desktop.postman.com/_ar-assets/vendors-8d1d0f339f6d4273.min.js:1494:36940)\n    at nrWrapper (https://desktop.postman.com/?desktopVersion=11.14.0&userId=*******&teamId=0&region=us:15:17817)"}]
[15520][1727721657945][requester][error]["Promise operation timed out after 10000 ms",{"stack":"Error: Operation timed out after 10000 ms\n    at n (https://desktop.postman.com/_ar-assets/CollectionRunnerWorkbench-427712cf6afdb56a.min.js:70:213711)\n    at a (https://desktop.postman.com/_ar-assets/CollectionRunnerWorkbench-427712cf6afdb56a.min.js:70:214536)\n    at s.updateWindowSize (https://desktop.postman.com/_ar-assets/CollectionPerformanceRunWorkbench-a92b412277279251.min.js:98:9705)\n    at E.refreshEverySecond (https://desktop.postman.com/_ar-assets/CollectionPerformanceRunWorkbench-a92b412277279251.min.js:98:30297)\n    at i (https://desktop.postman.com/_ar-assets/vendors-8d1d0f339f6d4273.min.js:1494:36940)\n    at nrWrapper (https://desktop.postman.com/?desktopVersion=11.14.0&userId=*******&teamId=0&region=us:15:17817)","promise":{}}]
[15520][1727721657945][requester][error]["VisualisationStore~refreshEverySecond - Error occurred while loading performance run Metrics",{"name":"Error","message":"Operation timed out after 10000 ms","stack":"Error: Operation timed out after 10000 ms\n    at n (https://desktop.postman.com/_ar-assets/CollectionRunnerWorkbench-427712cf6afdb56a.min.js:70:213711)\n    at a (https://desktop.postman.com/_ar-assets/CollectionRunnerWorkbench-427712cf6afdb56a.min.js:70:214536)\n    at s.updateWindowSize (https://desktop.postman.com/_ar-assets/CollectionPerformanceRunWorkbench-a92b412277279251.min.js:98:9705)\n    at E.refreshEverySecond (https://desktop.postman.com/_ar-assets/CollectionPerformanceRunWorkbench-a92b412277279251.min.js:98:30297)\n    at i (https://desktop.postman.com/_ar-assets/vendors-8d1d0f339f6d4273.min.js:1494:36940)\n    at nrWrapper (https://desktop.postman.com/?desktopVersion=11.14.0&userId=*******&teamId=0&region=us:15:17817)"}]
```

I don't see this problem in version 11.13.2.

**Comment by shreyas-panduranga** [comment]
@evorios We are looking into the issue on priority and will keep you updated.

**Comment by shreyas-panduranga** [comment]
We are working on getting the issue fixed, we are expecting to have it on the next release and should be available mid or later this week. Updates will be posted here.

**Comment by shreyas-panduranga** [comment]
We have fixed the issue in our latest release of 11.16.0. Please upgrade to the latest version of the Postman app.

@evorios  Let us know if you still face issues.

**Comment by malvika-chaudhary** [comment]
Hi @evorios We will be closing this issue. Please feel free to reopen if you still face a problem.
Thanks for your feedback. 

Cheers
Malvika
