### ISSUE TITLE
Postman FAIL for all since 11.16.0 -> 11.19.0 linux64 - "superCtor.prototype" property must be of type object

### ISSUE THREAD

**Issue by pjwelsh** [a85/POSTMan-Chrome-Extension#13195]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman 11.16.0 from 11.15.0 (or fresh install) fails to start and produces an error of:
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor.prototype" property must be of type object. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at inherits (node:util:251:11)
    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/@sentry/node/node_modules/https-proxy-agent/index.js:61:1)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)

### Steps To Reproduce

Tried both fresh install of 11.16.0 and upgrade on a couple of systems. Postman 11.16.0 Linux64 will not start.
Issue happens with both a signed-in and signed-out user.

### Operating System

Linux

### Postman Version

11.16.0

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

This new version may not be built the same as the previous version:
"version" check for 11.15.0:
tar -xf /tmp/postman-linux-x64.tar.gz Postman/app/resources/app/package.json --to-stdout|grep version
{"name":"Postman","version":"11.15.0","private":true,"description":"Postman","bugs":"https://github.com/postmanlabs/postman-app-support/issues","maintainers":[{"name":"Abhijit Kane"}],"main":"main.js","scripts":{"check-types":"tsc --noEmit --project jsconfig.json","test":"npm run test-lint && npm run test-unit","test-lint":"node ./npm/test-lint.js","test-system":"exit 0","test-unit":"node ../../tests/unit-test-setup/runner/test-runner.js","test:ci":"TS_JEST_DISABLE_VER_CHECKER=true node --unhandled-rejections=warn --expose-gc...

VS-
tar -xf /tmp/postman-linux-x64.tar.gz Postman/app/resources/app/package.json --to-stdout|grep version
  "version": "11.16.0",

**Comment by pjwelsh** [comment]
The issue continues to happen with the just released version 11.17.0. postman will not start on Linux:
(Note that "postman --disable-gpu" *will fail* but does not produce the "Failed to get fd for plane" message)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor.prototype" property must be of type object. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at inherits (node:util:251:11)
    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/@sentry/node/node_modules/https-proxy-agent/index.js:61:1)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
$ postman
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor.prototype" property must be of type object. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at inherits (node:util:251:11)
    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/@sentry/node/node_modules/https-proxy-agent/index.js:61:1)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
[1481353:1016/075416.187328:ERROR:gbm_wrapper.cc(75)] Failed to get fd for plane.: No such file or directory (2)
[1481353:1016/075416.187445:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
...

**Comment by pjwelsh** [comment]
Postman continues to fail on AlmaLinux 9.4 with the just released version 11.19.0 (with or without GPU):
postman --disable-gpu
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor.prototype" property must be of type object. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at inherits (node:util:251:11)
    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/@sentry/node/node_modules/https-proxy-agent/index.js:61:1)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)

**Comment by pjwelsh** [comment]
Looks like the issue was a result of how I was using the RHEL rpmbuild utility to create an RPM install package for Postman. The current 11.21.0 directly installs via the tar file and works, closing.

**Comment by pjwelsh** [comment]
closing.
