### ISSUE TITLE
Postman don't do anything (request)

### ISSUE THREAD

**Issue by CanKer** [a85/POSTMan-Chrome-Extension#2259]
1. Postman Version:
   4.6.0
2. App (Chrome app or Mac app):
   Mac app
3. OS details:
   OS X El Capitan
##  4. Is the Interceptor on and enabled in the app:
1. Did you encounter this recently, or has this bug always been there:
   recently, maybe it was because the update I received today
2. Expected behaviour:
   I want to do some POST/GET request to my localhost but the app is not doing anything. If I use the Chrome app it works but the OS X app doesn't
3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

`requester.js:267366 Uncaught Error Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cookie has domain set to a public suffix
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cookie has domain set to a public suffix
    at callFunction (/Applications/Postman.app/Contents/Resources/electron.asar/browser/rpc-server.js:225:11)
    at EventEmitter.<anonymous> (/Applications/Postman.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Postman.app/Contents/Resources/electron.asar/browser/api/web-contents.js:218:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7) /Applications/Postman.app/Contents/Resources/electron.asar/renderer/api/remote.js 176 7 Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cookie has domain set to a public suffix(…)(anonymous function) @ requester.js:267366
remote.js:176 Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cookie has domain set to a public suffix
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cookie has domain set to a public suffix
    at callFunction (/Applications/Postman.app/Contents/Resources/electron.asar/browser/rpc-server.js:225:11)
    at EventEmitter.<anonymous> (/Applications/Postman.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Postman.app/Contents/Resources/electron.asar/browser/api/web-contents.js:218:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)metaToValue @ remote.js:176remoteMemberFunction @ remote.js:110(anonymous function) @ requester.js:240256(anonymous function) @ requester.js:250786baseForOwn @ requester.js:249759(anonymous function) @ requester.js:251091(anonymous function) @ requester.js:240251(anonymous function) @ requester.js:250786baseForOwn @ requester.js:249759(anonymous function) @ requester.js:251091(anonymous function) @ requester.js:240250(anonymous function) @ requester.js:280904apply @ callbacks-registry.js:54(anonymous function) @ remote.js:241emitThree @ events.js:116emit @ events.js:194`
1. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
@CanKer Thanks for reporting this. We will be pushing a fix for this in the coming release. In the meantime, could you try deleting all the cookies via 'Manage Cookies', restart the app and check if that resolves the issue?

**Comment by CanKer** [comment]
Already did and if I restart the app it doesn't work but there's a default cookines running. I found that the `PHA_currentLocale` it may be the problem because if I delete that one without restart it works, but if I restart It doesn't work again because the cookie is again in the app.

**Comment by numaanashraf** [comment]
@CanKer That's odd. Would it be possible to share a screenshot of the cookie with the value field redacted? Like shown below?
<img width="672" alt="screen shot 2016-08-14 at 6 44 04 pm" src="https://cloud.githubusercontent.com/assets/3295568/17649316/b7b6f16a-624f-11e6-959f-2815fcd78ea1.png">

**Comment by longle255** [comment]
I got the same issue after upgraded to version 4.6.0

**Comment by CanKer** [comment]
Yes and after I delete that cookie I can do any request but after that request the cookie comes back again 😲 
<img width="676" alt="captura de pantalla 2016-08-14 a la s 3 23 22 p m" src="https://cloud.githubusercontent.com/assets/7593319/17649354/d1e4d398-6233-11e6-9050-79c4956263c4.png">

**Comment by numaanashraf** [comment]
@CanKer I have a feeling your proxy is configured via WPAD and that's adding the Cookie when the app boots up. Could you open `chrome://net-internals/#proxy` in Chrome and check if there is any entry mentioning `PAC script`? For security reasons, please don't share the location of the PAC script here. 🔒

**Comment by CanKer** [comment]
The PAC script is only a URL to wpad.dat 
I'm working in my hotel, it could be that the problem...

**Comment by numaanashraf** [comment]
Alright. I think we have what we need to get a fix ready for this. Thanks for the help, @CanKer.

**Comment by q42jaap** [comment]
I also have this issue, removing cookies gets requests through, but once cookies are set, postman doesn't respond. I'm using the mac osx app.

**Comment by Bartozzz** [comment]
Got the same error. It happens when I am requesting the `/login` route which creates a cookie:

```
sessionId=s%3AxKVVcGpTqkQyqmDL7iF6MAoBePa5nw89.tA3jCSnRhu4HP1eaM0e518FUe9zSUOG3dZFs2IBCN68; path=/; domain=localhost; Expires=Tue Jan 19 2038 02:14:07 GMT+0100 (CET);
```

... getting the same error:

```
Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cookie has domain set to a public suffix
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cookie has domain set to a public suffix
    at callFunction (/Applications/Postman.app/Contents/Resources/electron.asar/browser/rpc-server.js:225:11)
    at EventEmitter.<anonymous> (/Applications/Postman.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Postman.app/Contents/Resources/electron.asar/browser/api/web-contents.js:218:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by sdnts** [comment]
We pushed changes that should fix your issue. Can you update to the latest version (v4.6.1) and confirm?

**Comment by CanKer** [comment]
Im working at this moment and by the moment no problems. Ill let you know if anything happens.

**Comment by sdnts** [comment]
Awesome! Closing this for now. Feel free to reopen if needed.
