### ISSUE TITLE
RAML import does not work (and does not give an error)

### ISSUE THREAD

**Issue by SebastiaanKlippert** [a85/POSTMan-Chrome-Extension#2335]
1. Postman Version: 4.7.1 - win / x86-64 - Chrome 53.0.2785.116
2. App (Chrome app or Mac app): Chrome 
3. OS details: Windows 10 x64
4. Is the Interceptor on and enabled in the app: yes
5. Did you encounter this recently, or has this bug always been there: recently
6. Expected behaviour: Expect to see a new collection
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

```
TypeError: Cannot set property 'id' of undefined
    at chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/converters/all-converters.js:15241:35
    at arrayEach (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/converters/all-converters.js:71013:11)
    at Function.forEach (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/converters/all-converters.js:79502:14)
    at Object.convert (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/converters/all-converters.js:15239:11)
    at chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/converters/all-converters.js:14873:25
    at _fulfilled (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/converters/all-converters.js:33842:54)
    at self.promiseDispatch.done (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/converters/all-converters.js:33871:30)
    at Promise.promise.promiseDispatch (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/converters/all-converters.js:33804:13)
    at chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/converters/all-converters.js:33618:44
    at flush (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/converters/all-converters.js:33152:17)
```

8: 
https://carsys.s3.amazonaws.com/public/raml.gif

Hi all, 

When importing RAML files using _Import from link_ or _Paste Raw text_ the import does nothing as soon as API routes are inlcuded in the file.

For example:
When importing file https://raw.githubusercontent.com/go-raml/raml/v0/samples/simple_example.raml from link, I get no response at all.

If I copy and paste the following text:

```
#%RAML 0.8
title: Notes Example API
/jobs:
  displayName: Jobs
```

Also no response.

When only pasting 

```
#%RAML 0.8
title: Notes Example API
```

The import is done, but without any routes obviously.
On my own RAML files I get the same behavior, everything below the first **/** seems to break the import.

We have multiple clients with the same behaviour.

**Comment by sdnts** [comment]
Hey @SebastiaanKlippert, we've identified this issue, and will be pushing out a fix today. Will keep you updated.

**Comment by SebastiaanKlippert** [comment]
Great, thanks :smile:

**Comment by sdnts** [comment]
@SebastiaanKlippert Could you update to 4.7.2 and confirm if this is fixed?

**Comment by SebastiaanKlippert** [comment]
@madebysid I can confirm it works after the update. Tried a few RAML files and links and raw text files and they both seem to work.
Thanks.

**Comment by sdnts** [comment]
Awesome! Closing this.
