### ISSUE TITLE
Cannot save to Collection from History

### ISSUE THREAD

**Issue by BenSlabbert** [a85/POSTMan-Chrome-Extension#2706]
1. Postman Version: 
4.10.0
 2. App (Chrome app or Mac app):
 Linux (KDE (5.5.5) + Ubuntu (16.04))
 3. OS details: 
linux / x86-64
 4. Is the Interceptor on and enabled in the app: 
yes
 5. Did you encounter this recently, or has this bug always been there: 
recently

Steps to reproduce the problem:

1.) enable interceptor in app and browser
2.) navigate to a URL in the browser
3.) in the "History" tab, select to relevant request and click "Save to collection"
4.) the save to collection window appears, select the existing (or new collection) 
5.) click save

Actual Result:

Nothing happens, request is not saved to the collection. The "save" button appears to do nothing.

 6. Expected behaviour:

Request is save to selected Collection

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

common.js:146115 Uncaught Error Uncaught TypeError: this._request.processHelpers is not a function chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js 4311 8 TypeError: this._request.processHelpers is not a function
    at AddRequestToCollectionContainer.handleSubmit (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/requester.js:108927:22)
    at Button.handleClick (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:22044:65)
    at Object.invokeGuardedCallback (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:4285:13)
    at executeDispatch (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:4130:22)
    at Object.executeDispatchesInOrder (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:4153:6)
    at executeDispatchesAndRelease (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:3585:23)
    at executeDispatchesAndReleaseTopLevel (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:3596:11)
    at Array.forEach (native)
    at forEachAccumulated (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:4427:10)
    at Object.processEventQueue (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:3801:8)
(anonymous) @ common.js:146115
common.js:4311 Uncaught TypeError: this._request.processHelpers is not a function
    at AddRequestToCollectionContainer.handleSubmit (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/requester.js:108927:22)
    at Button.handleClick (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:22044:65)
    at Object.invokeGuardedCallback (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:4285:13)
    at executeDispatch (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:4130:22)
    at Object.executeDispatchesInOrder (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:4153:6)
    at executeDispatchesAndRelease (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:3585:23)
    at executeDispatchesAndReleaseTopLevel (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:3596:11)
    at Array.forEach (native)
    at forEachAccumulated (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:4427:10)
    at Object.processEventQueue (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js:3801:8)
handleSubmit @ requester.js:108927
handleClick @ common.js:22044
invokeGuardedCallback @ common.js:4285
executeDispatch @ common.js:4130
executeDispatchesInOrder @ common.js:4153
executeDispatchesAndRelease @ common.js:3585
executeDispatchesAndReleaseTopLevel @ common.js:3596
forEachAccumulated @ common.js:4427
processEventQueue @ common.js:3801
runEventQueueInBatch @ common.js:4456
handleTopLevel @ common.js:4472
handleTopLevelWithoutPath @ common.js:14646
handleTopLevelImpl @ common.js:14626
perform @ common.js:6616
batchedUpdates @ common.js:10640
batchedUpdates @ common.js:6124
dispatchEvent @ common.js:14757
https://app.getsentry.com/api/53934/store/?sentry_version=7&sentry_client=r…A%224.10.0%22%2C%22event_id%22%3A%22d8a51de384e74f9aa4a7cae581909d80%22%7D Failed to load resource: the server responded with a status of 429 (TOO MANY REQUESTS)

**Comment by sdnts** [comment]
@BenSlabbert Can you reproduce this in the latest version (4.10.2)?

**Comment by vegetableman** [comment]
@BenSlabbert Closing this issue. Feel free to reopen if this issue still exists ^_^.
