### ISSUE TITLE
Trying to post, get 500 Internal Server Error

### ISSUE THREAD

**Issue by arame3333** [a85/POSTMan-Chrome-Extension#3175]
## App Details:

```
Postman for Chrome
Version 5.0.1
win / x86-64
Chrome 58.0.3029.110
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

I want to attempt a post. I get this error.
![500internalservererror](https://user-images.githubusercontent.com/4223215/27233527-a3219e8c-52b1-11e7-851e-e10a9fa42fc7.png)

I get more information here:
        <h1>An unhandled exception occurred while processing the request.</h1>
        <div class="titleerror">InvalidOperationException: &#x27;Microsoft.AspNetCore.Mvc.MvcOptions.InputFormatters&#x27; must not be empty. At least one &#x27;Microsoft.AspNetCore.Mvc.Formatters.IInputFormatter&#x27; is required to bind from the body.</div>
        <p class="location">Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinderProvider.GetBinder(ModelBinderProviderContext context)</p>
The C# code is
    [Route("api/property")]
    public class PropertyController : BaseSirController
    {
        [HttpPost("{contractId}/saveproperty")]
        public IActionResult SaveProperty(int contractId, [FromBody] PropertyContractDto property)
        {
...

**Comment by sdnts** [comment]
Hi @arame3333 A 500 (Internal Server Error) status code usually indicates something went wrong with your server. Can you check your server logs to see what went wrong?

**Comment by sdnts** [comment]
I'm closing this, but please reopen if you find that something is wrong with Postman itself.

**Comment by skchao** [comment]
Hi, I'm see the similar error in my test, and at the same time the server end shows these error log at terminal:

2019-12-20 13:58:50,413.413 1662 ERROR flask.app [-] Exception on /v1/peer/192.168.14.1/send/update [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_httpauth.py", line 61, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yabgp/api/utils.py", line 39, in decorated_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yabgp/api/utils.py", line 48, in decorator
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yabgp/api/v1.py", line 120, in send_update_message
    attr = json_request.get('attr') or {}
AttributeError: 'NoneType' object has no attribute 'get'

Any clue? and advice?

Thanks!
/Kevin Chao
