### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by patrickhousley** [a85/POSTMan-Chrome-Extension#3373]
## App Details:

```
Postman for Mac
Version 5.1.3 (5.1.3)
OS X 16.11.6 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently encountered.
 2. Expected behaviour: Postman should show the response information.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```
requester.js:217991  ================================================================
     o
   (/) P O S T M A N
   ^

   Go to View -> Show Postman Console to check your script logs. 

================================================================
sails.io.js:142 🌏 sync service connectivity initiated
sails.io.js:759 socket replaying queued commands
sails.io.js:142 🌏 connected to sync service.
xml.js:22 GET file:///Applications/Postman.app/Contents/Resources/app/html/mode-auto.js net::ERR_FILE_NOT_FOUNDexports.loadScript @ xml.js:22exports.loadModule @ xml.js:22setMode @ xml.js:22componentDidMount @ xml.js:22notifyAll @ common.js:6829close @ common.js:17445closeAll @ common.js:7499perform @ common.js:7446perform @ common.js:7433perform @ common.js:6587flushBatchedUpdates @ common.js:6670closeAll @ common.js:7499perform @ common.js:7446batchedUpdates @ common.js:17027batchedUpdates @ common.js:6595dispatchEvent @ common.js:17184wrapped @ xml.js:22
```
 4. Screenshots (if applicable): None
 5. Console output:
```
POST
localhost:3000/api/auth/login
07:29:08.466
Error: socket hang up
Request Headers:
cache-control:"no-cache"
Postman-Token:"87e8b22b-07a3-4e9c-9ae5-6a92c8c0b7d7"
Content-Type:"application/json"
```

## Curl output:
```
curl -v -H "Content-type: application/json" -d '{"username": "phousley","password": "testPassword12"}' 'http://localhost:3000/api/auth/login'
*   Trying ::1...
* Connected to localhost (::1) port 3000 (#0)
> POST /api/auth/login HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.43.0
> Accept: */*
> Content-type: application/json
> Content-Length: 53
>
* upload completely sent off: 53 out of 53 bytes
< HTTP/1.1 401 Unauthorized
< X-DNS-Prefetch-Control: off
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=15552000; includeSubDomains
< X-Download-Options: noopen
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Content-Type: application/json; charset=utf-8
< Content-Length: 1053
< ETag: W/"41d-SVCmWqwjx8x9uckMnpe7hHVppa0"
< Vary: Accept-Encoding
< Date: Fri, 11 Aug 2017 00:22:30 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
{"name":"AuthenticationError","message":"Authentication failed.","stack":"Error\n    at AuthenticationError.HttpError [as constructor] (/Users/patrickhousley/Documents/projects/buffaloproject1/buffalo-chloe-web/src/http-error/HttpError.ts:19:22)\n    at new AuthenticationError (/Users/patrickhousley/Documents/projects/buffaloproject1/buffalo-chloe-web/src/server/express/errors/AuthenticationError.ts:7:5)\n    at LoginController.<anonymous> (/Users/patrickhousley/Documents/projects/buffaloproject1/buffalo-chloe-web/src/server/express/controllers/auth/Login.ts:59:13)\n    at step (/Users/patrickhousley/Documents/projects/buffaloproject1/buffalo-chloe-web/node_modules/tslib/tslib.js:122:27)\n    at Object.throw (/Users/patrickhousley/Documents/projects/buffaloproject1/buffalo-chloe-web/node_modules/tslib/tslib.js:103:57)\n    at rejected (/Users/patrickhousley/Documents/projects/buffaloproject1/buffalo-chloe-web/node_modules/tslib/tslib.js:94:69)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:208:7)"}
```

If I disable the output of the stack trace, everything works fine.

**Comment by patrickhousley** [comment]
I believe this can be closed. The issue is most likely attributed to https://github.com/pleerock/routing-controllers/issues/243 and https://github.com/nodejs/node/pull/14399.
