### ISSUE TITLE
Cannot read property 'coords' of undefined when running requests

### ISSUE THREAD

**Issue by reinouts** [a85/POSTMan-Chrome-Extension#3775]
## App Details:

```
Postman for Linux
Version 5.3.2
linux 4.13.10-200.fc26.x86_64 / x64
```

## Issue Report:
 1. I've only observed the issue with the linux native client
 2. Expected behaviour: request is processed normally
 3. Console logs: there are no entries in the Postman console
 4. Screenshots (if applicable)

Steps to reproduce the problem
Try to run a POST or GET request. The request does not appear to finish but in the terminal from which Postman was launched we can see:
```
Uncaught errors TypeError: Cannot read property 'coords' of undefined
    at PostmanCollectionRun.<anonymous> (/home/reinout/.local/Postman/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:20:36)
    at apply (/home/reinout/.local/Postman/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:496:27)
    at /home/reinout/.local/Postman/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9490:36
    at /home/reinout/.local/Postman/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:4920:15
    at Function.<anonymous> (/home/reinout/.local/Postman/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9489:7)
    at apply (/home/reinout/.local/Postman/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:497:27)
    at Function.invokeMap (/home/reinout/.local/Postman/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:6600:16)
    at Instruction.<anonymous> (/home/reinout/.local/Postman/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:138:49)
    at Instruction.execute (/home/reinout/.local/Postman/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:159:13)
    at Timeout._onTimeout (/home/reinout/.local/Postman/resources/app/node_modules/postman-runtime/lib/runner/run.js:84:25)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by sdnts** [comment]
@reinouts Thanks for reporting this. Just to be sure, can you make sure your pre-request / test scripts are not throwing this error?
@kamalaknn Could this be  related to postman-runtime?

**Comment by reinouts** [comment]
@madebysid Given that the same tests run fine on the same machine in the Chrome app (as opposed to the standalone one), what information would it add if the error was thrown by a pre-request script?

**Comment by RomanNess** [comment]
I am experiencing the same issue after installing updates via package manager on Linux Mint 18 (for the second time now). None of the requests in my standalone Postman 5.3.2 works any longer. The same stacktrace as in the initial report is visible in the terminal. 

I can confirm that the error is not thrown by any pre-request script. However, for me the issue only occurs if an authorization type is chosen under **Authorization -> Type**. Choosing type **No Auth** and providing the authorization header manually also works.

**Comment by kamalaknn** [comment]
This is coming out of `postman-runtime` when it couldn't handle the errors properly. This has been fixed in `postman-runtime`. The next release of Postman should include this fix. 

That should give you enough details as to what crashed while sending the request for you to debug.

**Comment by kamalaknn** [comment]
Hi @RomanNess @reinouts 

This fix should be out on production now. Please update your app to the latest version and give it a try.

Thanks.
