### ISSUE TITLE
Segmentation fault at startup

### ISSUE THREAD

**Issue by maedox** [a85/POSTMan-Chrome-Extension#3853]
## App Details:

```
Postman for Linux
Version 5.3.2
Ubuntu 17.10 / 4.13.0-17-generic / x64
```

## Issue Report:
I'm using Postman more or less every day, and today it suddenly SIGSEGV at startup.

gdb bt:
```
Thread 1 "Postman" received signal SIGSEGV, Segmentation fault.
0x00000000033aeacb in ?? ()
(gdb) bt
#0  0x00000000033aeacb in  ()
#1  0x0000000003d05a78 in __start_google_malloc ()
#2  0x00000000033a6023 in calloc ()
#3  0x00007ffff1fb35d1 in g_malloc0 () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff4bdb4c9 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff4be0855 in g_type_register_static () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff4be0af5 in g_type_register_static_simple () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff5d72f24 in gdk_display_manager_get_type () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#8  0x00007ffff5d72f69 in gdk_display_manager_get () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#9  0x00007ffff614f954 in  () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#10 0x00007ffff6135f28 in  () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#11 0x00007ffff1fb9fdf in g_option_context_parse () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff6136538 in gtk_parse_args () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#13 0x00007ffff61365b9 in gtk_init () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#14 0x000000000134c3b6 in  ()
#15 0x000000000134493f in  ()
#16 0x0000000001347366 in  ()
#17 0x0000000003cd7adb in brightray::BrowserMainParts::PreEarlyInitialization() ()
#18 0x0000000003b8a629 in atom::AtomBrowserMainParts::PreEarlyInitialization() ()
#19 0x00000000017ee1cb in  ()
#20 0x00000000017d76ff in  ()
#21 0x000000000164dde8 in  ()
#22 0x000000000134fe04 in  ()
#23 0x0000000001350210 in  ()
#24 0x0000000003b82e73 in main ()
```

Any ideas what happened? It might be the infamous "I added and removed a bunch of packages and didn't reboot for a while so now it suddenly blew up in my face". (It's an Electron app isn't it? The Slack app still works...)

**Comment by maedox** [comment]
Well, rebooted to 4.13.0-16-lowlatency. Postman works. Rebooted back to 17-generic. Postman still works. It's f##ked. Let's hope it was a one-time fluke of some package I removed before rebooting.
