### ISSUE TITLE
Error: "Unable to resolve variables" on request using no variables

### ISSUE THREAD

**Issue by acobster** [a85/POSTMan-Chrome-Extension#3957]
I have the following request configured in Postman:

```
GET /api/admin/product/4/date-ranges/ HTTP/1.1
Host: tourusa.lndo.site:8000
Cache-Control: no-cache
Postman-Token: 47c06972-79ac-383a-c010-6e02ccf8ebc4

```

After I click Send, the response pane displays the "Loading..." text with the cancel button, as if the request is pending; however, actual server-side access logs and the Postman dev console indicate that the request doesn't go out at all. Instead, the console displays this error:

> There was a fatal error when sending the request!
Unable to resolve variables. Require a List type property for variable auto resolution.

I am just doing a simple GET request to `http://tourusa.lndo.site:8000/api/admin/product/4/date-ranges/`; no variables referenced anywhere and no Auth/Headers/Pre-req./Tests even defined.

This happens regardless of whether I have an Environment selected or not. Exporting the Collection this request lives in and running it via `newman` (specifying no environment) works fine.

## App Details:

```
Postman for Linux
Version 5.4.1 (also tested with 5.5.0)
linux 4.10.0-40-generic / x64
```

## Issue Report:
 1. Recently, after upgrading to 5.5.0. I believe I was on 5.3.2 before.
 2. I expect Postman not to complain about resolving variables for requests that do not require any
 3. Full console output:
```
There was a fatal error when sending the request!
Object
message: "Unable to resolve variables. Require a List type property for variable auto resolution."
name: "Error"
stack: "Error: Unable to resolve variables. Require a List type property for variable auto resolution.
    at PostmanItem.toObjectResolved (/home/ctamayo/Applications/Postman/resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/collection/property.js:163:19)
    at resolveVariables (/home/ctamayo/Applications/Postman/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:36:57)
    at PostmanCollectionRun.request (/home/ctamayo/Applications/Postman/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:76:13)
    at Instruction.execute (/home/ctamayo/Applications/Postman/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:156:29)
    at PostmanCollectionRun._process (/home/ctamayo/Applications/Postman/resources/app/node_modules/postman-runtime/lib/runner/run.js:165:21)
    at PostmanCollectionRun.<anonymous> (/home/ctamayo/Applications/Postman/resources/app/node_modules/postman-runtime/lib/runner/run.js:166:76)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)"
```

**Comment by acobster** [comment]
Not sure why, but completely removing Postman and reinstalling 5.5.0 fixed this for me. Probably a corrupted download or something?
