### ISSUE TITLE
Names longer than 31 characters are not supported on the destination volume

### ISSUE THREAD

**Issue by marinomeneghel** [a85/POSTMan-Chrome-Extension#4010]
`Please choose a filename that is no longer than 31 characters.`
## App Details:
```
Postman for Mac
Version 5.5.0 (5.5.0)
OS X 10.13.1 (17B1003) / x64
```

## Issue Report:
I started seeing this bug as soon as I switched to the Postman standalone app

### Console logs
```
Uncaught TypeError: Cannot read property 'ownerDocument' of null
    at getScrollPosition (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:231081:66)
    at DraftEditor._focus (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:375463:34)
    at PluginEditor._this.(anonymous function) [as focus] (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:381819:56)
    at AutoSuggestInput.handleFocus (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:66729:46)
    at Object.invokeGuardedCallback (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:71732:5)
    at executeDispatch (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:71560:21)
    at Object.executeDispatchesInOrder (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:71580:7)
    at executeDispatchesAndRelease (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:46054:22)
    at executeDispatchesAndReleaseTopLevel (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:46065:10)
    at Array.forEach (native)
    at forEachAccumulated (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:92183:9)
    at Object.processEventQueue (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:46268:7)
    at runEventQueueInBatch (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:124190:18)
    at Object.handleTopLevel [as _handleTopLevel] (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:124201:5)
    at handleTopLevelImpl (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:127375:24)
    at Object.batchedUpdates (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:127290:14)
    at Object.batchedUpdates (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:18421:27)
    at dispatchEvent (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:127450:20)
    at HTMLDocument.wrapped (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:272050:29)
    at addPointToSelection (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:378052:13)
    at setDraftEditorSelection (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:377984:5)
    at DraftEditorLeaf._setSelection (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:376121:5)
    at DraftEditorLeaf.componentDidMount (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:376133:10)
    at CallbackQueue.notifyAll (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:92309:22)
    at ReactReconcileTransaction.close (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:127582:26)
    at ReactReconcileTransaction.closeAll (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:67201:25)
    at ReactReconcileTransaction.perform (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:67148:16)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:67135:20)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:18413:32)
    at Object.flushBatchedUpdates (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:18496:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:67201:25)
    at ReactDefaultBatchingStrategyTransaction.perform (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:67148:16)
    at Object.batchedUpdates (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:127292:26)
    at Object.enqueueUpdate (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:18524:22)
    at enqueueUpdate (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:72559:16)
    at Object.enqueueSetState (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:72744:5)
    at DraftEditor.ReactComponent.setState (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:71054:16)
    at DraftEditor._restoreEditorDOM (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:375519:10)
    at file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:379098:12
    at wrapped (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:272050:29)
sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 10958ms
sails.io.js:142 🌏 reconnecting to sync service. #(1/8)
sails.io.js:142 🌏 reconnected to sync service after being offline for 11.525seconds.
sails.io.js:759 socket replaying queued commands
sails.io.js:142 🌏 connected to sync service.
requester.js:281523 Array[7]
requester.js:87057 Error running scripts: SyntaxError | Unexpected identifier Object
exception @ requester.js:87057
4requester.js:282811 Save aborted
```

### Screenshots 
![screenshot 2017-12-29 12 19 50](https://user-images.githubusercontent.com/3415753/34436106-df283758-ec92-11e7-8930-3af05fc1aa66.png)

### Steps to reproduce the problem
- Apply any edit to a request inside a collection
- 'Export' the collection, choosing version 2.1
- Save it with the same name and in the same location as it was saved previously
- Click 'Save'
The message in the screenshot appears at this point. By clicking `ok` on the error and performing the same steps again the collection is successfully saved

**Comment by SamvelRaja** [comment]
@marinomeneghel Seems like the error is bubbling up from the OS level, can you confirm that the file name size is more than 31 characters.

**Comment by marinomeneghel** [comment]
@SamvelRaja I can confirm that the name have more than 31 characters. 
The weird thing is that once the problem happens, even by changing the name to "name" (or whatever short) the error persist. 
A thing that could be worth mentioning is that the name actually have exactly 31 chars, and it contains two dots. The format is like the following:
`nameLongExactly31Characters.postman_collection.json`

**Comment by SamvelRaja** [comment]
@marinomeneghel  Wierd that it is working for me :thinking: 
![export](https://user-images.githubusercontent.com/5114052/34521224-ad137722-f0b2-11e7-82a2-c0b7c048d199.gif)
Let me check further and get back

**Comment by marinomeneghel** [comment]
Hey @SamvelRaja, any news about this? I'm still having the error in a consistent way 🤔 
I noticed another thing that may be helpful: even with a short name (like `test_collection`) this error happen for me, but only when I try to save to the directory that postman automatically suggests (both if the file already exists there and if its the first time it's saved).
If before saving I change the location to anywhere else (eg. Documents) and then change it back to the suggested one (eg. Desktop) then the collection is saved correctly. 


![postman_bug](https://user-images.githubusercontent.com/3415753/35197995-6a434c58-fee8-11e7-865e-b52d06d75720.gif)

**Comment by sivcan** [comment]
Kindly update to the latest version of the Postman desktop app.
Feel free to reopen this issue if the issue persists.
