### ISSUE TITLE
Can't export results from runner when there has been a connection failure.

### ISSUE THREAD

**Issue by smoyse** [a85/POSTMan-Chrome-Extension#4076]
## App Details:

```
Postman for Linux
Version 5.5.0
linux 4.13.16-100.fc25.x86_64 / x64

Postman for Windows
Version 5.5.0
win32 10.0.10240 / x64

```

## Issue Report:

After using runner to perform a test on a number of different servers by parameterising the hostname of the request in a csv file.
If any of the requests fail because of a connection issue - SSL issue, or connection timeout then I am not able to export the results. I get the error:

Failed to export collection run: TypeError: Cannot read property 'code' of undefined

If all connections were successful I am able to export the results as expected.

 1. Did you encounter this recently, or has this bug always been there:
First time I have used this feature, so not sure.
I also get the same result on 5.0.0

 2. Expected behaviour:
Be able to export the results of a collection run regardless of connection errors.

 3. Console logs 
```
TypeError: Cannot read property 'code' of undefined
    at file:///opt/Postman/resources/app/js/runner.js:169726:35
    at arrayEach (file:///opt/Postman/resources/app/js/common.js:1450:11)
    at Function.forEach (file:///opt/Postman/resources/app/js/common.js:9939:14)
    at file:///opt/Postman/resources/app/js/runner.js:169696:7
    at arrayReduce (file:///opt/Postman/resources/app/js/common.js:1617:21)
    at Function.reduce (file:///opt/Postman/resources/app/js/common.js:10282:14)
    at getRequests (file:///opt/Postman/resources/app/js/runner.js:169695:12)
    at ReduxToBackbone (file:///opt/Postman/resources/app/js/runner.js:169922:15)
    at RunnerController.exportRun (file:///opt/Postman/resources/app/js/runner.js:245879:65)
    at Runner.handleExport (file:///opt/Postman/resources/app/js/runner.js:239974:17)
    at Button.handleClick (file:///opt/Postman/resources/app/js/runner.js:4717:64)
    at Object.invokeGuardedCallback (file:///opt/Postman/resources/app/js/runner.js:62798:5)
    at executeDispatch (file:///opt/Postman/resources/app/js/runner.js:62626:21)
    at Object.executeDispatchesInOrder (file:///opt/Postman/resources/app/js/runner.js:62649:5)
    at executeDispatchesAndRelease (file:///opt/Postman/resources/app/js/runner.js:40110:22)
    at executeDispatchesAndReleaseTopLevel (file:///opt/Postman/resources/app/js/runner.js:40121:10)
    at Array.forEach (native)
    at forEachAccumulated (file:///opt/Postman/resources/app/js/runner.js:78022:9)
    at Object.processEventQueue (file:///opt/Postman/resources/app/js/runner.js:40324:7)
    at runEventQueueInBatch (file:///opt/Postman/resources/app/js/runner.js:107752:18)
    at Object.handleTopLevel [as _handleTopLevel] (file:///opt/Postman/resources/app/js/runner.js:107763:5)
    at handleTopLevelImpl (file:///opt/Postman/resources/app/js/runner.js:110937:24)
    at ReactDefaultBatchingStrategyTransaction.perform (file:///opt/Postman/resources/app/js/runner.js:58808:20)
    at Object.batchedUpdates (file:///opt/Postman/resources/app/js/runner.js:110854:26)
    at Object.batchedUpdates (file:///opt/Postman/resources/app/js/runner.js:18264:27)
    at dispatchEvent (file:///opt/Postman/resources/app/js/runner.js:111012:20)
    at HTMLDocument.wrapped (file:///opt/Postman/resources/app/js/runner.js:222584:29)
```
 4. Screenshots (if applicable)
None

5. Steps to reproduce.

Ensure that SSL verification is on
Use runner to run a test that connects to https://localhost
(the connection should fail because of the self signed cert or host name mismatch)
Or use http://localhost:1111
(the connection should fail because nothing is listening on 1111)
Attempt to export the results.

**Comment by numaanashraf** [comment]
@smoyse Thanks for reporting this. We are looking into this issue.

**Comment by marvader** [comment]
Same problem here..

TypeError: Cannot read property 'code' of undefined
    at runner.js:169739
    at arrayEach (common.js:1734)
    at Function.forEach (common.js:10223)
    at runner.js:169709
    at arrayReduce (common.js:1901)
    at Function.reduce (common.js:10566)
    at getRequests (runner.js:169708)
    at ReduxToBackbone (runner.js:169935)
    at RunnerController.exportRun (runner.js:245980)
    at Runner.handleExport (runner.js:240075)
exportRun @ runner.js:245988

**Comment by macux** [comment]
I'm getting the same from Postman's collection runner (Windows Version 5.5.3 win32 6.1.7601 / x64).

I'm running a website trawl by caching links and using setNextRequest, only on the current host. It works as expected but I can't export the results, error is:

Failed to export collection run: TypeError: Cannot read property 'code' of undefined

If I short circuit the run so that the results are not large then it works OK, there are no connection timeouts only some 404s in my run (but that's the point of the run).

**Comment by sivcan** [comment]
@smoyse @macux I was unable to reproduce this issue.
Can you guys update to the latest version of the Postman App (v6.2 as of now) and try exporting?
Let me know, thanks!

**Comment by smoyse** [comment]
I installed 6.2.2 this morning.
I ran my tests again, and was able to export the results even with some connection failures.
Thanks
