### ISSUE TITLE
Collection Runner stops running with error "Cannot read property 'toString' of null"

### ISSUE THREAD

**Issue by viraxslot** [a85/POSTMan-Chrome-Extension#4094]
## App Details:
```
Postman for Windows
Version 5.5.0
win32 10.0.16299 / ia32
```
## Issue Report:
I have few steps in my project and I can run them one after another without any problem from main window of Postman.

In first and second request I use `pm.environment.set`.
In third request I use also something like that:
`
var filteredRec = _.filter(jsonData.data.test, {GroupId: Id})
`

When I try to use collection runner Postman returns an error and run stops.
In Console: undefined
In Dev-Tools:
`"TypeError: Cannot read property 'toString' of null
at PostmanVariable.toString (C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\lib\collection\variable.js:108:34)
at C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\lib\superstring\index.js:221:53
at C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\lib\superstring\index.js:47:23
at RegExp.[Symbol.replace] (<anonymous>)
at String.replace (native)
at SuperString.replace (C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\lib\superstring\index.js:45:34)
at Substitutor.parse (C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\lib\superstring\index.js:132:27)
at Function.replaceSubstitutions (C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\lib\collection\property.js:222:69)
at Function.<anonymous> (C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\lib\collection\property.js:253:25)
at C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\lib\collection\property.js:247:40
at C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\node_modules\lodash\lodash.js:4944:15
at baseForOwn (C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\node_modules\lodash\lodash.js:3001:24)
at Function.forOwn (C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\node_modules\lodash\lodash.js:13002:24)
at Function.<anonymous> (C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\lib\collection\property.js:246:19)
at C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\lib\collection\property.js:247:40
at C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\node_modules\lodash\lodash.js:4944:15
at baseForOwn (C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\node_modules\lodash\lodash.js:3001:24)
at Function.forOwn (C:\Users\someuser\AppData\Local\Postman\app-5.5.0\resources\app.asar\node_modules\postman-collection\node_modules\lodash\lodash.js:13002:24)"
`

What should I do? Thanks.

**Comment by kunagpal** [comment]
@viraxslot Thanks for reporting this! This is happening because the variable value you are trying to set is `null`. While a fix is being worked on, could you include a fallback value for the suspected `.set` statements, like so:
```js
// here, null/undefined values for the variable will cause a crash
pm.environment.set('my_var_name', value || ''); // This is a workaround while https://github.com/postmanlabs/postman-app-support/issues/4094 is fixed
```

**Comment by viraxslot** [comment]
@kunagpal Thank you very much, your advice helped me. I set "null" explicitly, because sometimes my parameters should be empty. Now I set empty string and the project runs without errors.
But I hope you'll fix it :)

**Comment by kunagpal** [comment]
@viraxslot This had been fixed a few months ago 😄. Feel free to try it out in the latest stable app.

**Comment by aspoehrer** [comment]
This is not fixed. I am running a valid and successful run in Postman but in Runner it fails with a variable undefined that isn't even mentioned. It almost acts  like its a caching issue because I have removed all code and replaced the referenced variable with another name throughout..

**Comment by chen-yi-tester** [comment]
> @viraxslot Thanks for reporting this! This is happening because the variable value you are trying to set is `null`. While a fix is being worked on, could you include a fallback value for the suspected `.set` statements, like so:
> 
> ```js
> // here, null/undefined values for the variable will cause a crash
> pm.environment.set('my_var_name', value || ''); // This is a workaround while https://github.com/postmanlabs/postman-app-support/issues/4094 is fixed
> ```
My test scripts have " pm.globals.set("newuser_id", data.data.id)" ,when the response code is 500, it wont run the rest of requests and show TypeError: Cannot read property 'id' of null. How can i solve it,thank you

**Comment by akashgkrishnan** [comment]
```
Req body {    
    "storeName":"{{storeName}}{{$randomAbbreviation}}",
    "productIds": [{{productIds}}]

}
```

test
```
const response = pm.response.json();
pm.globals.set("createdStoreId", response.data.id);
pm.globals.set("createdStoreName", response.data.storeName);
```



This works fine on normally hitting the API
but on using the collection runner gives out an error
 
`TypeError: Cannot read property 'id' of null`
