### ISSUE TITLE
Postman throws error and when environment value is null

### ISSUE THREAD

**Issue by ugenlik** [a85/POSTMan-Chrome-Extension#4199]
## App Details:

```
Postman for Mac
Version 5.5.3 (5.5.3)
OS X 10.13.3 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently
 2. Expected behaviour: Postman to complete the request. 
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```
Errors were encountered running your collection: Objectmessage: "Cannot read property 'toString' of null"name: "TypeError"stack: "TypeError: Cannot read property 'toString' of null↵    at PostmanVariable.toString (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/collection/variable.js:108:34)↵    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/superstring/index.js:221:53↵    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/superstring/index.js:47:23↵    at RegExp.[Symbol.replace] (<anonymous>)↵    at String.replace (native)↵    at SuperString.replace (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/superstring/index.js:45:34)↵    at Substitutor.parse (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/superstring/index.js:132:27)↵    at Function.replaceSubstitutions (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/collection/property.js:222:69)↵    at Function.<anonymous> (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/collection/property.js:253:25)↵    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/collection/property.js:247:40↵    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/node_modules/lodash/lodash.js:4944:15↵    at baseForOwn (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/node_modules/lodash/lodash.js:3001:24)↵    at Function.forOwn (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/node_modules/lodash/lodash.js:13002:24)↵    at Function.<anonymous> (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/collection/property.js:246:19)↵    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/collection/property.js:247:40↵    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/node_modules/lodash/lodash.js:4944:15↵    at baseForOwn (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/node_modules/lodash/lodash.js:3001:24)↵    at Function.forOwn (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/node_modules/lodash/lodash.js:13002:24)"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()arguments: nullcaller: nulllength: 1name: "isPrototypeOf"__proto__: ()[[FunctionLocation]]: <unknown>propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()arguments: nullcaller: nulllength: 1name: "set __proto__"__proto__: ()
onEndRun @ runner.js:247328
```
 4. Screenshots (if applicable)

![screen shot 2018-02-15 at 2 47 21 pm](https://user-images.githubusercontent.com/1995917/36277657-7ff871c4-125f-11e8-828d-b70c0972acb2.png)

Steps to Reproduce:

Request:

```
PATCH url HTTP/1.1
Host: qa-secure1.host.com
Authorization: Bearer eyJ0eXAiOi----token
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: a11247d9-f2e6-e6b7-edfd-1cae0e26c3c3

[
  { "op": "replace", "path": "/address1", "value": "US"},
  { "op": "replace", "path": "/address2", "value": ""},
  { "op": "replace", "path": "/city", "value": ""},
  { "op": "replace", "path": "/state", "value": ""},
  { "op": "replace", "path": "/zip", "value": ""},
  { "op": "replace", "path": "/primaryPhone", "value": ""},
  { "op": "replace", "path": "/secondaryPhone", "value": ""},
  { "op": "replace", "path": "/fax", "value": ""},
  { "op": "replace", "path": "/email", "value": ""},
  { "op": "replace", "path": "/notes", "value": ""},
  { "op": "replace", "path": "/latitude", "value": "37.09024"},
  { "op": "replace", "path": "/longitude", "value": "-95.712891"},
  { "op": "replace", "path": "/fullAddress", "value": "US"}
]
```

Response:
```
{
    "customerId": 10262666,
    "industryTypeId": "[Other]",
    "name": "customer alpha",
    "address1": "US",
    "address2": "",
    "city": "",
    "state": "",
    "zip": "",
    "primaryPhone": "",
    "secondaryPhone": "",
    "fax": "",
    "isActive": true,
    "creationDate": "2018-02-15T14:05:13.233",
    "lastModDate": "2018-02-15T14:14:38.320061-05:00",
    "portalId": 90056,
    "moduleID": null,
    "email": "",
    "notes": "",
    "createdBy": "6b04388b-22be-7a37-b69f-b398f72d4668@email.com",
    "updatedBy": "6b04388b-22be-7a37-b69f-b398f72d4668@email.com",
    "dataGroupId": null,
    "listId": null,
    "editSequence": null,
    "lastImport": null,
    "lastExport": null,
    "termsId": null,
    "customerTypeId": null,
    "customerType": null,
    "businessUnitId": null,
    "countryId": "US",
    "lastOpenedBy": null,
    "lastOpenedTime": null,
    "lastOpenedLocation": null,
    "parentId": null,
    "billToParent": null,
    "latitude": 37.09024,
    "longitude": -95.712891,
    "fullAddress": "US",
    "doNotText": true,
    "cleanPrimaryPhone": "",
    "cleanSecondaryPhone": "",
    "contacts": [],
    "customFields": [],
    "taxId": null
}
```

Tests:
```
tests["Status code is 200"] = responseCode.code === 200;
tests["Response time is less than 5 seconds"] = responseTime < 5000;

var obj = JSON.parse(responseBody);
    
tests["portalId matches environment var"] = environment.portal_id == obj.portalId;
tests["customerId is " + obj.customerId ] = responseBody.has("customerId");
tests["industryTypeId is " + obj.industryTypeId ] = responseBody.has("industryTypeId");
tests["name is " + obj.name ] = responseBody.has("name");
tests["address1 is " + obj.address1 ] = responseBody.has("address1");
tests["address2 is " + obj.address2 ] = responseBody.has("address2");
tests["city is " + obj.city ] = responseBody.has("city");
tests["state is " + obj.state ] = responseBody.has("state");
tests["zip is " + obj.zip ] = responseBody.has("zip");
tests["primaryPhone is " + obj.primaryPhone ] = responseBody.has("primaryPhone");
tests["secondaryPhone is " + obj.secondaryPhone ] = responseBody.has("secondaryPhone");
tests["fax is " + obj.fax ] = responseBody.has("fax");
tests["isActive is " + obj.isActive ] = responseBody.has("isActive");
tests["creationDate is " + obj.creationDate ] = responseBody.has("creationDate");
tests["lastModDate is " + obj.lastModDate ] = responseBody.has("lastModDate");
tests["portalId is " + obj.portalId ] = responseBody.has("portalId");
tests["moduleID is " + obj.moduleID ] = responseBody.has("moduleID");
tests["email is " + obj.email ] = responseBody.has("email");
tests["notes is " + obj.notes ] = responseBody.has("notes");
tests["createdBy is " + obj.createdBy ] = responseBody.has("createdBy");
tests["updatedBy is " + obj.updatedBy ] = responseBody.has("updatedBy");
tests["dataGroupId is " + obj.dataGroupId ] = responseBody.has("dataGroupId");
tests["listId is " + obj.listId ] = responseBody.has("listId");
tests["editSequence is " + obj.editSequence ] = responseBody.has("editSequence");
tests["lastImport is " + obj.lastImport ] = responseBody.has("lastImport");
tests["lastExport is " + obj.lastExport ] = responseBody.has("lastExport");
tests["termsId is " + obj.termsId ] = responseBody.has("termsId");
tests["customerTypeId is " + obj.customerTypeId ] = responseBody.has("customerTypeId");
tests["businessUnitId is " + obj.businessUnitId ] = responseBody.has("businessUnitId");
tests["countryId is " + obj.countryId ] = responseBody.has("countryId");
tests["lastOpenedBy is " + obj.lastOpenedBy ] = responseBody.has("lastOpenedBy");
tests["lastOpenedTime is " + obj.lastOpenedTime ] = responseBody.has("lastOpenedTime");
tests["lastOpenedLocation is " + obj.lastOpenedLocation ] = responseBody.has("lastOpenedLocation");
tests["parentId is " + obj.parentId ] = responseBody.has("parentId");
tests["billToParent is " + obj.billToParent ] = responseBody.has("billToParent");
tests["latitude is " + obj.latitude ] = responseBody.has("latitude");
tests["longitude is " + obj.longitude ] = responseBody.has("longitude");
tests["fullAddress is " + obj.fullAddress ] = responseBody.has("fullAddress");
tests["doNotText is " + obj.doNotText ] = responseBody.has("doNotText");
tests["cleanPrimaryPhone is " + obj.cleanPrimaryPhone ] = responseBody.has("cleanPrimaryPhone");
tests["cleanSecondaryPhone is " + obj.cleanSecondaryPhone ] = responseBody.has("cleanSecondaryPhone");
tests["contacts is " + obj.contacts ] = responseBody.has("contacts");
tests["customFields is " + obj.customFields ] = responseBody.has("customFields");
    
//set back to the original values      
tests["address1 matches environment "] = environment.original_customer_address1 == obj.address1; 
tests["address2 matches environment "] = environment.original_customer_address2 == obj.address2; 
tests["city matches environment "] = environment.original_customer_city == obj.city; 
tests["state matches environment "] = environment.original_customer_state == obj.state; 
tests["zip matches environment "] = environment.original_customer_zip == obj.zip; 
tests["primaryPhone matches environment "] = environment.original_customer_primaryPhone == obj.primaryPhone; 
tests["secondaryPhone matches environment "] = environment.original_customer_secondaryPhone == obj.secondaryPhone; 
tests["fax matches environment "] = environment.original_customer_fax == obj.fax;  
tests["email matches environment "] = environment.original_customer_email == obj.email; 
tests["notes matches environment "] = environment.original_customer_notes == obj.notes; 
tests["fullAddress matches environment "] = environment.original_customer_fullAddress == obj.fullAddress;
```

Above works fin when requested manually, hangs when requested in collection run or throws error in newman with:
**Cannot read property 'toString' of null.**

**Comment by harryi3t** [comment]
@ugenlik Thanks for reporting. We are looking into this

**Comment by ugenlik** [comment]
@harryi3t  my guess is this has to do with environmental variables. because in a previous script I set variables like this


Previous script response is 

```
{
    "customerId": 10262711,
    "industryTypeId": "[Other]",
    "name": "Bob's Great Burgers & Fries",
    "address1": "US",
    "address2": null,
    "city": null,
    "state": null,
    "zip": null,
    "primaryPhone": null,
    "secondaryPhone": null,
    "fax": null,
    "isActive": true,
    "creationDate": "2018-02-16T15:26:09.977",
    "lastModDate": null,
    "portalId": 90081,
    "moduleID": null,
    "email": null,
    "notes": null,
    "createdBy": "b01c45c1-b9a9-c7e9-e541-a501386438cf@email.com",
    "updatedBy": "b01c45c1-b9a9-c7e9-e541-a501386438cf@email.com",
    "dataGroupId": null,
    "listId": null,
    "editSequence": null,
    "lastImport": null,
    "lastExport": null,
    "termsId": null,
    "customerTypeId": null,
    "customerType": null,
    "businessUnitId": null,
    "countryId": "US",
    "lastOpenedBy": null,
    "lastOpenedTime": null,
    "lastOpenedLocation": null,
    "parentId": null,
    "billToParent": null,
    "latitude": 37.09024,
    "longitude": -95.712891,
    "fullAddress": "US",
    "doNotText": false,
    "cleanPrimaryPhone": null,
    "cleanSecondaryPhone": null,
    "contacts": null,
    "customFields": [],
    "taxId": null
}
```

as you can see there is a lot of null's in there. 

```
postman.setEnvironmentVariable("original_customer_name", obj.name);
postman.setEnvironmentVariable("original_customer_address1", obj.address1);
postman.setEnvironmentVariable("original_customer_address2", obj.address2);
postman.setEnvironmentVariable("original_customer_city", obj.city);
postman.setEnvironmentVariable("original_customer_state", obj.state);
postman.setEnvironmentVariable("original_customer_zip", obj.zip);
postman.setEnvironmentVariable("original_customer_primaryPhone", obj.primaryPhone);
postman.setEnvironmentVariable("original_customer_secondaryPhone", obj.secondaryPhone);
postman.setEnvironmentVariable("original_customer_fax", obj.fax);
postman.setEnvironmentVariable("original_customer_isActive", obj.isActive);
postman.setEnvironmentVariable("original_customer_email", obj.email);
postman.setEnvironmentVariable("original_customer_notes", obj.notes);
postman.setEnvironmentVariable("original_customer_latitude", obj.latitude);
postman.setEnvironmentVariable("original_customer_longitude", obj.longitude);
postman.setEnvironmentVariable("original_customer_fullAddress", obj.fullAddress);
postman.setEnvironmentVariable("original_customer_doNotText", obj.doNotText);
  ```

then I request the above PATCH like this:
```
[
  { "op": "replace", "path": "/address1", "value": "{{original_customer_address1}}"},
  { "op": "replace", "path": "/address2", "value": "{{original_customer_address2}}"},
  { "op": "replace", "path": "/city", "value": "{{original_customer_city}}"},
  { "op": "replace", "path": "/state", "value": "{{original_customer_state}}"},
  { "op": "replace", "path": "/zip", "value": "{{original_customer_zip}}"},
  { "op": "replace", "path": "/primaryPhone", "value": "{{original_customer_primaryPhone}}"},
  { "op": "replace", "path": "/secondaryPhone", "value": "{{original_customer_secondaryPhone}}"},
  { "op": "replace", "path": "/fax", "value": "{{original_customer_fax}}"},
  { "op": "replace", "path": "/email", "value": "{{original_customer_email}}"},
  { "op": "replace", "path": "/notes", "value": "{{original_customer_notes}}"},
  { "op": "replace", "path": "/latitude", "value": "{{original_customer_latitude}}"},
  { "op": "replace", "path": "/longitude", "value": "{{original_customer_longitude}}"},
  { "op": "replace", "path": "/fullAddress", "value": "{{original_customer_fullAddress}}"}
]
```

In the last version did any changes applied to how postman handles environmental vars ?  

or is it because`obj.city` is null but then when I try to save it in `postman.setEnvironmentVariable("original_customer_city", obj.city);`, it tries to save as a string `""` 

It is a bit strange this works manually, but I can not do anymore automated test because of this bug, it is really annoying.

**Comment by harryi3t** [comment]
@ugenlik I tried running a request with following script
```js
postman.setEnvironmentVariable('variable', null)
```
This works fine with no exception and my runner also does not hang. Can you provide a minimal example request with a script that can reproduce this?

**Comment by RSM-DRO** [comment]
Hi,

I've had exactly the same issue and I found out that it had to do with variables in Headers.

I have this as a header variable in lets say request°2:
`[{"key":"X-SessionId","value":"{{sessionId}}","description":"","enabled":true}]`

In request°1 I was doing this:
`postman.setEnvironmentVariable("sessionId", null);`
which led instantly to  **_Errors were encountered running your collection_**

I "fixed" it by simply do this:
`postman.setEnvironmentVariable("sessionId", 123456);`

I guess that Postman is not able to handle not defined variables in the Collection Runner anymore. One nasty bug among a lot of others. I hope that Postman can catch up with a good product quality soon.

I have Postman v5.5.3 on Windows 7.

Hope this helps you out.

**Comment by harryi3t** [comment]
@RossmannRoggenkamp Thanks. I was able to pinpoint the issue with your help.
We will be fixing this bug.

**Comment by harryi3t** [comment]
@RossmannRoggenkamp @ugenlik 
As a workaround, always set environment values as an empty string instead of null.
```js
postman.setEnvironmentVariable("sessionId", "");
```
I will update this thread as soon as a fix is released.

**Comment by harryi3t** [comment]
@RossmannRoggenkamp @ugenlik This is fixed in the latest version of Postman 6.2.3

**Comment by Tomiiisin** [comment]
Hello I have this same issue,

The variable is not updated with the new value. see my configuration below
Can someone please point out what I am doing wrongly
![image](https://user-images.githubusercontent.com/44162340/50599165-84b38780-0ead-11e9-9e90-ab94ba66a02c.png)

![image](https://user-images.githubusercontent.com/44162340/50599217-ac0a5480-0ead-11e9-9373-03b47e8a24d4.png)

**Comment by harryi3t** [comment]
@tomiiisin shouldn't it be:
```
data.data.token.accessToken
```
?
