### ISSUE TITLE
Operational when joining "Team Workspace": Would violate uniqueness constraint

### ISSUE THREAD

**Issue by Rodske** [a85/POSTMan-Chrome-Extension#4259]
## App Details:
```
Postman for Windows & PostmanCanary for Windows
Version 6.0.7 & 6.0.8-canary02 
Windows 10 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
New, as I've only just joined a Team and could relate to the Transfer of a team Collection

 2. Expected behaviour:
I'm able to [Join] "Team Workspace"

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
OperationalError__stackCleaned__: trueadapterMethodName: "create"attrNames: Array[0]cause: Error: Would violate uniqueness constraint-- a record already exists with conflicting value(s).
    at file:///C:/Users/rodney.greenfield/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:29484:15code: "E_UNIQUE"isOperational: truemessage: "Would violate uniqueness constraint-- a record already exists with conflicting value(s)."modelIdentity: "syncworkspace"name: "AdapterError"raw: Error: Can't insert key ce3a1da3-ed8f-430c-830d-bed8317f19ca, it violates the unique constraint
    at _AVLTree.insert (file:///C:/Users/rodney.greenfield/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:317540:19)
    at AVLTree.insert (file:///C:/Users/me/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:317574:27)
    at Index.insert (file:///C:/Users/me/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:159990:15)
    at Datastore.addToIndexes (file:///C:/Users/me/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:316644:29)
    at Datastore._insertInCache (file:///C:/Users/me/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:316866:10)
    at Datastore._insert (file:///C:/Users/me/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:316812:10)
    at file:///C:/Users/me/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:317214:13
    at Object.process (file:///C:/Users/me/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:119128:21)
    at next (file:///C:/Users/me/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:119125:27)
    at Immediate.<anonymous> (file:///C:/Users/me/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:118421:16)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)stack: "AdapterError: Would violate uniqueness constraint-- a record already exists with conflicting value(s).â†µ    at file:///C:/Users/me/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:29484:15â†µFrom previous event:â†µ    at Deferred.toPromise (file:///C:/Users/me/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:269357:19)â†µ    at Deferred.then (file:///C:/Users/me/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:269218:22)â†µ    at file:///C:/Users/me/AppData/Local/PostmanCanary/app-6.0.8-canary02/resources/app.asar/js/shared.js:29486:15"toJSON: ()__proto__: Error
(anonymous) @ shared.js:113755
[PostmanCanary.SharedConsole.log](https://github.com/postmanlabs/postman-app-support/files/1770249/PostmanCanary.SharedConsole.log)

 4. Screenshots (if applicable)
![join error](https://user-images.githubusercontent.com/24272/36833720-7b8f45ec-1d84-11e8-9b8d-701790dd6145.JPG)

**Comment by kamalaknn** [comment]
Hi @Rodske 

We are investigating this. Could you give use more info on how you got into this state?

1. Did you join the Team Workspace now?
2. Were you added to this workspace by another member?
3. Were you added to the workspace even before you opened/updated the app?

Also, can you try closing and opening the app and see if it still exists?

**Comment by Rodske** [comment]
I’ve tried restarting my machine, different versions (older, reinstalling stable and then trying Canary beta release). All fail to “Join” the “Team Workplace”. The button is active after switching to the Workplace, then to do any action I’m asked to “Join” to continue, but nothing happens. I cannot proceed with the Workspace, however for other Workspaces, everything is fine.
I subscribed to Collections via the web interface (and have now unsubscribed to all Collections). Still errors.
Clicking to Manage Workspaces via the api, takes me to unfinished and buggy web experiences.
I was add the Team today after first trialing the Pro account.

**Comment by Rodske** [comment]
Further info; I created a Pro Trial with the name “chiefapp” , then I was added as an admin / billing person to a different full Pro account “mylocalbroker” and that was then subsequently named “chiefapp” without issue. Related?

**Comment by kamalaknn** [comment]
@Rodske Could you drop an email to `help[at]getpostman.com` from your registered email address?

This will allow us to verify the data on this account on our servers.

**Comment by Rodske** [comment]
I’ve done that already. You didn’t receive it?

**Comment by kamalaknn** [comment]
@Rodske We can confirm the issue. We are working on this.

We'll get back to you with updates.

**Comment by kamalaknn** [comment]
Hi @Rodske 

We've identified and fixed this issue on our side. Please restart the app and try joining again.

I'm closing this ticket. Reopen if the issue still exists.
