### ISSUE TITLE
Request is not sent

### ISSUE THREAD

**Issue by bermeitinger-b** [a85/POSTMan-Chrome-Extension#4303]
## App Details:
```
Postman for Linux
Version 6.0.9
linux 4.15.6-300.fc27.x86_64 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
It worked for older versions but I don't know which ones.
 2. Expected behaviour: Send request, get response.
 3. Console logs (started with `NODE_DEBUG=request /opt/Postman/Postman`):
- on Terminal: Only prints lines for authentication (I deleted ~/.config/Postman before)
- Postman Console empty
- DevTools: Console prints
```json
{
"message": "Unable to resolve variables. Require a List type property for variable auto resolution.",
"name": "Error",
"stack": "Error: Unable to resolve variables. Require a List type property for variable auto resolution.
    at PostmanItem.toObjectResolved (/opt/Postman/resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/collection/property.js:163:19)
    at resolveVariables (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:36:57)
    at PostmanCollectionRun.request (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:76:13)
    at Instruction.execute (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:156:29)
    at PostmanCollectionRun._process (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/run.js:165:21)
    at PostmanCollectionRun.<anonymous> (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/run.js:166:76)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)"
}
```

**Comment by thecuriousdev** [comment]
@bermeitinger-b thanks for reporting this issue. We'll look into this and will keep you posted here.

**Comment by reallyroy** [comment]
Seeing the same thing for 6.0.9 on Ubuntu 16.04.2 LTS 

[Postman.log](https://github.com/postmanlabs/postman-app-support/files/1811752/Postman.log)

**Comment by thecuriousdev** [comment]
Can you update to the latest Postman app and verify whether this issue is still there? If its still occurs for you, please provide the steps to reproduce this. We'll look into this.

**Comment by bermeitinger-b** [comment]
I think this has something to do with leftover files from previous versions. Overwriting the same folder with the new files was not enough, I had to remove the old folder before (or use a new folder).

**Comment by SamvelRaja** [comment]
Closing this issue in-favor of Linux auto updater which does the replacing files properly.
