### ISSUE TITLE
Couldn't find path to postman-prod.ico

### ISSUE THREAD

**Issue by antpr** [a85/POSTMan-Chrome-Extension#4310]
## App Details:

```
Postman for Windows
Version 6.0.9 (The exe says Version 1.6.16.0) /shrug
win32 10.0.16299 / x64
```

## Issue Report:
1. Did you encounter this recently, or has this bug always been there: Noticed it today
2. Expected behaviour: Postman icon shows up on the app shortcut 
3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Hi,

I installed Postman and noticed the Postman icon wasn't set in my Start menu or Taskbar in Win 10.

2018-03-08 12:44:32> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: Could not find a part of the path 'C:\Users\Postman\buildkite-agent\builds\postman-ci-agent-windows-1\postman\electron-package-and-deploy\resources\postman-prod.ico'. ---> System.Net.WebException: Could not find a part of the path 'C:\Users\Postman\buildkite-agent\builds\postman-ci-agent-windows-1\postman\electron-package-and-deploy\resources\postman-prod.ico'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Postman\buildkite-agent\builds\postman-ci-agent-windows-1\postman\electron-package-and-deploy\resources\postman-prod.ico'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
--- End of inner exception stack trace ---

SquirrelSetup logs attached FWIW.

I submitted this through support first and they told me to post it here. 

[SquirrelSetup.log](https://github.com/postmanlabs/postman-app-support/files/1794527/SquirrelSetup.log)

Thanks.

**Comment by dangerusslee** [comment]
I have the same issue - no icon on windows 10.

**Comment by SamvelRaja** [comment]
@dangerusslee  @antr we fixed this in our latest app (6.1.4) kindly update it. Also, follow https://github.com/postmanlabs/postman-app-support/issues/3107%23issuecomment-307015494 if you still faces it.

**Comment by bbrosius** [comment]
@SamvelRaja Mine actually broke after updating to 6.1.4 and I don't have a GitHub Inc. folder just a Postman folder.

**Comment by aajjss3** [comment]
I have the same problem stated above, after updating to 6.1.4 the  postman icon is missing. I do not have a GitHub folder, just a Postman folder.  I am using Windows 10 (latest patch).
The following is from my SquirrelSetup.log file. (FYI... i do not have a C:\Users\Administrator directory);
2018-07-05 21:31:48> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: Could not find a part of the path 'C:\Users\Administrator\buildkite-agent\builds\postman-ci-agent-windows-1\postman\electron-package-and-deploy\resources\postman-prod.ico'. 
When i click on to the 'Change Icon...' button for the windows Postman shortcut i get an error message saying:  "Windows can't find the file %USERPROFILE%\AppData\Local\Postman\app-6.0.10\Postman.exe" . I do not have version 6.0.10, just version 6.1.4, and I cannot seem to find out where this location is stored. I did a search in my registry and there is no mention of 6.0.10 anywhere. 
Also, I did a search on my hard drive and do not have the file 'postman-prod.ico'

**Comment by mmunchandersen** [comment]
On my win10 I updated the properties of the postman link: removed start in folder and pointed get-icon-from to c:\Users\[name]\AppData\Local\Postman\Update.exe

**Comment by alantallwave** [comment]
Awesome, that worked. Thank you.

**Comment by bcusto** [comment]
I had the same problem with version 6.7.2 windows 10 and managed to get around it
Right click the *setup.exe 
Click on Compatibility
Tick the box "Run this program in compatibility mode for:"
and choose Windows 8
press okay.
double click the *setup.exe

**Comment by harryi3t** [comment]
@antpr @bbrosius @aajjss3
The original issue where the error `InstallHelperImpl: Couldn't write uninstall icon` can be seen should be fixed.
For the other issues where the icon is broken, we are currently tracking 2 issues:
 - https://github.com/postmanlabs/postman-app-support/issues/2816
 - https://github.com/postmanlabs/postman-app-support/issues/6897

Please let us know if you are still facing the same issue (with the same error as mentioned above).
