### ISSUE TITLE
Constant disconnects

### ISSUE THREAD

**Issue by Tapppi** [a85/POSTMan-Chrome-Extension#4342]
```
Postman for Mac
Version 6.0.9 (6.0.9)
macOS 10.12.6 / x64
```

## Issue Report:
Constant disconnects and errors about sync connections. Really disturbing to workflow.

 1. Did you encounter this recently, or has this bug always been there:
This started happening after update to postman 6
 2. Expected behaviour:
No constant disconnection errors
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```
requester.js:41849 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41849
requester.js:554822 Check that entitites shown here should only be personal entites
componentWillMount @ requester.js:554822
requester.js:363121 error fetching Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (requester.js:75363)
    at EventEmitter.109.EventEmitter.emit (common.js:17109)
    at _dispatch (common.js:24502)
    at EventEmitter.<anonymous> (common.js:24512)
    at emitTwo (events.js:106)
    at EventEmitter.emit (events.js:191)
requester.js:75363 Uncaught (in promise) Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (requester.js:75363)
    at EventEmitter.109.EventEmitter.emit (common.js:17109)
    at _dispatch (common.js:24502)
    at EventEmitter.<anonymous> (common.js:24512)
    at emitTwo (events.js:106)
    at EventEmitter.emit (events.js:191)
3requester.js:41849 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41849
mode-auto.js Failed to load resource: net::ERR_FILE_NOT_FOUND
2requester.js:41849 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41849
requester.js:41849 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41849
requester.js:356140 Uncaught TypeError: Cannot read property 'ownerDocument' of null
    at getScrollPosition (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:393359:66)
    at DraftEditor._focus (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:496540:34)
    at PluginEditor._this.(anonymous function) [as focus] (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:502896:56)
    at AutoSuggestInput.handleFocus (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:123213:46)
    at Object.invokeGuardedCallback (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:112261:5)
    at executeDispatch (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:112089:21)
    at Object.executeDispatchesInOrder (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:112109:7)
    at executeDispatchesAndRelease (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:79566:22)
    at executeDispatchesAndReleaseTopLevel (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:79577:10)
    at Array.forEach (native)
    at forEachAccumulated (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:133358:9)
    at Object.processEventQueue (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:79780:7)
    at runEventQueueInBatch (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:206321:18)
    at Object.handleTopLevel [as _handleTopLevel] (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:206332:5)
    at handleTopLevelImpl (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:209506:24)
    at Object.batchedUpdates (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:209421:14)
    at Object.batchedUpdates (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:43034:27)
    at dispatchEvent (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:209581:20)
    at HTMLDocument.wrapped (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:356136:29)
    at addPointToSelection (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:499129:13)
    at setDraftEditorSelection (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:499070:7)
    at DraftEditorLeaf._setSelection (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:497198:5)
    at DraftEditorLeaf.componentDidMount (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:497210:10)
    at CallbackQueue.notifyAll (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:133484:22)
    at ReactReconcileTransaction.close (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:209713:26)
    at ReactReconcileTransaction.closeAll (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:101747:25)
    at ReactReconcileTransaction.perform (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:101694:16)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:101681:20)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:43026:32)
    at Object.flushBatchedUpdates (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:43109:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:101747:25)
    at ReactDefaultBatchingStrategyTransaction.perform (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:101694:16)
    at Object.batchedUpdates (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:209423:26)
    at Object.enqueueUpdate (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:43137:22)
    at enqueueUpdate (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:113088:16)
    at Object.enqueueSetState (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:113273:5)
    at DraftEditor.ReactComponent.setState (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:111583:16)
    at DraftEditor._restoreEditorDOM (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:496596:10)
    at file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:500175:12
    at wrapped (file:///Applications/Postman.app/Contents/Resources/app/js/requester.js:356136:29)
2requester.js:41849 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41849
requester.js:41849 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41849
requester.js:75715 Object
2requester.js:41849 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41849
requester.js:75715 Object
6requester.js:41849 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41849
requester.js:130096 Error running scripts: TypeError | Cannot read property 'length' of undefined Object
exception @ requester.js:130096
requester.js:41849 Could not find on CollectionStore. Missing or invalid parameter.
```
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/3275280/37435043-620fec96-27ea-11e8-9eae-8fa4449774b9.png)

**Comment by jpringle** [comment]
I am experiencing the same issue, with the same errors showing in Console logs.

I am also on Postman 6.0.9, but am using MacOS 10.11.6.

In fact, the above error message popped up 2x while I was typing this comment.

**Comment by anreddy018** [comment]
Iam also experiencing below error. any advise much appreciated. Thanks
Check that entitites shown here should only be personal entites
componentWillMount @ requester.js:560115
requester.js:368600 error fetching Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (file:///C:/Users/aredd11/AppData/Local/Postman/app-6.0.9/resources/app.asar/js/requester.js:75363:26)
    at EventEmitter.108.EventEmitter.emit (file:///C:/Users/aredd11/AppData/Local/Postman/app-6.0.9/resources/app.asar/js/common.js:17099:17)
    at _dispatch (file:///C:/Users/aredd11/AppData/Local/Postman/app-6.0.9/resources/app.asar/js/common.js:24502:14)
    at EventEmitter.<anonymous> (file:///C:/Users/aredd11/AppData/Local/Postman/app-6.0.9/resources/app.asar/js/common.js:24512:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)

**Comment by Tapppi** [comment]
Anyone from postman have more information on this bug?

**Comment by a85** [comment]
We are seeing heavy loads on the server. Will update this thread with more information soon.

**Comment by kamalaknn** [comment]
We've pushed a few fixes in both Postman App and Sync servers. We expect the load to go down over the next few days.

Thanks for understanding.

**Comment by marcgug** [comment]
I'm seeing this error right now in my postman logs :( Are there server issues again?

<img width="780" alt="cloudapp annotation 2018-04-20 at 2 30 14 pm png" src="https://user-images.githubusercontent.com/8808/39067632-5e7f1b2c-44a7-11e8-8b9c-ecab2d9854eb.png">

**Comment by brad-gardner** [comment]
I've been having this happen continuously since the last update, the majority of my team has the same issue. We are using Postman 6.0.10 on the mac.

I'm keeping an eye on the postman console now as well and will post any errors I find if there are any.

**Comment by Tapppi** [comment]
@kamalaknn looks like the error isn't constant anymore, but still on/off happening.

**Comment by JP-from-Postman** [comment]
These intermittent sync disconnects appear to still be occurring. I've seen them on my own app, as well as in reports from some users. Adding examples where they appear.
