### ISSUE TITLE
Blank window for collection runner .

### ISSUE THREAD

**Issue by sujitblues** [a85/POSTMan-Chrome-Extension#4522]
Blank window is opening while running runner.I am using the latest version window application of postman.
![latest](https://user-images.githubusercontent.com/37321410/39613227-6eee59fa-4f83-11e8-8c2c-f4fd456099c6.png)
![blank](https://user-images.githubusercontent.com/37321410/39613232-732abd60-4f83-11e8-8a74-acf0d3a91b22.png)

**Comment by sivcan** [comment]
@sujitblues - Can you share the console logs with us? 
While the runner window is active just go to View  > Developer > Show DevTools (Current View)

**Comment by sujitblues** [comment]
Console log:
Initializing the global config
requester.js:360887 Initializing settings
requester.js:298482 Booting waterline models
requester.js:298548 Object "Successful ORM initialization"
requester.js:369095  ================================================================
     o
   (/) P O S T M A N
   ^

   Go to View -> Show Postman Console to check your script logs.
================================================================
requester.js:41889 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41889
requester.js:560264 Check that entitites shown here should only be personal entites
componentWillMount @ requester.js:560264
requester.js:368809 error fetching Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (file:///C:/Users/Sujit/AppData/Local/Postman/app-6.0.10/resources/app.asar/js/requester.js:75398:26)
    at EventEmitter.108.EventEmitter.emit (file:///C:/Users/Sujit/AppData/Local/Postman/app-6.0.10/resources/app.asar/js/common.js:17099:17)
    at _dispatch (file:///C:/Users/Sujit/AppData/Local/Postman/app-6.0.10/resources/app.asar/js/common.js:24502:14)
    at EventEmitter.<anonymous> (file:///C:/Users/Sujit/AppData/Local/Postman/app-6.0.10/resources/app.asar/js/common.js:24512:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
3requester.js:41889 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41889
requester.js:410163 You tried to return focus to null but it is not in the DOM anymore
exports.returnFocus @ requester.js:410163
requester.js:41889 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41889
mode-auto.js Failed to load resource: net::ERR_FILE_NOT_FOUND
requester.js:41889 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41889
requester.js:130106 Error running scripts: TypeError | Cannot read property '0' of undefined Object
exception @ requester.js:130106
requester.js:41889 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41889
requester.js:171798 528xy29t8
requester.js:41889 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41889

Thanks,
Sujit

**Comment by sivcan** [comment]
@sujitblues - You shared the logs of the requester,
make sure you have the runner running and as the active window, then share the logs please?

**Comment by sujitblues** [comment]
Hello,
runner window is opening with blank screen I am not able to run the runner.this is the log on click of runner button.


Thanks,
Sujit

**Comment by sivcan** [comment]
Yes, @sujitblues - I understand that the runner window is black. Just click on the runner window and then open developer tools -  View > Developer > Show DevTools (Current View)

**Comment by sujitblues** [comment]
Please see the attached file for log .[developer tools - View > Developer > Show DevTools (Current View)]

Thanks,
Sujit

**Comment by sivcan** [comment]
@sujitblues - There's no log file attached.
Can you re-attach it ?

**Comment by sivcan** [comment]
Closing due to inactivity.
