### ISSUE TITLE
Add support for installing in user profiles on share path

### ISSUE THREAD

**Issue by uvarajkrishna** [a85/POSTMan-Chrome-Extension#4559]
**Description**
Recently switched from Chrome extension to Windows Native App. The app would start normally and i was able to create request at the beginning and after some time the Send button wouldn't respond and displays "Sending" state for ever. 
The console would show the error **"InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing."**. 
If I try to close the application it wouldn't close properly. So I shall close the app in command prompt using taskkill /F /IM postman.exe. 
Now if I open again either through short cut or directly in appdata/Postman folder from command prompt, I get a pop up saying **"Could not open Postman. Please contact help@getpostman.com".**

My machine is in corporate network VMWare VMs pool with my user profile present in shared path. So part of installation is present in **c:/user/myuser/AppData/Local** and remaining is present in **//sharepath.domain/xxx/profile/yyy/myuser/Application Data**
If I delete Postman folder present at share path, I am able to open the application again but the "IDBDatabase': The database connection is closing" issue re-occurs after some time. Especially after i try to save a request in collection or create a collection.
**But the same postman application and build version works perfectly fine in my personal laptop** with every data stored in my hard drive at  c:/user/myuser/AppData/Local and c:/user/myuser/AppData/Roaming

**To Reproduce**
1. Use a Windows 7+ VMWare VM with user profile present in share path
2. Install Postman native application
3. Create and make some request. 
4. Save the request in collection
5. Send the request again

**Expected behavior**
Application sends the request without any error. If the application is closed and opened again it opens without any issue.

**Screenshots**
 - Launch failure
![launch-failure-2](https://user-images.githubusercontent.com/5997305/40097267-0cc05598-588a-11e8-9c9e-8036a3f76139.PNG)

- Command line launch outcome
![command-line-launch](https://user-images.githubusercontent.com/5997305/40097181-8c1be0c4-5889-11e8-8001-ab689e940e15.PNG)
 - Appdata vs Local App data in windows
![appdata-vs-localappdata](https://user-images.githubusercontent.com/5997305/40097190-9fe5e762-5889-11e8-8ddf-951c0f9e13bb.PNG)
 - Postman console error while sending request or saving collection
![console-error](https://user-images.githubusercontent.com/5997305/40097210-b3895e0c-5889-11e8-9d52-c1d1ca84e4aa.PNG)
 - Postman console error log
[postman-console-error.txt](https://github.com/postmanlabs/postman-app-support/files/2007552/postman-console-error.txt)

**App information:**
 - App Type : Native App
 - Postman Version - 6.0.10
 - OS: Windows 7

**Additional context**
Tried with latest canary build and the issue would continue to occur.

**Comment by sivcan** [comment]
Hi @uvarajkrishna, we'll look into this issue and get back to you.

**Comment by uvarajkrishna** [comment]
Hi,
Do we have any update on this issue?
As an alternative i have been using Insomnia. But i couldn't do lot of stuffs. So i wrote testNG suites with Rest-Assured.

**Comment by preethammavin** [comment]
@uvarajkrishna  is the issue still persistent on the latest version of the app?

**Comment by uvarajkrishna** [comment]
@preethammavin The issue still persists. I checked with version 6.1.3

**Comment by uvarajkrishna** [comment]
Is there any chance of this issue getting resolved? My Customer's entire organization testers works in a similar VM setup of mine and none could use Postman.
The issue still persists with app-6.6.1

**Comment by cailyoung** [comment]
This is occurring for me, too, on a similar environment under Windows Server 2016 with app-6.7.3

**Comment by cailyoung** [comment]
Specific info:

I have already applied the GPU disabling environment variable.

Postman loads (slowly) and I have a few requests saved.

After some period of time, new requests fail to work and I cannot open new ones from collections.

Dev tools console output (redacted) when I try to open a new request (and it fails silently):

```
requester.html:1 Uncaught (in promise) OperationalError {cause: Error: Malformed error from adapter: Should always be an Error instance, but instead, got:
[Inva…, isOperational: true, adapterMethodName: "find", modelIdentity: "user", raw: DexieError…}adapterMethodName: "find"cause: Error: Malformed error from adapter: Should always be an Error instance, but instead, got:
[InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.]
    at file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:46616:20
    at <anonymous>isOperational: truemodelIdentity: "user"raw: DexieErrorinner: DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Transaction.create (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:171553:58)
    at tempTransaction (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:170503:23)
    at Table.getTransaction (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:170999:17)
    at Table.getIDBObjectStore (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:171008:25)
    at Collection._read (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:172146:31)
    at Collection.each (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:172177:29)
    at Object.find (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:251500:10)
    at _getPopulatedRecords (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:160039:21)
    at helpFind (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:160476:6)
    at _afterPotentiallyRunningBeforeLC (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:245011:9)
    at _maybeRunBeforeLC (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:244985:16)
    at Deferred._.extend._WLModel [as _handleExec] (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:244987:9)
    at Deferred.exec (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:216353:10)
    at promisified (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:221157:16)
    at Deferred.toPromise (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:216639:19)
    at Deferred.then (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:216498:22)message: "Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing."name: "InvalidStateError"_e: Error
    at getErrorWithStack (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:168986:12)
    at new DexieError (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:169115:19)
    at mapError (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:169145:14)
    at handleRejection (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:169629:14)
    at propagateToListener (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:169681:69)
    at file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:169427:17
    at executePromiseTask (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:169598:9)
    at new Promise (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:169415:5)
    at Promise.then (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:169426:22)
    at Collection._read (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:172146:55)
    at Collection.each (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:172177:29)
    at Object.find (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:251500:10)
    at _getPopulatedRecords (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:160039:21)
    at helpFind (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:160476:6)
    at _afterPotentiallyRunningBeforeLC (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:245011:9)
    at _maybeRunBeforeLC (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:244985:16)
    at Deferred._.extend._WLModel [as _handleExec] (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:244987:9)
    at Deferred.exec (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:216353:10)
    at promisified (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:221157:16)
    at Deferred.toPromise (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:216639:19)
    at Deferred.then (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:216498:22)stack: (...)get stack: function ()__proto__: DexieErrormessage: "Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.]↵```"name: "AdapterError"stack: "AdapterError: Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.]↵```↵    at file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:46616:20↵    at <anonymous>↵From previous event:↵    at Deferred.toPromise (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:216639:19)↵    at Deferred.then (file://machinename.local/home/Profiles/username/Documents/postman2/postman-portable/app/app-6.7.3/resources/app.asar/js/vendor-shared.js:216498:22)"__stackCleaned__: true__proto__: Error
```

**Comment by cailyoung** [comment]
Could the issue be in the way that Citrix in particular handles roaming profile sync?

**Comment by cailyoung** [comment]
https://github.com/louischatriot/nedb/issues/407

May be relevant. Node itself or nedb don't like permissions issues in the filestore?

**Comment by cailyoung** [comment]
#4602 may also be relevant here

**Comment by cailyoung** [comment]
Local ops team suggesting mapping the app location to a drive letter and launching it from the drive letter instead of a UNC path. This seems to be helping, at least for the last day. Will keep an eye on it.

**Comment by LarrysGIT** [comment]
When the issue happening, Git has a similar issue as well. The desktop is using Citrix and roaming profile,  `AppData` is pointing at a UNC path.
Git: `fatal: fsync error on 'sha1 file': Bad file descriptor`
Postman: `fsync known error`
Insomnia: `Failed to flush storage`
All pointing to "fsync", the only way I know for now is to reboot the server, looks like some underlying file system API doesn't like network path.

**Comment by mniesen** [comment]
I am also having a lot of problems using Postman with Folder Redirection and Roaming User Profiles. Almost all versions do not work or stop working after some time (hours to days). Version 9.8.2 works for me, higher and it doesn't work or stops working after some time.
