### ISSUE TITLE
Postman native app keeps failing to open

### ISSUE THREAD

**Issue by connelhooley** [a85/POSTMan-Chrome-Extension#4602]
**Describe the bug**
Postman keeps failing to open. The issue appears intermittent. Sometimes the splash screen comes up. Sometimes not even that appears. If I try and open Postman several times, then I can see several Postman instances running in the background inside Task Manager. I then kill all of the Postman processes and sometimes it begins to work again for a little while, it then regresses again.

**To Reproduce**
1. Open Postman via a start menu shortcut

**Expected behavior**
The splash screen should appear, followed by the main window.

**Screenshots**
N/A

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 6.1.2
 - OS: Windows 10

**Additional context**
I've tried modifying the shortcut in my start menu to disable GPU (as I saw a recent bug that recommended turning it off if it fails to open properly) but this doesn't appear to fix it:
`C:\Users\USERNAME\AppData\Local\Postman\Update.exe --processStart "Postman.exe --disable-gpu"`

**Comment by connelhooley** [comment]
Just tried opening from the command line. I get the message:
`Shared window not present`

I then went back to Task Manager and killed all instances of Postman.

I then tried again from the command line and got this error. This time the app stopped during the splash screen:
```
ORM initialization failed:  { Error: EPERM: operation not permitted, rename 'C:\Users\username\AppData\Roaming\Postman\archive~' -> 'C:\Users\username\AppData\Roaming\Postman\archive'
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'C:\\Users\\username\\AppData\\Roaming\\Postman\\archive~',
  dest: 'C:\\Users\\username\\AppData\\Roaming\\Postman\\archive' }
Uncaught errors TypeError: Cannot read property 'collections' of undefined
    at bootstrapModels (C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\main.js:94:27)
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\bootstrap-models.js:26:14
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\waterline\lib\waterline.js:918:25
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\waterline\lib\waterline.js:719:25
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\waterline\node_modules\async\dist\async.js:952:25
    at iteratorCallback (C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\waterline\node_modules\async\dist\async.js:995:17)
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\waterline\node_modules\async\dist\async.js:847:20
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\async\lib\async.js:52:16
    at done (C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\async\lib\async.js:241:17)
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\async\lib\async.js:44:16
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\common\adapters\waterline-shared-nedb.js:320:29
    at newArguments.(anonymous function) (C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\nedb\lib\executor.js:29:17)
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\nedb\lib\persistence.js:305:26
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\nedb\lib\persistence.js:138:23
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\nedb\lib\storage.js:105:30
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\nedb\node_modules\async\lib\async.js:485:30
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\nedb\lib\storage.js:102:70
    at FSReqWrap.oncomplete (fs.js:135:15)
Uncaught errors Error: Callback was already called.
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\waterline\node_modules\async\dist\async.js:844:36
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\async\lib\async.js:52:16
    at done (C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\async\lib\async.js:246:17)
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\async\lib\async.js:44:16
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\common\adapters\waterline-shared-nedb.js:342:18
    at newArguments.(anonymous function) (C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\nedb\lib\executor.js:29:17)
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\nedb\lib\persistence.js:308:15
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\nedb\lib\persistence.js:140:12
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\nedb\lib\storage.js:105:30
    at storage.flushToStorage (C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\nedb\lib\storage.js:56:97)
    at C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\nedb\node_modules\async\lib\async.js:597:23
    at fn (C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\nedb\node_modules\async\lib\async.js:582:34)
    at Immediate._onImmediate (C:\Users\username\AppData\Local\Postman\app-6.1.2\resources\app.asar\node_modules\nedb\node_modules\async\lib\async.js:498:34)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by harryi3t** [comment]
@connelhooley Can you try our latest canary build and follow the steps mentioned here
https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621

**Comment by jemerald** [comment]
@harryi3t the workaround to disable GPU fixes the issue for me. But is there going to be a permanent fix coming soon?

**Comment by connelhooley** [comment]
I'm still seeing the issue in the latest canary build, with the environment variable set. I'll try and run it via the command line again to get some logs.

I can also confirm a few other devs on my team are seeing the same behaviour.

**Comment by connelhooley** [comment]
```
Disabling hardware acceleration
ORM initialization failed:  { Error: EPERM: operation not permitted, rename 'C:\Users\username\AppData\Roaming\PostmanCanary\window~' -> 'C:\Users\username\AppData\Roaming\PostmanCanary\window'
  errno: -4048,ppUpdate' }
  code: 'EPERM', name: 'booted', namespace: 'requester' }
  syscall: 'rename',)
  path: 'C:\\Users\\username\\AppData\\Roaming\\PostmanCanary\\window~',
  dest: 'C:\\Users\\username\\AppData\\Roaming\\PostmanCanary\\window' }
Uncaught errors TypeError: Cannot read property 'collections' of undefined
    at bootstrapModels (C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\main.js:107:27)
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\bootstrap-models.js:26:14
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\waterline\lib\waterline.js:918:25
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\waterline\lib\waterline.js:719:25
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\waterline\node_modules\async\dist\async.js:952:25
    at iteratorCallback (C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\waterline\node_modules\async\dist\async.js:995:17)
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\waterline\node_modules\async\dist\async.js:847:20
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\async\lib\async.js:52:16
    at done (C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\async\lib\async.js:241:17)
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\async\lib\async.js:44:16
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\common\adapters\waterline-shared-nedb.js:320:29
    at newArguments.(anonymous function) (C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\nedb\lib\executor.js:29:17)
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\nedb\lib\persistence.js:305:26
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\nedb\lib\persistence.js:138:23
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\nedb\lib\storage.js:105:30
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\nedb\node_modules\async\lib\async.js:485:30
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\nedb\lib\storage.js:102:70
    at FSReqWrap.oncomplete (fs.js:135:15)
Uncaught errors Error: Callback was already called.
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\waterline\node_modules\async\dist\async.js:844:36
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\async\lib\async.js:52:16
    at done (C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\async\lib\async.js:246:17)
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\async\lib\async.js:44:16
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\common\adapters\waterline-shared-nedb.js:342:18
    at newArguments.(anonymous function) (C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\nedb\lib\executor.js:29:17)
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\nedb\lib\persistence.js:308:15
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\nedb\lib\persistence.js:140:12
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\nedb\lib\storage.js:105:30
    at storage.flushToStorage (C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\nedb\lib\storage.js:56:97)
    at C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\nedb\node_modules\async\lib\async.js:597:23
    at fn (C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\nedb\node_modules\async\lib\async.js:582:34)
    at Immediate._onImmediate (C:\Users\username\AppData\Local\PostmanCanary\app-6.1.3-canary01\resources\app.asar\node_modules\nedb\node_modules\async\lib\async.js:498:34)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by harryi3t** [comment]
@connelhooley That's weird. Normally the user should have permissions on the appData directory.
Can you try
 - Running the app as administrator. If this works then we know the issue is with permissions.
 - If the above works, can you try changing the owner of the `C:\Users\username\AppData\Roaming\PostmanCanary` directory to yourself recursively.

Am not sure how to change owners in windows, but maybe `right click on Postman -> properties -> securities` might help.

![image](https://user-images.githubusercontent.com/5207331/40767823-3e554520-64d1-11e8-8271-d8bce762805f.png)

**Comment by connelhooley** [comment]
I have checked the permissions for the `%APPDATA%\PostmanCanary` directory and I have access to all the files. It's impossible to say for sure, as the bug is intermittent, but I have been unable re-create it when running the application as administrator. Is there a way of knowing which files it can't read? Running as admin isn't an option for me as my admin account doesn't have access to the internet (company policy).

**Comment by connelhooley** [comment]
Just realised the filename is in the exception message, my mistake.

I've just had Postman also fail to rename the "archive~" file in the same directory so its probably something on my work machine that's stopping the renames somehow.

**Comment by RobertTBoyerPhD** [comment]
I am running into the same hang on start issue.  
Running by hand I found a EPERM failure, which I tracked down to a read-only setting on both of the directories C:\Users\Owner\AppData\Roaming (and I changed ...\Local for good measure).
Although it fixed the permission failure, it still hangs on start-up.  I can only see the window with icon, but no menu.  The output from by-hand-execution is:

C:\Users\Owner\AppData\Local\PostmanCanary>
1553811507687 main info "Booting PostmanCanary 7.1.0-canary01, win32-6.3.9600 on x64"
1553811507688 main info "EventBus~initialize - Success"
1553811507696 main info "UpdateHandler~init - Success"
1553811507698 main info "RuntimeExecutionService~initialized: Success"
1553811507776 main info "ProtocolHandler~init - Success with status: true]"
1553811508002 main info "PluginHost~bootHost: Booted - 1"
1553811508521 main info "Bootstrap-models~bootstrap - Success"
1553811511415 pluginHost info "Booting Plugin Host for PostmanCanary 7.1.0-canary01, win32-6.3.9600 on x64"
1553811511421 pluginHost info "PluginsHost: Booted"
1553811511431 pluginHost info "PluginInstallationService~_shouldReInstallPlugin",{"installedVersion":"0.0.10","currentVersion":"0.0.10"}
1553811511436 pluginHost info "PluginInstallationService~_shouldReInstallPlugin",{"installedVersion":"0.0.1","currentVersion":"0.0.1"}
1553811511438 pluginHost info "PluginsHost~installOrUpdatePlugins: Synced all plugins",[{"pluginId":"postman.openApi","version":"0.0.10","status":"skipped"},{"p
luginId":"postman.sample","version":"0.0.1","status":"skipped"}]
1553811545945 main info "Main~AppEvents - Received booted event for process shared"
1553811572966 main info "UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}
1553811572968 main info "Main~AppEvents - Received booted event for process requester"

**Comment by wlarch** [comment]
I had the same issue because I launched Postman with root privileges. The solution is to set permissions and ownership correctly for my user : 

`$ sudo chown -R user:user /home/user/.config/Postman/`

**Comment by terrynguyen255** [comment]
To me, @wlarch 's answer is the most helpful solution on the internet.

I had the problem when I updated Postman:
- Downloading the newer version required `root` privilege, so did the update progress
- After installed, executing Postman without `sudo` (like launching from app dock)

@wlarch saved my day :+1:
