### ISSUE TITLE
Postman 6.3.0 Just Hangs tried disable GPU VersionError The requested version (30) is less than the existing version (40).',

### ISSUE THREAD

**Issue by maccurt** [a85/POSTMan-Chrome-Extension#5313]
My postman just hangs, I tried  the disable GPU flag, and then I went to the command line to try to run it and get this error

Disabling hardware acceleration
ProtocolHandler~init: Setting custom protocol handling [status: true]
ORM initialization successful
App events bus { name: 'booted', namespace: 'shared' }
App events bus { data:
   { adapterMethodName: 'find',
     cause:
      { adapterMethodName: 'find',
        modelIdentity: 'workspacesession',
        name: 'AdapterError',
        raw: [Object] },
     isOperational: true,
     modelIdentity: 'workspacesession',
     raw:
      { _e: {},
        _stack: 'OpenFailedError: VersionError The requested version (30) is less than the existing version (40).\n    at Transaction.create (file:///C:/Users/Michael%20McGee/AppData/Local/Postman/app-6.3.0/resources/app.asar/js/vendor-shared.js:122438:31)\n    at tempTransaction (file:///C:/Users/Michael%20McGee/AppData/Local/Postman/app-6.3.0/resources/app.asar/js/vendor-shared.js:121394:23)\n    at Table.getTransaction (file:///C:/Users/Michael%20McGee/AppData/Local/Postman/app-6.3.0/resources/app.asar/js/vendor-shared.js:121890:17)\n    at Table.getIDBObjectStore (file:///C:/Users/Michael%20McGee/AppData/Local/Postman/app-6.3.0/resources/app.asar/js/vendor-shared.js:121899:25)\n    at Collection._read (file:///C:/Users/Michael%20McGee/AppData/Local/Postman/app-6.3.0/resources/app.asar/js/vendor-shared.js:123037:31)\n    at Collection.each (file:///C:/Users/Michael%20McGee/AppData/Local/Postman/app-6.3.0/resources/app.asar/js/vendor-shared.js:123068:29)\n    at Object.find (file:///C:/Users/Michael%20McGee/AppData/Local/Postman/app-6.3.0/resources/app.asar/js/vendor-shared.js:184630:10)\n    at _getPopulatedRecords (file:///C:/Users/Michael%20McGee/AppData/Local/Postman/app-6.3.0/resources/app.asar/js/vendor-shared.js:111090:21)\n    at helpFind (file:///C:/Users/Michael%20McGee/AppData/Local/Postman/app-6.3.0/resources/app.asar/js/vendor-shared.js:111527:6)\n    at _afterPotentiallyRunningBeforeLC (file:///C:/Users/Michael%20McGee/AppData/Local/Postman/app-6.3.0/resources/app.asar/js/vendor-shared.js:178510:9)\n    at _maybeRunBeforeLC (file:///C:/Users/Michael%20McGee/AppData/Local/Postman/app-6.3.0/resources/app.asar/js/vendor-shared.js:178484:16)\n    at Deferred._.extend._WLModel [as _handleExec] (file:///C:/Users/Michael%20McGee/AppData/Local/Postman/app-6.3.0/resources/app.asar/js/vendor-shared.js:178486:9)\n    at Deferred.exec (file:///C:/Users/Michael%20McGee/AppData/Local/Postman/app-6.3.0/resources/app.asar/js/vendor-shared.js:149867:10)\n    at promisified (file:///C:/Users/Michael%20McGee/AppData/Local/Postman/app-6.3.0/resources/app.asar/js/vendor-shared.js:154671:16)',
        inner: [Object],
        message: 'VersionError The requested version (30) is less than the existing version (40).',
        name: 'OpenFailedError' } },
  name: 'booted',

**Comment by maccurt** [comment]
I updated to 6.4 and it now works
