### ISSUE TITLE
Postman app fails to show response body

### ISSUE THREAD

**Issue by RidgeA** [a85/POSTMan-Chrome-Extension#5385]
**Describe the bug**
Postman fails to process a response body.

**To Reproduce**
1. Create  new request GET `https://postman-echo.com/get`
2. Click on 'Send'
3. In the response field see "Loading..."

In Postman console you can see that request finished successfully.

**Expected behavior**
See response body in the app

**App information (please complete the following information):**
 - Native app
 - 6.4.4
 - Linux Fedora 28 4.18.12-200.fc28.x86_64

**Additional context**
Stack trace:
```
main info ["Main~AppEvents - Received booted event for process requester"]
Main~handleUncaughtError - Uncaught errors TypeError: response.contentInfo is not a function
    at Function.response (/opt/Postman/resources/app/services/RuntimeExecutionService.js:350:47)
    at PostmanCollectionRun.<anonymous> (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:66:50)
    at PostmanCollectionRun.<anonymous> (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:87:21)
    at apply (/opt/Postman/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:496:27)
    at /opt/Postman/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9490:36
    at /opt/Postman/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:4920:15
    at Function.<anonymous> (/opt/Postman/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9489:7)
    at apply (/opt/Postman/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:497:27)
    at Function.invokeMap (/opt/Postman/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:6600:16)
    at Instruction.<anonymous> (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:142:48)
    at safeNext (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:69:28)
    at complete (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:169:40)
    at /opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:182:29
    at /opt/Postman/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1140:9
    at /opt/Postman/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16
    at replenish (/opt/Postman/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1006:25)
    at /opt/Postman/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1016:9
    at _asyncMap (/opt/Postman/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1133:5)
    at /opt/Postman/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1219:16
    at /opt/Postman/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1046:16
    at Object.<anonymous> (/opt/Postman/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:240:20)
    at Object.<anonymous> (/opt/Postman/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:74:12)
```

Looks simular to https://github.com/postmanlabs/postman-app-support/issues/5354

**Comment by kamalaknn** [comment]
It looks like your installation is corrupt. This might happen sometimes when you try to update the app by extracting the newer version in the location as the older version without removing the older version.  This will merge the contents of both the packages leading to corrupted installations.

I suggest moving to an installation method that uses the supported auto update from Postman over manual installations.

I understand that it might not be feasible always. If you have to stick with a manual update flow, *please remove the existing installation directory before installing the new version*. Note that the data is stored in a different directory. Removing the installation directory does not remove your data.

Please let us know if that fixes this.

**Comment by RidgeA** [comment]
Yeah, my bad. 
Fresh install solved the issue.
