### ISSUE TITLE
Postman Native App not Working at all

### ISSUE THREAD

**Issue by AnuragAmbuj** [a85/POSTMan-Chrome-Extension#5538]
Postman not starting:

Uncaught Exception:
Error: Cannot find module './services/RuntimeExecutionService'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/home/anuragambuj/tool/Postman/app/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/anuragambuj/tool/Postman/app/resources/app/main.js:26:31)
    at Object.<anonymous> (/home/anuragambuj/tool/Postman/app/resources/app/main.js:549:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Object.<anonymous> (/home/anuragambuj/tool/Postman/app/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/home/anuragambuj/tool/Postman/app/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3

at console

Environment: Ubuntu 16.04

**To Reproduce**
1. Go to 'cd <PathToPostmanFolderAfterUnzipping>'
2. ./Postman (provide necessary permissions if necessary)

and the error occurs

**Expected behavior**
Postman app should open.

**App information (please complete the following information):**
 - App Type: Native App
- Version: 6.5.2
 - OS: Ubuntu 16.04

Version: Latest Release

**Comment by SamvelRaja** [comment]
@AnuragAmbuj Seems like https://github.com/postmanlabs/postman-app-support/issues/5385#issuecomment-430969435 issue?

Could you cross check this?

**Comment by SamvelRaja** [comment]
@AnuragAmbuj  Closing this for now. Kindly re-open this if you still faces the issue.
