### ISSUE TITLE
Unable to install Postman on Windows: System.IndexOutOfRangeException error

### ISSUE THREAD

**Issue by 397v1exuI0bT** [a85/POSTMan-Chrome-Extension#5968]

**Comment by 397v1exuI0bT** [comment]
2019-02-22 16:04:32> Program: Starting Squirrel Updater: --install .
2019-02-22 16:04:32> Program: Starting install, writing to C:\Users\AppData\Local\SquirrelTemp
2019-02-22 16:04:32> Program: About to install to: C:\Users\Postman
2019-02-22 16:04:32> Program: Install path C:\Users\Postman already exists, burning it to the ground
2019-02-22 16:04:32> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Squirrel.UnsafeUtility.<>c__DisplayClass0_0.<EnumerateProcesses>b__0(Int32 i)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Squirrel.UnsafeUtility.EnumerateProcesses()
   at Squirrel.UpdateManager.InstallHelperImpl.KillAllProcessesBelongingToPackage()
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Squirrel.UnsafeUtility.<>c__DisplayClass0_0.<EnumerateProcesses>b__0(Int32 i)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Squirrel.UnsafeUtility.EnumerateProcesses()
   at Squirrel.UpdateManager.InstallHelperImpl.KillAllProcessesBelongingToPackage()
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

**Comment by numaanashraf** [comment]
@mayankag02 Thanks for reporting this. This seems to be caused by an underlying installation/updation framework we are using. We'll update here when we have a fix from upstream.

Platform: win64
App version: 6.7.3

Related issues on Squirrel:
https://github.com/Squirrel/Squirrel.Windows/issues/731
https://github.com/Squirrel/Squirrel.Windows/issues/1438

**Comment by 397v1exuI0bT** [comment]
Thank you.

**Comment by UnKnoWn-Consortium** [comment]
@mayankag02 I have encountered the exact same issue with the exact same log output. I was able to get rid of it by manually removing the folder as shown in the last line before the "Unhandled exception", i.e. `C:\Users\Postman` in your case. I hope it works for you too.

**Comment by harryi3t** [comment]
@mayankag02 Are you still facing the issue and are able to reproduce it?
We have updated the underlying installation/updation framework we use and have released it as part of our canary releases.
You can get our canary build from https://www.getpostman.com/downloads/canary

**Comment by harryi3t** [comment]
Closing the ticket due to inactivity. If the issue still exists on the latest version of Postman (v7.3.4) please let us know.
