### ISSUE TITLE
Postman v 6.7.4 can't be installed on macOS 10.14.3

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#6029]
## App Details:
Installer for version 6.7.4

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```
**Log (from ~/Library/Application Support/Postman/logs/main.log)**

[35941][1551918346698][main][info]["Booting Postman 6.7.4, darwin-18.2.0 on x64"]
[35941][1551918346703][main][info]["EventBus\\x7einitialize - Success"]
[35941][1551918346706][main][info]["UpdateHandler\\x7einit - Success"]
[35941][1551918346707][main][info]["RuntimeExecutionService\\x7einitialized: Success"]
[35941][1551918346709][main][info]["ProtocolHandler\\x7einit - Success with status: true]"]
[35941][1551918346723][main][info]["PluginHost - Booted for 1th time"]
[35941][1551918346770][main][info]["Main\\x7epromptMoveToApplicationsFolder - Postman is not in applications folder, showing a prompt to move it there"]
[35941][1551918387408][main][info]["Qitting app"]
[35941][1551918387409][main][error]["WindowManager\\x7egetSharedWindow: Shared window is not available"]
[35941][1551918387416][main][info][null]
[35941][1551918387438][main][error][{"name":"Error","message":"PluginHost exited with code null","stack":"Error: PluginHost exited with code null\n    at PluginHost.onHostExit (/private/var/folders/ry/zxxl4td54mn6931tldq2kxqh0000gn/T/AppTranslocation/3B763DED-F7D5-4E59-9CBD-DEF046E00E23/d/Postman-1.app/Contents/Resources/app/node_modules/@postman/app-plugins-host/index.js:100:21)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)"}]
[35941][1551918387439][main][error][{"name":"Error","message":"Trying to boot plugin host for 2th time","stack":"Error: Trying to boot plugin host for 2th time\n    at PluginHost.bootHost (/private/var/folders/ry/zxxl4td54mn6931tldq2kxqh0000gn/T/AppTranslocation/3B763DED-F7D5-4E59-9CBD-DEF046E00E23/d/Postman-1.app/Contents/Resources/app/node_modules/@postman/app-plugins-host/index.js:23:23)\n    at PluginHost.onHostExit (/private/var/folders/ry/zxxl4td54mn6931tldq2kxqh0000gn/T/AppTranslocation/3B763DED-F7D5-4E59-9CBD-DEF046E00E23/d/Postman-1.app/Contents/Resources/app/node_modules/@postman/app-plugins-host/index.js:101:10)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)"}]
[35988][1551918481656][main][info]["Booting Postman 6.7.4, darwin-18.2.0 on x64"]
[35988][1551918481673][main][info]["EventBus\\x7einitialize - Success"]
[35988][1551918481683][main][info]["UpdateHandler\\x7einit - Success"]
[35988][1551918481689][main][info]["RuntimeExecutionService\\x7einitialized: Success"]
[35988][1551918481693][main][info]["ProtocolHandler\\x7einit - Success with status: true]"]
[35988][1551918481720][main][info]["PluginHost - Booted for 1th time"]
[35988][1551918481823][main][info]["Main\\x7epromptMoveToApplicationsFolder - Postman is not in applications folder, showing a prompt to move it there"]
[35988][1551918517071][main][info]["Qitting app"]
[35988][1551918517072][main][error]["WindowManager\\x7egetSharedWindow: Shared window is not available"]
[35988][1551918517079][main][info][null]
[35988][1551918517109][main][error][{"name":"Error","message":"PluginHost exited with code null","stack":"Error: PluginHost exited with code null\n    at PluginHost.onHostExit (/private/var/folders/ry/zxxl4td54mn6931tldq2kxqh0000gn/T/AppTranslocation/BE5E28F2-EB71-4A7D-845D-948A450A4681/d/Postman.app/Contents/Resources/app/node_modules/@postman/app-plugins-host/index.js:100:21)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)"}]
[35988][1551918517112][main][error][{"name":"Error","message":"Trying to boot plugin host for 2th time","stack":"Error: Trying to boot plugin host for 2th time\n    at PluginHost.bootHost (/private/var/folders/ry/zxxl4td54mn6931tldq2kxqh0000gn/T/AppTranslocation/BE5E28F2-EB71-4A7D-845D-948A450A4681/d/Postman.app/Contents/Resources/app/node_modules/@postman/app-plugins-host/index.js:23:23)\n    at PluginHost.onHostExit (/private/var/folders/ry/zxxl4td54mn6931tldq2kxqh0000gn/T/AppTranslocation/BE5E28F2-EB71-4A7D-845D-948A450A4681/d/Postman.app/Contents/Resources/app/node_modules/@postman/app-plugins-host/index.js:101:10)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)"}]

**Second Log (from ~/Library/Application Support/Postman/logs/pluginHost.log)**

[35941][1551918347392][pluginHost][info]["Booting Plugin Host for Postman 6.7.4, darwin-18.2.0 on x64"]
[35941][1551918347399][pluginHost][info]["PluginsHost - Host: Booted"]
[35941][1551918347404][pluginHost][info]["not exist",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/Users/behnam/Library/Application Support/Postman/plugins/postman.openApi/version.json","name":"Error","message":"ENOENT: no such file or directory, open '/Users/behnam/Library/Application Support/Postman/plugins/postman.openApi/version.json'","stack":"Error: ENOENT: no such file or directory, open '/Users/behnam/Library/Application Support/Postman/plugins/postman.openApi/version.json'"}]
[35941][1551918347405][pluginHost][info]["PluginInstallationService-installOrUpdatePlugins Installing plugin",{"version":"0.0.9","pluginId":"postman.openApi","isInstalled":false}]
[35941][1551918347405][pluginHost][info]["PluginInstallationService-installFromLocal",{"pluginZipPath":"/private/var/folders/ry/zxxl4td54mn6931tldq2kxqh0000gn/T/AppTranslocation/3B763DED-F7D5-4E59-9CBD-DEF046E00E23/d/Postman-1.app/Contents/Resources/app/plugins/postman.openApi.zip","pluginsDir":"/Users/behnam/Library/Application Support/Postman/plugins","currVersionDirPath":"/Users/behnam/Library/Application Support/Postman/plugins/postman.openApi/0.0.9","tempDir":"/var/folders/ry/zxxl4td54mn6931tldq2kxqh0000gn/T/","result":{"pluginId":"postman.openApi","version":"0.0.9","status":null}}]
[35941][1551918347405][pluginHost][info]["PluginInstallationService-installFromLocal extracting"]
[35941][1551918347584][pluginHost][info]["PluginInstallationService-installFromLocal extracted",{"pluginId":"postman.openApi","version":"0.0.9","status":null}]
[35941][1551918347585][pluginHost][info]["PluginInstallationService-installFromLocal moving",{"extractedPluginPath":"/var/folders/ry/zxxl4td54mn6931tldq2kxqh0000gn/T/postman.openApi"}]
[35941][1551918347587][pluginHost][info]["PluginInstallationService-installFromLocal updating version.json","{\"latest\":\"0.0.9\"}"]
[35941][1551918347589][pluginHost][info]["PluginInstallationService-installFromLocal Completed installing plugin",{"pluginId":"postman.openApi","version":"0.0.9","status":"installed"}]
[35941][1551918347589][pluginHost][info]["PluginsHost: Synced all plugins",[{"pluginId":"postman.openApi","version":"0.0.9","status":"installed"}]]
[35988][1551918482664][pluginHost][info]["Booting Plugin Host for Postman 6.7.4, darwin-18.2.0 on x64"]
[35988][1551918482669][pluginHost][info]["PluginsHost - Host: Booted"]
[35988][1551918482676][pluginHost][info]["PluginInstallationService-_shouldReInstallPlugin",{"installedVersion":"0.0.9","currentVersion":"0.0.9"}]
[35988][1551918482676][pluginHost][info]["PluginsHost: Synced all plugins",[{"pluginId":"postman.openApi","version":"0.0.9","status":"skipped"}]]

**Comment by SamvelRaja** [comment]
@behnamoh 

Could you provide us the workflow you are following.

- We can see that you have been prompt to move postman to Applications 
- Could you provide us the information from there on?

This will help us in debugging the issue further down.

**Comment by numaanashraf** [comment]
Thank you for your issue! With only the details that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have more information for us that'll help us debug/triage this issue.

**Comment by stcalica** [comment]
Posting on behalf of user: 

I have a user who accidentally updated to v7 when migrating his settings. He re-downloaded v6 on a new computer, he’s not able to sync.
This is the issue he receives in his logs:

`[10068][1565620164508][pluginHost][info]["not exist",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/Users/XXXX/Library/Application Support/Postman/plugins/postman.openApi/version.json","name":"Error","message":"ENOENT: no such file or directory, open '/Users/charlesb/Library/Application Support/Postman/plugins/postman.openApi/version.json'","stack":"Error: ENOENT: no such file or directory, open '/Users/XXXX/Library/Application Support/Postman/plugins/postman.openApi/version.json'"}]`



`[10068][1565622268620][main][error][{"name":"Error","message":"PluginHost exited with code null","stack":"Error: PluginHost exited with code null\n    at PluginHost.onHostExit (/Applications/Postman.app/Contents/Resources/app/node_modules/@postman/app-plugins-host/index.js:100:21)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)"}]`

Postman App seems to not be able to find his version.jsonand returns with a null, I’m assuming because the call to his accounts may have change in the version.

**Comment by mdavis-xyz** [comment]
I'm getting the same problem.

# Steps to reproduce

1. Go to https://www.postman.com/downloads/
2. Click the top download button (currently version 7.18.0)
3. Double click the downloaded file
4. Optionally: Move it to the applications folder and open from there

# Versions

* Postman Version 7.18.0
* Mac OS Catalina 10.15.3

# Expected Results

Either the app opens, or an installer for the app opens

# Actual results

Error message popup saying:

> “Postman.app” can’t be opened because Apple cannot check it for malicious software.
> This software needs to be updated. Contact the developer for more information.
> Firefox downloaded this file today at 10:37 am from www.postman.com.

**Comment by gsakthinarayanan** [comment]
Happens to me as well. macOS Catalina v10.15.5. Postman Version 7.27.0
![Screen Shot 2020-06-26 at 3 11 30 PM](https://user-images.githubusercontent.com/60193318/85892697-6509d080-b7bf-11ea-8046-82a4109fd128.png)

**Comment by chaithanya1996** [comment]
> Happens to me as well. macOS Catalina v10.15.5. Postman Version 7.27.0
> ![Screen Shot 2020-06-26 at 3 11 30 PM](https://user-images.githubusercontent.com/60193318/85892697-6509d080-b7bf-11ea-8046-82a4109fd128.png)

Same issue Mac Pro 16

**Comment by BlueMona** [comment]
This is not a Postman issue but a Mac OS issue. Right click and force open and/or give the app permission through System Preferences when you see the error.

**Comment by chaithanya1996** [comment]
> This is not a Postman issue but a Mac OS issue. Right click and force open and/or give the app permission through System Preferences when you see the error.

I am new to Mac OS , This worked. Thanks

**Comment by mccannt** [comment]
This appears to be an OS-level issue and not a product issue. Closing this out. 
If there are further issues, please feel free to open an issue.

**Comment by devsgtech** [comment]
try this
`sudo spctl --master-disable`

**Comment by matt-canty-dragon** [comment]
I had more difficulty than I'm used to with Postman (7.33.1). I upgraded via Brew and I started getting this message. It also reappeared after clicking OK without taking any other actions.

None of the usuals worked:
* Right-click + Open
* Security & Privacy Controls

After `sudo spctl --master-disable` I would recommend `sudo spctl --master-enable`

MIght I suggest that there is something _about_ Postman which makes it susceptible to this kind of inconvenience?

**Comment by numaanashraf** [comment]
@matt-canty-dragon The brew distribution is not official and we do not recommend it as we cannot guarantee the stability and security of that package. The official package from https://www.postman.com/downloads is code-signed by Postman and can be installed without disabling any security controls on your macOS.

**Comment by matt-canty-dragon** [comment]
I had the same issue after trying the official download. I should have mentioned. Perhaps something else was going on.

**Comment by VaranauskasD** [comment]
Same issue macOS Catalina 10.15.7 Postman 8.2.2. Should this be shrugged off as 'macOS' issue? Can't find a simple fix, thus can't use the product.

**Comment by sparkbold** [comment]
Got same code-signed issue on macOS version 11.5.2
Postman downloaded version 8.11.1

Unfortunately, I can't use the workaround Right click and force open and/or give the app permission through System Preferences when you see the error. IT department disable this ability. 

Can the app be distributed on App Store or updated so it can work with macOS version 11.5.2?
Thanks.

**Comment by ghost** [comment]
Press `command` button while you open the app. It worked on my mac.

**Comment by giovannipds** [comment]
I just downloaded it again from https://www.postman.com/downloads/ and it worked, not sure what went wrong. This time it has asked if I wanted to open it and also suggested to move it to the Applications folder.

**Comment by itwrites** [comment]
this is clearly a way to push users to buy the web feature. dark practices.

**Comment by kw** [comment]
Downloaded 11.2.0 today, got this issue.

```sh
% spctl -a -vvv -t install Postman.app
Postman.app: rejected
source=Unnotarized Developer ID
origin=Developer ID Application: Postdot Technologies, Inc (H7H8Q7M5CK)
```

**Comment by didiervdb** [comment]
same here 
spctl -a -vvv -t install Postman.app
Postman.app: rejected
source=Unnotarized Developer ID
origin=Developer ID Application: Postdot Technologies, Inc (H7H8Q7M5CK)

**Comment by lambdaFunctions** [comment]
This worked for me:
- Download the Mac Apple Chip version on Postman
- Unzip it in the downloads folder
- Move the Postman icon to the documents folder manually
- Right click on the icon and choose "Open"
- Confirm the message that asks to move it to the application folder

I didn't do any previous configuration, just tried to download a few times and some steps in this thread. After doing what I described, it started worked.
