### ISSUE TITLE
Postman crashes with NTLM auth

### ISSUE THREAD

**Issue by steigerm** [a85/POSTMan-Chrome-Extension#6231]
**Describe the bug**
Postman crashes when sending a http PUT using JSON body and **NTLM Auth**
After clicking on Send the console displays two entries.
I can not read them because Postman vanishes shortly after click

main.log shows
[6220][1554385531808][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.","stack":"TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.\n    at Function.Buffer.from (buffer.js:179:11)

**To Reproduce**
1. Create a PUT request
2. Change Body to raw
3. Paste JSON data
4. Change Auth to NTLM (Beta) [no further data entered]
5. Send

If I check "Yes, disable retrying the request" -> Expected 401.2

If I fill userid and domain fields -> crash

**Expected behavior**
no crash

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version 7.0.7
 - OS: Windows 7 x64 (latest updates)

**Additional context**

complete main.log:
```
[6220][1554385279169][main][info]["Booting Postman 7.0.7, win32-6.1.7601 on x64"]
[6220][1554385279174][main][info]["EventBus~initialize - Success"]
[6220][1554385279182][main][info]["UpdateHandler~init - Success"]
[6220][1554385279184][main][info]["RuntimeExecutionService~initialized: Success"]
[6220][1554385279185][main][info]["ProtocolHandler~init - Success with status: true]"]
[6220][1554385279565][main][info]["PluginHost~bootHost: Booted - 1"]
[6220][1554385279818][main][info]["Bootstrap-models~bootstrap - Success"]
[6220][1554385284172][main][info]["Main~AppEvents - Received booted event for process shared"]
[6220][1554385288276][main][info]["Main~AppEvents - Received booted event for process console"]
[6220][1554385288357][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[6220][1554385288359][main][info]["Main~AppEvents - Received booted event for process requester"]
[6220][1554385531808][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.","stack":"TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.\n    at Function.Buffer.from (buffer.js:179:11)\n    at new Buffer (buffer.js:154:17)\n    at Object.createType3Message (C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\httpntlm\\ntlm.js:172:19)\n    at Object.post (C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\authorizer\\ntlm.js:140:44)\n    at Object.module.exports (C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\runner\\request-helpers-postsend.js:31:21)\n    at C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:241:31\n    at C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1135:9\n    at replenish (C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1011:17)\n    at C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1016:9\n    at _asyncMap (C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1133:5)\n    at C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1219:16\n    at C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:1046:16\n    at Object.<anonymous> (C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:240:20)\n    at Object.<anonymous> (C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:74:12)\n    at Object.applyEachSeries (C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\node_modules\\async\\dist\\async.js:245:23)\n    at C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\runner\\extensions\\http-request.command.js:182:31\n    at complete (C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:109:24)\n    at Request._callback (C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-runtime\\lib\\requester\\requester.js:178:13)\n    at Request.self.callback (C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-request\\request.js:247:22)\n    at emitTwo (events.js:125:13)\n    at Request.emit (events.js:213:7)\n    at Request.<anonymous> (C:\\Users\\e974050\\AppData\\Local\\Postman\\app-7.0.7\\resources\\app.asar\\node_modules\\postman-request\\request.js:1230:10)"}]
```

**Comment by steigerm** [comment]
Duplicate of #5768
