### ISSUE TITLE
request.size is not a function when sending any request

### ISSUE THREAD

**Issue by luisfrlb** [a85/POSTMan-Chrome-Extension#6345]
**Describe the bug**
When a request is made, regardless the method, the app crashes and the error "request.size is not a function" is thrown

**To Reproduce**
1. Update postman to version 7.0.9
2. Use or create a new request, any type of request, and press send the request
3. See error thrown

**Expected behavior**
The app should complete the request without error

**Screenshots**
![image](https://user-images.githubusercontent.com/13617319/56612278-2bdd3b80-65d1-11e9-8560-7156e87fde80.png)

![image](https://user-images.githubusercontent.com/13617319/56612329-53340880-65d1-11e9-8aa7-ee19113cfa7e.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.0.9
 - OS: linux-4.18.0-17-generic on x64

**Additional context**
Log:
`1556050103766 main info "Booting Postman 7.0.9, linux-4.18.0-17-generic on x64"
1556050103767 main info "EventBus~initialize - Success"
1556050103780 main info "UpdateHandler~init - Success"
1556050103783 main info "RuntimeExecutionService~initialized: Success"
1556050103787 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1556050103855 main info "ProtocolHandler~init - Success with status: false]"
1556050103867 main info "PluginHost~bootHost: Booted - 1"
1556050104184 main info "Bootstrap-models~bootstrap - Success"
1556050104377 pluginHost info "Booting Plugin Host for Postman 7.0.9, linux-4.18.0-17-generic on x64"
1556050104381 pluginHost info "PluginsHost: Booted"
1556050104387 pluginHost info "PluginInstallationService~_shouldReInstallPlugin",{"installedVersion":"0.0.10","currentVersion":"0.0.10"}
1556050104388 pluginHost info "PluginInstallationService~_shouldReInstallPlugin",{"installedVersion":"0.0.1","currentVersion":"0.0.1"}
1556050104389 pluginHost info "PluginsHost~installOrUpdatePlugins: Synced all plugins",[{"pluginId":"postman.openApi","version":"0.0.10","status":"skipped"},{"pluginId":"postman.sample","version":"0.0.1","status":"skipped"}]
1556050106542 main info "Main~AppEvents - Received booted event for process shared"
1556050108941 main info "UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}
1556050108943 main info "Main~AppEvents - Received booted event for process requester"
TypeError: request.size is not a function
    at Function.response (/opt/Postman/app/resources/app/services/RuntimeExecutionService.js:319:36)
    at PostmanCollectionRun.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:66:50)
    at PostmanCollectionRun.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:87:21)
    at apply (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:475:27)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9475:36
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:4887:15
    at Function.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9474:7)
    at apply (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:476:27)
    at Function.invokeMap (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:6569:16)
    at Instruction.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:145:48)
    at safeNext (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:68:28)
    at complete (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:171:40)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:184:29
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1140:9
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16
    at replenish (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1006:25)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1016:9
    at _asyncMap (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1133:5)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1219:16
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1046:16
    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:240:20)
    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:74:12)
1556050163617 main error "Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"request.size is not a function","stack":"TypeError: request.size is not a function\n    at Function.response (/opt/Postman/app/resources/app/services/RuntimeExecutionService.js:319:36)\n    at PostmanCollectionRun.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:66:50)\n    at PostmanCollectionRun.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:87:21)\n    at apply (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:475:27)\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9475:36\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:4887:15\n    at Function.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9474:7)\n    at apply (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:476:27)\n    at Function.invokeMap (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:6569:16)\n    at Instruction.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:145:48)\n    at safeNext (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:68:28)\n    at complete (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:171:40)\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:184:29\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1140:9\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16\n    at replenish (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1006:25)\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1016:9\n    at _asyncMap (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1133:5)\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1219:16\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1046:16\n    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:240:20)\n    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:74:12)"}
Main~handleUncaughtError - Uncaught errors TypeError: request.size is not a function
    at Function.response (/opt/Postman/app/resources/app/services/RuntimeExecutionService.js:319:36)
    at PostmanCollectionRun.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:66:50)
    at PostmanCollectionRun.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:87:21)
    at apply (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:475:27)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9475:36
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:4887:15
    at Function.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9474:7)
    at apply (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:476:27)
    at Function.invokeMap (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:6569:16)
    at Instruction.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:145:48)
    at safeNext (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:68:28)
    at complete (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:171:40)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:184:29
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1140:9
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16
    at replenish (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1006:25)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1016:9
    at _asyncMap (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1133:5)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1219:16
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1046:16
    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:240:20)
    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:74:12)
`

**Comment by shamasis** [comment]
How did you upgrade? Try doing a clean re-install.

**Comment by luisfrlb** [comment]
A clear re-install fix the issue, Thanks.


*Luis Fernando López Barrera*

**Comment by codenirvana** [comment]
@luisfrlb Thanks for the update.

We have seen similar issues on Linux after the upgrade.
Here's the post-mortem from previous issue thread: https://github.com/postmanlabs/postman-app-support/issues/5039#issuecomment-420258338
