### ISSUE TITLE
deepin(linux) v7.1.1 crash when send request

### ISSUE THREAD

**Issue by mokyle** [a85/POSTMan-Chrome-Extension#6579]
**Describe the bug**
i am use postman native client in deepin15.10.1.
yestoday was good.but today open postman, when send request, is crash . i restart postman 
more than once , it alway occur. Below is the command line log:
k-pc:~▶09:47:41 $▶/opt/Postman/Postman 
Not disabling GPU
(node:11301) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
Main~createDefaultWorkingDir - Default working dir creation already attempted
1558576080290 main info "Booting Postman 7.1.1, linux-4.15.0-29deepin-generic on x64"
1558576080291 main info "EventBus~initialize - Success"
1558576080311 main info "UpdateHandler~init - Success"
1558576080314 main info "RuntimeExecutionService~initialized: Success"
1558576080316 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1558576080336 main info "PluginHost~bootHost: Booted - 1"
1558576080482 main info "Bootstrap-models~bootstrap - Success"
1558576080812 pluginHost info "Booting Plugin Host for Postman 7.1.1, linux-4.15.0-29deepin-generic on x64"
1558576080816 pluginHost info "PluginsHost: Booted"
1558576080821 pluginHost info "PluginInstallationService~_shouldReInstallPlugin",{"installedVersion":"0.0.10","currentVersion":"0.0.10"}
1558576080821 pluginHost info "PluginInstallationService~_shouldReInstallPlugin",{"installedVersion":"0.0.1","currentVersion":"0.0.1"}
1558576080822 pluginHost info "PluginsHost~installOrUpdatePlugins: Synced all plugins",[{"pluginId":"postman.openApi","version":"0.0.10","status":"skipped"},{"pluginId":"postman.sample","version":"0.0.1","status":"skipped"}]
1558576082795 main info "Main~AppEvents - Received booted event for process shared"
1558576085744 main info "UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}
1558576085746 main info "Main~AppEvents - Received booted event for process requester"
TypeError: request.size is not a function
    at Function.response (/opt/Postman/app/resources/app/services/RuntimeExecutionService.js:352:36)
    at PostmanCollectionRun.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:66:50)
    at PostmanCollectionRun.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:87:21)
    at apply (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:475:27)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9475:36
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:4887:15
    at Function.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9474:7)
    at apply (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:476:27)
    at Function.invokeMap (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:6569:16)
    at Instruction.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:145:48)
    at safeNext (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:68:28)
    at complete (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:171:40)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:184:29
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1140:9
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16
    at replenish (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1006:25)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1016:9
    at _asyncMap (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1133:5)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1219:16
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1046:16
    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:240:20)
    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:74:12)
1558576092917 main error "Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"request.size is not a function","stack":"TypeError: request.size is not a function\n    at Function.response (/opt/Postman/app/resources/app/services/RuntimeExecutionService.js:352:36)\n    at PostmanCollectionRun.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:66:50)\n    at PostmanCollectionRun.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:87:21)\n    at apply (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:475:27)\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9475:36\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:4887:15\n    at Function.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9474:7)\n    at apply (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:476:27)\n    at Function.invokeMap (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:6569:16)\n    at Instruction.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:145:48)\n    at safeNext (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:68:28)\n    at complete (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:171:40)\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:184:29\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1140:9\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16\n    at replenish (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1006:25)\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1016:9\n    at _asyncMap (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1133:5)\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1219:16\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1046:16\n    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:240:20)\n    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:74:12)"}
Main~handleUncaughtError - Uncaught errors TypeError: request.size is not a function
    at Function.response (/opt/Postman/app/resources/app/services/RuntimeExecutionService.js:352:36)
    at PostmanCollectionRun.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:66:50)
    at PostmanCollectionRun.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:87:21)
    at apply (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:475:27)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9475:36
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:4887:15
    at Function.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9474:7)
    at apply (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:476:27)
    at Function.invokeMap (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:6569:16)
    at Instruction.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:145:48)
    at safeNext (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:68:28)
    at complete (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:171:40)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:184:29
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1140:9
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16
    at replenish (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1006:25)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1016:9
    at _asyncMap (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1133:5)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1219:16
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1046:16
    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:240:20)
    at Object.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:74:12)

**To Reproduce**
1. open postman
2. send any request 
3. wait a moment
4. is crash

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.1.1
 - OS: deepin 15.10.1(debian_version 9.0)

**Additional context**
Yesterday was good

**Comment by hindermyertim** [comment]
Same issue here. On Linux Mint 19.1

**Comment by shamasis** [comment]
Before deep diving, my first order of debugging would be to completely cleanup your Postman app directory and reinstall the app. I have a hunch that the way the app was updated has cause parts of its internal dependencies to remain stale. 

cc @numaanashraf is there any link / wiki we can send here as a reference?

**Comment by andreagubellini** [comment]
I'm running postman 7.0.7 on Deepin, got it from snap and works fine.

**Comment by hindermyertim** [comment]
Ya I tried reinstalling multiple times. Reinstalled from the website, snap, and mint's software manager. Same issue each time.

**Comment by hindermyertim** [comment]
After booting, he's my log. This time I installed from the 64 bit tar.gz from the website. Linux Mint 19.1

Not disabling GPU
(node:19120) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
Main~createDefaultWorkingDir - Default working dir creation already attempted
1558712146790 main info "Booting Postman 7.1.1, linux-4.15.0-50-generic on x64"
1558712146791 main info "EventBus~initialize - Success"
1558712146805 main info "UpdateHandler~init - Success"
1558712146814 main info "RuntimeExecutionService~initialized: Success"
1558712146818 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1558712146853 main info "PluginHost~bootHost: Booted - 1"
1558712147076 main info "Bootstrap-models~bootstrap - Success"
1558712147326 pluginHost info "Booting Plugin Host for Postman 7.1.1, linux-4.15.0-50-generic on x64"
1558712147332 pluginHost info "PluginsHost: Booted"
1558712147337 pluginHost info "PluginInstallationService~_shouldReInstallPlugin",{"installedVersion":"0.0.10","currentVersion":"0.0.10"}
1558712147338 pluginHost info "PluginInstallationService~_shouldReInstallPlugin",{"installedVersion":"0.0.1","currentVersion":"0.0.1"}
1558712147338 pluginHost info "PluginsHost~installOrUpdatePlugins: Synced all plugins",[{"pluginId":"postman.openApi","version":"0.0.10","status":"skipped"},{"pluginId":"postman.sample","version":"0.0.1","status":"skipped"}]
1558712149014 main info "Main~AppEvents - Received booted event for process shared"
1558712151337 main info "UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}
1558712151338 main info "Main~AppEvents - Received booted event for process requester"
TypeError: Cannot read property 'toLowerCase' of null
    at Object.getRequestOptions (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/core.js:304:59)
    at Requester.request (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester.js:178:31)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:117:37
    at Function.create (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester.js:336:16)
    at RequesterPool.create (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester-pool.js:60:22)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:105:32
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1140:9
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16
    at replenish (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:995:17)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:969:16
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1137:13
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/request-helpers-presend.js:315:20
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16
    at next (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:5329:29)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:969:16
    at Function.session.resolveProxy (/opt/Postman/app/resources/app/utils/getSystemProxy.js:32:16)
1558712173442 main error "Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"Cannot read property 'toLowerCase' of null","stack":"TypeError: Cannot read property 'toLowerCase' of null\n    at Object.getRequestOptions (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/core.js:304:59)\n    at Requester.request (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester.js:178:31)\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:117:37\n    at Function.create (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester.js:336:16)\n    at RequesterPool.create (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester-pool.js:60:22)\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:105:32\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1140:9\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16\n    at replenish (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1006:25)\n    at iterateeCallback (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:995:17)\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:969:16\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1137:13\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/request-helpers-presend.js:315:20\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16\n    at next (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:5329:29)\n    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:969:16\n    at Function.session.resolveProxy (/opt/Postman/app/resources/app/utils/getSystemProxy.js:32:16)"}
Main~handleUncaughtError - Uncaught errors TypeError: Cannot read property 'toLowerCase' of null
    at Object.getRequestOptions (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/core.js:304:59)
    at Requester.request (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester.js:178:31)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:117:37
    at Function.create (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester.js:336:16)
    at RequesterPool.create (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester-pool.js:60:22)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:105:32
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1140:9
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16
    at replenish (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:995:17)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:969:16
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:1137:13
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/request-helpers-presend.js:315:20
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:473:16
    at next (/opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:5329:29)
    at /opt/Postman/app/resources/app/node_modules/postman-runtime/node_modules/async/dist/async.js:969:16
    at Function.session.resolveProxy (/opt/Postman/app/resources/app/utils/getSystemProxy.js:32:16)

**Comment by shamasis** [comment]
Ok. The two stack traces aren’t from same error. The first one can only arrive when during upgrading the app by copying newer app on older version, resulting in file integrity failure. This is easily resolved by deleting Postman app completely and then fresh installing. This usually does not happen if app’s own self updater is used to update app. 

Interestingly, the second error is from a different case that we are already tracking https://github.com/postmanlabs/postman-app-support/issues/6533 and have already fixed. Waiting to release it within the week. 

Can you check if your issue is actually fixed when you reinstalled and that by luck you caught on to a case where url has invalid characters?

@codenirvana @saswatds - can we have a third and fourth pair of eyes on this? 😛

**Comment by mokyle** [comment]
Yes. I did overwrite the old application directory directly with the new application. So, manually updating it by deleting the old directory before unzipping and installing it is no problem.
