### ISSUE TITLE
Postman-linux-x64-7.1.1 Error: Cannot find module 'circular-json'

### ISSUE THREAD

**Issue by rmoskal** [a85/POSTMan-Chrome-Extension#6647]
**Describe the bug**
After downloading and unpacking Postman-linux-x64-7.1.1.tar.gz on Fedora 30. I try to run ./Postman from the app directory with the following results:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'circular-json'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/home/rob/dev_support/Postman/app/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/rob/dev_support/Postman/app/resources/app/main.js:7:20)
    at Object.<anonymous> (/home/rob/dev_support/Postman/app/resources/app/main.js:685:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Expected behavior**
I expected the app to start!

**Environment**

Fedora 30, native app.

**Comment by shamasis** [comment]
Looks like the app was corrupted during an upgrade process. Can you do a fresh install?

**Comment by Huge** [comment]
I have experienced the same with the https://dl.pstmn.io/download/latest/linux64 v7.2.2, and re-download & extraction solved that. Thanks!

**Comment by harryi3t** [comment]
@rmoskal It looks like your installation is corrupt. Might be related to https://github.com/postmanlabs/postman-app-support/issues/5385 and https://github.com/postmanlabs/postman-app-support/issues/5039#issuecomment-420258338

This might happen sometimes when you try to update the app by extracting the newer version in the location as the older version without removing the older version. This will merge the contents of both the packages leading to corrupted installations.

I suggest moving to an installation method that uses the supported auto update from Postman over manual installations.

I understand that it might not be feasible always. If you have to stick with a manual update flow, *please remove the existing installation directory before installing the new version*. Note that the data is stored in a different directory. Removing the installation directory does not remove your data.

Please let us know if that fixes this.

**Comment by harryi3t** [comment]
Closing the ticket due to inactivity. If the issue still exists please let us know.

**Comment by woodspring** [comment]
CentOS 8.3.211 get the same issue. Postname version : Postman-linux-x64-7.36.1.tar.gz
Can't start Postman :+1: A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'circular-json'
Require stack:
- /opt/postman/Postman/app/resources/app/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7729:16)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/opt/postman/Postman/app/resources/app/main.js:7:20)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
