### ISSUE TITLE
Latest Postman crashed, reporting URL malformed

### ISSUE THREAD

**Issue by physicsLoveJava** [a85/POSTMan-Chrome-Extension#7268]
When I update the app to the latest version, I don't know what a url decode error means. It is just a simple get request: http://xxx.com/solution/getFreeWordList.html. Below is the stack trace.
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Function.ensureEncoded (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/util.js:62:35)
    at PostmanCookie.update (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/collection/cookie.js:205:38)
    at new PostmanCookie (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/collection/cookie.js:115:25)
    at toPostmanCookie (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester.js:51:16)
    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester.js:389:38
    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:13806:16
    at arrayEach (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:516:11)
    at Function.transform (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:13805:43)
    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester.js:388:37
    at /Applications/Postman.app/Contents/Resources/app/node_modules/tough-cookie/lib/cookie.js:1110:5
    at forEachWithCallback (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:674:7)
    at next (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:82:16)
    at _cache (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:668:9)
    at persistentStore.get (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:466:7)
    at Function.store.get (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:260:7)
1567671582621 main error "Main~handleUncaughtError - Uncaught errors",{"name":"URIError","message":"URI malformed","stack":"URIError: URI malformed\n    at decodeURIComponent (<anonymous>)\n    at Function.ensureEncoded (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/util.js:62:35)\n    at PostmanCookie.update (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/collection/cookie.js:205:38)\n    at new PostmanCookie (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/collection/cookie.js:115:25)\n    at toPostmanCookie (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester.js:51:16)\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester.js:389:38\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:13806:16\n    at arrayEach (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:516:11)\n    at Function.transform (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:13805:43)\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester.js:388:37\n    at /Applications/Postman.app/Contents/Resources/app/node_modules/tough-cookie/lib/cookie.js:1110:5\n    at forEachWithCallback (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:674:7)\n    at next (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:82:16)\n    at _cache (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:668:9)\n    at persistentStore.get (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:466:7)\n    at Function.store.get (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:260:7)"}
Main~handleUncaughtError - Uncaught errors URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Function.ensureEncoded (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/util.js:62:35)
    at PostmanCookie.update (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/collection/cookie.js:205:38)
    at new PostmanCookie (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-collection/lib/collection/cookie.js:115:25)
    at toPostmanCookie (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester.js:51:16)
    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester.js:389:38
    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:13806:16
    at arrayEach (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:516:11)
    at Function.transform (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:13805:43)
    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/requester/requester.js:388:37
    at /Applications/Postman.app/Contents/Resources/app/node_modules/tough-cookie/lib/cookie.js:1110:5
    at forEachWithCallback (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:674:7)
    at next (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:82:16)
    at _cache (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:668:9)
    at persistentStore.get (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:466:7)
    at Function.store.get (/Applications/Postman.app/Contents/Resources/app/services/CookieStore.js:260:7)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...24 completed.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS Mojave 10.14.6]
Version 7.6.0
OS X 18.7.0 / x64
**Additional context**

**Comment by codenirvana** [comment]
@physicsLoveJava Can you share more detail about the request?
Request URL (is it a [Punycode](https://en.wikipedia.org/wiki/Punycode) hostname?), Request and Response headers, etc.?

**Comment by codenirvana** [comment]
@physicsLoveJava Thanks for reporting this issue.
It's now fixed in the latest version of the Postman App (v7.7.2).
