### ISSUE TITLE
App crashes when trying to open any dialog

### ISSUE THREAD

**Issue by baztian** [a85/POSTMan-Chrome-Extension#7544]
**Describe the bug**
For happens the same as in #7515. But additionally the app crashes when I run "new" or any other dialog.

**To Reproduce**
1. Go to 'new'

**Expected behavior**
It should just work as documented.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.9.0 and 7.10.0
 - OS: Linux 64 bit

**Additional context**
Console output:

    TypeError: Cannot read property '0' of undefined
        at Object.handleMenuAction (/home/me/Postman7.10.0/app/resources/app/services/menuManager.js:502:114)
        at click (/home/me/Postman7.10.0/app/resources/app/services/menuManager.js:228:78)
        at MenuItem.click (/home/me/Postman7.10.0/app/resources/electron.asar/browser/api/menu-item.js:56:9)
        at Function.executeCommand (/home/me/Postman7.10.0/app/resources/electron.asar/browser/api/menu.js:31:13)
    1572080734662 main error "Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"Cannot read property '0' of undefined","stack":"TypeError: Cannot read property '0' of undefined\n    at Object.handleMenuAction (/home/me/Postman7.10.0/app/resources/app/services/menuManager.js:502:114)\n    at click (/home/me/Postman7.10.0/app/resources/app/services/menuManager.js:228:78)\n    at MenuItem.click (/home/me/Postman7.10.0/app/resources/electron.asar/browser/api/menu-item.js:56:9)\n    at Function.executeCommand (/home/me/Postman7.10.0/app/resources/electron.asar/browser/api/menu.js:31:13)"}
    Main~handleUncaughtError - Uncaught errors TypeError: Cannot read property '0' of undefined
        at Object.handleMenuAction (/home/me/Postman7.10.0/app/resources/app/services/menuManager.js:502:114)
        at click (/home/me/Postman7.10.0/app/resources/app/services/menuManager.js:228:78)
        at MenuItem.click (/home/me/Postman7.10.0/app/resources/electron.asar/browser/api/menu-item.js:56:9)
        at Function.executeCommand (/home/me/Postman7.10.0/app/resources/electron.asar/browser/api/menu.js:31:13)

**Comment by harryi3t** [comment]
@baztian That you for providing the additional information on the bug.
I am closing this in favour of https://github.com/postmanlabs/postman-app-support/issues/7515
Will be adding this additional information to the original bug ticket.
