### ISSUE TITLE
Unable to Merge changes from forked Collection back to parent

### ISSUE THREAD

**Issue by markashton** [a85/POSTMan-Chrome-Extension#7564]
**Describe the bug**
Using a collection that has been forked from a Team workspace, and has changes that should be merged back, selecting "Merge Changes" takes me to the Postman website but the page just sits with a spinner and an uncaught exception shown in the developer console.

**To Reproduce**
Steps to reproduce the behavior (on my forked collection, YMMV) :
1. Go to 'Forked collection ... menu'
2. Click on 'Merge Changes'
3. Website opens, open the developer console

**Expected behavior**
After website opens I am presented with the option to Pull any changes (if appropriate) and then Merge my changes.

**App information:**
 - App Type [Native App + Chrome browser]
 - Postman Version [7.10.0]
 - OS: [Windows 10]

**Additional context**
Console error log:
app.0200e81aca6e55a00fee.js:10 uncaught at fetchCollectionDiff TypeError: c.find is not a function
    at https://static.postman.co/js/app.0200e81aca6e55a00fee.js:21:155150
    at Array.forEach (<anonymous>)
    at ItemDiff.parseScripts (https://static.postman.co/js/app.0200e81aca6e55a00fee.js:21:155075)
    at https://static.postman.co/js/app.0200e81aca6e55a00fee.js:21:158017
    at Array.reduce (<anonymous>)
    at ItemDiff.getPropertyWiseDiff (https://static.postman.co/js/app.0200e81aca6e55a00fee.js:21:157032)
    at pmDiff (https://static.postman.co/js/app.0200e81aca6e55a00fee.js:21:159435)
    at extractDiff (https://static.postman.co/js/app.0200e81aca6e55a00fee.js:10:364127)
    at https://static.postman.co/js/app.0200e81aca6e55a00fee.js:10:385290
    at Array.forEach (<anonymous>)
    at https://static.postman.co/js/app.0200e81aca6e55a00fee.js:10:385228
    at Array.forEach (<anonymous>)
    at parseCollectionDiff (https://static.postman.co/js/app.0200e81aca6e55a00fee.js:10:385021)
    at collectionDiffReducers (https://static.postman.co/js/app.0200e81aca6e55a00fee.js:10:385734)
    at combination (https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:7:42537)
    at combination (https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:7:42537)
    at dispatch (https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:7:40229)
    at https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:7:57858
    at https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:1:85790
    at dispatch (https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:7:43908)
    at https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:7:51457
    at https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:1:80424
    at exec (https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:27:67661)
    at flush (https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:27:67852)
    at asap (https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:27:67725)
    at runPutEffect (https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:1:80382)
    at runEffect (https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:1:80522)
    at next (https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:1:78919)
    at currCb (https://static.postman.co/js/vendor.0eae139bc5ab0c66b60c.chunk.js:1:79722)
(anonymous) @ app.0200e81aca6e55a00fee.js:10

**Comment by Ghusar** [comment]
@markashton Thanks for reporting this issue. Until we triage and fix this from our end. Can you try updating the script (both pre-request and tests) of parent collection as well (empty string would be fine)? Which should unblock you for the merge

**Comment by markashton** [comment]
Thanks for the suggestion @Ghusar, but updating the parent collection pre-request and test scripts did not allow a merge to take place. The same error appears in the browser console log.

**Comment by Ghusar** [comment]
@markashton We will soon push out the fix for this issue, I will keep the thread updated when the fix goes out in production.

**Comment by Ghusar** [comment]
@markashton We have pushed the fix for this. Can you verify if it's working?

**Comment by markashton** [comment]
Hi Ghusar ... I can confirm I have now been able to merge my fork back to the parent collection. Thanks!
