### ISSUE TITLE
Can't launch Postman from terminal in Ubuntu 19.04

### ISSUE THREAD

**Issue by sithu-ab** [a85/POSTMan-Chrome-Extension#7587]
I'm using Ubuntu 19.04. I downloaded Postman from https://www.getpostman.com/downloads/ and extracted it. But I can't execute it from terminal and got Javascript error. Any idea?

    ab-ubuntu@sithu:/opt/Postman$ ./Postman
    A JavaScript error occurred in the main process
    Uncaught Exception:
    Error: Cannot find module 'circular-json'
        at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
        at Function.Module._resolveFilename (/opt/Postman/app/resources/electron.asar/common/reset-search-paths.js:35:12)
        at Function.Module._load (internal/modules/cjs/loader.js:528:25)
        at Module.require (internal/modules/cjs/loader.js:658:17)
        at require (internal/modules/cjs/helpers.js:20:18)
        at Object.<anonymous> (/opt/Postman/app/resources/app/main.js:7:20)
        at Object.<anonymous> (/opt/Postman/app/resources/app/main.js:733:3)
        at Module._compile (internal/modules/cjs/loader.js:711:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
        at Module.load (internal/modules/cjs/loader.js:620:32)

**Comment by kamalaknn** [comment]
Hey @sithu-ab 

Thanks for reporting this issue. Can you give us some information on how you installed the latest version of Postman? 

Did you have a previous installation of Postman? If you extracted the new version over the existing installation the contents of the two versions might get merged leading to unexpected behaviors.

You can try deleting the current installation of the App and extract the new version.

**Note that the application data is stored outside of the source and will not be affected if you delete the source.**

**Comment by kamalaknn** [comment]
This looks very similar to what you would see when extracting the new version over the old installation directory. You can find more details about it on the previous conversations

https://github.com/postmanlabs/postman-app-support/issues/6647
https://github.com/postmanlabs/postman-app-support/issues/5039#issuecomment-420258338

I'm closing this issue for now. Please let us know if you are seeing issues even after doing a clean install.
