### ISSUE TITLE
Interceptor never connects for Postman installed via Snap

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7607]
**Describe the bug**
Interceptor always shows up as Disconnected on Ubuntu Linux, when Postman is installed via Snap.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Postman using [snap](https://snapcraft.io/) on Ubuntu Linux.
2. Install interceptor binary
3. Install chrome interceptor extensions
4. Enable capture in chrome extension
5. Check Postman app - Interceptor always shows up as disconnected.

**Expected behaviour**
Interceptor should connect from Postman installed via snap as well.

**Screenshots**
Postman DevTools Console shows following:
<img width="267" alt="Screen Shot 2019-11-06 at 10 03 53 AM" src="https://user-images.githubusercontent.com/21366/68445482-e9164480-023e-11ea-8b43-c41aef79ebc2.png">

**This logs snippet piqued my interest**
May be related
```
[3957][1571690644301][main][error][{"name":"Error","message":"PluginHost exited with code 127","stack":"Error: PluginHost exited with code 127\n    at PluginHost.onHostExit (/snap/postman/93/usr/share/Postman/resources/app/node_modules/@postman/app-plugins-host/index.js:100:21)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)"}]
```
**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : 7.10.0
 - OS: Ubuntu 18.04.3 LTS

**Additional context**
Logged by Postman on behalf of a user.
Logs and other details provided internally.

**Comment by mickeysden** [comment]
Any update on this? I am facing the same issue

**Comment by marekmueller** [comment]
+1

**Comment by krasimirkostadinow** [comment]
Same issue here, nativeserver binary is running, but the interceptor is not able to connect.

**Comment by fadykstas** [comment]
+1

**Comment by carlos-garcia** [comment]
+1.. getting back to downloaded version

**Comment by fcalzolai** [comment]
+1

**Comment by kevinpark1217** [comment]
+1

**Comment by bolex222** [comment]
+1, Has anyone tried the downloadable version? (on postman website)

**Comment by bolex222** [comment]
update: snap version of postman don't work you should use the downloadable package on their web site, it work!   https://www.postman.com/downloads/
hope it could help you.

**Comment by mccannt** [comment]
Just following up on this issue. 
We currently have a request in with Snap to help address this issue. 

For now, we ask you to download the app from our [website](https://www.postman.com/downloads/)
We will update when this is resolved.

**Comment by hauzlife** [comment]
+1

**Comment by jakubreron** [comment]
+1

**Comment by sviatoslav-bordovski** [comment]
Anyone?

**Comment by loscil06** [comment]
It's 2022, a war is currently being waged and still this error hasn't been fixed
