### ISSUE TITLE
Error on starting native app

### ISSUE THREAD

**Issue by AndreMaz** [a85/POSTMan-Chrome-Extension#7617]
**Describe the bug**
After updating to latest version (7.11.0) of the app I can't open it. I'm getting a `Could not open Postman` error. Made a clean download to see if it helps but it didn't.

**Screenshots**
![image](https://user-images.githubusercontent.com/9802754/68530880-6788ea00-0304-11ea-80de-d552a681171e.png)

**Logs**
Trying to start the app from bash I get the following log:
```
Not disabling GPU
Main~createDefaultWorkingDir - Default working dir creation already attempted
1573312577967 main info "Booting Postman 7.11.0, linux-4.15.0-65-generic on x64"
1573312577967 main info "EventBus~initialize - Success"
1573312577974 main info "UpdateHandler~init - Success"
1573312577976 main info "RuntimeExecutionService~initialized: Success"
1573312577977 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1573312578072 main info "Bootstrap-models~bootstrap - Success"
1573312578320 main info "window-manager~newSharedWindow: Shell loaded"
1573312579449 main info "Main~AppEvents - Received booted event for process shared"
1573312579452 main error "Main~AppEvents - Shared window boot failed",{"_e":{"message":"","name":"Error","stack":"Error\n    at getErrorWithStack (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152308:12)\n    at new DexieError (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152437:19)\n    at mapError (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152467:14)\n    at handleRejection (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152951:14)\n    at IDBOpenDBRequest.<anonymous> (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:156158:9)\n    at IDBOpenDBRequest.<anonymous> (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:153164:23)"},"_stack":"VersionError: The requested version (40) is less than the existing version (120).\n    at mapError (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152467:14)\n    at handleRejection (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152951:14)\n    at IDBOpenDBRequest.<anonymous> (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:156158:9)\n    at IDBOpenDBRequest.<anonymous> (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:153164:23)","inner":{"message":"The requested version (40) is less than the existing version (120).","name":"VersionError"},"message":"The requested version (40) is less than the existing version (120).","name":"VersionError","stack":"VersionError: The requested version (40) is less than the existing version (120).\n    at mapError (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152467:14)\n    at handleRejection (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152951:14)\n    at IDBOpenDBRequest.<anonymous> (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:156158:9)\n    at IDBOpenDBRequest.<anonymous> (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:153164:23)"}
```
Judging by the error it's something in `Postman/app/resources/app/js/vendor-shared.js`:
```json
{
  "_e": {
    "message": "",
    "name": "Error",
    "stack": "Error\n    at getErrorWithStack (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152308:12)\n    at new DexieError (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152437:19)\n    at mapError (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152467:14)\n    at handleRejection (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152951:14)\n    at IDBOpenDBRequest.<anonymous> (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:156158:9)\n    at IDBOpenDBRequest.<anonymous> (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:153164:23)"
  },
  "_stack": "VersionError: The requested version (40) is less than the existing version (120).\n    at mapError (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152467:14)\n    at handleRejection (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152951:14)\n    at IDBOpenDBRequest.<anonymous> (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:156158:9)\n    at IDBOpenDBRequest.<anonymous> (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:153164:23)",
  "inner": {
    "message": "The requested version (40) is less than the existing version (120).",
    "name": "VersionError"
  },
  "message": "The requested version (40) is less than the existing version (120).",
  "name": "VersionError",
  "stack": "VersionError: The requested version (40) is less than the existing version (120).\n    at mapError (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152467:14)\n    at handleRejection (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:152951:14)\n    at IDBOpenDBRequest.<anonymous> (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:156158:9)\n    at IDBOpenDBRequest.<anonymous> (file:///home/user/Postman/app/resources/app/js/vendor-shared.js:153164:23)"
}
```

**App information:**
 - App Type:Native App
 - Postman Version: 7.11.0
 - OS: Kubuntu 18.04.3 LTS

**Comment by cyrielle-hada** [comment]
@AndreMaz clearing the local files for your Postman installation generally resolves this issue. You can find full instructions for doing so in [this article](https://support.getpostman.com/hc/en-us/articles/360025359014). If the issue persists, feel free to open a ticket from [this page](https://www.getpostman.com/support).

**Comment by AndreMaz** [comment]
@cyrielle-hada thanks :smile:  It solved the issue. 
It would be nice if you could add a link to this article in the `Could not open Postman` pop-up

**Comment by kamalaknn** [comment]
@AndreMaz I'm glad the workaround unblocked you. We are tracking the root cause of this issue in #5373.
