### ISSUE TITLE
Could open Postman, please contact help@getpostman.com

### ISSUE THREAD

**Issue by KevUKHD** [a85/POSTMan-Chrome-Extension#7746]
OS: Windows 10
State: Fresh install of Postman
Error Message: "Could not open Postman, please contact help@getpostman.com"
After that the Postman Process does not stop running and needs to be terminated with Task Manager

**To Reproduce**
1. Launch Postman
2. See Error Message

**Expected behavior**
Launching Postman Application.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information):**
 - Postman-win64-7.11.0
 - OS: Windows 10.0.17763 Build 17763

![PostManError](https://user-images.githubusercontent.com/54797948/70212389-78782000-1737-11ea-899b-7140c4da5f2d.PNG)

**Comment by cyrielle-hada** [comment]
@KevUKHD Removing your local data _should_ fix the issue. You can find the full instructions in this article - https://support.getpostman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-

**Comment by KevUKHD** [comment]
Solved the Issue but only temporary. 
Got the same Problem only a few hours later. 
Are there any insights on why this occurs?

**Comment by kamalaknn** [comment]
Hey @KevUKHD 

There could be a few reasons why this happens. most likely errors coming from storage engine. Could you send us the logs from `View -> Developer -> Show logs in Explorer`?

If you are not able to access the menu bar when this error happens you can find the logs in one of these directories 

C:\Users\<user>\AppData\Local\Postman and
C:\Users\<user>\AppData\Roaming\Postman

**Comment by kamalaknn** [comment]
Hey @KevUKHD 

Could you let us know if you're still seeing this issue?

**Comment by sunnydavis** [comment]
[19316][1583892288474][main][info]["Booting PostmanCanary 7.21.0-canary01, win32-10.0.18363 on x64"]
[19316][1583892288476][main][info]["EventBus~initialize - Success"]
[19316][1583892288489][main][warn]["CloudProxyManager~init: Error while reading proxy configuration from user data - ",{"errno":-4058,"code":"ENOENT","syscall":"open","path":"C:\\Users\\xforce\\AppData\\Roaming\\PostmanCanary\\Postman_Config\\proxy","name":"Error","message":"ENOENT: no such file or directory, open 'C:\\Users\\xforce\\AppData\\Roaming\\PostmanCanary\\Postman_Config\\proxy'","stack":"Error: ENOENT: no such file or directory, open 'C:\\Users\\xforce\\AppData\\Roaming\\PostmanCanary\\Postman_Config\\proxy'"}]
[19316][1583892288489][main][info]["CloudProxyManager~init - Success"]
[19316][1583892288492][main][info]["UpdateHandler~init - Success"]
[19316][1583892288493][main][info]["RuntimeExecutionService~initialized: Success"]
[19316][1583892288885][main][info]["Bootstrap-models~bootstrap - Success"]
[19316][1583892289671][main][info]["window-manager~newSharedWindow: Shell loaded"]
[19316][1583892291709][main][info]["Main~AppEvents - Received booted event for process shared"]
[19316][1583892291710][main][error]["Main~AppEvents - Shared window boot failed",{"_e":{"message":"","name":"Error","stack":"Error\n    at getErrorWithStack (file:///C:/Users/Sunny/AppData/Local/PostmanCanary/app-7.21.0-canary01/resources/app.asar/js/vendor-shared.js:180288:12)\n    at new DexieError (file:///C:/Users/Sunny/AppData/Local/PostmanCanary/app-7.21.0-canary01/resources/app.asar/js/vendor-shared.js:180417:19)\n    at mapError (file:///C:/Users/Sunny/AppData/Local/PostmanCanary/app-7.21.0-canary01/resources/app.asar/js/vendor-shared.js:180447:14)\n    at handleRejection (file:///C:/Users/Sunny/AppData/Local/PostmanCanary/app-7.21.0-canary01/resources/app.asar/js/vendor-shared.js:180931:14)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Sunny/AppData/Local/PostmanCanary/app-7.21.0-canary01/resources/app.asar/js/vendor-shared.js:184138:9)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Sunny/AppData/Local/PostmanCanary/app-7.21.0-canary01/resources/app.asar/js/vendor-shared.js:181144:23)"},"_stack":"VersionError: The requested version (40) is less than the existing version (190).\n    at mapError (file:///C:/Users/Sunny/AppData/Local/PostmanCanary/app-7.21.0-canary01/resources/app.asar/js/vendor-shared.js:180447:14)\n    at handleRejection (file:///C:/Users/Sunny/AppData/Local/PostmanCanary/app-7.21.0-canary01/resources/app.asar/js/vendor-shared.js:180931:14)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Sunny/AppData/Local/PostmanCanary/app-7.21.0-canary01/resources/app.asar/js/vendor-shared.js:184138:9)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Sunny/AppData/Local/PostmanCanary/app-7.21.0-canary01/resources/app.asar/js/vendor-shared.js:181144:23)","inner":{"message":"The requested version (40) is less than the existing version (190).","name":"VersionError"},"message":"The requested version (40) is less than the existing version (190).","name":"VersionError","stack":"VersionError: The requested version (40) is less than the existing version (190).\n    at mapError (file:///C:/Users/Sunny/AppData/Local/PostmanCanary/app-7.21.0-canary01/resources/app.asar/js/vendor-shared.js:180447:14)\n    at handleRejection (file:///C:/Users/Sunny/AppData/Local/PostmanCanary/app-7.21.0-canary01/resources/app.asar/js/vendor-shared.js:180931:14)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Sunny/AppData/Local/PostmanCanary/app-7.21.0-canary01/resources/app.asar/js/vendor-shared.js:184138:9)\n    at IDBOpenDBRequest.<anonymous> (file:///C:/Users/Sunny/AppData/Local/PostmanCanary/app-7.21.0-canary01/resources/app.asar/js/vendor-shared.js:181144:23)"}]

**Comment by kamalaknn** [comment]
Closing this issue since we are tracking this via email support.

**Comment by prithwirajbose** [comment]
> Closing this issue since we are tracking this via email support.

Is there any permanent solution for this issue available? I am facing the same problem. Basically I am trying to open Postman from a system which is behind a proxy server and the proxy requires authentication. My system Proxy settings is configured properly. Seems like Postman is looking for a file at /AppData/Roaming/Postman/Postman_config/proxy and is unable to find it. Hence it is getting stuck at the splash screen.

**Comment by arlemi** [comment]
@prithwirajbose I would also recommend contacting the support team and providing your logs on help@postman.com.
