### ISSUE TITLE
Cannot skip login when connection to Postman's servers is blocked

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7802]
**Describe the bug**
From a fresh installed state, the app shows "Something went wrong" error when connection cannot be established to our service. This may be because the client is disconnected from the internet, or because an organization has blocked access to our servers.

This is problematic for users who are part of an organization that blocks access to Postman's servers. Due to the error, users are not given the option to skip sign-in. This prevents them from using the app without logging in.

**To Reproduce**
1. Have either Postman or Postman Canary installed
2. Disconnect from WAN, or otherwise block access to Postman's servers.
3. Clear any local files for the app (to replicate a fresh install state):
* `rm -rf ~/Library/Application\ Support/Postman`
* `rm -rf ~/Library/Application\ Support/PostmanCanary`
4. See "Something went wrong" error
5. Notice that there is no option to continue without signing in.

**Expected behavior**
If access to login is not available for any reason, the option to continue without signing in is still shown.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.13.0
 - OS: MacOS Catalina

**Comment by jkjgabrielsen** [comment]
To clarify, I had postman installed @7.13.0 then:
* moved Postman.app to trash
* `rm -rf ~/Postman`
* `rm -rf ~/Library/Application\ Support/Postman`
* re-downloaded postman-osx-7.13.0.zip
* extracted to `~/Downloads`
* double-click to run

and error is displayed in main:
![image](https://user-images.githubusercontent.com/15989039/70827461-e7481f80-1dae-11ea-951f-447b594ba8cb.png)
Attempting to e.g. display preferences using cmd-, causes app to close. No other actions appear.

I've repeated the above cycle, also trying `rm -rf /private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/TemporaryItems/` and `/private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/`, on the hypothesis that Postman had written something to one of these dirs. I also tried restarting laptop, on hypothesis that temp fs would be cleared of anything that was dynamically written at Postman.app startup.

**My question: How to completely remove all traces of Postman.app such that, upon re-installing, it doesn't attempt to log me in using my google account?** 

For reference here are snips from the local logs:
`main.log:`
```
  [70702][1576252621305][main][info]["Booting Postman 7.13.0, darwin-18.7.0 on x64"]
  [70702][1576252621307][main][info]["EventBus~initialize - Success"]
  [70702][1576252621309][main][info]["UpdateHandler~init - Success"]
  [70702][1576252621310][main][info]["RuntimeExecutionService~initialized: Success"]
  [70702][1576252621341][main][info]["Main~promptMoveToApplicationsFolder - Postman is not in applications folder, showing a prompt to move it there"]
  [70702][1576252622958][main][info]["Bootstrap-models~bootstrap - Success"]
  [70702][1576252623200][main][info]["window-manager~newSharedWindow: Shell loaded"]
  [70702][1576252624620][main][info]["Main~AppEvents - Received booted event for process shared"]
  [70702][1576252626187][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
  [70702][1576252626195][main][info]["Main~AppEvents - Received booted event for process requester"]
  [70702][1576252630367][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"Cannot read property '0' of undefined","stack":"TypeError: Cannot read property '0' of undefined
    at Object.handleMenuAction (/private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/services/menuManager.js:509:114)
    at click (/private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/services/menuManager.js:159:82)
    at MenuItem.click (/private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/electron.asar/browser/api/menu-item.js:56:9)
    at Function.executeCommand (/private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/electron.asar/browser/api/menu.js:31:13)"}]
```
`renderer-auth.log`
```
  ...
  [70702][1576252623517][auth][info]["EventBus~initialize - Success"]
  [70702][1576252623825][auth][info]["Authentication~did-fail-load: Error with code ",-101,"https://identity.getpostman.com"]
  [70702][1576252623826][auth][warn]["Authentication~Window Failed to load",{"errorCode":-101,"errorDescription":"ERR_CONNECTION_RESET","isTrusted":false,"isMainFrame":true}]
  [70702][1576252623964][auth][info]["Authentication~did-navigate:","file://"]
```

`renderer-requester.log`
```
  ...
  [70702][1576252626192][requester][info]["Requester~boot - Success"]
  [70702][1576252626192][requester][info]["booted - requester"]
  [70702][1576252626384][requester][warn]["Failed to subscribe to workspace for all APIs",{"name":"Error","message":"","stack":"Error
    at SafeSubscriber.realtimeRequest$.pipe.subscribe.event [as _next] (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:405111:24)
    at SafeSubscriber.__tryOrUnsub (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:42001:16)
    at SafeSubscriber.next (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:41939:22)
    at Subscriber._next (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:41882:26)
    at Subscriber.next (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:41859:18)
    at FilterSubscriber._next (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:145290:30)
    at FilterSubscriber.Subscriber.next (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:41859:18)
    at RefCountSubscriber.Subscriber._next (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:41882:26)
    at RefCountSubscriber.Subscriber.next (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:41859:18)
    at Subject.next (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:75787:25)
    at ConnectableSubscriber.Subscriber._next (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:41882:26)
    at ConnectableSubscriber.Subscriber.next (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:41859:18)
    at EventEmitter.realtimeRequestBus.subscribe.event (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:405058:14)
    at EventEmitter.emit (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:50085:5)
    at _dispatch (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:143867:14)
    at EventEmitter.<anonymous> (file:///private/var/folders/t3/mzqj0hf13873jyg00_591_q58flyy4/T/AppTranslocation/E519DD2F-6D6E-4734-BA8C-035DCF8F531A/d/Postman.app/Contents/Resources/app/js/vendor-shared.js:143877:9)
    at EventEmitter.emit (events.js:182:13)"}]
```

**Comment by jkjgabrielsen** [comment]
?? any help with this issue?

**Comment by anudeepmedicharla** [comment]
@ArjunSingh-PM I was able to replicate this issue. The app should show the "Skip signing in" button but in this case, the button changes to "Sign in through email instead". This should be a bug and not a feature. 

![image](https://user-images.githubusercontent.com/16399370/73171631-36f86580-4127-11ea-99db-9c8495460302.png)

**Comment by ArjunSingh-PM** [comment]
@jkjgabrielsen This issue is fixed. Could you please confirm that you are able to skip login in case of a network issue.

**Comment by ArjunSingh-PM** [comment]
Closing this ticket as this issue is resolved.
