### ISSUE TITLE
Postman crashing when sending any request, "request.size" is not a function

### ISSUE THREAD

**Issue by itsmoirob** [a85/POSTMan-Chrome-Extension#7950]
**Describe the bug**
When I try to make a request in Postman the app just stops and closes. Logs show a `Uncaught errors",{"name":"TypeError","message":"request.size is not a function","stack":"TypeError: request.size is not a function\n    at Function.response (/usr/share/Postman/app/resources/app/services/RuntimeExecutionService.js:415:38)\`

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.16.0
 - OS: Linux Mint 4.15.0-74

**Additional context**
I was having problems opening the app to start with, so I followed the instructions here https://support.getpostman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error- then I could open the app and everything synced. But when I try to run a query the app just closes. The logs show this.

```[4042][1579786972627][main][info]["Booting Postman 7.16.0, linux-4.15.0-74-generic on x64"]
[4042][1579786972630][main][info]["EventBus~initialize - Success"]
[4042][1579786972638][main][info]["UpdateHandler~init - Success"]
[4042][1579786972640][main][info]["RuntimeExecutionService~initialized: Success"]
[4042][1579786972642][main][info]["LinuxAutoUpdater~Cleanup - Initial cleanup successful"]
[4042][1579786972895][main][info]["Bootstrap-models~bootstrap - Success"]
[4042][1579786973154][main][info]["window-manager~newSharedWindow: Shell loaded"]
[4042][1579786978558][main][info]["Main~AppEvents - Received booted event for process shared"]
[4042][1579786984820][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[4042][1579786984859][main][info]["Main~AppEvents - Received booted event for process requester"]
[4042][1579787563020][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"request.size is not a function","stack":"TypeError: request.size is not a function\n    at Function.response (/usr/share/Postman/app/resources/app/services/RuntimeExecutionService.js:415:38)\n    at PostmanCollectionRun.<anonymous> (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:66:50)\n    at PostmanCollectionRun.<anonymous> (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:87:21)\n    at apply (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:475:27)\n    at /usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9473:36\n    at /usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:4881:15\n    at Function.<anonymous> (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9472:7)\n    at apply (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:476:27)\n    at Function.invokeMap (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:6563:16)\n    at Instruction.<anonymous> (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:145:48)\n    at safeNext (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:69:28)\n    at /usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:178:36\n    at onEnd (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester.js:309:24)\n    at Request._callback (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester.js:439:24)\n    at self.callback (/usr/share/Postman/app/resources/app/node_modules/postman-request/request.js:256:12)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:442:20)\n    at Request.onRequestError (/usr/share/Postman/app/resources/app/node_modules/postman-request/request.js:1099:8)\n    at ClientRequest.emit (events.js:187:15)\n    at ClientRequest.EventEmitter.emit (domain.js:442:20)\n    at Socket.socketErrorListener (_http_client.js:382:9)\n    at Socket.emit (events.js:182:13)"}]
[19106][1579787574750][main][info]["Booting Postman 7.16.0, linux-4.15.0-74-generic on x64"]
[19106][1579787574756][main][info]["EventBus~initialize - Success"]
[19106][1579787574785][main][info]["UpdateHandler~init - Success"]
[19106][1579787574791][main][info]["RuntimeExecutionService~initialized: Success"]
[19106][1579787574794][main][info]["LinuxAutoUpdater~Cleanup - Initial cleanup successful"]
[19106][1579787575306][main][info]["Bootstrap-models~bootstrap - Success"]
[19106][1579787575695][main][info]["window-manager~newSharedWindow: Shell loaded"]
[19106][1579787578147][main][info]["Main~AppEvents - Received booted event for process shared"]
[19106][1579787581213][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[19106][1579787581232][main][info]["Main~AppEvents - Received booted event for process requester"]
[19106][1579787591093][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"request.size is not a function","stack":"TypeError: request.size is not a function\n    at Function.response (/usr/share/Postman/app/resources/app/services/RuntimeExecutionService.js:415:38)\n    at PostmanCollectionRun.<anonymous> (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:66:50)\n    at PostmanCollectionRun.<anonymous> (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:87:21)\n    at apply (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:475:27)\n    at /usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9473:36\n    at /usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:4881:15\n    at Function.<anonymous> (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9472:7)\n    at apply (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:476:27)\n    at Function.invokeMap (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:6563:16)\n    at Instruction.<anonymous> (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:145:48)\n    at safeNext (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:69:28)\n    at /usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:178:36\n    at onEnd (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester.js:309:24)\n    at Request._callback (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester.js:439:24)\n    at self.callback (/usr/share/Postman/app/resources/app/node_modules/postman-request/request.js:256:12)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:442:20)\n    at Request.onRequestError (/usr/share/Postman/app/resources/app/node_modules/postman-request/request.js:1099:8)\n    at ClientRequest.emit (events.js:187:15)\n    at ClientRequest.EventEmitter.emit (domain.js:442:20)\n    at Socket.socketErrorListener (_http_client.js:382:9)\n    at Socket.emit (events.js:182:13)"}]
[19536][1579787687508][main][info]["Booting Postman 7.16.0, linux-4.15.0-74-generic on x64"]
[19536][1579787687510][main][info]["EventBus~initialize - Success"]
[19536][1579787687519][main][info]["UpdateHandler~init - Success"]
[19536][1579787687522][main][info]["RuntimeExecutionService~initialized: Success"]
[19536][1579787687525][main][info]["LinuxAutoUpdater~Cleanup - Initial cleanup successful"]
[19536][1579787687817][main][info]["Bootstrap-models~bootstrap - Success"]
[19536][1579787688024][main][info]["window-manager~newSharedWindow: Shell loaded"]
[19536][1579787689820][main][info]["Main~AppEvents - Received booted event for process shared"]
[19536][1579787692627][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[19536][1579787692648][main][info]["Main~AppEvents - Received booted event for process requester"]
[19536][1579787729246][main][error]["Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"request.size is not a function","stack":"TypeError: request.size is not a function\n    at Function.response (/usr/share/Postman/app/resources/app/services/RuntimeExecutionService.js:415:38)\n    at PostmanCollectionRun.<anonymous> (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:66:50)\n    at PostmanCollectionRun.<anonymous> (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:87:21)\n    at apply (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:475:27)\n    at /usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9473:36\n    at /usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:4881:15\n    at Function.<anonymous> (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:9472:7)\n    at apply (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:476:27)\n    at Function.invokeMap (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/node_modules/lodash/lodash.js:6563:16)\n    at Instruction.<anonymous> (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:145:48)\n    at safeNext (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:69:28)\n    at /usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/http-request.command.js:178:36\n    at onEnd (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester.js:309:24)\n    at Request._callback (/usr/share/Postman/app/resources/app/node_modules/postman-runtime/lib/requester/requester.js:439:24)\n    at self.callback (/usr/share/Postman/app/resources/app/node_modules/postman-request/request.js:256:12)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:442:20)\n    at Request.onRequestError (/usr/share/Postman/app/resources/app/node_modules/postman-request/request.js:1099:8)\n    at ClientRequest.emit (events.js:187:15)\n    at ClientRequest.EventEmitter.emit (domain.js:442:20)\n    at Socket.socketErrorListener (_http_client.js:382:9)\n    at Socket.emit (events.js:182:13)"}]
[19788][1579787752882][main][info]["Booting Postman 7.16.0, linux-4.15.0-74-generic on x64"]
[19788][1579787752885][main][info]["EventBus~initialize - Success"]
[19788][1579787752893][main][info]["UpdateHandler~init - Success"]
[19788][1579787752895][main][info]["RuntimeExecutionService~initialized: Success"]
[19788][1579787752897][main][info]["LinuxAutoUpdater~Cleanup - Initial cleanup successful"]
[19788][1579787753230][main][info]["Bootstrap-models~bootstrap - Success"]
[19788][1579787753508][main][info]["window-manager~newSharedWindow: Shell loaded"]
[19788][1579787755382][main][info]["Main~AppEvents - Received booted event for process shared"]
[19788][1579787759009][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[19788][1579787759025][main][info]["Main~AppEvents - Received booted event for process requester"]```

**Comment by itsmoirob** [comment]
So I couldnt wait for a response. 

I tried 7.16.1, but still the app crashes when trying to do anything with the same `"request.size" is not a function` error

So I renamed my Postman files, deleted 7.16, installed 7.15, and the app works fine.

**Comment by codenirvana** [comment]
@itsmoirob do you remember the previous version of the Postman app from where you upgraded from?

Looks like there's some issue updating the dependencies on the Linux platform.
Can you verify if the issue persists on fresh installing the v7.16?

Maybe try installing it into a different directory.

**Comment by itsmoirob** [comment]
@codenirvana  I only ever manually download from getpostman.com/downloads/

I done as suggested, and deleted the app and tried a fresh install of 7.16.1 and it seems to doing requests fine, ie not crashing. I can close this now.
