### ISSUE TITLE
Possible memory leak on start

### ISSUE THREAD

**Issue by rmaenk** [a85/POSTMan-Chrome-Extension#8252]
**Describe the bug**
A day ago I have installed latest version of Postman (7.21.1) on virtual machine (Windows 10).
It was worked fine before I restarted VM. Postman hangs on start.

**To Reproduce**

During starting the app, I have looked to postman processes in Task Manager and one of them starts to eat memory until 2139 MB and then disappeared. There are 4 other that do not do anything and still present in Task Manager. Also postman splash screen is still shown with loading indicator.

in logs there are next errors:
renderer-shell.log: 
```
[12216][1585339370429][shell][error]["Render process for shared webview crashed",{"isTrusted":false}]
```
renderer-requester.log:
```
[20424][1585155697830][requester][warn]["CloudProxyHandler: Error while reading proxy configuration from user data - ",{"errno":-4058,"code":"ENOENT","syscall":"open","path":"C:\\Users\\Roma\\AppData\\Roaming\\Postman\\Postman_Config\\proxy","name":"Error","message":"ENOENT: no such file or directory, open 'C:\\Users\\Roma\\AppData\\Roaming\\Postman\\Postman_Config\\proxy'","stack":"Error: ENOENT: no such file or directory, open 'C:\\Users\\Roma\\AppData\\Roaming\\Postman\\Postman_Config\\proxy'"}]
[20424][1585155699726][requester][warn]["FeatureFlagsStore~updateFlags: Could not find feature flags",{"error":{"message":"SyncRequestService\\x7erequestListener: Could not fetch from sync. Socket not connected."}}]
[20424][1585155856435][requester][warn]["Failed to subscribe to workspace for all APIs",{"name":"Error","message":"","stack":"Error\n    at SafeSubscriber.realtimeRequest$.pipe.subscribe.event [as _next] (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:467653:24)\n    at SafeSubscriber.__tryOrUnsub (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:41962:16)\n    at SafeSubscriber.next (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:41900:22)\n    at Subscriber._next (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:41843:26)\n    at Subscriber.next (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:41820:18)\n    at FilterSubscriber._next (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:155116:30)\n    at FilterSubscriber.Subscriber.next (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:41820:18)\n    at RefCountSubscriber.Subscriber._next (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:41843:26)\n    at RefCountSubscriber.Subscriber.next (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:41820:18)\n    at Subject.next (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:78802:25)\n    at ConnectableSubscriber.Subscriber._next (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:41843:26)\n    at ConnectableSubscriber.Subscriber.next (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:41820:18)\n    at EventEmitter.realtimeRequestBus.subscribe.event (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:467600:14)\n    at EventEmitter.emit (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:50144:5)\n    at _dispatch (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:153363:14)\n    at EventEmitter.<anonymous> (file:///C:/Users/Roma/AppData/Local/Postman/app-7.21.1/resources/app.asar/js/vendor-shared.js:153373:9)\n    at EventEmitter.emit (events.js:182:13)"}]
[20424][1585155856515][requester][warn]["APIDevService~getAPIs: Failed to get APIs.",{"error":{"message":"SyncRequestService\\x7erequestListener: Could not fetch from sync. Socket not connected."}}]
[20424][1585155856518][requester][warn]["Failed to refresh API List",{"error":{"message":"SyncRequestService\\x7erequestListener: Could not fetch from sync. Socket not connected."}}]
[20424][1585155857060][requester][warn]["FeatureFlagsStore~updateFlags: Could not find feature flags",{"error":{"message":"SyncRequestService\\x7erequestListener: Could not fetch from sync. Socket not connected."}}]
[20424][1585163078608][requester][warn]["APIDevInterface~getAPIForModel: There is no API linked to the model"]
```

the last entry `[20424][1585163078608][requester][warn]["APIDevInterface~getAPIForModel: There is no API linked to the model"]
` is repeated many times

**Expected behavior**
Probably, it should work, but may be this is a feature :)

**App information (please complete the following information):**
 - Postman x64
 - Postman Version: 7.21.1
 - OS: Windows 10 Pro (russian language) 1903 build 18362.720

**Logs**
[renderer-requester.log](https://github.com/postmanlabs/postman-app-support/files/4395937/renderer-requester.log)
[renderer-shared.log](https://github.com/postmanlabs/postman-app-support/files/4395938/renderer-shared.log)
[renderer-shell.log](https://github.com/postmanlabs/postman-app-support/files/4395939/renderer-shell.log)
[main.log](https://github.com/postmanlabs/postman-app-support/files/4395940/main.log)
[renderer-auth.log](https://github.com/postmanlabs/postman-app-support/files/4395941/renderer-auth.log)

Thanks,
Roman

**Comment by rmaenk** [comment]
After some investigation it looks like 000003.log in Local Storage/leveldb folder is corrupted by synchronization or other thing ...

**Comment by sunilkbis** [comment]
this issue still exists version 7.24.0

**Comment by numaanashraf** [comment]
@sunil7796 Would it be possible to share a screen recording? It'll help us understand the resource usage on your system and identify the issue faster.

**Comment by poshizzle** [comment]
I had a similar issue, and when I reinstall, it works...for a while...then starts hanging/crashing again.  After various troubleshooting, I was able to determine that it was the database files in the "IndexedDB" folder that are not being properly cleaned up by the app.  My DB files (in total) grew to almost 2 GB, with 1,300 DB files.  When I deleted the "file__0.indexeddb.leveldb" folder and restarted, it came back up, and I didn't lose any configurations that I can tell.  However, without me doing anything except opening Postman, it has already created 6 x *.ldb files at about 2MB each.  I'm am sure once I start using Postman a bit, this scenario will repeat itself, since it's already happened to me 3 times in 1 month.  I am using v7.25.0.

**Comment by postman-kenji** [comment]
@poshizzle @sunilkbis Could you confirm if you are still seeing this issue on the latest version of Postman?

**Comment by MC-sanderv** [comment]
This issue is Electron-related, but its reported on a  very old Postman and Electron version. 

Closing as stale. If this still reproduces on the latest Postman version, please open a new issue with fresh logs and details.
