### ISSUE TITLE
Stuck when launch postman with notice "Preparing your workspaces...This might take a few minutes "

### ISSUE THREAD

**Issue by jjsty1e** [a85/POSTMan-Chrome-Extension#8255]
**Describe the bug**
on mac osx 10.12, Postman navtive app,  Stuck when launch postman with notice "Preparing your workspaces...This might take a few minutes "

**To Reproduce**
1. Launch Postman 

**Expected behavior**
get to work

**Screenshots**
![image](https://user-images.githubusercontent.com/5469845/77842603-e228a800-71c6-11ea-9baa-7548cdf2bc6b.png)

**App information (please complete the following information):**
I laterly launch the Postman in terminal with this command: `/Applications/Postman.app/Contents/MacOS/Postman` , the screenshot shows again, and below is the output:

```plain
Not disabling GPU
ProtocolHandler~init - Success with status: true]
Main~createDefaultWorkingDir - Default working dir creation already attempted
1585461971722 main info "Booting Postman 7.21.1, darwin-16.7.0 on x64"
1585461971723 main info "EventBus~initialize - Success"
1585461971726 main warn "CloudProxyManager~init: Error while reading proxy configuration from user data - ",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/Users/jake/Library/Application Support/Postman/Postman_Config/proxy","name":"Error","message":"ENOENT: no such file or directory, open '/Users/jake/Library/Application Support/Postman/Postman_Config/proxy'","stack":"Error: ENOENT: no such file or directory, open '/Users/jake/Library/Application Support/Postman/Postman_Config/proxy'"}
1585461971726 main info "CloudProxyManager~init - Success"
1585461971729 main info "UpdateHandler~init - Success"
1585461971730 main info "RuntimeExecutionService~initialized: Success"
1585461972238 main info "Bootstrap-models~bootstrap - Success"
1585461972521 main info "window-manager~newSharedWindow: Shell loaded"
1585461974448 main info "Main~AppEvents - Received booted event for process shared"
1585461974452 main error "Main~AppEvents - Shared window boot failed",{"_e":{"message":"","name":"Error","stack":"Error\n    at getErrorWithStack (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:180998:12)\n    at new DexieError (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181127:19)\n    at mapError (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181157:14)\n    at handleRejection (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181641:14)\n    at IDBOpenDBRequest.<anonymous> (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181857:29)"},"inner":{"message":"Failed to execute 'createIndex' on 'IDBObjectStore': An index with the specified name already exists.","name":"ConstraintError","stack":"Error: Failed to execute 'createIndex' on 'IDBObjectStore': An index with the specified name already exists.\n    at addIndex (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182490:15)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182379:29\n    at Array.forEach (<anonymous>)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182378:36\n    at Array.forEach (<anonymous>)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182371:29\n    at runQueue (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182409:64)\n    at updateTablesAndIndexes (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182412:16)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182344:17\n    at usePSD (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182006:16)\n    at newScope (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181903:14)\n    at runUpgraders (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182334:9)\n    at IDBOpenDBRequest.<anonymous> (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182607:25)\n    at IDBOpenDBRequest.<anonymous> (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181854:23)"},"message":"Failed to execute 'createIndex' on 'IDBObjectStore': An index with the specified name already exists.","name":"ConstraintError","stack":"Error: Failed to execute 'createIndex' on 'IDBObjectStore': An index with the specified name already exists.\n    at addIndex (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182490:15)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182379:29\n    at Array.forEach (<anonymous>)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182378:36\n    at Array.forEach (<anonymous>)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182371:29\n    at runQueue (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182409:64)\n    at updateTablesAndIndexes (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182412:16)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182344:17\n    at usePSD (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182006:16)\n    at newScope (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181903:14)\n    at runUpgraders (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182334:9)\n    at IDBOpenDBRequest.<anonymous> (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182607:25)\n    at IDBOpenDBRequest.<anonymous> (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181854:23)"}
```

***update*

formatted the last json string output:

```json
{
	"_e": {
		"message": "",
		"name": "Error",
		"stack": "Error\n    at getErrorWithStack (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:180998:12)\n    at new DexieError (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181127:19)\n    at mapError (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181157:14)\n    at handleRejection (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181641:14)\n    at IDBOpenDBRequest.<anonymous> (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181857:29)"
	},
	"inner": {
		"message": "Failed to execute 'createIndex' on 'IDBObjectStore': An index with the specified name already exists.",
		"name": "ConstraintError",
		"stack": "Error: Failed to execute 'createIndex' on 'IDBObjectStore': An index with the specified name already exists.\n    at addIndex (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182490:15)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182379:29\n    at Array.forEach (<anonymous>)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182378:36\n    at Array.forEach (<anonymous>)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182371:29\n    at runQueue (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182409:64)\n    at updateTablesAndIndexes (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182412:16)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182344:17\n    at usePSD (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182006:16)\n    at newScope (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181903:14)\n    at runUpgraders (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182334:9)\n    at IDBOpenDBRequest.<anonymous> (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182607:25)\n    at IDBOpenDBRequest.<anonymous> (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181854:23)"
	},
	"message": "Failed to execute 'createIndex' on 'IDBObjectStore': An index with the specified name already exists.",
	"name": "ConstraintError",
	"stack": "Error: Failed to execute 'createIndex' on 'IDBObjectStore': An index with the specified name already exists.\n    at addIndex (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182490:15)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182379:29\n    at Array.forEach (<anonymous>)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182378:36\n    at Array.forEach (<anonymous>)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182371:29\n    at runQueue (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182409:64)\n    at updateTablesAndIndexes (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182412:16)\n    at file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182344:17\n    at usePSD (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182006:16)\n    at newScope (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181903:14)\n    at runUpgraders (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182334:9)\n    at IDBOpenDBRequest.<anonymous> (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:182607:25)\n    at IDBOpenDBRequest.<anonymous> (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:181854:23)"
}
```

**Comment by xk0der** [comment]
Hey @Jaggle try out the steps listed at this article to rename(or clear) Postman folders and then re-install Postman, that should help: https://support.getpostman.com/hc/en-us/articles/360025359014

**Comment by jjsty1e** [comment]
@xk0der thank you for you quick reply, it saved my life!😀

**Comment by jrichardsz** [comment]
@xk0der thank you!!

On Linux

Backup this folder and then delete it:
```
~/.config/Postman
```

If the new postman is empty and you want to restore your workspace, follow these steps:

Paste or override these folders from older to new ~/.config/Postman folder:

- databases
- Local Storage
- Postman_Config
- Session Storage
- storage

**Comment by yuhaowin** [comment]
@xk0der It is very useful ,it saved my life! think you! 😊

**Comment by iqqmuT** [comment]
Removing `~/.config/Postman` was not enough for me. I had to remove `~/Postman` too.

**Comment by aynacorp** [comment]
Just replace the existing application file in the Applications folder with the latest application file downloaded from Postman website. This worked and kept all data.
