### ISSUE TITLE
The native app crashes a few seconds after I open it

### ISSUE THREAD

**Issue by jaytekwani** [a85/POSTMan-Chrome-Extension#8690]
**Describe the bug**
The native app crashes a few seconds after I open it. This happens across all the versions of Postman so I am guessing there is some settings issue on my end but I cannot figure out what it is. One online solution recommended opening it through admin command prompt by issuing 'start /affinity 1 C:\Users\{userName}\AppData\Local\Postman\app-7.25.0\Postman.exe' and that fails as well. I have attached the screenshot of the message from that fail to this report. 

**To Reproduce**
1. Go to administrative command prompt
2. Enter 'start /affinity 1 C:\Users\{userName}\AppData\Local\Postman\app-7.25.0\Postman.exe' 
3. Hopefully this will reproduce the error on your end

**Expected behavior**

**Screenshots**

```js
C:\>start /affinity 1 C:\Users\{userName}\AppData\Local\Postman\app-7.25.0\Postman.exe

C:\>
Not disabling GPU
ProtocolHandler~init - Success with status: true]
Main~createDefaultWorkingDir - Default working dir creation already attempted
1592777232894 main info "Booting Postman 7.25.0, win32-10.0.18363 on x64"
1592777232895 main info "EventBus~initialize - Success"
1592777232896 main warn "CloudProxyManager~init: Error while reading proxy configuration from user data - ",{"errno":-4058,"code":"ENOENT","syscall":"open","path":"C:\\Users\\{userName}\\AppData\\Roaming\\Postman\\Postman_Config\\proxy","name":"Error","message":"ENOENT: no such file or directory, open 'C:\\Users\\{userName}\\AppData\\Roaming\\Postman\\Postman_Config\\proxy'","stack":"Error: ENOENT: no such file or directory, open 'C:\\Users\\{userName}\\AppData\\Roaming\\Postman\\Postman_Config\\proxy'"}
1592777232897 main info "CloudProxyManager~init - Success"
1592777232899 main info "UpdateHandler~init - Success"
1592777232899 main info "RuntimeExecutionService~initialized: Success"
1592777233104 main info "Bootstrap-models~bootstrap - Success"
1592777233593 main info "window-manager~newSharedWindow: Shell loaded"
1592777235103 main info "Main~AppEvents - Received booted event for process shared"
1592777237091 main info "UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}
INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge
InterceptorBridge: Trying to connect Native App IPC~Interceptor Bridge
IPCClient ~ WindowHandler: New event is received { type: 'window-opened' }
1592777237170 main info "Main~AppEvents - Received booted event for process requester"
sed: script file "Z:/bin/thismodel.scr": The system cannot find the path specified.
File not found: clpHKCU\Software\Google\Chrome\NativeMessagingHosts\com.postman.postmanapp.in very first

TypeError: Cannot read property 'trim' of undefined
    at C:\Users\{userName}\AppData\Local\Postman\app-7.25.0\resources\app.asar\utils\interceptor\utils.js:1168:40
    at C:\Users\{userName}\AppData\Local\Postman\app-7.25.0\resources\app.asar\node_modules\shelljs\src\exec.js:172:7
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
1592777240276 main error "Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"Cannot read property 'trim' of undefined","stack":"TypeError: Cannot read property 'trim' of undefined\n    at C:\\Users\\{userName}\\AppData\\Local\\Postman\\app-7.25.0\\resources\\app.asar\\utils\\interceptor\\utils.js:1168:40\n    at C:\\Users\\{userName}\\AppData\\Local\\Postman\\app-7.25.0\\resources\\app.asar\\node_modules\\shelljs\\src\\exec.js:172:7\n    at ChildProcess.exithandler (child_process.js:294:7)\n    at ChildProcess.emit (events.js:182:13)\n    at ChildProcess.EventEmitter.emit (domain.js:442:20)\n    at maybeClose (internal/child_process.js:961:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)"}
Main~handleUncaughtError - Uncaught errors TypeError: Cannot read property 'trim' of undefined
    at C:\Users\{userName}\AppData\Local\Postman\app-7.25.0\resources\app.asar\utils\interceptor\utils.js:1168:40
    at C:\Users\{userName}\AppData\Local\Postman\app-7.25.0\resources\app.asar\node_modules\shelljs\src\exec.js:172:7
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.25.0 but any other version as well
 - Windows 10

**Additional context**
I am fairly certain this is a unique problem with my setting and not necessarily a bug because I have not found anyone else in the postman community who has had the same error. Nonetheless, it would be great if someone can help me out.

**Comment by Cryssa10** [comment]
I have a similar problem. When I start the application it hangs with the following error on my Event Viewer:

```xml
Log Name:      Application
Source:        Application Error
Date:          6/22/2020 11:48:51 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ECD01-TST-04.ecdc.europa.local
Description:
Faulting application name: Postman.exe, version: 7.26.1.0, time stamp: 0x5edb407a
Faulting module name: ntdll.dll, version: 10.0.14393.3630, time stamp: 0x5e8d4386
Exception code: 0xc0000005
Fault offset: 0x000000000002ddd0
Faulting process id: 0x2cec
Faulting application start time: 0x01d64871c4316a50
Faulting application path: C:\Users\mastoric\AppData\Local\Postman\app-7.26.1\Postman.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: ee654a18-4903-480f-83b3-99e3e67953dc
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-06-22T08:48:51.731525100Z" />
    <EventRecordID>42719</EventRecordID>
    <Channel>Application</Channel>
    <Computer>ECD01-TST-04.ecdc.europa.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Postman.exe</Data>
    <Data>7.26.1.0</Data>
    <Data>5edb407a</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.14393.3630</Data>
    <Data>5e8d4386</Data>
    <Data>c0000005</Data>
    <Data>000000000002ddd0</Data>
    <Data>2cec</Data>
    <Data>01d64871c4316a50</Data>
    <Data>C:\Users\mastoric\AppData\Local\Postman\app-7.26.1\Postman.exe</Data>
    <Data>C:\Windows\SYSTEM32\ntdll.dll</Data>
    <Data>ee654a18-4903-480f-83b3-99e3e67953dc</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

I'm running it on Windows server 2016 Version 1607 (OS Build 14393.3686)

Please advice on further steps to resolve this asap

Thanks

**Comment by vinitshahdeo** [comment]
Hello @jaytekwani, @Cryssa10 👋 

Could you send us the following details in order to help us debug this issue better?

**1.** Do you have [Interceptor](https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo) Browser extension installed?

**2.** **If yes for 1**, please go to `%USERPROFILE%/.postman/InterceptorBridge/` location and zip the `logs` folder.

**3.** Open your command prompt and run the following command and take a screenshot:
```
REG QUERY HKCU\Software\Google\Chrome\NativeMessagingHosts\com.postman.postmanapp
```
Please send all the above details to help@postman.com with the subject as `Logs for GitHub issue #8690`.

**Comment by henry-arroyo** [comment]
Hi @vinitshahdeo,

I am experiencing the same issue as the folks above on Windows Server 2012 R2:

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Postman.exe
  Application Version:	7.27.0.0
  Application Timestamp:	5edb407a
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.3.9600.19678
  Fault Module Timestamp:	5e82c88a
  Exception Code:	c0000005
  Exception Offset:	00000000000cb12d
  OS Version:	6.3.9600.2.0.0.16.7
  Locale ID:	1033
  Additional Information 1:	d25e
  Additional Information 2:	d25e6a61df0e6ee70cf73ed57f45ab64
  Additional Information 3:	fa3e
  Additional Information 4:	fa3e5aa2ca0ff92c22e6bff8e3772a6a
```

I do have Interceptor installed nor do I see a registry key for NativeMessagingHosts at that location.

Please advise on how to get this application running.

Henry

**Comment by vinitshahdeo** [comment]
Hey @henry-arroyo,

Thanks for reporting this. Could you send us the app logs in order to help us debug this issue further? Please send all the logs located in this directory to help@postman.com with the subject as `Logs for GitHub issue #8690`.

> The logs can be found using the View menu in the app - `View -> Developer -> View Logs in Explorer`.

**Comment by mccannt** [comment]
This should be resolved in the latest version of Postman. v7.28.0
Give this a try and let us know if you are still experiencing issues.

**Comment by hugodasilvadasilva** [comment]
Hi there,

I'm facing the same issue when trying to install Postman 7.29 version (further than that which this issue is supposed to be fixed) on Windows Server 2016. You can check my Windows Event Viewer screen at https://drive.google.com/file/d/1JmSXkkg5Dv_xHqh2PwpazInPZT-rrYUw/view?usp=sharing

**Comment by mccannt** [comment]
@hugodasilvadasilva Can you try this on v7.30?

**Comment by jackvaughanjr** [comment]
I'm experiencing the same issue today with 8.0.7. After installing Postman on a fresh build on Server 2019, it does something to ntdll.dll that then causes the server to hang on reboots and also stops GitHub Desktop from opening.

**Comment by RaisinTen** [comment]
Is this still a problem on the latest version of Postman (v9.13.0)?

**Comment by MC-sanderv** [comment]
The last report in this thread was 4y ago, and there has been no such specific recurrence in recent closed or open issues in 2years at least.
Since this issue appears tied to outdated runtime/extension state and has not recurred in modern builds, I’m closing the issue.

IF any user still experiences it, submit a fresh crash dump.
