### ISSUE TITLE
Cannot install on Windows 10 2020H2 64-Bit

### ISSUE THREAD

**Issue by kking124** [a85/POSTMan-Chrome-Extension#9537]
**Describe the Issue**

I cannot install Postman 8.0.4 through any installer available (32 bit standalone, 64 bit standalone, 64 bit web agent)

**Steps to Reproduce**

1. Download the installer
2. Run the installer

**Screenshots or Videos**

Logs:
```
2021-02-03 10:20:55> Program: Starting Squirrel Updater: --install .
2021-02-03 10:20:55> Program: Starting install, writing to %APPDATA%\Local\SquirrelTemp
2021-02-03 10:20:55> Program: About to install to: %APPDATA%\Local\Postman
2021-02-03 10:20:55> Program: Install path %APPDATA%\Local\Postman already exists, burning it to the ground
2021-02-03 10:20:56> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path '%APPDATA%\Local\Postman\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2021-02-03 10:20:56> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path '%APPDATA%\Local\Postman\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2021-02-03 10:20:56> CheckForUpdateImpl: Reading RELEASES file from %APPDATA%\Local\SquirrelTemp
2021-02-03 10:20:56> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2021-02-03 10:20:58> ApplyReleasesImpl: Writing files to app directory: %APPDATA%\Local\Postman\app-8.0.4
```

Run As Administrator Logs:
```
2021-02-03 10:22:12> Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC
2021-02-03 10:22:12> Program: Starting install, writing to %APPDATA%\Local\SquirrelTemp
2021-02-03 10:22:12> Program: About to install to: %APPDATA%\Local\Postman
2021-02-03 10:22:12> Program: Install path %APPDATA%\Local\Postman already exists, burning it to the ground
2021-02-03 10:22:13> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path '%APPDATA%\Local\Postman\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2021-02-03 10:22:13> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path '%APPDATA%\Local\Postman\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2021-02-03 10:22:13> CheckForUpdateImpl: Reading RELEASES file from %APPDATA%\Local\SquirrelTemp
2021-02-03 10:22:13> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2021-02-03 10:22:15> ApplyReleasesImpl: Writing files to app directory: %APPDATA%\Local\Postman\app-8.0.4

```

Although the app **appears** to install, it cannot be run, giving the following error:

![image](https://user-images.githubusercontent.com/21278391/106769304-cc67e880-660a-11eb-9f0d-c6824cfbc443.png)

**Environment Information**

 - Platform Type: Desktop App
 - Postman Version: 8.0.4
 - Operating System: Windows 10 2020H2 64 Bit

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

**Comment by kking124** [comment]
Any suggestions on how to resolve? I still cannot install.
