### ISSUE TITLE
 Can not get Token from browser shows "Error: OAuth 2.0 request timed out. Please try again." about after upgrade 8.04 Ver.

### ISSUE THREAD

**Issue by ningma007** [a85/POSTMan-Chrome-Extension#9542]
Hi team,
 I upgraded Postman from 7.36 to 8.04, then Postman can not get Token form browser  shows "Error: OAuth 2.0 request timed out. Please try again."

 No settings was changed Postman and browser, browser pop-ups as normal, however, Postman looks can not get the token from browser 

 However, if downgrade to 7.36, everything return to normal.

Thanks.

**Comment by mareklinka** [comment]
Having the same issue - the redirect from browser happens and the main log shows that it received it:

`[28208][1612429118344][main][info]["ProtocolHandler~handleOpenUrl: postman://app/oauth2/callback?code=...&state=&session_state=..."]`

However, the popup `Authenticate via browser` remains open and eventually times out.

**Comment by satyavh** [comment]
Same here, 8.04 has this issue. Prev version was working fine.

**Comment by ningma007** [comment]
Hi team,

I updated the latest verison v8.0.5 today, this issue looks was not solved yet.
Dose anyone has same case?

Warm regards,

**Comment by sabrina-biersack-smit** [comment]
Same behavior for me. Checked my browser and set it so it allows all popups, no change.

**Comment by knarf94** [comment]
Same issue for me... waiting for a fix.
FYI, there is a way to downgrade to the older version until there is a fix, by downloading and installing https://dl.pstmn.io/download/version/7.36.5/win64 (WARNING - collections and variables will be deleted by downgrade)

**Comment by sabrina-biersack-smit** [comment]
I figured out another workaround:
Uncheck the "Authorized using browser" and set "https://oauth.pstmn.io/v1/callback" to the Callback URL.

**Comment by LNTS2021** [comment]
Same here, but:
1. A colleague has the same version of postman (8.0.7), like me, without the issue. We checked all our postman settings, browser settings, all the same. I imported his collection. Issue is still there.
2. The workaround doesn't work for me because, the web service I call, allows only the Edge browser for the authentication.

**Comment by zajkuu11** [comment]
Issue still exists on postman 8.4.0 linux client. Although sabrina-biersack-smit workaround did the trick.
Same version of Windows client works as expected.

**Comment by HarshithaSaiK** [comment]
Just have to enable "Use the system proxy" under proxy settings while trying to make such a call.
It worked for me :)

**Comment by susan-shu-c** [comment]
I can't even uncheck the "Authorize using browser" because there's no such option for me.

<img width="583" alt="Screen Shot 2021-09-16 at 4 22 08 PM" src="https://user-images.githubusercontent.com/23287722/133680648-a390e90b-c59e-4db8-b821-a61b0dcdb31b.png">


I've seen screenshots online that do have it:
<img width="456" alt="Screen Shot 2021-09-16 at 4 23 33 PM" src="https://user-images.githubusercontent.com/23287722/133680938-1d28f566-86c4-49db-8228-d09b05662b49.png">

**Comment by 0x78f1935** [comment]
I'm working with Oauth2 for a while now and used Postman to test it. I used the following configuration:
![image](https://user-images.githubusercontent.com/14298262/135186247-da0ac86a-7969-41a7-8c32-7e59eb358ee1.png)
Notice the access token. It worked before.

Suddenly Postman gets stuck the moment I click the orange button "Get New Access Token".
![image](https://user-images.githubusercontent.com/14298262/135186339-3f92b2a9-3ebf-4557-9be0-bb6d07c9b582.png)
After a while I get a timeout.
![image](https://user-images.githubusercontent.com/14298262/135186593-bf5f6a65-d9bb-4393-bdb9-831ed9be8e48.png)


My default browser allows popups from oauth.pstman.io
![image](https://user-images.githubusercontent.com/14298262/135186582-1fbde8ea-3c1d-40e9-962b-2a5e24eb5042.png)

This happend suddenly. Why?.

Edit:
My `domain` variable was overwritten which resulted in two invalid URL's. The `Auth URL` and the `Access Token URL`. Simple mistake on my side.

**Comment by gckunjadiya** [comment]
> I figured out another workaround: Uncheck the "Authorized using browser" and set "https://oauth.pstmn.io/v1/callback" to the Callback URL.

This worked after trying out so many solutions!! Thanks

**Comment by giridharvc7** [comment]
Closing the issue now because of the possible solution and inactivity. Feel free to reopen this if you still find this happening.

**Comment by stanboerekamp** [comment]
This started happening to me yesterday on 10.13.4.
Disabling Authorize using browser as a workaround worked for me, but this is not ideal since I can't use my password manager there. I'm also on Chrome.

**Comment by bikashmailguard** [comment]
I am using latest version 11.51.5 and still I am having the same issue.

**Comment by TarunEarle** [comment]
Hi @giridharvc7 , Can you please reopen the issue, I am using latest version 11.52.5 and still I am having the same issue.

**Comment by QMiqTx6DHn1bA9yaNaAbsD3CLG8gTmd4** [comment]
Version 11.58.5
UI Version: 11.58.5-ui-250815-1156
Desktop Platform Version: 11.58.4 (11.58.4)

Redirected via https://oauth.pstmn.io/v1/callback?code=db1cb5ef74136f988ccfffd8bb407cdabcdb4fa32ba0c1446ed7a7ec1cbd8fa2 to `postman://app/oauth2/callback?code=db1cb5ef74136f988ccfffd8bb407cdabcdb4fa32ba0c1446ed7a7ec1cbd8fa2`

Fails with 

```
[53630][1755333881282][requester][error][{"name":"Error","message":"ProtocolHandler~handleProtocolUrl: Incorrect URL format, url: postman://app/oauth2/callback?code=632b47e81cf6875d53fafb9fbb744988ca1d53b007908e7d6c09b124ac67ff43","stack":"Error: ProtocolHandler~handleProtocolUrl: Incorrect URL format, url: postman://app/oauth2/callback?code=632b47e81cf6875d53fafb9fbb744988ca1d53b007908e7d6c09b124ac67ff43\n    at Object.handleProtocolUrl (https://desktop.postman.com/_ar-assets/requester-desktop-2b852292729d6a3d.min.js:1369:98665)\n    at https://desktop.postman.com/_ar-assets/requester-desktop-2b852292729d6a3d.min.js:1369:98143\n    at nrWrapper (https://desktop.postman.com/?desktopVersion=11.58.4&userId=13960327&teamId=4986291&region=us:15:17817)"}]
[53630][1755333881282][requester][error]["ProtocolHandler~onProtocolEvent - error while handling protocol URl postman://app/oauth2/callback?code=632b47e81cf6875d53fafb9fbb744988ca1d53b007908e7d6c09b124ac67ff43",{"name":"Error","message":"ProtocolHandler~handleProtocolUrl: Incorrect URL format, url: postman://app/oauth2/callback?code=632b47e81cf6875d53fafb9fbb744988ca1d53b007908e7d6c09b124ac67ff43","stack":"Error: ProtocolHandler~handleProtocolUrl: Incorrect URL format, url: postman://app/oauth2/callback?code=632b47e81cf6875d53fafb9fbb744988ca1d53b007908e7d6c09b124ac67ff43\n    at Object.handleProtocolUrl (https://desktop.postman.com/_ar-assets/requester-desktop-2b852292729d6a3d.min.js:1369:98665)\n    at https://desktop.postman.com/_ar-assets/requester-desktop-2b852292729d6a3d.min.js:1369:98143\n    at nrWrapper (https://desktop.postman.com/?desktopVersion=11.58.4&userId=13960327&teamId=4986291&region=us:15:17817)"}]
```

There's this weirdness in `handleProtocolUrl` function of https://desktop.postman.com/_ar-assets/requester-desktop-2b852292729d6a3d.min.js

<img width="1401" height="303" alt="Image" src="https://github.com/user-attachments/assets/4c934d29-baa6-4388-ad71-4e9d3e908bd3" />

Specifically, `"app" !== p.get(r, "[0]")` executes to `false`, as `p.get(r, "[0]")` is `"auth2"`. The `r` is `['auth2', 'callback']`.

---

**Workaround**: Don't use automated (JS-based) redirect from https://oauth.pstmn.io/v1/callback. Instead change Postman app-specific redirect URL to include extra `aapp/` [yes, with two "a"'s 🤦] after initial `app` for full URL `postman://app/aapp/oauth2/callback?code=db1cb5ef74136f988ccfffd8bb407cdabcdb4fa32ba0c1446ed7a7ec1cbd8fa2`.

@giridharvc7 This needs to be solved on Postman end. 


---

**Update:**

Per release notes this was fixed in 11.59.1

> # Postman 11.59.1
> August 18, 2025
> 
> ## Bug Fixes
> Fixed an issue with OAuth 2.0 authentication redirects in the Postman desktop app that prevented users from sucessfully getting a new access token.

**Comment by samueltuoyo15** [comment]
> This started happening to me yesterday on 10.13.4. Disabling Authorize using browser as a workaround worked for me, but this is not ideal since I can't use my password manager there. I'm also on Chrome.

Same here, i don't like it
