### ISSUE TITLE
Exception when add tests result

### ISSUE THREAD

**Issue by youranwj** [a85/POSTMan-Chrome-Extension#983]
I have a collection which will use a json data file. When I add test result with different test name which will contain some dynamic information in each iteration, such as 

tests["verify " + data.userName] = response.userName === data.userName;

I got the following exception

TypeError: Cannot read property 'pass' of undefined
    at C:\Program Files\nodejs\node_modules\npm\node_modules\newman\src\utilities\ResponseExporter.js:193:42
    at Function._.each._.forEach (C:\Program Files\nodejs\node_modules\npm\node_modules\newman\node_modules\underscore\underscore.js:145:9)
    at Object.jsface.Class._mergeTestCounts (C:\Program Files\nodejs\node_modules\npm\node_modules\newman\src\utilities\ResponseExporter.js:192:8)
    at Object.jsface.Class._appendToResultsObject (C:\Program Files\nodejs\node_modules\npm\node_modules\newman\src\utilities\ResponseExporter.js:186:8)
    at Object.jsface.Class.addResult (C:\Program Files\nodejs\node_modules\npm\node_modules\newman\src\utilities\ResponseExporter.js:32:9)
    at Object.jsface.Class._onRequestExecuted (C:\Program Files\nodejs\node_modules\npm\node_modules\newman\src\responseHandlers\AbstractResponseHandler.js:32:20)
    at Object.jsface.Class._onRequestExecuted (C:\Program Files\nodejs\node_modules\npm\node_modules\newman\src\responseHandlers\TestResponseHandler.js:30:52)
    at EventEmitter.emit (events.js:117:20)
    at Object.jsface.Class.emit (C:\Program Files\nodejs\node_modules\npm\node_modules\newman\src\utilities\EventEmitter.js:34:16)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\newman\src\runners\RequestRunner.js:184:22)

**Comment by abhijitkane** [comment]
What version of Newman are you using?
    newman -V
Try upgrading to the latest version.

**Comment by youranwj** [comment]
It works after upgrade to latest version. Thanks!
